SUBROUTINE ASSIGN_SICERR

!.. OBS ERRORS ASSIGNEMENT FOR SPACE-BORNE SIC OBS
!..


USE SET_KND
USE OBSDEF
USE OBS_STR
USE GRD_STR
USE OBSHANDLING
USE MYFRTPROF
USE MYNETCDF

IMPLICIT NONE

INTEGER(I4) :: JK,ISAT
REAL(R8) :: ZR
REAL(DP) :: TD, TD2, OETIM, ZT2

CALL MYFRTPROF_WALL('ASSIGN_SICERR: ASSIGN SIC OBS ERROR',0)

!... FOR SIC, CYCLE THE OBS
!!to be added if needed, repreentativeness
   ZR = 0._R8

CYOBS : DO JK=1,SIC%NO

     IF(SIC%FLC(JK) .EQ. 0 ) CYCLE CYOBS


     !IF(SIC%KSAT(JK) .EQ. 1 ) THEN
       SIC%ERR(JK) = MAX(SIC%ERR(JK),0.05_R8)*COEFF_SIC_ERR
     !ELSE
     !  SST%ERR(JK) = SST_ERRS(SST%KSAT(JK))
     !ENDIF

     TD=MIN(ZTIME_WEIGTH,ABS(SIC%TDIST(JK)))
     TD2=TD*TD
     ZT2=ZTIME_WEIGTH*ZTIME_WEIGTH
     OETIM = 1._DP / EXP( -TD2 / ZT2 )

!     ZR = OSUM( SIC%PQ(JK,1:NPQ),ZREP(SST%IB(JK,1:NPQ),SST%JB(JK,1:NPQ)) )

     SIC%ERR(JK) = SQRT(SIC%ERR(JK)**2+ZR**2)*REAL(OETIM,R8)

ENDDO CYOBS

CALL MYFRTPROF_WALL('ASSIGN_SICERR: ASSIGN SIC OBS ERROR',1)

END SUBROUTINE ASSIGN_SICERR
