SUBROUTINE ICE_CHECKS_BEFORE_WRT

USE GRD_STR
USE IOUNITS, ONLY : IOUNLOG
USE RUN, ONLY : NTSTEPS
USE MYFRTPROF, ONLY : MYFRTPROF_WALL

IMPLICIT NONE

INTEGER (I4) :: NUM_OBS_OUT_BOUNDARIES,I,J

CALL MYFRTPROF_WALL('ICE CHECKS: OUT OF BOUNDARY',0)

!SIC
NUM_OBS_OUT_BOUNDARIES=0
     DO J=1,GRD%JM
     DO I=1,GRD%IM
         IF (GRD%MSK(I,J,1) .GT. 0.9_R8 .AND. (GRD%SICB(I,J,NTSTEPS) + GRD%SIC(I,J)) .GT. 1._R8 .AND. abs(GRD%SICB(I,J,NTSTEPS)) .LT. 500._R8 ) THEN
            !WRITE(IOUNLOG,*),I,J,GRD%SICB(I,J,NTSTEPS),GRD%SIC(I,J), GRD%SICB(I,J,NTSTEPS) + GRD%SIC(I,J)
            GRD%SIC(I,J)=1._R8 -GRD%SICB(I,J,NTSTEPS)
             NUM_OBS_OUT_BOUNDARIES=NUM_OBS_OUT_BOUNDARIES+1
         ENDIF
         IF (GRD%MSK(I,J,1) .GT. 0.9_R8 .AND. (GRD%SICB(I,J,NTSTEPS) + GRD%SIC(I,J)) .LT. 0._R8 .AND. abs(GRD%SICB(I,J,NTSTEPS)) .LT. 500._R8 ) THEN
!WRITE(IOUNLOG,*),I,J,GRD%SICB(I,J,NTSTEPS),GRD%SIC(I,J), GRD%SICB(I,J,NTSTEPS) +GRD%SIC(I,J)

            GRD%SIC(I,J)=GRD%SICB(I,J,NTSTEPS)* (-1._R8)
            IF (GRD%SICB(I,J,NTSTEPS) + GRD%SIC(I,J) .LT. -0.001_R8) NUM_OBS_OUT_BOUNDARIES=NUM_OBS_OUT_BOUNDARIES+1
         ENDIF
     ENDDO
     ENDDO
 WRITE(IOUNLOG,*) ' NUMBER OF SIC GRIDDED POINT OUT OFBOUNDARIES:',NUM_OBS_OUT_BOUNDARIES

!SIT
NUM_OBS_OUT_BOUNDARIES=0
     DO J=1,GRD%JM
     DO I=1,GRD%IM
         IF (GRD%MSK(I,J,1) .GT. 0.9_R8 .AND. (GRD%SITB(I,J,NTSTEPS) + GRD%SIT(I,J)) .LT. 0._R8 .AND. abs(GRD%SICB(I,J,NTSTEPS)) .LT. 500._R8) THEN
            GRD%SIT(I,J)=GRD%SITB(I,J,NTSTEPS)* (-1._R8)
         IF (GRD%SICB(I,J,NTSTEPS) + GRD%SIC(I,J) .LT. -0.001_R8) NUM_OBS_OUT_BOUNDARIES=NUM_OBS_OUT_BOUNDARIES+1 
        ENDIF
     ENDDO
     ENDDO
  WRITE(IOUNLOG,*) ' NUMBER OF SIT GRIDDED POINT OUT OF BOUNDARIES:',NUM_OBS_OUT_BOUNDARIES

 IF(ALLOCATED(GRD%SICB) ) DEALLOCATE(GRD%SICB)
 IF(ALLOCATED(GRD%SITB) ) DEALLOCATE(GRD%SITB)

CALL MYFRTPROF_WALL('ICE CHECKS: OUT OF BOUNDARY',1)
END SUBROUTINE ICE_CHECKS_BEFORE_WRT
