#undef SHARED_MEMORY
SUBROUTINE INT_PAR_SIT

!-----------------------------------------------------------------------
!                                                                      !
! GET INTERPOLATION PARAMETERS FOR A GRID                              !
!                                                                      !
!-----------------------------------------------------------------------

 USE SET_KND
 USE GRD_STR
! USE PHINTERP
 USE PHINTERP2
 USE RUN
 USE OBS_STR
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE IOUNITS

 IMPLICIT NONE

  INTEGER(I4)   ::  K, N_TOPEX, N_ERS, II, JJ,I2
  INTEGER(I4)   ::  I1, J1, KK, I, J, ITER, IAUX, JP
  INTEGER(I4)   ::  MSCOUNT
  REAL(R8)      ::  P1, Q1, P, Q, SUMT, SUMI, NEWLON
  REAL(R8)      ::  MSK4, ZZSS

#include "obs_events.h"

 CALL MYFRTPROF_WALL('INT_PAR_SIT: SIT INTERPOLATION',0)

 IF(SIT%NO.EQ.0) THEN
   CALL MYFRTPROF_WALL('INT_PAR_SIT: SIT INTERPOLATION',1)
   RETURN
 ENDIF

 SIT%FLC = 0
 SIT%IB  = 0
 SIT%JB  = 0
 SIT%TDIST(1:SIT%NO)=SIT%TIM(1:SIT%NO) - ZANJUL1950


#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(PRIVATE), SHARED(SIT)
!$OMP DO SCHEDULE(DYNAMIC)
#endif
CYOBS0 : DO KK = 1,SIT%NO

      IF( SIT%EVE(KK) .EQ. KEVE_PDOM ) CYCLE CYOBS0

         CALL PREPINTERP2(SIT%LON(KK),SIT%LAT(KK),SIT%IB(KK,:),SIT%JB(KK,:),SIT%PQ(KK,:))

ENDDO CYOBS0
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(SHARED), PRIVATE(KK,ZZSS,JP,MSK4)
!$OMP DO SCHEDULE(DYNAMIC)
#endif
CYOBS : DO KK = 1,SIT%NO
       IF( ALL(SIT%IB(KK,:).GT.1 ) .AND. ALL(SIT%JB(KK,:).GT.1 ) .AND. &
       & ALL(SIT%IB(KK,:).LT.GRD%IM ) .AND. ALL(SIT%JB(KK,:).LT.GRD%JM ) ) THEN
          SIT%FLC(KK) = 1
       ELSE
          SIT%FLC(KK) = 0
          SIT%EVE(KK) = KEVE_INTE
          CYCLE CYOBS
       ENDIF

       SIT%PQ(KK,1) = SIT%PQ(KK,1) * GRD%MSK(SIT%IB(KK,1),SIT%JB(KK,1),1)
       SIT%PQ(KK,2) = SIT%PQ(KK,2) * GRD%MSK(SIT%IB(KK,2),SIT%JB(KK,2),1)
       SIT%PQ(KK,3) = SIT%PQ(KK,3) * GRD%MSK(SIT%IB(KK,3),SIT%JB(KK,3),1)
       SIT%PQ(KK,4) = SIT%PQ(KK,4) * GRD%MSK(SIT%IB(KK,4),SIT%JB(KK,4),1)

       ZZSS = 0._R8
       DO JP=1,NPQ
         ZZSS = ZZSS + GRD%MSK(SIT%IB(KK,JP),SIT%JB(KK,JP),1)
       ENDDO

       IF( ABS( ZZSS ) .LT. 1._R8 ) THEN
           SIT%FLC(KK) = 0
           SIT%EVE(KK) = KEVE_MASK
           CYCLE CYOBS
       ELSE
           SIT%PQ(KK,:) = SIT%PQ(KK,:) / SUM(SIT%PQ(KK,:))
       ENDIF

ENDDO CYOBS
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

MSCOUNT=COUNT(SIT%EVE(1:SIT%NO).EQ.KEVE_INTE)
WRITE(IOUNLOG,*) &
& ' SIT OBS FILTERED OUT FOR INTERP PROBLEMS: ',MSCOUNT

MSCOUNT=COUNT(SIT%EVE(1:SIT%NO).EQ.KEVE_MASK)
WRITE(IOUNLOG,*) &
& ' SIT OBS FILTERED OUT FOR MASKING INCONSISTENCIES: ',MSCOUNT

! ---
! COUNT GOOD OBSERVATIONS
  SIT%NC = COUNT(SIT%FLC(1:SIT%NO) .EQ. 1)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' *** SIT OBS AFTER INTERPOLATION SET-UP'
  WRITE(IOUNLOG,*) ' TOTAL NUMBER OF SIT OBS           :',SIT%NO
  WRITE(IOUNLOG,*) ' TOTAL NUMBER OF RETAINED SIT  OBS :',SIT%NC

CALL MYFRTPROF_WALL('INT_PAR_SIT: SIT INTERPOLATION',1)
END SUBROUTINE INT_PAR_SIT
