SUBROUTINE READSIC

!! READ SPACE-BORNE SIC data FROM FILE

USE IOUNITS
USE RUN
USE SET_KND
USE OBS_STR
USE GRD_STR
USE ALLOCOBS
USE CALENDAR, ONLY : JU2YMDS


IMPLICIT NONE

INTEGER(I4) :: NOBS,IERR,JSAT,KFILE,KSAT,ISTART,&
             & K,IJ,JOBS,IDIFFER1,IRET,ISAT,KOS,IFILE
LOGICAL :: LLEXIST,LEX
INTEGER(I4),PARAMETER :: MAX_SICOBS = 10368000
CHARACTER(LEN=10) :: &
                   & CSICDATE,CTEMPDATE
CHARACTER(LEN=60) :: CFILEIN, CFILEIN2
REAL(R8),DIMENSION(MAX_SICOBS) :: ZLON,ZLAT,ZDAT,ZERR
REAL(DP),DIMENSION(MAX_SICOBS) :: ZTIM
REAL(R8)          :: DTSTART,DTEND
CHARACTER(LEN=10) :: CDTSTART,CDTEND
INTEGER(I4) :: YYYY,MM,DD
REAL(R8) :: SS, RDAY

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) '... ENTERING READSIC ...'

DTSTART = ZJULSTART - ZJUL1950
DTEND   = ZJULEND   - ZJUL1950

WRITE(IOUNLOG,*) ' STARTDATE (JULIAN DAYS SINCE 1950) : ', DTSTART
WRITE(IOUNLOG,*) ' END  DATE (JULIAN DAYS SINCE 1950) : ', DTEND
WRITE(IOUNLOG,*)


SIC%NO=0

CALL ALLOCSIC(MAX_SICOBS,.TRUE.)
KOS=0
   IF ( SIC%LLOSISAF ) THEN
       WRITE(IOUNLOG,*) '... READING OSISAF DATA ...'
       
       ISAT = 1
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSICDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0._8

       DO WHILE( CSICDATE .LE. CDTEND )

        WRITE(CFILEIN,'(A,A,A)') 'OSISAF_nh_',CSICDATE(1:8),&
        & '.nc'
        INQUIRE(FILE=CFILEIN,EXIST=LEX)
        IF(LEX) THEN

          CALL READ_OSISAF_SIC_NC(CFILEIN,MAX_SICOBS,NOBS,ZDAT,&
          & ZLON,ZLAT,ZERR)

          SIC%NO = SIC%NO + NOBS
          ISTART = SIC%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SIC%NO .GT. MAX_SICOBS ) &
        & CALL ABOR1('FATAL IN READSIC: MAX_SSTOBS MUST BE INCREASED')

          SIC%LON(ISTART:SIC%NO) = ZLON(1:NOBS)
          SIC%LAT(ISTART:SIC%NO) = ZLAT(1:NOBS)
          SIC%TIM(ISTART:SIC%NO) = DTSTART+RDAY
          SIC%VAL(ISTART:SIC%NO) = ZDAT(1:NOBS)
          SIC%ERR(ISTART:SIC%NO) = ZERR(1:NOBS)

          SIC%TDIST(ISTART:SIC%NO) = SIC%TIM(ISTART:SIC%NO) - ZANJUL1950
          SIC%KSAT (ISTART:SIC%NO) = ISAT
        ENDIF

        WRITE(CFILEIN,'(A,A,A)') 'OSISAF_sh_',CSICDATE(1:8),'.nc'
        INQUIRE(FILE=CFILEIN,EXIST=LEX)
        IF(LEX) THEN

          CALL READ_OSISAF_SIC_NC(CFILEIN,MAX_SICOBS,NOBS,ZDAT,&
          & ZLON,ZLAT,ZERR)

          SIC%NO = SIC%NO + NOBS
          ISTART = SIC%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SIC%NO .GT. MAX_SICOBS ) &
        & CALL ABOR1('FATAL IN READSIC: MAX_SSTOBS MUST BE INCREASED')

          SIC%LON(ISTART:SIC%NO) = ZLON(1:NOBS)
          SIC%LAT(ISTART:SIC%NO) = ZLAT(1:NOBS)
          SIC%TIM(ISTART:SIC%NO) = DTSTART+RDAY
          SIC%VAL(ISTART:SIC%NO) = ZDAT(1:NOBS)
          SIC%ERR(ISTART:SIC%NO) = ZERR(1:NOBS)

          SIC%TDIST(ISTART:SIC%NO) = SIC%TIM(ISTART:SIC%NO) - ZANJUL1950
          SIC%KSAT (ISTART:SIC%NO) = ISAT
        ENDIF

        RDAY = RDAY + 1._8
        CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
        WRITE(CSICDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

      ENDDO

       SIC%ISICOBS(ISAT) = KOS

   ENDIF
KOS=0
IF ( SIC%LLHADISST ) THEN
    WRITE(IOUNLOG,*) '... READING HADISST DATA ...'
    ISAT = 2
    CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
    WRITE(CSICDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
    CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
    WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
    RDAY=0._8

    DO WHILE( CSICDATE .LE. CDTEND )

     WRITE(CFILEIN,'(A,A,A)') 'HADISST_',CSICDATE(1:8),&
     & '.nc'
     INQUIRE(FILE=CFILEIN,EXIST=LEX)
     IF(LEX) THEN

       CALL READ_HADISST_SIC_NC(CFILEIN,MAX_SICOBS,NOBS,ZDAT,&
       & ZLON,ZLAT,ZERR,MM)

       SIC%NO = SIC%NO + NOBS
       ISTART = SIC%NO-NOBS+1
       KOS = KOS + NOBS

       IF( SIC%NO .GT. MAX_SICOBS ) &
     & CALL ABOR1('FATAL IN READSIC: MAX_SSTOBS MUST BE INCREASED')

       SIC%LON(ISTART:SIC%NO) = ZLON(1:NOBS)
       SIC%LAT(ISTART:SIC%NO) = ZLAT(1:NOBS)
       SIC%TIM(ISTART:SIC%NO) = DTSTART+RDAY
       SIC%VAL(ISTART:SIC%NO) = ZDAT(1:NOBS)
       SIC%ERR(ISTART:SIC%NO) = ZERR(1:NOBS)

       SIC%TDIST(ISTART:SIC%NO) = SIC%TIM(ISTART:SIC%NO) - ZANJUL1950
       SIC%KSAT (ISTART:SIC%NO) = ISAT
     ENDIF

     RDAY = RDAY + 1._8
    CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
    WRITE(CSICDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

   ENDDO

    SIC%ISICOBS(ISAT) = KOS

ENDIF


WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ========================================'
WRITE(IOUNLOG,*) ' SIC REPORT : TOTAL NO OF OBS IS',SIC%NO

END SUBROUTINE READSIC
