SUBROUTINE READ_GIOMAS_SIT_NC(CFILE,MAXOBS,NTOBS,ZDATA,&
          & ZLLON,ZLLAT,ZERR,MM)

USE SET_KND
USE RUN
USE NETCDF
USE IOUNITS
USE OBSHANDLING

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CFILE
INTEGER(I4), INTENT(IN) :: MAXOBS,MM
INTEGER(I4), INTENT(OUT) :: NTOBS
REAL   (R8), DIMENSION(MAXOBS), INTENT(OUT) :: ZDATA,&
          & ZLLON,ZLLAT,ZERR
INTEGER(I4) :: NX, NY,NT
REAL(R4), ALLOCATABLE ,  DIMENSION(:,:)  :: ZOLON,ZOLAT
REAL(R4), ALLOCATABLE ,  DIMENSION(:,:,:)  :: ZOSIT,ZOERR
!INTEGER , ALLOCATABLE ,  DIMENSION(:,:,:) :: ZOFLAG

INTEGER(I4) :: STAT,IDIM,IDVAR,NCID,JX,JY,JT

WRITE(IOUNLOG,*) ' :: OPENING GIOMAS SIT FILE '//TRIM(CFILE)


STAT=NF90_OPEN(CFILE,NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

!WRITE(IOUNLOG,*) 'xc '
STAT = NF90_INQ_DIMID (NCID, 'i', IDIM)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID, IDIM, LEN = NX)

!WRITE(IOUNLOG,*) 'yc '
STAT = NF90_INQ_DIMID (NCID, 'j', IDIM)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID, IDIM, LEN = NY)

STAT = NF90_INQ_DIMID (NCID, 'n', IDIM)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID, IDIM, LEN = NT)

ALLOCATE(ZOLON(NX,NY),ZOLAT(NX,NY))
ALLOCATE(ZOSIT(NX,NY,NT),ZOERR(NX,NY,NT))

!WRITE(IOUNLOG,*) 'lon '
STAT = NF90_INQ_VARID (NCID, 'lon_scaler', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,ZOLON)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

WHERE(ZOLON(:,:) .GT. 180.) ZOLON=ZOLON-360
!WRITE(IOUNLOG,*) 'lat '

STAT = NF90_INQ_VARID (NCID, 'lat_scaler', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,ZOLAT)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

!WRITE(IOUNLOG,*) 'ice_conc '

STAT = NF90_INQ_VARID (NCID, 'heff', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,ZOSIT)
STAT=NF90_CLOSE(NCID)


!WRITE(IOUNLOG,*) 'total_standard_error '
STAT=NF90_OPEN("giomas_std.nc",NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (NCID, 'heff', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,ZOERR,start=(/1,1,MM/),count=(/NX,NY,1/))
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

WHERE(ZOERR .LT. 0.1 ) ZOERR=0.1

WRITE(IOUNLOG,*) ' :: ONLY SOUTHER HEM DATA ARE ASSIMILATED '

DO JT=1,NT
   WHERE(ZOLAT(:,:) .gt. 0. ) ZOSIT(:,:,JT)=9999.9
ENDDO

!WRITE(IOUNLOG,*) ' :: REDUCING FROM [0-100] to [0-1]  '

!STAT = NF90_INQ_VARID (NCID, 'status_flag', IDVAR)
!IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
!STAT = NF90_GET_VAR (NCID,IDVAR,ZOFLAG)
!IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
!no check on the time
!STAT = NF90_INQ_VARID (NCID, 'time', IDVAR)
!IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
!STAT = NF90_GET_VAR (NCID,IDVAR,ZOTIM)
!IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
!!seconds from 19780101
!CALL YMDS2JU(1978,01,01,0._DP,ZJUL1978)

STAT=NF90_CLOSE(NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

NTOBS=0

DO JT=1,NT
 DO JY=1,NY
  DO JX=1,NX
        IF(ZOSIT(JX,JY,JT).GE. 0. .AND. ZOSIT(JX,JY,JT).LE. 10. ) THEN
          NTOBS=NTOBS+1
          IF(NTOBS.GT.MAXOBS) &
          & CALL ABOR1('READ_PIOAMS_SIT_NC   : MAXOBS TO INCREASE')
          ZDATA(NTOBS) = REAL(ZOSIT(JX,JY,JT),KIND=R8)
          ZLLON(NTOBS) = REAL(ZOLON(JX,JY),KIND=R8)
          ZLLAT(NTOBS) = REAL(ZOLAT(JX,JY),KIND=R8)
          ZERR(NTOBS)  = REAL(ZOERR(JX,JY,1),KIND=R8)*COEFF_SIT_ERR_GIOMAS
         ENDIF
  ENDDO
 ENDDO
ENDDO

WRITE(IOUNLOG,*) ' --> FOUND ',NTOBS,' OBSERVATIONS'
DEALLOCATE(ZOSIT,ZOLAT,ZOERR,ZOLON)

END SUBROUTINE READ_GIOMAS_SIT_NC

