SUBROUTINE READSIT

!! READ SPACE-BORNE SIT data FROM FILE

USE IOUNITS
USE RUN
USE SET_KND
USE OBS_STR
USE GRD_STR
USE ALLOCOBS
USE CALENDAR, ONLY : JU2YMDS


IMPLICIT NONE

INTEGER(I4) :: NOBS,IERR,JSAT,KFILE,KSAT,ISTART,&
             & K,IJ,JOBS,IDIFFER1,IRET,ISAT,KOS,IFILE
LOGICAL :: LLEXIST,LEX
INTEGER(I4),PARAMETER :: MAX_SITOBS = 10368000
CHARACTER(LEN=10) :: &
                   & CSITDATE,CTEMPDATE
CHARACTER(LEN=60) :: CFILEIN, CFILEIN2
REAL(R8),DIMENSION(MAX_SITOBS) :: ZLON,ZLAT,ZDAT,ZERR
REAL(DP),DIMENSION(MAX_SITOBS) :: ZTIM
REAL(R8)          :: DTSTART,DTEND
CHARACTER(LEN=10) :: CDTSTART,CDTEND
INTEGER(I4) :: YYYY,MM,DD
REAL(R8) :: SS, RDAY

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) '... ENTERING READSIT ...'

DTSTART = ZJULSTART - ZJUL1950
DTEND   = ZJULEND   - ZJUL1950

WRITE(IOUNLOG,*) ' STARTDATE (JULIAN DAYS SINCE 1950) : ', DTSTART
WRITE(IOUNLOG,*) ' END  DATE (JULIAN DAYS SINCE 1950) : ', DTEND
WRITE(IOUNLOG,*)


SIT%NO=0

WRITE(IOUNLOG,*) "WARNING!! ALSO OBS SIT DIVIDED BY TEN (ALSO THE MINIMUM IN ASSIGN ERR"
! The current configurtion works not in meter by 10m, soobs must be divided by
! 10 !

CALL ALLOCSIT(MAX_SITOBS,.TRUE.)

    IF ( SIT%LLESACRY2 ) THEN
         WRITE(IOUNLOG,*) '... READING CRYOSAT2 SIT DATA ...'
         KOS=0
         ISAT = 1
         CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
         WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
         CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
         WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
         RDAY=0._8

         DO WHILE( CSITDATE .LE. CDTEND )

          WRITE(CFILEIN,'(A,A,A)') 'ESACRYO2_nh_',CSITDATE(1:8),&
          & '.nc'
          INQUIRE(FILE=CFILEIN,EXIST=LEX)
          IF(LEX) THEN

            CALL READ_ESACRYO2_SIT_NC(CFILEIN,MAX_SITOBS,NOBS,ZDAT,&
            & ZLON,ZLAT,ZERR)

            SIT%NO = SIT%NO + NOBS
            ISTART = SIT%NO-NOBS+1
            KOS = KOS + NOBS

            IF( SIT%NO .GT. MAX_SITOBS ) &
          & CALL ABOR1('FATAL IN READSIT: MAX_SITOBS MUST BE INCREASED')

            SIT%LON(ISTART:SIT%NO) = ZLON(1:NOBS)
            SIT%LAT(ISTART:SIT%NO) = ZLAT(1:NOBS)
            SIT%TIM(ISTART:SIT%NO) = DTSTART+RDAY
            SIT%VAL(ISTART:SIT%NO) = ZDAT(1:NOBS) / 10._R8
            SIT%ERR(ISTART:SIT%NO) = ZERR(1:NOBS) /10._R8

            SIT%TDIST(ISTART:SIT%NO) = SIT%TIM(ISTART:SIT%NO) - ZANJUL1950
            SIT%KSAT (ISTART:SIT%NO) = ISAT
          ENDIF

          RDAY = RDAY + 1._8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

        ENDDO
        SIT%ISITOBS(ISAT) = KOS

     ENDIF

     IF ( SIT%LLSMOS ) THEN
          WRITE(IOUNLOG,*) '... READING SMOS SIT DATA ...'
          KOS=0
          ISAT = 2
          CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
          WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
          WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          RDAY=0._8

          DO WHILE( CSITDATE .LE. CDTEND )

           WRITE(CFILEIN,'(A,A,A)') 'SMOS_nh_',CSITDATE(1:8),&
           & '.nc'
           INQUIRE(FILE=CFILEIN,EXIST=LEX)
           IF(LEX) THEN

             CALL READ_SMOS_SIT_NC(CFILEIN,MAX_SITOBS,NOBS,ZDAT,&
             & ZLON,ZLAT,ZERR)

             SIT%NO = SIT%NO + NOBS
             ISTART = SIT%NO-NOBS+1
             KOS = KOS + NOBS

             IF( SIT%NO .GT. MAX_SITOBS ) &
           & CALL ABOR1('FATAL IN READSIT: MAX_SITOBS MUST BE INCREASED')

             SIT%LON(ISTART:SIT%NO) = ZLON(1:NOBS)
             SIT%LAT(ISTART:SIT%NO) = ZLAT(1:NOBS)
             SIT%TIM(ISTART:SIT%NO) = DTSTART+RDAY
             SIT%VAL(ISTART:SIT%NO) = ZDAT(1:NOBS) /10._R8
             SIT%ERR(ISTART:SIT%NO) = ZERR(1:NOBS) /10._R8

             SIT%TDIST(ISTART:SIT%NO) = SIT%TIM(ISTART:SIT%NO) - ZANJUL1950
             SIT%KSAT (ISTART:SIT%NO) = ISAT
           ENDIF

           RDAY = RDAY + 1._8
           CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
           WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

         ENDDO
         SIT%ISITOBS(ISAT) = KOS

      ENDIF

     IF ( SIT%LLCRYOSMOSMERGED ) THEN
          WRITE(IOUNLOG,*) '... READING CRYO-SMOS MERGED SIT DATA ...'
          KOS=0
          ISAT = 3
          CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
          WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
          WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          RDAY=0._8

          DO WHILE( CSITDATE .LE. CDTEND )

           WRITE(CFILEIN,'(A,A,A)') 'CRYO2-SMOS_MERGED_nh_',CSITDATE(1:8),&
           & '.nc'
           INQUIRE(FILE=CFILEIN,EXIST=LEX)
           IF(LEX) THEN

             CALL READ_CRYO2SMOS_MERGED_SIT_NC(CFILEIN,MAX_SITOBS,NOBS,ZDAT,&
             & ZLON,ZLAT,ZERR)

             SIT%NO = SIT%NO + NOBS
             ISTART = SIT%NO-NOBS+1
             KOS = KOS + NOBS

             IF( SIT%NO .GT. MAX_SITOBS ) &
           & CALL ABOR1('FATAL IN READSIT: MAX_SITOBS MUST BE INCREASED')

             SIT%LON(ISTART:SIT%NO) = ZLON(1:NOBS)
             SIT%LAT(ISTART:SIT%NO) = ZLAT(1:NOBS)
             SIT%TIM(ISTART:SIT%NO) = DTSTART+RDAY
             SIT%VAL(ISTART:SIT%NO) = ZDAT(1:NOBS) /10._R8
             SIT%ERR(ISTART:SIT%NO) = ZERR(1:NOBS) /10._R8

             SIT%TDIST(ISTART:SIT%NO) = SIT%TIM(ISTART:SIT%NO) - ZANJUL1950
             SIT%KSAT (ISTART:SIT%NO) = ISAT
           ENDIF

           RDAY = RDAY + 1._8
           CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
           WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

         ENDDO
         SIT%ISITOBS(ISAT) = KOS
      ENDIF

      IF ( SIT%LLPIOMAS ) THEN
          WRITE(IOUNLOG,*) '... READING PIOMAS SIT DATA ...'
          KOS=0
          ISAT = 4
          CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
          WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
          WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          RDAY=0._8

          DO WHILE( CSITDATE .LE. CDTEND )

           WRITE(CFILEIN,'(A,A,A)') 'PIOMAS_',CSITDATE(1:8),&
           & '.nc'
           INQUIRE(FILE=CFILEIN,EXIST=LEX)
           IF(LEX) THEN

             CALL READ_PIOMAS_SIT_NC(CFILEIN,MAX_SITOBS,NOBS,ZDAT,&
             & ZLON,ZLAT,ZERR,MM)

             SIT%NO = SIT%NO + NOBS
             ISTART = SIT%NO-NOBS+1
             KOS = KOS + NOBS

             IF( SIT%NO .GT. MAX_SITOBS ) &
           & CALL ABOR1('FATAL IN READSIT: MAX_SITOBS MUST BE INCREASED')

             SIT%LON(ISTART:SIT%NO) = ZLON(1:NOBS)
             SIT%LAT(ISTART:SIT%NO) = ZLAT(1:NOBS)
             SIT%TIM(ISTART:SIT%NO) = DTSTART+RDAY
             SIT%VAL(ISTART:SIT%NO) = ZDAT(1:NOBS) /10._R8
             SIT%ERR(ISTART:SIT%NO) = ZERR(1:NOBS) /10._R8

             SIT%TDIST(ISTART:SIT%NO) = SIT%TIM(ISTART:SIT%NO) - ZANJUL1950
             SIT%KSAT (ISTART:SIT%NO) = ISAT
           ENDIF

           RDAY = RDAY + 1._8
           CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
           WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

         ENDDO
         SIT%ISITOBS(ISAT) = KOS
      ENDIF

      IF ( SIT%LLGIOMAS ) THEN
          WRITE(IOUNLOG,*) '... READING GIOMAS SIT DATA ...'
          KOS=0
          ISAT = 5
          CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
          WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
          WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
          RDAY=0._8

          DO WHILE( CSITDATE .LE. CDTEND )

           WRITE(CFILEIN,'(A,A,A)') 'GIOMAS_',CSITDATE(1:8),&
           & '.nc'
           INQUIRE(FILE=CFILEIN,EXIST=LEX)
           IF(LEX) THEN

             CALL READ_GIOMAS_SIT_NC(CFILEIN,MAX_SITOBS,NOBS,ZDAT,&
             & ZLON,ZLAT,ZERR,MM)

             SIT%NO = SIT%NO + NOBS
             ISTART = SIT%NO-NOBS+1
             KOS = KOS + NOBS

             IF( SIT%NO .GT. MAX_SITOBS ) &
           & CALL ABOR1('FATAL IN READSIT: MAX_SITOBS MUST BE INCREASED')

             SIT%LON(ISTART:SIT%NO) = ZLON(1:NOBS)
             SIT%LAT(ISTART:SIT%NO) = ZLAT(1:NOBS)
             SIT%TIM(ISTART:SIT%NO) = DTSTART+RDAY
             SIT%VAL(ISTART:SIT%NO) = ZDAT(1:NOBS) /10._R8
             SIT%ERR(ISTART:SIT%NO) = ZERR(1:NOBS) /10._R8

             SIT%TDIST(ISTART:SIT%NO) = SIT%TIM(ISTART:SIT%NO) - ZANJUL1950
             SIT%KSAT (ISTART:SIT%NO) = ISAT
           ENDIF

           RDAY = RDAY + 1._8
           CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
           WRITE(CSITDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

         ENDDO
         SIT%ISITOBS(ISAT) = KOS
      ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ========================================'
WRITE(IOUNLOG,*) ' SIT REPORT : TOTAL NO OF OBS IS',SIT%NO

END SUBROUTINE READSIT
