SUBROUTINE READFGFIELDS_ICE(ICEB,TRA_ICEB,SIC_OR_SIT)
USE SET_KND
USE IOUNITS, ONLY : IOUNERR,IOUNOUT,IOUNLOG
USE GRD_STR, ONLY : GRD
USE READFG
USE RUN, ONLY : NTSTEPS, LL_RESTART_FILE, NSUBDOMAINS
USE MPIREL
USE MYNETCDF
USE ICE_TRANSF
IMPLICIT NONE

REAL(R8),DIMENSION(GRD%IM,GRD%JM,NFGTSTEPS), INTENT(INOUT) :: ICEB,TRA_ICEB
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:)   :: W3D
INTEGER(I4) :: ISTARTX,ISTARTY,IENDX,IENDY
INTEGER(I4) :: ISX,ISY,IEX,IEY,I,J,status
INTEGER(I4) :: JF,MNX,MNY
INTEGER(I4) :: MAXX,MAXY
INTEGER(I4) :: TSFIRST, JT
INTEGER(I4) :: JR,KR
INTEGER(I4), INTENT(IN) :: SIC_OR_SIT
CHARACTER(LEN=8) :: CVARS(2)=(/"soicecov","icethic"/)
CHARACTER(LEN=100) :: CFGFILES_open, CAUX

!IF( LL_RESTART_FILE ) THEN
!  CVARS(1)(1:8) = 'soicecov'
!  CVARS(2)(1:8) = 'icethic'
!ELSE
!  CVARS(1)(1:8) = 'soicecov'
!  CVARS(2)(1:8) = 'icethic'
!ENDIF

MAXX=MAXVAL(KDSL(1:NFGFILES,1))
MAXY=MAXVAL(KDSL(1:NFGFILES,2))

WRITE(IOUNLOG,*) '  CHECK --- NFGFILES = ',NFGFILES
WRITE(IOUNLOG,*) '  MAXVALUES FOR LOCAL DOMAIN SIZE =',MAXX,MAXY

ALLOCATE ( W3D(MAXX,MAXY,NFGTSTEPS))

!
!IMESTEPS : DO JT = 1,NTSTEPS
!IF (LL_FGASSIM(JT) ) THEN
!    TSFIRST =  JT
!    EXIT TIMESTEPS
!ENDIF
!NDDO TIMESTEPS
TSFIRST = 1
!IF(LMPION) THEN
!  OPEN(901,FILE='FIRSTGUESS_READING.OUT.'//TRIM(CMPIDOM))
!ELSE
!  OPEN(901,FILE='FIRSTGUESS_READING.OUT')
!ENDIF


DO JF=1,NFGFILES

  IF( LMPION .AND. NSUBDOMAINS .EQ. 0) THEN
        IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_ice.nc'
 !           WRITE(IOUNLOG,*) TRIM(CFGFILES_open),GRD%IM,GRD%JM,TSFIRST,NFGTSTEPS
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(SIC_OR_SIT)),GRD%IM,GRD%JM,TSFIRST,NFGTSTEPS,ICEB)
        WHERE(abs(ICEB) .GT. 10000.) ICEB=0.
        ELSE
          !IF(LL_READBYREC) THEN
          !  KR=0
          !  DO JR=TSFIRST,NFGTSTEPS
          !    KR=KR+1
          !    WRITE(CAUX,'(A,I4.4,A)') TRIM(CBGDIR)//'/'//'OPA_FIRSTGUESS_record_',JR,'.nc'
          !    CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(6)),GRD%IM,GRD%JM,       T2M(:,:,  KR))
          !    CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(7)),GRD%IM,GRD%JM,       Q2M(:,:,  KR))
          !  ENDDO
          !ELSE
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_ice.nc'
!            WRITE(IOUNLOG,*) 'now  ',TRIM(CFGFILES_open),GRD%IM,GRD%JM,TSFIRST,NFGTSTEPS
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(SIC_OR_SIT)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,ICEB)
          !  CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(7)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,Q2M)
          !ENDIF
        WHERE(abs(ICEB) .GT. 10000.) ICEB=0.
        ENDIF

  ELSE

   ISTARTX=KDNS(JF,1)-MP_XST(MYPROC)+1
   ISTARTY=KDNS(JF,2)-MP_YST(MYPROC)+1
   IENDX=KDNE(JF,1)-MP_XST(MYPROC)+1
   IENDY=KDNE(JF,2)-MP_YST(MYPROC)+1
   ISX=KDLS(JF,1)
   ISY=KDLS(JF,2)
   IEX=KDLE(JF,1)
   IEY=KDLE(JF,2)

   MNX=KDSL(JF,1)
   MNY=KDSL(JF,2)

   WRITE(IOUNLOG,*) ' === LOCAL SIZE FOR DOMAIN',JF,' :',MNX,MNY,NFGTSTEPS
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) '    N      FILE         MNX  MAXX '; CALL FLUSH(IOUNLOG)
   WRITE(IOUNLOG,*) ' ',JF, TRIM(CFGFILES(JF)),MNX,MAXX ; CALL FLUSH(IOUNLOG)
   WRITE(IOUNLOG,*) ' LAYOUT FOR DOMAIN',JF,':',ISTARTX,IENDX,ISTARTY,IENDY
   WRITE(IOUNLOG,*) ' WHICH IS IN FILE:',ISX,IEX,ISY,IEY
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) ' ABOUT TO READ SIC FIELDS'
   CALL FLUSH(IOUNLOG)

   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
     WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_ice.nc'
   ELSE
     WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF

   CALL READFGETAB(TRIM(CFGFILES_open),TRIM(CVARS(SIC_OR_SIT)),MNX,MNY,TSFIRST,NFGTSTEPS,MAXX,MAXY,&
   & W3D,.TRUE.,.TRUE.,NCIDFG(JF) )
   WRITE(IOUNLOG,*) ' DONE'
   WRITE(IOUNLOG,*) ' SIC/SIT  - LOCAL TO GLOBAL COPY'
   CALL FLUSH(IOUNLOG)
   ICEB(ISTARTX:IENDX,ISTARTY:IENDY,:) = W3D(ISX:IEX,ISY:IEY,:)
   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

  ENDIF

ENDDO
DEALLOCATE( W3D )

WRITE(IOUNLOG,*) ' TRANSFORMING VARIABLE THROUGH ANAMORPHOSIS '
DO JF=1,NFGFILES
   TRA_ICEB(:,:,JF)=0._R8
   IF (SIC_OR_SIT .EQ. 1) THEN
           DO J=1,GRD%JM
           DO I=1,GRD%IM
              IF (GRD%MSK(I,J,1) .LT. 0.9_R8 .OR. ICEB(I,J,JF) .EQ. 0._R8 .OR. ICEB(I,J,JF) .GT. 99999._R8 ) CYCLE
              TRA_ICEB(I,J,JF)=ICEB(I,J,JF)
              CALL sangoma_anamorphosis(1,qdim_sic,1,qua_ref_sic,SIC_QUANT(:,:,I,J),TRA_ICEB(I,J,JF),status)
           ENDDO
           ENDDO
    ENDIF
    IF (SIC_OR_SIT .EQ. 2) THEN

          WRITE(IOUNLOG,*) ' !!!! warning!!! '
           WRITE(IOUNLOG,*) ' !!!! sit divided by 10 as in EOF'
           ICEB=ICEB/10._R8
           DO J=1,GRD%JM
           DO I=1,GRD%IM
              IF (GRD%MSK(I,J,1) .LT. 0.9_R8 .OR. ICEB(I,J,JF) .EQ. 0._R8 .OR. ICEB(I,J,JF) .GT. 99999._R8 ) CYCLE
              TRA_ICEB(I,J,JF)=ICEB(I,J,JF)
              CALL sangoma_anamorphosis(1,qdim_sit,1,qua_ref_sit,SIT_QUANT(:,:,I,J),TRA_ICEB(I,J,JF),status)
           ENDDO
           ENDDO
    ENDIF
   
ENDDO
END SUBROUTINE READFGFIELDS_ICE

