SUBROUTINE ABOR1FL(CDFILE, KLINENUM, CDTEXT)
USE SET_KND  ,ONLY : I4
USE IOUNITS, ONLY : IOUNERR
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CDFILE,CDTEXT
INTEGER(KIND=I4), INTENT(IN) :: KLINENUM
IF (LEN(CDFILE) > 0 .AND. KLINENUM > 0 .AND. IOUNERR >= 0) THEN
 1000 FORMAT(1X,A,A,":",I6.6)
  WRITE(IOUNERR,1000) 'ABOR1FL HAS BEEN CALLED AT ',CDFILE,KLINENUM
  CALL FLUSH(IOUNERR)
ENDIF
CALL ABOR1(CDTEXT)
END SUBROUTINE ABOR1FL
