SUBROUTINE ADDTIME(COPT,CDATE1,CDATE2,IDIFFER,IRETC,LWRN)

!
! DRIVING ROUTINE FOR ADDDATE
! A.STORTO
!

USE TIMEFINC

IMPLICIT NONE


CHARACTER,INTENT(IN) :: COPT
CHARACTER(LEN=*),INTENT(INOUT) :: CDATE1
CHARACTER(LEN=*),INTENT(OUT) :: CDATE2
INTEGER,INTENT(IN) :: IDIFFER
INTEGER,INTENT(OUT) :: IRETC
LOGICAL,INTENT(IN) :: LWRN

INTEGER :: IDAYS,IHOURS,IMINS,ISEC,DATE1,DATE2,II
LOGICAL :: LNOEXIT
INTEGER :: IDATETEMP,IDATEARR,ISIGNPN,IDATE1(6),IDATE2(6),IDIFF(6)
INTEGER :: IRET,IL1,IL2
CHARACTER(LEN=10) :: CSTRING

LNOEXIT=LWRN
IRETC=0

CALL TOUPPERDT(COPT)

IDATE1=0
IDATE2=0
IDIFF=0

IL1=LEN_TRIM(CDATE1)
IL2=LEN_TRIM(CDATE2)

DO II=1,IL2
    CDATE2(II:II)=' '
ENDDO

IF(IL1.LT.8 .OR. IL2.LT.8) CALL WRLNG(LNOEXIT,1,IRETC)

READ(CDATE1(1:4),*) IDATE1(1)
READ(CDATE1(5:6),*) IDATE1(2)
READ(CDATE1(7:8),*) IDATE1(3)

SELECT CASE(COPT)

      CASE('D')   ! DAYS

           IDIFF(3)=IDIFFER

      CASE('H')   ! HOURS

           IF(IL1.LT.10 .OR. IL2.LT.10) CALL WRLNG(LNOEXIT,1,IRETC)
           READ(CDATE1(9:10),*) IDATE1(4)
           IDIFF(4)=IDIFFER

      CASE('M')   ! MINUTES

           IF(IL1.LT.12 .OR. IL2.LT.12) CALL WRLNG(LNOEXIT,1,IRETC)
           READ(CDATE1(9:10),*) IDATE1(4)
           READ(CDATE1(11:12),*) IDATE1(5)
           IDIFF(5)=IDIFFER

      CASE('S')   ! SECONDS

           IF(IL1.LT.14 .OR. IL2.LT.14) CALL WRLNG(LNOEXIT,1,IRETC)
           READ(CDATE1(9:10),*) IDATE1(4)
           READ(CDATE1(11:12),*) IDATE1(5)
           READ(CDATE1(13:14),*) IDATE1(6)
           IDIFF(6)=IDIFFER

      CASE DEFAULT

           WRITE(0,*) '*** FROM NEWDATE:'
           WRITE(0,*) 'ILLEGAL OPTION ',COPT

           IRETC=-1
           IF(LNOEXIT) THEN
              WRITE(0,*) 'CONTINUING...'
           ELSE
              STOP 'EXITING'
           ENDIF

ENDSELECT

IRET=CHECK_TIME(IDATE1,1)
IF(IRET.NE.0) IRETC=IRET
IF(IRET.NE.0 .AND. .NOT.LNOEXIT) STOP 'EXITING'

!..... COMMON CALL TO ADDDATE

CALL ADDDATE(IDATE1,IDIFF,IDATE2)

IRET=CHECK_TIME(IDATE2,1)
IF(IRET.NE.0) IRETC=IRET
IF(IRET.NE.0 .AND. .NOT.LNOEXIT) STOP 'EXITING'

WRITE(CDATE2(1:8),'(I4.4,I2.2,I2.2)') IDATE2(1),IDATE2(2),IDATE2(3)

!... ADD RIGHT SUFFIX

SELECT CASE(COPT)

      CASE('D')   ! DAYS

           ! NOTHING TO DO

      CASE('H')   ! HOURS

           WRITE(CDATE2(9:10),'(I2.2)') IDATE2(4)

      CASE('M')   ! MINUTES

           WRITE(CDATE2(9:12),'(I2.2,I2.2)') IDATE2(4),IDATE2(5)

      CASE('S')   ! SECONDS

           WRITE(CDATE2(9:14),'(I2.2,I2.2,I2.2)') IDATE2(4),IDATE2(5),IDATE2(6)

END SELECT

END SUBROUTINE ADDTIME
