SUBROUTINE ADDTIMER(COPT,CDATE1,CDATE2,IDIFFER,IRETC,LWRN)

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
CHARACTER,INTENT(IN) :: COPT
CHARACTER(LEN=*),INTENT(INOUT) :: CDATE1,CDATE2
INTEGER(KIND=JPIM),INTENT(OUT) :: IRETC
INTEGER(KIND=JPIM),INTENT(IN) :: IDIFFER
INTEGER :: IDIFFERL,IRETCL
LOGICAL,INTENT(IN) :: LWRN

IDIFFERL=INT(IDIFFER)
CALL ADDTIME(COPT,CDATE1,CDATE2,IDIFFERL,IRETCL,LWRN)
IRETC=INT(IRETCL,KIND=JPIM)
END SUBROUTINE ADDTIMER
