SUBROUTINE CALCDETA(KX,KY,KZ,SAL,TEM,SALB,TEMB,ZETAN)

!.. DIAGNOSE INCREMENT OF SSH
!..
!.. A.S.

USE SET_KND
USE GRD_STR
USE OCEANTOOLS , ONLY : RHO_UNESCO, RHO_UNESCOTL

IMPLICIT NONE


INTEGER(I4), INTENT(IN) :: KX,KY,KZ
REAL(R8), INTENT(IN),DIMENSION(KX,KY,KZ) :: SAL,TEM,SALB,TEMB
REAL(R8), INTENT(OUT),DIMENSION(KX,KY) :: ZETAN

INTEGER(I4) :: JX,JY,JZ
REAL(R8) :: ZRHOTL,ZRHO0,ZAT,ZAS

ZRHO0=RHO_UNESCO(35.0_R8 ,0.0_R8 ,0.0_R8 ,.FALSE.)
ZETAN=0._R8

DO JX=1,KX
  DO JY=1,KY

     ZRHOTL=0._R8

     DO JZ=1,KZ

          IF(ABS(SAL(JX,JY,JZ)).LT.50._R8 .AND.&
          &  ABS(SAL(JX,JY,JZ)).LT.50._R8 .AND.&
          &  ABS(SAL(JX,JY,JZ)).LT.50._R8 .AND.&
          &  ABS(SAL(JX,JY,JZ)).LT.50._R8 ) THEN

            ZAS=SAL(JX,JY,JZ)-SALB(JX,JY,JZ)
            ZAT=TEM(JX,JY,JZ)-TEMB(JX,JY,JZ)
            ZRHOTL=ZRHOTL+RHO_UNESCOTL(SALB(JX,JY,JZ),TEMB(JX,JY,JZ),&
                & ZAS,ZAT,0._R8,.FALSE.)*GRD%DEP(JZ)

          ENDIF

     ENDDO

     ZETAN(JX,JY) = -1._R8*ZRHOTL/ZRHO0

  ENDDO
ENDDO

END SUBROUTINE CALCDETA
