SUBROUTINE COASTREJ

! COASTAL REJECTION

USE SET_KND
USE GRD_STR
USE OBS_STR
USE IOUNITS
USE RUN
USE MYFRTPROF

IMPLICIT NONE

INTEGER(I4) :: JP,K, MSCOUNT
REAL   (R8) :: ZDC

#include "obs_events.h"

CALL MYFRTPROF_WALL('COASTREJ: COASTAL REJECTION',0)

WRITE(IOUNLOG,*)

IF( LL_COASTREJ_INS .AND. INS%NO .GT. 0) THEN
  DO K=1,INS%NO
    IF(INS%FLC(K).EQ.1) THEN
       ZDC=0._R8
       DO JP=1,NPQ
          ZDC=ZDC+INS%PQ(K,JP)*GRD%DISTC(INS%IB(K,JP),INS%JB(K,JP))
       ENDDO
       DO JP=1,NPQ
          ZDC=ZDC+INS%PQ(K,NPQ+JP)*GRD%DISTC(INS%IB(K,JP),INS%JB(K,JP))
       ENDDO
       IF(ZDC .LT. REAL(NN_COASTREJ_INS)*1000._R8) THEN
           INS%FLC(K)=0
           INS%EVE(K)=KEVE_DSTC
       ENDIF
    ENDIF
  ENDDO
  MSCOUNT=COUNT(INS%EVE(1:INS%NO).EQ.KEVE_DSTC)
  WRITE(IOUNLOG,*) &
  & ' INS REJECTED DUE TO COASTAL REJECTION :',MSCOUNT
ENDIF

IF( LL_COASTREJ_SLA .AND. SLA%NO .GT. 0) THEN
  DO K=1,SLA%NO
    IF(SLA%FLC(K).EQ.1) THEN
       ZDC=0._R8
       DO JP=1,NPQ
          ZDC=ZDC+SLA%PQ(K,JP)*GRD%DISTC(SLA%IB(K,JP),SLA%JB(K,JP))
       ENDDO
       IF(ZDC .LT. REAL(NN_COASTREJ_SLA)*1000._R8) THEN
           SLA%FLC(K)=0
           SLA%EVE(K)=KEVE_DSTC
       ENDIF
    ENDIF
  ENDDO
  MSCOUNT=COUNT(SLA%EVE(1:SLA%NO).EQ.KEVE_DSTC)
  WRITE(IOUNLOG,*) &
  & ' SLA REJECTED DUE TO COASTAL REJECTION :',MSCOUNT
ENDIF

IF( LL_COASTREJ_SST .AND. SST%NO .GT. 0) THEN
  DO K=1,SST%NO
    IF(SST%FLC(K).EQ.1) THEN
       ZDC=0._R8
       DO JP=1,NPQ
          ZDC=ZDC+SST%PQ(K,JP)*GRD%DISTC(SST%IB(K,JP),SST%JB(K,JP))
       ENDDO
       IF(ZDC .LT. REAL(NN_COASTREJ_SST)*1000._R8) THEN
           SST%FLC(K)=0
           SST%EVE(K)=KEVE_DSTC
       ENDIF
    ENDIF
  ENDDO
  MSCOUNT=COUNT(SST%EVE(1:SST%NO).EQ.KEVE_DSTC)
  WRITE(IOUNLOG,*) &
  & ' SST REJECTED DUE TO COASTAL REJECTION :',MSCOUNT
ENDIF

IF( LL_COASTREJ_SSS .AND. SSS%NO .GT. 0) THEN
  DO K=1,SSS%NO
    IF(SSS%FLC(K).EQ.1) THEN
       ZDC=OSUM(SSS%PQ(K,:),GRD%DISTC(SSS%IB(K,:),SSS%JB(K,:)))
       IF(ZDC .LT. REAL(NN_COASTREJ_SSS)*1000._R8) THEN
           SSS%FLC(K)=0
           SSS%EVE(K)=KEVE_DSTC
       ENDIF
    ENDIF
  ENDDO
  MSCOUNT=COUNT(SSS%EVE(1:SSS%NO).EQ.KEVE_DSTC)
  WRITE(IOUNLOG,*) &
  & ' SSS REJECTED DUE TO COASTAL REJECTION :',MSCOUNT
ENDIF

CALL MYFRTPROF_WALL('COASTREJ: COASTAL REJECTION',1)
END SUBROUTINE COASTREJ
