SUBROUTINE DEALLBG

USE GRD_STR
USE MYFRTPROF
USE READFG
USE ICE_TRANSF

IMPLICIT NONE

 CALL MYFRTPROF_WALL('DEALLBG: DEALLOCATE BG FIELDS',0)

 DEALLOCATE( GRD%TEMB ) 
 DEALLOCATE( GRD%SALB ) 
 DEALLOCATE( GRD%ETAB ) 
 DEALLOCATE( LL_FGASSIM )
 IF(ALLOCATED(GRD%T2MB) ) DEALLOCATE(GRD%T2MB,GRD%Q2MB)
 IF(ALLOCATED(GRD%TRA_SICB) ) DEALLOCATE(GRD%TRA_SICB)
 IF(ALLOCATED(GRD%TRA_SITB) ) DEALLOCATE(GRD%TRA_SITB)
 IF(ALLOCATED(SIC_quant) ) DEALLOCATE(SIC_quant)
 IF(ALLOCATED(SIT_quant) ) DEALLOCATE(SIT_quant)

 CALL MYFRTPROF_WALL('DEALLBG: DEALLOCATE BG FIELDS',1)

END SUBROUTINE DEALLBG
