        SUBROUTINE DEF_NML

        !-----------------------------------------------------------------------
        !                                                                      !
        ! DEFINE ANALYSIS PARAMETERS FROM NAMELISTS                            !
        !                                                                      !
        ! VERSION 1: S.DOBRICIC 2006                                           !
        ! VERSION 2: A.STORTO   2009  -  GLOBAL OCEAN ADAPTATION               ! 
        ! VERSION 3: A.STORTO   2011  -  CLEANING + EXTENSION                  ! 
        !-----------------------------------------------------------------------

          USE SET_KND
          USE DRV_STR
          USE GRD_STR
          USE BMD_STR
          USE OBS_STR, ONLY : SLA,SST,INS,OBS,SSS
          USE EOF_STR
          USE CTL_STR
          USE OBSDEF
          USE IOUNITS
          USE RUN
          USE BAL
          USE EXTGRID
          USE OBSHANDLING
          USE RECFILTER
          USE WRITECORR
          USE DEBUGTMP
          USE ICE
          USE MPIREL
          USE READFG, ONLY : LL_ADJETAB
          USE TLAD_VARS
          USE WEAKLY
          USE HYBRID
          USE EOFS3D
          USE TRACK_CORREL
          USE PROF_CORREL
          USE CERES

          IMPLICIT NONE

          INTEGER(I4)   :: IERR
          INTEGER(I4)   :: RCF_NTR, NTR, NEOF,NREGS,NKMT
          INTEGER(I4)   :: CTL_M, JSAT
          INTEGER(I4)   :: OBS_SLA,OBS_ARG,OBS_XBT,OBS_GLD,OBS_VEL,OBS_TRJ,&
                         & OBS_SST, OBS_SSS, OBS_AIR,OBS_SIC,OBS_SIT
          REAL(R8)      :: SLA_DEP, RCF_L, CTL_TOL, CTL_PER, BMD_FC1, BMD_FC2
          LOGICAL       :: SLA_USES(NOSLASATS), OBS_AMSRE_SST, OBS_MWOI_SST,&
                         & OBS_AQUAR_SSS, OBS_SMOS_SSS,OBS_AMSRE_SWATH_SST,&
                         & OBS_TMI_SWATH_SST, OBS_COPERN_L3S, OBS_COPERN_L3, &
                         & OBS_AMSR2_SST,OBS_METOP_AVHRR_SST,OBS_SACD_SSS,&
                         & OBS_NOAA_OI_SST,OBS_OSISAF_SIC,OBS_HADISST_SIC,OBS_SMOS_SIT,OBS_CRY2_SIT,&
                         & OBS_CRY2_SMOS_SIT,OBS_PIOMAS_SIT,OBS_GIOMAS_SIT
          REAL(R8)      :: BMD_DT, BMD_NDY, BMD_ADY, BMD_ALP,&
                         & BMD_OVR, BMD_RESEM, BMD_NCNT, RCF_EFC, RMD_DEP_MAX
          INTEGER(I4)   :: CTL_NIMAX,CTL_NSMAX, CTL_EPS
          INTEGER(I4)   :: CTL_GMETHOD, CTL_IREST
          INTEGER(I4)   :: EOGNX,EOGNY,EOGNZ
          INTEGER(I4)   :: GRID (NGRIDS)
          REAL(R8)      :: RATIO(NGRIDS)
          INTEGER(I4)   :: MASK (NGRIDS)
          INTEGER(I4)   :: BARMD(NGRIDS)
          INTEGER(I4)   :: DIVDA(NGRIDS)
          INTEGER(I4)   :: DIVDI(NGRIDS)
          INTEGER(I4)   :: BALMD(NGRIDS)
          INTEGER(I4)   :: BA2MD(NGRIDS)
          INTEGER(I4)   :: ICEOP(NGRIDS)
          CHARACTER(LEN=50)  :: CGRID(NGRIDS)
          CHARACTER(LEN=3)  :: OBSOPT
          CHARACTER(LEN=10) :: CTL_ALG
          REAL(R8)      :: ZSLANML
          LOGICAL       :: LCORRSSH,LLSSTDIAMPLCORR

          LOGICAL       :: RCF_LLVVCR,RCF_LLTSAPART
          CHARACTER (LEN=300) :: CFILEEOF, CSTRING

          NAMELIST /RUNLST/ NCONF,LL_NOFGAT,NSUBDOMAINS,LLVARMDT,ZVARMDT_RATIOSD,IDOUBLEDOM,LL_LSBC, NN_INS_SST, &
                            LL_RESTART_FILE, LL_DENSLEVS, LL_READBYREC, CBGDIR
          NAMELIST /STVLST/ LL_TS, LL_UV, LL_SSH, LL_SST, LL_SSS, LL_TQ2, LL_ICE
          NAMELIST /DBGLST/ LL_DEBUGTMP, LL_ONEPOINT, IDB_X, IDB_Y, IDB_Z, LL_FLDPRINT
          NAMELIST /ICELST/ LL_ICEREJ, LL_ICEBGFILT, LL_ICERFMASK, NN_ICEREC,&
                            LL_ICEREJ_DCOAST, ZMIN_ICEDIST,LL_ICEANFILT,ZICEINFLDIST,&
                            LL_ICE_ONEFILE,COEFF_SIT_ERR_SMOS,COEFF_SIT_ERR_CRYOSMOS,COEFF_SIT_ERR_CRYO,COEFF_SIC_ERR,&
                            COEFF_SIT_ERR_PIOMAS,COEFF_SIT_ERR_GIOMAS
          NAMELIST /EXTLST/ NWRAPS,LLDUPLOBS
          NAMELIST /ANPPLST/ LL_BOUNDANAL, ZANMAXTEM, ZANMAXSAL,LL_WRITECORRBIN,&
                            LLSHAPIROANL,NN_ITERSHAP,LL_IAU,LL_BOTTOMFILTER,NJPI,NJPJ,LL_HRINTERP
          NAMELIST /EOFLST/ NEOF,NREGS,NKMT,&
                            EOGNX,EOGNY,EOGNZ,CFILEEOF,REDNMC, &
                            NPRINTEOF,LSQUAREDEVA,LL_MDEOFS, RMD_DEP_MAX, NN_DENSREC,&
                            LL_WRITE_MDEOFS, LLFLOWDEP, LLFLOWDEP_CALIBR, NN_MLD_VLOC, LL_BGFACT, &
                            LL_UNMASK_EOFS, LL_SSH_UNBALANCED, LL_TQ2_UNBALANCED
          NAMELIST /OBSLST/ OBS_SLA, OBS_ARG, OBS_XBT, OBS_GLD, OBS_VEL, OBS_TRJ,&
                            OBS_SST,OBS_AIR,OBS_SIC,OBS_SIT,OBS_AMSRE_SST,OBS_MWOI_SST,OBS_SSS,&
                            OBS_AQUAR_SSS,OBS_SMOS_SSS,OBS_AMSRE_SWATH_SST,&
                            OBS_TMI_SWATH_SST,OBS_AMSR2_SST,OBS_METOP_AVHRR_SST,OBS_NOAA_OI_SST,&
                            OBS_COPERN_L3S,OBS_COPERN_L3, OBS_SACD_SSS,&
                            LL_TQ2_ASSIM,LL_PROJDOWN,LL_CERES,OBS_OSISAF_SIC,OBS_HADISST_SIC,OBS_SMOS_SIT,OBS_CRY2_SIT,&
                            OBS_CRY2_SMOS_SIT,OBS_PIOMAS_SIT,OBS_GIOMAS_SIT,PRINT_NIGHT_OBSERVATION_ONLY,LL_NIGHT_ONLY_AMSR2_AVHHR
          NAMELIST /GRDLST/ NTR, GRID, RATIO, MASK, BARMD, DIVDA, DIVDI, CGRID, LL_ADJETAB, BALMD, BA2MD,ICEOP
          NAMELIST /CTLLST/ CTL_M, CTL_TOL, CTL_PER, CTL_ALG, CTL_NIMAX, CTL_NSMAX, LL_BFEND, &
                            CTL_EPS, CTL_IREST, CTL_GMETHOD
          NAMELIST /RCFLST/ RCF_NTR, RCF_L, RCF_LLVVCR,RCF_LLTSAPART,RCF_TYPE,&
                            RCF_EFC, LLPRINTRCFLC,LLRFMASK, LL_CORRAD_2D, &
                            LL_RFLV, RF_CRMN,RF_CRMX, RF_NCR, RF_NRES, LL_NOSRF_RF, &
                            RF_CORRAD_MFACT, LL_READCOMPSC_LV, LL_WRITECOMPSC_LV,ZMDT_CLS
          NAMELIST /SLALST/ SLA_DEP,SLA_USES,LCORRSSH,CSLA_FMT,CSLA_OPT,&
                            LLFILTERSLA,NLANC_KN,ZLANC_CL,SLA_ERR,&
                            LLUSEMDTERR,ZSLANML, LL_VARLNM, LL_UNBIAS_SLA,LL_IBERR,LL_UNBIAS_SLA_LAT,LL_UNBIAS_SLA_AT,&
                            SLA_REPERR_INFLAT,LL_SLABCORR,NN_SLABC_BY,&
                            LL_SLA_CORRECTIVE_MAP, LL_WRITE_SLA_BIAS,&
                            NN_TRACK_CORREL,RR_TRACK_CORREL,RR_TRACK_CORREL_TIME,LHA_ERR
          NAMELIST /SSTLST/ LLSSTMODBIAS, LLSSTDIAMPLCORR, SST_ERRS, LL_SST_REPRERR
          NAMELIST /SSSLST/ SSS_ERRS, LL_SSS_BCORR
          NAMELIST /BMDLST/ BMD_DT, BMD_NDY, BMD_ADY, BMD_ALP, BMD_FC1, BMD_FC2,  &
                            BMD_OVR, BMD_RESEM, BMD_NCNT, LL_ADTEST_BMD
          NAMELIST /OBSHAN/ OBSOPT,ZTIME_WEIGTH, LLLATINT_TAB,LL_READALLBIN103,&
                            LLEVEFORMV,IO_OBSFORMAT,LLOBSSTAT,LL_ONEPROC103,&
                            LL_WRITE_OBS_SCREEN,LL_NOPSABORT,NN_INTERPM, LL_OBSS_TSP,&
                            ICOSST_DEF_ERR, NN_REG_REJ, NN_OBS_RET
          NAMELIST /PERTLST/LLPERTOBS,NSEED,ZRFACT
          NAMELIST /INSLST/ CINS_FMT,ZMAXDEP,INS_LQC_POS, INS_LQC_TIME,INS_LQC_SAL, &
                            INS_LQC_PRE, INS_LQC_PROF_T, INS_LQC_PROF_S,INS_LQC_TEMP,&
                            INS_LQC_PROF_P,INS_CHK_TIME, INS_ARG_GREYL, LL_VERTCHECK, &
                            LL_ICOADS, LL_KEEP_SURFACE, CICOADS_FMT, LL_NEWINSERR, &
                            LL_INSREPERR_IRREG, LL_VTHINNING, LL_VAVERAGING,&
                            NN_VERTMESH, NN_PROF_CORREL, LL_PROFCORR_ONLYP, LL_DRIFTER_SST
          NAMELIST /THINLST/ LTHIN_SLA,LTHIN_INS,LTHIN_SST,LTHIN_SSS, &
                            LTHIN_SIC,LTHIN_SIT, & 
                            CINSTHINOPT, LDOUBLETHIN, RTHIND_SLA_X, RTHIND_SLA_Y,&
                            RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z,&
                            RTHIND_SST_X,RTHIND_SST_Y,&
                            RTHIND_SSS_X,RTHIND_SSS_Y, RTHIND_SIC_X,RTHIND_SIC_Y, &
                            RTHIND_SIT_X,RTHIND_SIT_Y, LL_SAVETHINOUTSLA
          NAMELIST /BGQCLST/ LLBGQC_SLA,LLBGQC_INS,LLBGQC_SST,LLBGQC_SSS,LLBGQC_SIC,LLBGQC_SIT,LLFORMBGE,&
                            LLUSEBGERR,RALFA_SLA, RALFA_INS, RALFA_SST,RALFA_SSS,RALFA_SIC,RALFA_SIT, &
                            RBGERR_SSH, RBGERR_SAL, RBGERR_TEM, RBGERR_SST, RBGERR_SSS,RBGERR_SIC,RBGERR_SIT,&
                            LL_READ_BGE
          NAMELIST /CLCKLST/LLCLCK_INS,LLCLCK_SST,LLCLCK_SSS,CLIMLIM
          NAMELIST /CREJLST/LL_COASTREJ_INS,LL_COASTREJ_SLA,LL_COASTREJ_SST,LL_COASTREJ_SSS,&
                            NN_COASTREJ_INS,NN_COASTREJ_SLA,NN_COASTREJ_SST,NN_COASTREJ_SSS
          NAMELIST /HUBERLST/ LL_HUBERQC,LL_HUBERQC_SLA,LL_HUBERQC_INS,LL_HUBERQC_SST,LL_HUBERQC_SSS,&
                            ITER_HUBQC, LL_HUBERQC_INS_VERBOSE,LL_HUBER_ASYMM,LL_HUBER_L05
          NAMELIST /BALLST/ BAL_NNEOS, RDT_AML, NN_ICEBAL
          NAMELIST /TLADLST/LL_4DVAR,AHT0,RDT,RDT_TRAJ,LL_VDIFF,KN_ZDFEXP,NN_VDIFF, &
                            NTS_WRITE,TS_WRITE,LL_TLMODEL,LL_ADMODEL,LL_TLDEB,IDB_COO,&
                            LL_ADTEST,LL_SRFFLX,LL_HDIFF,LL_HADV,LL_VADV,&
                            LL_WEAKLY,NEOF_WW,EDECAY,NREGW,LSQEOFW,NPHOR,WRADC,LL_TEST_WEAK,&
                            LL_CONSTERR,LL_WC_NOCORR,LL_VVEL_NEMO,LL_SYSTERR,ZZ_VMIXC,&
                            LL_WCEOF,NN_WCEOF3D,LL_DEBUG_WEAKLY,NN_WCEOF3D_2,WCE_HW2
          NAMELIST /HYBLST/ LL_HYBRID,ZALPHA,NN_ALPHA_CTL,NEOF,NREGS,NKMT,LL_ALPHA_ONLINE,&
                            EOGNX,EOGNY,EOGNZ,CFILEEOF,REDNMC_H,LSQUAREDEVA_H,NN_MLD_VLOC_H,&
                            LL_BGFACT_H,LL_UNMASK_EOFS_H,ZALPHA_VAR,LL_PRECON_ALPHA, &
                            LL_EOFS3D, NN_EOFS3D, AEO, LL_DIAHYBRID, LL_HYBRID_CR

        !---------------------------------------------------------------------

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' ----------------------------------------'
          WRITE(IOUNLOG,*) ' :: DEF_NML : READ IN NAMELIST'
          WRITE(IOUNLOG,*) ' ----------------------------------------'

        !...... RUNLST

        !... DEFAULT VALUES

          LLVARMDT = .FALSE.
          LL_RESTART_FILE = .FALSE.
          LL_NOFGAT = .FALSE.
          LL_LSBC = .FALSE.
          IDOUBLEDOM = 0
          NN_INS_SST = 0
          LL_DENSLEVS = .FALSE. 

          CALL POSNAM(IOUNNAM,'RUNLST')
          READ(IOUNNAM,RUNLST)

          ! OVERWRITE NSUBDOMAINS IF NEEDED
          IF( NSUBDOMAINS .LT. 0 ) THEN
              NSUBDOMAINS = 0
          ELSE
              IF( LMPION ) NSUBDOMAINS = MP_SD(MYPROC)
          ENDIF

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' RUN NAMELIST INPUT (RUNLST): '
          WRITE(IOUNLOG,*) ' NUMBER OF CONFIGURATION:            NCONF = ', NCONF
          WRITE(IOUNLOG,*) ' NUMBER OF INPUT FIRST-GUESS FILES NSUBDOMAINS=', NSUBDOMAINS
          WRITE(IOUNLOG,*) ' ANALYSIS ON DENSITY LEVELS LL_DENSLEVS = ', LL_DENSLEVS
          WRITE(IOUNLOG,*) ' WHETHER TO SWITCH OFF FGAT LL_NOFGAT = ', LL_NOFGAT
          WRITE(IOUNLOG,*) ' VARIATIONAL CORRECTION OF MDT LLVARMDT = ', LLVARMDT
          WRITE(IOUNLOG,*) ' REDUCTION OF MDT ERROR ZVARMDT_RATIOSD = ', ZVARMDT_RATIOSD
          WRITE(IOUNLOG,*) ' DOUBLE DOMAIN CONFIGURATION IDOUBLEDOM = ', IDOUBLEDOM
          WRITE(IOUNLOG,*) ' LARGE-SCALE BIAS CORRECTION LL_LSBC = ', LL_LSBC
          WRITE(IOUNLOG,*) ' STEP OF SST ASSIMILATION (IF ANY) NN_INS_SST = ',NN_INS_SST
          WRITE(IOUNLOG,*) ' USE RESTART FILE AS FG LL_RESTART_FILE = ',LL_RESTART_FILE
          WRITE(IOUNLOG,*) ' BG SPLITTED IN RECORDS LL_READBYREC = ',LL_READBYREC
          WRITE(IOUNLOG,*) ' BG PATH                CBGDIR       = ',TRIM(CBGDIR)

          WRITE(IOUNOUT,*) ' *** CONFIGURATION ',NCONF
          WRITE(IOUNLOG,*) 
          WRITE(IOUNLOG,*) ' *** CONFIGURATION ',NCONF

          LLSLAATCORR = .FALSE.
          LLONLYOBSPP = .FALSE.
          SELECT CASE (NCONF)
              CASE (101)
                   CSTRING=' COMPLETE 3DVAR'
              CASE (102)
                   CSTRING=' OBS PREPARING'
              CASE (103)
                   CSTRING=' SCREENING AND MINIMIZATION'
              CASE (104)
                   CSTRING=' COMPUTATION OF HCLS LOOKUP TABLE'
              CASE (105)
                   CSTRING=' STANDALONE MODULATION OF EOFS'
              CASE (106)
                   CSTRING=' ONLY OBS PREPROCESSING'
                   NCONF = 103
                   LLONLYOBSPP = .TRUE.
              CASE (107)
                   CSTRING=' ONLY OBS PREPROCESSING'
                   NCONF = 101
                   LLONLYOBSPP = .TRUE.
              CASE (201)
                   CSTRING=' COMPUTATION OF SLA ALONG-TRACK CORRELATION'
                   LLSLAATCORR=.TRUE.
              CASE (202)
                   CSTRING=' 2DVAR OF SLA MISFITS FOR MDT CORRECTION'
              CASE (301)
                   CSTRING=' TANGENT LINEAR MODEL RUN'
              CASE (401)
                   CSTRING=' BACKGROUND BASED PERTURBATION'
              CASE DEFAULT
                   CALL ABOR1('NUMBER OF CONFIGURATION NCONF IS NOT VALID')
          ENDSELECT

          WRITE(IOUNOUT,*) TRIM(CSTRING)
          WRITE(IOUNLOG,*) TRIM(CSTRING)

          IF(NCONF .EQ. 202 .AND. LLVARMDT ) &
          CALL ABOR1('NCONF 202 CANNOT PROCEED WITH LLVARMDT')

          IF(LL_LSBC .AND. NCONF .NE. 103) &
          CALL ABOR1('LL_LSBC CANNOT PROCEED ON CONF OTHER THAN 103T')

        ! ---

          LL_TS = .TRUE.
          LL_UV = .FALSE.
          LL_SSH= .FALSE.
          LL_SST= .FALSE.
          LL_SSS= .FALSE.
          LL_TQ2= .FALSE.
          LL_ICE= .FALSE.

          CALL POSNAM(IOUNNAM,'STVLST')
          READ(IOUNNAM,STVLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' STATE VECTOR NAMELIST INPUT (STVLST): '
          WRITE(IOUNLOG,*) ' TEMPERATURE AND SALINITY:  LL_TS  = ', LL_TS
          WRITE(IOUNLOG,*) ' CURRENTS (U, V)         :  LL_UV  = ', LL_UV
          WRITE(IOUNLOG,*) ' SEA SURFACE HEIGHT      :  LL_SSH = ', LL_SSH
          WRITE(IOUNLOG,*) ' SEA SURFACE TEMPERATURE :  LL_SST = ', LL_SST
          WRITE(IOUNLOG,*) ' SEA SURFACE SALINITY    :  LL_SSS = ', LL_SSS
          WRITE(IOUNLOG,*) ' TEMPER./HUMID. AT 2M    :  LL_TQ2 = ', LL_TQ2
          WRITE(IOUNLOG,*) ' ICE CONC./THICKENSS     :  LL_ICE = ', LL_ICE

          PSV3D = 2 * COUNT((/LL_TS/)) + 2 * COUNT((/LL_UV/))
          PSV2D = COUNT((/LL_SSH/)) + COUNT((/LL_SST/)) + COUNT((/LL_SSS/)) + &
          & 2*COUNT((/LL_TQ2/)) + 2*COUNT((/LL_ICE/))

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' *** NUMBER OF 3D FIELDS =', PSV3D
          WRITE(IOUNLOG,*) ' *** NUMBER OF 2D FIELDS =', PSV2D
          WRITE(IOUNLOG,*)

        ! ---

          LL_DEBUGTMP = .FALSE.
          LL_ONEPOINT = .TRUE. 
          IDB_X = GRD%IM/2
          IDB_Y = GRD%JM/2
          IDB_Z = 1

          CALL POSNAM(IOUNNAM,'DBGLST')
          READ(IOUNNAM,DBGLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' DEBUG NAMELIST INPUT (DBGLST): '
          WRITE(IOUNLOG,*) ' SWITCH ON DEBUG         :  LL_DEBUGTMP  = ', LL_DEBUGTMP
          WRITE(IOUNLOG,*) ' ONE-POINT DEBUG         :  LL_ONEPOINT  = ', LL_ONEPOINT
          WRITE(IOUNLOG,*) ' FIELD PRINTING DEBUG    :  LL_FLDPRINT  = ', LL_FLDPRINT
          WRITE(IOUNLOG,*) ' POINT COORDINATES       :  IDBX, IDBY, IDBZ= ', &
          & IDB_X, IDB_Y, IDB_Z

        ! ---
          NWRAPS=0
          LLDUPLOBS = .TRUE.

          CALL POSNAM(IOUNNAM,'EXTLST')
          READ(IOUNNAM,EXTLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' EXTENDED DOMAIN NAMELIST INPUT (EXTLST): '
          WRITE(IOUNLOG,*) ' NUMBER OF WRAP POINTS FOR CYCLIC CONDITIONS  NWRAPS = ', NWRAPS
          WRITE(IOUNLOG,*) ' WHETHER TO DUPLICATE OBS IN THE EXTENDED GRID LLDUPLOBS = ', LLDUPLOBS

          LLEXTGRID = (NWRAPS >0 )

          IF(NWRAPS>MAXWRAPS) THEN
            WRITE(IOUNERR,*) 'MAXWRAPS',MAXWRAPS,' TO INCREASE'
            CALL ABOR1('NWRAPS > MAXWRAPS')
          ENDIF

          IF(NWRAPS<0) THEN
            WRITE(IOUNERR,*) 'NWRAPS',NWRAPS,' NOT ALLOWED'
            CALL ABOR1('NWRAPS < 0')
          ENDIF

          IF( NCONF .NE. 104 ) THEN
              WRITE(IOUNLOG,*)
              WRITE(IOUNLOG,*) ' *** USE OF EXTENDED DOMAIN ', LLEXTGRID
          ELSE
              WRITE(IOUNLOG,*) ' CONF 104 : LLEXTGRID FORCED TO FALSE'
              WRITE(IOUNOUT,*) ' CONF 104 : LLEXTGRID FORCED TO FALSE'
              LLEXTGRID = .FALSE.
          ENDIF

        ! ---
          LL_BOUNDANAL = .FALSE.
          ZANMAXTEM = 9._R8 
          ZANMAXSAL = 3._R8
          LLSHAPIROANL = .FALSE.
          LL_BOTTOMFILTER = .FALSE.
          NN_ITERSHAP = 4
          LL_IAU = .FALSE.
          LL_WRITECORRBIN  = .FALSE.
          LL_HRINTERP  = .FALSE.

          CALL POSNAM(IOUNNAM,'ANPPLST')
          READ(IOUNNAM,ANPPLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' ANALYSIS POSTPROCESSING NAMELIST INPUT (ANPPLST): '
          WRITE(IOUNLOG,*) ' WHETHER TO BOUND ANALYSIS INCREMENTS LL_BOUNDANAL = ', LL_BOUNDANAL
          WRITE(IOUNLOG,*) ' TEMPERATURE MAX ANALYSIS INCREMENTS ZANMAXTEM = ', ZANMAXTEM 
          WRITE(IOUNLOG,*) ' SALINITY    MAX ANALYSIS INCREMENTS ZANMAXSAL = ', ZANMAXSAL 
          WRITE(IOUNLOG,*) ' WHETHER TO SHAPIRO-FILTER ANALYSIS INCREMENTS LLSHAPIROANL = ', LLSHAPIROANL
          WRITE(IOUNLOG,*) ' NUMBER OF SHAPIRO FILTER ITERATIONS NN_ITERSHAP = ', NN_ITERSHAP
          WRITE(IOUNLOG,*) ' WHETHER TO PREPARE ANALYSIS FILES FOR IAU ONLY LL_IAU = ', LL_IAU
          WRITE(IOUNLOG,*) ' WHETHER TO FILTER ANALYSIS INCREMENTS AT BOTTOM LL_BOTTOMFILTER = ', LL_BOTTOMFILTER
          WRITE(IOUNLOG,*) ' WHETHER TO WRITE BINARY ANALYSIS INCR LL_WRITECORRBIN  = ', LL_WRITECORRBIN
          WRITE(IOUNLOG,*) ' NUMBER OF OUTPUT BIN X-POINTS NJPI = ', NJPI
          WRITE(IOUNLOG,*) ' NUMBER OF OUTPUT BIN Y-POINTS NJPJ = ', NJPJ
          WRITE(IOUNLOG,*) ' WHETHER TO INTERPOLATE ONTO HIGHER RES GRID LL_HRINTERP= ', LL_HRINTERP

        ! ---
          LL_ICEREJ = .TRUE.
          LL_ICEBGFILT = .TRUE.
          LL_ICEANFILT = .TRUE.
          LL_ICERFMASK = .TRUE.
          LL_ICEREJ_DCOAST = .FALSE.
          ZMIN_ICEDIST = 100._R8
          ZICEINFLDIST = 300._R8

          CALL POSNAM(IOUNNAM,'ICELST')
          READ(IOUNNAM,ICELST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' ICE NAMELIST INPUT (ICELST): '
          WRITE(IOUNLOG,*) ' WHETHER TO REJECT OBS UNDER SEA-ICE LL_ICEREJ  = ', LL_ICEREJ
          WRITE(IOUNLOG,*) ' WHETHER TO FILTER B-MATRIX UNDER SEA-ICE LL_ICEBGFILT = ', LL_ICEBGFILT
          WRITE(IOUNLOG,*) ' WHETHER TO MASK RF COEFFS UNDER SEA-ICE LL_ICERFMASK = ', LL_ICERFMASK
          WRITE(IOUNLOG,*) ' WHETHER TO REJECT OBS CLOSE TO SEA-ICE LL_ICEREJ_DCOAST  = ', LL_ICEREJ_DCOAST
          WRITE(IOUNLOG,*) ' DISTANCE (KM) TO SEA-ICE FOR OBS TO BE REJECTED ZMIN_ICEDIST  = ', ZMIN_ICEDIST
          WRITE(IOUNLOG,*) ' WHETHER TO FILTER ANALYSIS UNDER SEA-ICE LL_ICEANFILT = ', LL_ICEANFILT
          WRITE(IOUNLOG,*) ' DISTANCE (KM) TO SEA-ICE FOR AN TO BE FILTERED ZICEINFLDIST = ', ZICEINFLDIST
          WRITE(IOUNLOG,*) ' TIME RECORD TO READ IN SEA-ICE FILE NN_ICEREC = ', NN_ICEREC
          WRITE(IOUNLOG,*) ' WHETHER TO READ ICE FROM ONE FILE LL_ICE_ONEFILE = ', LL_ICE_ONEFILE
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIC OBS ERR= ', COEFF_SIC_ERR
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIT SMOMS OBS ERR= ',COEFF_SIT_ERR_SMOS
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIT CRYO2 OBS ERR=',COEFF_SIT_ERR_CRYO
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIT CRYO2SMOS MERGED OBS ERR=',COEFF_SIT_ERR_CRYOSMOS
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIT PIOMAS MERGED OBS ERR=',COEFF_SIT_ERR_PIOMAS
          WRITE(IOUNLOG,*) ' MULTIPLICATON COEFF FOR SIT GIOMAS MERGED OBS ERR=',COEFF_SIT_ERR_GIOMAS




          IF( NCONF .EQ. 105 ) THEN
              WRITE(IOUNLOG,*) ' CONF 105 : LL_ICEBGFILT FORCED TO FALSE'
              WRITE(IOUNOUT,*) ' CONF 105 : LL_ICEBGFILT FORCED TO FALSE'
              LL_ICEBGFILT = .FALSE. 
          ENDIF

        ! ---
          NEOF = 10
          NPRINTEOF = 1
          LSQUAREDEVA = .FALSE.
          LL_MDEOFS   = .FALSE.
          RMD_DEP_MAX = 500._R8
          REDNMC=1._R8
          NN_MLD_VLOC = 0
          LL_BGFACT = .FALSE.
          LL_UNMASK_EOFS = .TRUE.
          LL_SSH_UNBALANCED = .FALSE.
          LL_TQ2_UNBALANCED = .FALSE.

          CALL POSNAM(IOUNNAM,'EOFLST')
          READ(IOUNNAM,EOFLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' EOF NAMELIST INPUT (EOFLST): '
          WRITE(IOUNLOG,*) ' NUMBER OF LEADING EOFS               NEOF = ', NEOF
          WRITE(IOUNLOG,*) ' NUMBER OF EOF VERTICAL  LEVELS       NKMT = ', NKMT
          WRITE(IOUNLOG,*) ' NUMBER OF EOF REGIONS               NREGS = ', NREGS
          WRITE(IOUNLOG,*) ' NAME OF EOF FILE                 CFILEEOF = ', TRIM(CFILEEOF)
          WRITE(IOUNLOG,*) ' X-DIMENSION OF EOF GRID             EOGNX = ', EOGNX
          WRITE(IOUNLOG,*) ' Y-DIMENSION OF EOF GRID             EOGNY = ', EOGNY
          WRITE(IOUNLOG,*) ' Z-DIMENSION OF EOF GRID             EOGNZ = ', EOGNZ
          WRITE(IOUNLOG,*) ' COEFFICIENT FOR EIGENVALUES IN FILE REDNMC= ',REDNMC
          WRITE(IOUNLOG,*) ' EOF DIAGNOSTICS VERBOSITY LEVEL NPRINTEOF = ', NPRINTEOF
          WRITE(IOUNLOG,*) ' WHETHER EIGENVALS ARE SQUARED LSQUAREDEVA = ', LSQUAREDEVA
          WRITE(IOUNLOG,*) ' WHETHER MODULATE EOFS WITH DENSITY CRIT LL_MDEOFS = ', LL_MDEOFS
          WRITE(IOUNLOG,*) ' MAXIMUM DEPTH TO USE FOR LL_MDEOFS RMD_DEP_MAX = ', RMD_DEP_MAX
          WRITE(IOUNLOG,*) ' TIME RECORD TO READ IN GRID_T FILE NN_DENSREC = ', NN_DENSREC
          WRITE(IOUNLOG,*) ' WRITE MODULATED EOFS LL_WRITE_MDEOFS = ', LL_WRITE_MDEOFS
          WRITE(IOUNLOG,*) ' APPLY FLOW-DEP FACT. LLFLOWDEP      = ', LLFLOWDEP
          WRITE(IOUNLOG,*) ' CALIBR FLOW-DEP FACT. LLFLOWDEP_CALIBR = ', LLFLOWDEP_CALIBR
          WRITE(IOUNLOG,*) ' MLD-DEPENDENT LOCALIZATION NN_MLD_VLOC = ', NN_MLD_VLOC
          WRITE(IOUNLOG,*) ' GRID-DEPENDENT INFLATION B LL_BGFACT   = ', LL_BGFACT
          WRITE(IOUNLOG,*) ' UNMASK EOFS LL_UNMASK_EOFS = ', LL_UNMASK_EOFS
          WRITE(IOUNLOG,*) ' SSH BAL+UNBAL LL_SSH_UNBALANCED = ', LL_SSH_UNBALANCED
          WRITE(IOUNLOG,*) ' TQ2 BAL+UNBAL LL_TQ2_UNBALANCED = ', LL_TQ2_UNBALANCED

          ROS%EOGNX = EOGNX
          ROS%EOGNY = EOGNY
          ROS%EOGNZ = EOGNZ
          ROS%NEOF = NEOF
          ROS%NREG = NREGS
          ROS%KMT  = NKMT
          ROS%EOF_FILE = CFILEEOF
          ROS%DEP_MAX = RMD_DEP_MAX
          WRITE( ROS%EOF_FILE_ICE_SEP, "(A)") "EOF_ice.nc"
          IF( NCONF .EQ. 105 ) THEN
              WRITE(IOUNLOG,*) ' CONF 105 : LL_MDEOFS FORCED TO TRUE'
              WRITE(IOUNOUT,*) ' CONF 105 : LL_MDEOFS FORCED TO TRUE'
              LL_MDEOFS = .TRUE. 
          ENDIF

        ! ---
          OBS_AIR = 0
          OBS_SIC = 0
          OBS_SIT = 0
          OBS_OSISAF_SIC = .FALSE. 
          OBS_HADISST_SIC = .FALSE.
          OBS_SMOS_SIT  = .FALSE.
          OBS_CRY2_SMOS_SIT = .FALSE.
          OBS_CRY2_SIT  = .FALSE.
          OBS_PIOMAS_SIT = .FALSE.
          OBS_GIOMAS_SIT = .FALSE.
          LL_TQ2_ASSIM = .FALSE.
          !LL_ICE_ASSIM = .FALSE.
          LL_PROJDOWN = .FALSE.
          LL_CERES    = .FALSE.
          CALL POSNAM(IOUNNAM,'OBSLST')
          READ(IOUNNAM,OBSLST)

          WRITE(IOUNLOG,*)
          WRITE(IOUNLOG,*) ' OSERVATIONS NAMELIST INPUT (OBSLST): '
          WRITE(IOUNLOG,*) ' USE SLA OBSERVATIONS:            OBS_SLA = ', OBS_SLA
          WRITE(IOUNLOG,*) ' USE ARGO OBSERVATIONS:           OBS_ARG = ', OBS_ARG
          WRITE(IOUNLOG,*) ' USE XBT OBSERVATIONS:            OBS_XBT = ', OBS_XBT
          WRITE(IOUNLOG,*) ' USE GLIDER OBSERVATIONS:         OBS_GLD = ', OBS_GLD
          WRITE(IOUNLOG,*) ' USE VELOCITY OBSERVATIONS:       OBS_VEL = ', OBS_VEL
          WRITE(IOUNLOG,*) ' USE TRAJECTORY OBSERVATIONS:     OBS_TRJ = ', OBS_TRJ
          WRITE(IOUNLOG,*) ' USE SST OBSERVATIONS:            OBS_SST = ', OBS_SST
          WRITE(IOUNLOG,*) ' USE SSS OBSERVATIONS:            OBS_SSS = ', OBS_SSS
          WRITE(IOUNLOG,*) ' USE AIR OBSERVATIONS:            OBS_AIR = ', OBS_AIR
          WRITE(IOUNLOG,*) ' USE SIC OBSERVATIONS:            OBS_SIC = ', OBS_SIC
          WRITE(IOUNLOG,*) ' USE SIT OBSERVATIONS:            OBS_SIT = ', OBS_SIT
          WRITE(IOUNLOG,*) ' USE NIGHT TIME SST DATA ONLY FOR AMRS2 AND AVHRR  = ', &
          & LL_NIGHT_ONLY_AMSR2_AVHHR
          WRITE(IOUNLOG,*) ' USE AMSR-E SST OBSERVATIONS: OBS_AMSRE_SST = ', &
          & OBS_AMSRE_SST
          WRITE(IOUNLOG,*) ' USE MWOI   SST OBSERVATIONS: OBS_MWOI_SST  = ', &
          & OBS_MWOI_SST
          WRITE(IOUNLOG,*) ' USE SWATH AMSR-E SST OBSERVATIONS: OBS_AMSRE_SWATH_SST  = ', &
          & OBS_AMSRE_SWATH_SST
          WRITE(IOUNLOG,*) ' USE L3S COPERNICUS SST DATA : OBS_COPERN_L3S  = ', &
          & OBS_COPERN_L3S
          WRITE(IOUNLOG,*) ' USE L3 COPERNICUS SST DATA : OBS_COPERN_L3  = ', &
          & OBS_COPERN_L3
          WRITE(IOUNLOG,*) ' USE SWATH TMI  SST OBSERVATIONS: OBS_TMI_SWATH_SST  = ', &
          & OBS_TMI_SWATH_SST
          WRITE(IOUNLOG,*) ' USE NOAA OI SST OBSERVATIONS: OBS_NOAA_OI_SST  = ', &
          & OBS_NOAA_OI_SST
          WRITE(IOUNLOG,*) ' USE AQUARIUS SSS OBSERVATIONS: OBS_AQUAR_SSS  = ', &
          & OBS_AQUAR_SSS
          WRITE(IOUNLOG,*) ' USE SMOS SSS OBSERVATIONS: OBS_SMOS_SSS  = ', &
          & OBS_SMOS_SSS
          WRITE(IOUNLOG,*) ' USE SAC-D SSS OBSERVATIONS: OBS_SACD_SSS  = ', &
          & OBS_SACD_SSS
          WRITE(IOUNLOG,*) ' ASSIMILATE AIR OBSERVATIONS: LL_TQ2_ASSIM  = ', &
          & LL_TQ2_ASSIM
          WRITE(IOUNLOG,*) ' USE OSISAF SIC OBSERVATIONS: OBS_OSISAF_SIC  = ', &
          & OBS_OSISAF_SIC
          WRITE(IOUNLOG,*) ' USE HADISST SIC OBSERVATIONS: OBS_HADISST_SIC  = ', &
          & OBS_HADISST_SIC
         WRITE(IOUNLOG,*) ' USE CRYOSAT2 SIT OBSERVATIONS: OBS_CRY2_SIT  = ', &
          & OBS_CRY2_SIT
          WRITE(IOUNLOG,*) ' USE SMOS SIT OBSERVATIONS: OBS_SMOS_SIT  = ', &
          & OBS_SMOS_SIT
          WRITE(IOUNLOG,*) ' USE CRYOS2 SMOS MERGED SIT OBSERVATIONS: OBS_CRY2_SMOS_SIT  = ', &
          & OBS_CRY2_SMOS_SIT
          WRITE(IOUNLOG,*) ' USE PIOMAS SIT OBSERVATIONS: OBS_PIOMAS_SIT  = ', &
          & OBS_PIOMAS_SIT
          WRITE(IOUNLOG,*) ' USE GIOMAS SIT OBSERVATIONS: OBS_GIOMAS_SIT  = ', &
          & OBS_GIOMAS_SIT
         !  WRITE(IOUNLOG,*) ' ASSIMILATE AIR OBSERVATIONS: LL_ICE_ASSIM  = ', &
        !  & LL_ICE_ASSIM
          WRITE(IOUNLOG,*) ' PROJECT BG FIELDS DOWNWARDS: LL_PROJDOWN = ',LL_PROJDOWN
          WRITE(IOUNLOG,*) ' USE CERES EBAF-TOA DATA    : LL_CERES    = ',LL_CERES

          OBS%SLA = OBS_SLA
          OBS%ARG = OBS_ARG
          OBS%XBT = OBS_XBT
          OBS%GLD = OBS_GLD
          OBS%VEL = OBS_VEL
          OBS%TRJ = OBS_TRJ
          OBS%SST = OBS_SST
          OBS%SSS = OBS_SSS
          OBS%AIR = OBS_AIR
          OBS%SIC = OBS_SIC
          OBS%SIT = OBS_SIT
          SST%LLAMSRE = OBS_AMSRE_SST
          SST%LLREMSS_MWOI_NC = OBS_MWOI_SST
          SST%LLREMSS_SWATH_AMSRE = OBS_AMSRE_SWATH_SST
          SST%LLREMSS_SWATH_TMI = OBS_TMI_SWATH_SST
          SST%LL_COPERN_L3S  = OBS_COPERN_L3S
          SST%LL_COPERN_L3  = OBS_COPERN_L3
          SST%LL_METOPA_AVHRR = OBS_METOP_AVHRR_SST
          SST%LL_AMSR2  =  OBS_AMSR2_SST
          SST%LL_NOAA_OI = OBS_NOAA_OI_SST

          SSS%LLAQUARIUS     = OBS_AQUAR_SSS
          SSS%LLSMOS         = OBS_SMOS_SSS
          SSS%LLSACD         = OBS_SACD_SSS

          SIC%LLOSISAF = OBS_OSISAF_SIC
          SIC%LLHADISST = OBS_HADISST_SIC
          SIT%LLESACRY2 = OBS_CRY2_SIT
          SIT%LLSMOS = OBS_SMOS_SIT
          SIT%LLCRYOSMOSMERGED = OBS_CRY2_SMOS_SIT
          SIT%LLPIOMAS = OBS_PIOMAS_SIT
          SIT%LLGIOMAS = OBS_GIOMAS_SIT

  IF( .NOT. LL_TQ2 ) THEN
    IF(LL_TQ2_ASSIM) WRITE(IOUNOUT,*) ' WARNING : LL_TQ2_ASSIM FORCED TO FALSE'
    LL_TQ2_ASSIM = .FALSE.
  ENDIF
!  IF( .NOT. LL_ICE ) THEN
!    IF(LL_ICE_ASSIM) WRITE(IOUNOUT,*) ' WARNING : LL_ICE_ASSIM FORCED TO FALSE'
!    LL_ICE_ASSIM = .FALSE.
!  ENDIF

! ---
  CALL POSNAM(IOUNNAM,'GRDLST')
  READ(IOUNNAM,GRDLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' GRID NAMELIST INPUT (GRDLST): '
  WRITE(IOUNLOG,*) ' MULTIGRID ITERRATIONS:                  NTR = ', NTR
  WRITE(IOUNLOG,*) ' GRIDS:                                 GRID = ', GRID (1:NTR)
  WRITE(IOUNLOG,*) ' RATIO:                                RATIO = ', RATIO(1:NTR)
  WRITE(IOUNLOG,*) ' MASKS:                                 MASK = ',  MASK(1:NTR)
  WRITE(IOUNLOG,*) ' RUN BAROTROPIC MODEL:                 BARMD = ', BARMD(1:NTR)
  WRITE(IOUNLOG,*) ' DIVERGENCE DAMPING IN ANALYSIS:       DIVDA = ', DIVDA(1:NTR)
  WRITE(IOUNLOG,*) ' DIVERGENCE DAMPING IN INITIALISATION: DIVDI = ', DIVDI(1:NTR)
  WRITE(IOUNLOG,*) ' SIMPLIFIED BALANCE                    BALMD = ', BALMD(1:NTR)
  WRITE(IOUNLOG,*) ' SIMPLIFIED BALANCE AT 2M              BA2MD = ', BA2MD(1:NTR)
  WRITE(IOUNLOG,*) ' TRANSFORMATION ANAM. ICE              ICEOP = ', ICEOP(1:NTR)
  WRITE(IOUNLOG,*) ' ADJUST GLOBAL MEAN FG SSH FIELDS LL_ADJETAB = ', LL_ADJETAB

  DRV%NTR = NTR
#ifndef NECSX
  ALLOCATE( DRV%GRID (DRV%NTR))
  ALLOCATE( DRV%RATIO(DRV%NTR))
  ALLOCATE( DRV%MASK (DRV%NTR))
  ALLOCATE( DRV%BMD(DRV%NTR))
  ALLOCATE( DRV%DDA(DRV%NTR))
  ALLOCATE( DRV%DDI(DRV%NTR))
  ALLOCATE( DRV%CGRID(DRV%NTR))
  ALLOCATE( DRV%BAL(DRV%NTR))
  ALLOCATE( DRV%BA2(DRV%NTR))
   ALLOCATE( DRV%ICEOP(DRV%NTR))
#endif
  DRV%GRID (1:DRV%NTR) = GRID (1:DRV%NTR)
  DRV%RATIO(1:DRV%NTR) = RATIO(1:DRV%NTR)
  DRV%MASK (1:DRV%NTR) = MASK (1:DRV%NTR)
  DRV%BMD  (1:DRV%NTR) = BARMD(1:DRV%NTR)
  DRV%DDA  (1:DRV%NTR) = DIVDA(1:DRV%NTR)
  DRV%DDI  (1:DRV%NTR) = DIVDI(1:DRV%NTR)
  DRV%CGRID(1:DRV%NTR) = CGRID(1:DRV%NTR)
  DRV%BAL  (1:DRV%NTR) = BALMD(1:DRV%NTR)
  DRV%BA2  (1:DRV%NTR) = BA2MD(1:DRV%NTR)
  DRV%ICEOP(1:DRV%NTR) = ICEOP(1:DRV%NTR)

! ---
  CTL_ALG=' '
  LL_BFEND = .FALSE.
  CTL_GMETHOD=1
  CTL_IREST  =0
  CTL_EPS    =1.0E-4_R8
  CALL POSNAM(IOUNNAM,'CTLLST')
  READ(IOUNNAM,CTLLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' MINIMIZER NAMELIST INPUT (CTLLST): '
  WRITE(IOUNLOG,*) ' MINIMIZATION ALGORITHM:          CTL_ALG  = ', CTL_ALG
  WRITE(IOUNLOG,*) ' MAX NUMBER ITERATIONS            CTL_NIMAX= ', CTL_NIMAX
  WRITE(IOUNLOG,*) ' MAX NUMBER SIMULATIONS (M1QN3)   CTL_NSMAX= ', CTL_NSMAX
  WRITE(IOUNLOG,*) ' NUMBER OF SAVED VECTORS:         CTL_M    = ', CTL_M
  WRITE(IOUNLOG,*) ' MINIMUM GRADIENT OF J:           CTL_TOL  = ', CTL_TOL
  WRITE(IOUNLOG,*) ' PERCENTAGE OF INITIAL GRADIENT:  CTL_PER  = ', CTL_PER
  WRITE(IOUNLOG,*) ' BOUNDARIES FILTERING AT THE END  LL_BFEND = ', LL_BFEND

  CTL%ALG   = CTL_ALG
  CTL%NIMAX = CTL_NIMAX
  CTL%NSMAX = CTL_NSMAX
  CTL%M     = CTL_M
  CTL%PGTOL = CTL_TOL
  CTL%PGPER = CTL_PER
  CTL%GMETHOD = CTL_GMETHOD
  CTL%IREST   = CTL_IREST
  CTL%EPS     = CTL_EPS

  IF(CTL%ALG(1:5) .NE. 'M1QN3' .AND. CTL%ALG(1:8) .NE. 'L-BFGS-B' &
  .AND. CTL%ALG(1:3) .NE. 'CG1' .AND. CTL%ALG(1:3) .NE. 'CG+') THEN
     WRITE(IOUNERR,*) 'WRONG ALGORITHM '//TRIM(CTL%ALG)
     WRITE(IOUNERR,*) 'ONLY L-BFGS-B M1QN3 OR CG1 OR CG+ PERMITTED'
     CALL ABOR1('UNKNOWN MINIMIZER')
  ENDIF
  IF(CTL%ALG(1:8) .NE. 'L-BFGS-B' .AND. NCONF .EQ. 202) &
  CALL ABOR1('NCONF 202 REQUIRES L-BFGS-B MINIMIZER')

! ---

  RCF_NTR=4
  RCF_EFC=3._R8
  RCF_L = 600.
  RCF_LLVVCR = .FALSE.
  RCF_LLTSAPART = .FALSE.
  LL_READCOMPSC_LV = .TRUE.
  LL_WRITECOMPSC_LV = .FALSE.
  LL_RFLV = .TRUE.
  RF_NRES = 20
  ZMDT_CLS = -1._R8
  LL_CORRAD_2D = .FALSE.

  CALL POSNAM(IOUNNAM,'RCFLST')
  READ(IOUNNAM,RCFLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' RECURSIVE FILTER NAMELIST INPUT (RCFLST): '
  WRITE(IOUNLOG,*) ' TYPE OF REC FILTER: 1-FIRST ORD. 2-THIRD ORD. RCF_TYPE = ',RCF_TYPE
  WRITE(IOUNLOG,*) ' HALF NUMBER OF ITERATIONS:       RCF_NTR  = ', RCF_NTR
  WRITE(IOUNLOG,*) ' HORIZONTAL CORRELATION RADIUS, USED ONLY IF'
  WRITE(IOUNLOG,*) ' CONSTANT ALL OVER THE DOMAIN :   RCF_L    = ', RCF_L
  WRITE(IOUNLOG,*) ' SECURITY FACTOR FOR EXT. GRID:   RCF_EFC  = ', RCF_EFC
  WRITE(IOUNLOG,*) ' VERTICALLY-VARYING  RADIUS :  RCF_LLVVCR = ',RCF_LLVVCR
  WRITE(IOUNLOG,*) ' T,S TREATED APART         :RCF_LLTSAPART = ',RCF_LLTSAPART
  WRITE(IOUNLOG,*) ' WHETHER TO OUTPUT RF COEFFS LLPRINTRCFLC = ',LLPRINTRCFLC
  WRITE(IOUNLOG,*) ' USE LOCALLY VARYING LOOKUP TABLE LL_RFLV = ',LL_RFLV
  WRITE(IOUNLOG,*) ' NUMBER OF DISCRETE CORR RADIUS RF_NCR = ',RF_NCR
  WRITE(IOUNLOG,*) ' MINIMUM CORR RAD TO USE RF_CRMN = ',RF_CRMN
  WRITE(IOUNLOG,*) ' MAXIMUM CORR RAD TO USE RF_CRMX = ',RF_CRMX
  WRITE(IOUNLOG,*) ' NUMBER OF DISCRETE RESOLUTIONS RF_NRES = ',RF_NRES
  WRITE(IOUNLOG,*) ' FACTOR TO HAVE CR IN M FROM FILE RF_CORRAD_MFACT= ',RF_CORRAD_MFACT
  WRITE(IOUNLOG,*) ' WHETHER TO READ LOOUKUP TAB IN BIN LL_READCOMPSC_LV = ',LL_READCOMPSC_LV
  WRITE(IOUNLOG,*) ' WHETHER TO WRITE LOOUKUP TAB IN BIN LL_WRITECOMPSC_LV = ',LL_WRITECOMPSC_LV
  WRITE(IOUNLOG,*) ' WHETHER TO USE SPECIFIC RF LSM LLRFMASK = ',LLRFMASK
  WRITE(IOUNLOG,*) ' CLS OFR MDT (NEGATIVE: READ FROM FILE) ZMDT_CLS  = ',ZMDT_CLS
  WRITE(IOUNLOG,*) ' 2D FIELD FOR CORR LENGTH SCALE LL_CORRAD_2D = ',LL_CORRAD_2D
  WRITE(IOUNLOG,*) ' RECURS. FILTER ONLY ON 3D FIELDS LL_NOSRF_RF = ',LL_NOSRF_RF

  RF_NTR = RCF_NTR
  RF_L = RCF_L
  LLVVCR = RCF_LLVVCR
  LLTSAPART = RCF_LLTSAPART
  RF_EFC = RCF_EFC

  IF( NCONF .EQ. 104 ) THEN
      WRITE(IOUNLOG,*) ' CONF 104 : LL_RFLV FORCED TO TRUE'
      WRITE(IOUNOUT,*) ' CONF 104 : LL_RFLV FORCED TO TRUE'
      LL_READCOMPSC_LV = .FALSE. 
      LL_WRITECOMPSC_LV = .TRUE.
      LL_RFLV = .TRUE.
  ENDIF

  IF( NCONF .EQ. 202 ) THEN
      WRITE(IOUNLOG,*) ' CONF 202 : LL_RFLV FORCED TO TRUE'
      WRITE(IOUNOUT,*) ' CONF 202 : LL_RFLV FORCED TO TRUE'
      LL_RFLV = .TRUE.
  ENDIF

! ---

  SLA_USES = .TRUE.
  LCORRSSH = .FALSE.
  LLFILTERSLA = .FALSE.
  NLANC_KN = 5
  ZLANC_CL = 75._R8
  CSLA_FMT='OLD'
  CSLA_OPT='DT'
  ZSLANML=1000._R8
  SLA_REPERR_INFLAT = 1._R8
  NN_TRACK_CORREL = 0
  RR_TRACK_CORREL = 20._R8
  RR_TRACK_CORREL_TIME = 1._R8
  LL_SLA_CORRECTIVE_MAP = .FALSE.
  LL_UNBIAS_SLA = .FALSE.
  LL_WRITE_SLA_BIAS = .FALSE.
  LHA_ERR = .TRUE.

  CALL POSNAM(IOUNNAM,'SLALST')
  READ(IOUNNAM,SLALST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' SLA NAMELIST INPUT (SLALST): '
  WRITE(IOUNLOG,*) ' MINIMUM DEPTH FOR OBSERVATIONS:  SLA_DEP  = ',SLA_DEP
  WRITE(IOUNLOG,*) ' SATELLITE    ENABLED  INSTR.ERR'
  DO JSAT=1,NOSLASATS
    WRITE(IOUNLOG,*) ' ',TRIM(CSLASATID(JSAT)),SLA_USES(JSAT),SLA_ERR(JSAT)
  ENDDO
  WRITE(IOUNLOG,*) ' WHETHER TO CORRECT SSH    :  LCORRSSH    = ',LCORRSSH
  WRITE(IOUNLOG,*) ' WHETHER TO FILTER AT SLA  :  LLFILTERSLA = ',LLFILTERSLA
  WRITE(IOUNLOG,*) ' NUMBER OF WEIGHTS IN LANCZ:  NLANC_KN    = ',NLANC_KN
  WRITE(IOUNLOG,*) ' CUT-OFF WAVELENGTH IN LANC:  ZLANC_CL    = ',ZLANC_CL
  WRITE(IOUNLOG,*) ' SLA OPTION (DT OR NT)     :  CSLA_OPT    = ',CSLA_OPT
  WRITE(IOUNLOG,*) ' SLA FORMAT (OLD OR NEW)   :  CSLA_FMT    = ',CSLA_FMT
  WRITE(IOUNLOG,*) ' NO MOTION LEVEL FOR SLA (M): ZSLANML     = ', ZSLANML
  WRITE(IOUNLOG,*) ' USE MDT ERROR IN SLA ERROR: LLUSEMDTERR  = ',LLUSEMDTERR
  WRITE(IOUNLOG,*) ' VARIABLE LEVEL NO MOTION  : LL_VARLNM    = ',LL_VARLNM
  WRITE(IOUNLOG,*) ' GLOBALLY UNBIAS SLA OBS   : LL_UNBIAS_SLA= ',LL_UNBIAS_SLA
  WRITE(IOUNLOG,*) ' UNBIAS SLA PER LATITUDE   : LL_UNBIAS_SLA_LAT = ',LL_UNBIAS_SLA_LAT
  WRITE(IOUNLOG,*) ' UNBIAS SLA OBS ALONG-TRACK: LL_UNBIAS_SLA_AT = ',LL_UNBIAS_SLA_AT
  WRITE(IOUNLOG,*) ' WRITE SLA BIAS IN SSH ANAL: LL_WRITE_SLA_BIAS = ',LL_WRITE_SLA_BIAS
  WRITE(IOUNLOG,*) ' ADD IB ERROR TO SLA ERROR : LL_IBERR     = ',LL_IBERR
  WRITE(IOUNLOG,*) ' INFLATION FOR SLA REP. ERROR : SLA_REPERR_INFLAT = ',SLA_REPERR_INFLAT
  WRITE(IOUNLOG,*) ' SLA BIAS CORRECTION SCHEME : LL_SLABCORR = ', LL_SLABCORR
  WRITE(IOUNLOG,*) ' SLA BCOR PASS REDUCED GRID : NN_SLABC_BY = ', NN_SLABC_BY
  WRITE(IOUNLOG,*) ' SLA ALONG-TRACK CORR. FUNCT.: NN_TRACK_CORREL = ', NN_TRACK_CORREL
  WRITE(IOUNLOG,*) ' SLA ALONG-TRACK CORR. SCALE : RR_TRACK_CORREL = ', RR_TRACK_CORREL
  WRITE(IOUNLOG,*) ' SLA ALONG-TRACK TIME CORR. DECAY : RR_TRACK_CORREL_TIME = ', RR_TRACK_CORREL_TIME
  WRITE(IOUNLOG,*) ' SLA CORRECTIVE FACTOR    : LL_SLA_CORRECTIVE_MAP = ', LL_SLA_CORRECTIVE_MAP
  WRITE(IOUNLOG,*) ' ACCOUNT FOR LHA OO ERROR : LHA_ERR  =  ', LHA_ERR

  SLA%DEP  = SLA_DEP
  SLA%USES = SLA_USES
  LLCORRSSH = LCORRSSH

! ---
  SST_ERRS = (/0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5/)
  LLSSTDIAMPLCORR = .TRUE.
  LLSSTMODBIAS = .FALSE.
  LL_SST_REPRERR = .TRUE.

  CALL POSNAM(IOUNNAM,'SSTLST')
  READ(IOUNNAM,SSTLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' SST NAMELIST INPUT (SSTLST): '
  WRITE(IOUNLOG,*) ' REF ERROR FOR SST = ',SST_ERRS(:)
  WRITE(IOUNLOG,*) ' WHETHER TO CORRECT MODEL SST LLSSTMODBIAS = ',LLSSTMODBIAS
  WRITE(IOUNLOG,*) ' WHETHER TO CORRECT SST DIURNAL WARMING LLSSTDIAMPLCORR = ',LLSSTDIAMPLCORR

! ---
  SSS_ERRS = (/0.3,0.3,0.3/)
  LL_SSS_BCORR = .FALSE.

  CALL POSNAM(IOUNNAM,'SSSLST')
  READ(IOUNNAM,SSSLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' SSS NAMELIST INPUT (SSSLST): '
  WRITE(IOUNLOG,*) ' REF ERROR FOR SSS = ',SSS_ERRS(:)
  WRITE(IOUNLOG,*) ' BIAS CORRECTION LL_SSS_BCORR = ',LL_SSS_BCORR


! ---
  CALL POSNAM(IOUNNAM,'BMDLST')
  READ(IOUNNAM,BMDLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' BAROTROPIC MODEL NAMELIST INPUT (BMDLST): '
  WRITE(IOUNLOG,*) ' TIME STEP:           BMD_DT     = ', BMD_DT
  WRITE(IOUNLOG,*) ' SIMULATION DAYS:     BMD_NDY    = ', BMD_NDY
  WRITE(IOUNLOG,*) ' AVERAGED DAYS:       BMD_ADY    = ', BMD_ADY
  WRITE(IOUNLOG,*) ' IMPLICIT WEIGHT:     BMD_ALP    = ', BMD_ALP
  WRITE(IOUNLOG,*) ' FRICTION INTENSITY:  BMD_FC1    = ', BMD_FC1
  WRITE(IOUNLOG,*) ' FRICTION INTENSITY:  BMD_FC2    = ', BMD_FC2
  WRITE(IOUNLOG,*) ' OVER-RELAXATION:     BMD_OVR    = ', BMD_OVR
  WRITE(IOUNLOG,*) ' MINIMUM RESIDUAL:    BMD_RESEM  = ', BMD_RESEM
  WRITE(IOUNLOG,*) ' MAXIMUM ITERATIONS   BMD_NCNT   = ', BMD_NCNT
  WRITE(IOUNLOG,*) ' ADJOINT TEST:   LL_ADTEST_BMD   = ', LL_ADTEST_BMD

  BMD%DT    = BMD_DT !7200. !1800.
  BMD%NDY   = BMD_NDY ! 3.
  BMD%ADY   = BMD_ADY ! 1.
  BMD%ALP1  = BMD_ALP !1.0
  BMD%FC1  = BMD_FC1
  BMD%FC2  = BMD_FC2
  BMD%OVR = BMD_OVR !1.9
  BMD%RESEM = BMD_RESEM !5.E-2
  BMD%NCNT = BMD_NCNT !201

! ---
  ZTIME_WEIGTH = 3.5_R8
  ICOSST_DEF_ERR = 0.78_R8
  LLEVEFORMV= .TRUE.
  LLLATINT_TAB = .TRUE.
  IO_OBSFORMAT = 1
  LLFORMBGE = .FALSE.
  LLOBSSTAT = .TRUE.
  LL_WRITE_OBS_SCREEN = .FALSE.
  LL_NOPSABORT = .FALSE.
  NN_INTERPM = 2
  NN_REG_REJ = 0
  NN_OBS_RET = 0

  CALL POSNAM(IOUNNAM,'OBSHAN')
  READ(IOUNNAM,OBSHAN)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' GENERAL OBS HANDLING NAMELIST INPUT (OBSHAN): '
  WRITE(IOUNLOG,*) ' WHICH OPTION TO USE TO PROCESS OBS OBSOPT = ', OBSOPT
  WRITE(IOUNLOG,*) ' DAYS USED FOR ERROR ASSIGN == ASSIM. TIMEWINDOW ZTIME_WEIGTH = ',ZTIME_WEIGTH
  WRITE(IOUNLOG,*) ' FORMAT OF OBS FOR 102-103    IO_OBSFORMAT = ', IO_OBSFORMAT
  WRITE(IOUNLOG,*) ' WHETHER TO PRINT OBS EVE FOR METVIEW LLEVEFORMV = ', LLEVEFORMV
  WRITE(IOUNLOG,*) ' WHETHER TO USE LAT TABLE FOR INTERP. LLLATINT_TAB = ', LLLATINT_TAB
  WRITE(IOUNLOG,*) ' WHETHER TO COMPUTE GLOBAL OBS STATS LLOBSSTAT = ', LLOBSSTAT
  WRITE(IOUNLOG,*) ' WHETHER TO FORCE 1 PROC FOR C 103 LL_ONEPROC103 = ', LL_ONEPROC103
  WRITE(IOUNLOG,*) ' WHETHER TO USE READ103BIN LL_READALLBIN103 = ',LL_READALLBIN103
  WRITE(IOUNLOG,*) ' WHETHER TO WRITE OBS ALSO BEFOR MINIM LL_WRITE_OBS_SCREEN = ',LL_WRITE_OBS_SCREEN
  WRITE(IOUNLOG,*) ' WHETHER TO SKIP ABORT IN PROCSPLIT LL_NOPSABORT = ', LL_NOPSABORT
  WRITE(IOUNLOG,*) ' INTERPOLATION TYPE NN_INTERPM   = ', NN_INTERPM
  WRITE(IOUNLOG,*) ' WHETHER TO WRITE TS PROFILES LL_OBSS_TSP  = ', LL_OBSS_TSP
  WRITE(IOUNLOG,*) ' DEFAULT ERR FOR ICOADS SST ICOSST_DEF_ERR = ', ICOSST_DEF_ERR
  WRITE(IOUNLOG,*) ' REGIONAL REJECTION OPTION NN_REG_REJ = ', NN_REG_REJ
  WRITE(IOUNLOG,*) ' RETAINED RANDOMIZED OBS   NN_OBS_RET = ', NN_OBS_RET

  IF( NN_INTERPM .NE.1 .AND. NN_INTERPM .NE. 2 ) &
  CALL ABOR1('NN_INTERPM SHOULD EQUAL 1 OR 2')

  CALL TOUPPERDT(OBSOPT)
  COBSOPT(1:3)=OBSOPT(1:3)
  ZNOML=ZSLANML
  SST%LLSSTDACORR=LLSSTDIAMPLCORR

  IF( NCONF.EQ.202 .AND. COBSOPT .NE. 'GLO' ) &
  CALL ABOR1('NCONF IS 202 AND COBSOPT NOT GLO, THIS IS NOT SUPPORTED')

! ---
  LLPERTOBS=.FALSE.
  NSEED=1
  ZRFACT=1._R8

  CALL POSNAM(IOUNNAM,'PERTLST')
  READ(IOUNNAM,PERTLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' PERTURBATION  NAMELIST INPUT (PERTLST): '
  WRITE(IOUNLOG,*) ' WHETHER TO PERTURB OBSERVATIONS LLPERTOBS = ',LLPERTOBS
  WRITE(IOUNLOG,*) ' SEED FOR RANDOM NUMBER GENERATION   NSEED = ',NSEED
  WRITE(IOUNLOG,*) ' FACTOR TO MULTIPLY TO RANDOM REALIZ. ZRFACT =', ZRFACT

! ---
  CINS_FMT = 'EN3'
  CICOADS_FMT = 'NCDF'
  LL_VERTCHECK = .TRUE.
  LL_ICOADS = .FALSE.
  LL_DRIFTER_SST = .FALSE.
  LL_KEEP_SURFACE = .FALSE.
  LL_NEWINSERR = .FALSE.
  LL_VTHINNING = .FALSE.
  LL_VAVERAGING = .FALSE.
  NN_VERTMESH = 1
  NN_PROF_CORREL = 0
  LL_PROFCORR_ONLYP = .FALSE.

  CALL POSNAM(IOUNNAM,'INSLST')
  READ(IOUNNAM,INSLST)
  
  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' INSITU OSB NAMELIST INPUT (INSLST): '
  WRITE(IOUNLOG,*) ' MAXIMUM DEPTH FOR XBT = ',ZMAXDEP(1)
  WRITE(IOUNLOG,*) ' MAXIMUM DEPTH FOR TES = ',ZMAXDEP(2)
  WRITE(IOUNLOG,*) ' MAXIMUM DEPTH FOR ARG = ',ZMAXDEP(3)
  WRITE(IOUNLOG,*) ' MAXIMUM DEPTH FOR BUO = ',ZMAXDEP(4)
  WRITE(IOUNLOG,*) ' WHETHER TO USE EN3 OR NRT CINS_FMT = ', CINS_FMT
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC POSITION INS_LQC_POS  = ',INS_LQC_POS
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC TIME     INS_LQC_TIME = ',INS_LQC_TIME
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC SALINITY INS_LQC_SAL  = ',INS_LQC_SAL
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC TEMPER   INS_LQC_TEMP = ',INS_LQC_TEMP
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC PRESSION INS_LQC_PRE  = ',INS_LQC_PRE
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC T PROFILE INS_LQC_PROF_T= ',INS_LQC_PROF_T
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC S PROFILE INS_LQC_PROF_S= ',INS_LQC_PROF_S
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK QC P PROFILE INS_LQC_PROF_P= ',INS_LQC_PROF_P
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK OBS TIME     INS_CHK_TIME = ',INS_CHK_TIME
  WRITE(IOUNLOG,*) ' WHETHER TO CHECK ARGO GREY LIST INS_ARG_GREYL= ',INS_ARG_GREYL
  WRITE(IOUNLOG,*) ' WHETHER TO REJECT OBS WITH ABOVE REJECTIONS LL_VERTCHECK=',LL_VERTCHECK
  WRITE(IOUNLOG,*) ' WHETHER TO INGEST SST OBS FROM ICOADS LL_ICOADS =',LL_ICOADS
  WRITE(IOUNLOG,*) ' WHETHER TO INGEST SST OBS FROM DRIFTERS LL_DRIFTER_SST =',LL_DRIFTER_SST
  WRITE(IOUNLOG,*) ' FORMAT OF ICOADS OBS FILES CICOADS_FMT = ',CICOADS_FMT
  WRITE(IOUNLOG,*) ' KEEP SEA SURFACE OBS LL_KEEP_SURFACE =',LL_KEEP_SURFACE
  WRITE(IOUNLOG,*) ' NEW INSITU ERR DEF LL_NEWINSERR =',LL_NEWINSERR
  WRITE(IOUNLOG,*) ' IRREGULAR GRID INSITU REP ERR LL_INSREPERR_IRREG =',LL_INSREPERR_IRREG
  WRITE(IOUNLOG,*) ' VERTICAL THINNING PROCEDURE LL_VTHINNING = ',LL_VTHINNING
  WRITE(IOUNLOG,*) ' VERTICAL AVERAGING PROCEDURE LL_VAVERAGING = ',LL_VAVERAGING
  WRITE(IOUNLOG,*) ' OPTION FOR VERTICAL SPACING NN_VERTMESH = ',NN_VERTMESH
  WRITE(IOUNLOG,*) ' OPTION FOR CORRELATING OBS IN PROFILES NN_PROF_CORREL = ',NN_PROF_CORREL
  WRITE(IOUNLOG,*) ' PROFILES CORREL., ONLY PREPROC LL_PROFCORR_ONLYP =',LL_PROFCORR_ONLYP

! ---

  LL_SAVETHINOUTSLA = .FALSE.
  CALL POSNAM(IOUNNAM,'THINLST')
  READ(IOUNNAM,THINLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' THINLST NAMELIST INPUT (THINLST): '
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON SLA LTHIN_SLA = ', LTHIN_SLA
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON INS LTHIN_INS = ', LTHIN_INS
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON SST LTHIN_SST = ', LTHIN_SST
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON SSS LTHIN_SSS = ', LTHIN_SSS
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON SIC LTHIN_SIC = ', LTHIN_SIC
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM THINNING ON SIT LTHIN_SIT = ', LTHIN_SIT
  WRITE(IOUNLOG,*) ' THINNING OPTION FOR INSITU CINSTHINOPT       = ', CINSTHINOPT
  WRITE(IOUNLOG,*) ' USE 2-STEP PROCEDURE        LDOUBLETHIN      = ', LDOUBLETHIN
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SLA ON X RTHIND_SLA_X = ', RTHIND_SLA_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SLA ON Y RTHIND_SLA_Y = ', RTHIND_SLA_Y
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR INS ON X RTHIND_INS_X = ', RTHIND_INS_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR INS ON Y RTHIND_INS_Y = ', RTHIND_INS_Y
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR INS ON Z RTHIND_INS_Z = ', RTHIND_INS_Z
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SST ON X RTHIND_SST_X = ', RTHIND_SST_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SST ON Y RTHIND_SST_Y = ', RTHIND_SST_Y
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SSS ON X RTHIND_SSS_X = ', RTHIND_SSS_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SSS ON Y RTHIND_SSS_Y = ', RTHIND_SSS_Y
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SIC ON Y RTHIND_SIC_X = ', RTHIND_SIC_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SIC ON Y RTHIND_SIC_Y = ', RTHIND_SIC_Y
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SIT ON Y RTHIND_SIT_X = ', RTHIND_SIT_X
  WRITE(IOUNLOG,*) ' THINNING SCALE (GRIDPOINTS) FOR SIT ON Y RTHIND_SIT_Y = ', RTHIND_SIT_Y

  WRITE(IOUNLOG,*) ' SAVE THINNING OUT FOR SLA LL_SAVETHINOUTSLA = ',LL_SAVETHINOUTSLA

! ---

  CALL POSNAM(IOUNNAM,'BGQCLST')
  READ(IOUNNAM,BGQCLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' BACKGROUND QUALITY CHECK NAMELIST INPUT (BGQCLST): '
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM BGQC ON SLA LBGQC_SLA = ', LLBGQC_SLA
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM BGQC ON INS LBGQC_INS = ', LLBGQC_INS
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM BGQC ON SST LBGQC_SST = ', LLBGQC_SST
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM BGQC ON SSS LBGQC_SSS = ', LLBGQC_SSS
  WRITE(IOUNLOG,*) ' RATIO FOR BGQCHECK (ALPHA) SLA RALFA_SLA = ', RALFA_SLA
  WRITE(IOUNLOG,*) ' RATIO FOR BGQCHECK (ALPHA) INS RALFA_INS = ', RALFA_INS
  WRITE(IOUNLOG,*) ' RATIO FOR BGQCHECK (ALPHA) SST RALFA_SST = ', RALFA_SST
  WRITE(IOUNLOG,*) ' RATIO FOR BGQCHECK (ALPHA) SSS RALFA_SSS = ', RALFA_SSS
  WRITE(IOUNLOG,*) ' USE 3D FILES BG-ERRORS FOR QUALITYCHECK  = ', LLUSEBGERR
  WRITE(IOUNLOG,*) ' READ (OR COMPUTE) BG-ERRORS FOR Q. CHECK = ', LL_READ_BGE
  WRITE(IOUNLOG,*) ' BG-ERR. IF NOT LLUSEBGERR SSH RBGERR_SSH = ',RBGERR_SSH
  WRITE(IOUNLOG,*) ' BG-ERR. IF NOT LLUSEBGERR SAL RBGERR_SAL = ',RBGERR_SAL
  WRITE(IOUNLOG,*) ' BG-ERR. IF NOT LLUSEBGERR TEM RBGERR_TEM = ',RBGERR_TEM
  WRITE(IOUNLOG,*) ' BG-ERR. IF NOT LLUSEBGERR SST RBGERR_SST = ',RBGERR_SST
  WRITE(IOUNLOG,*) ' BG-ERR. IF NOT LLUSEBGERR SSS RBGERR_SSS = ',RBGERR_SSS

! ---

  CALL POSNAM(IOUNNAM,'CLCKLST')
  READ(IOUNNAM,CLCKLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' CLIMATOLOGY CHECK NAMELIST INPUT: '
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM CLIMCHECK ON INS LLCLCK_INS = ',LLCLCK_INS
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM CLIMCHECK ON SST LLCLCK_SST = ',LLCLCK_SST
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM CLIMCHECK ON SSS LLCLCK_SSS = ',LLCLCK_SSS
  WRITE(IOUNLOG,*) ' MAX DIFF WITH CLIM (S,T,PT) CLIMLIM = ',CLIMLIM(:)

! ---
  LL_COASTREJ_INS = .FALSE.
  LL_COASTREJ_SLA = .FALSE.
  LL_COASTREJ_SST = .FALSE.
  LL_COASTREJ_SSS = .FALSE.
  NN_COASTREJ_INS = 5
  NN_COASTREJ_SLA = 5
  NN_COASTREJ_SST = 5
  NN_COASTREJ_SSS = 5

  CALL POSNAM(IOUNNAM,'CREJLST')
  READ(IOUNNAM,CREJLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' COASTAL REJECTION CHECK NAMELIST INPUT: '
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM COASTAL REJ ON INS LL_COASTREJ_INS = ', LL_COASTREJ_INS
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM COASTAL REJ ON SLA LL_COASTREJ_SLA = ', LL_COASTREJ_SLA
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM COASTAL REJ ON SST LL_COASTREJ_SST = ', LL_COASTREJ_SST
  WRITE(IOUNLOG,*) ' WHETHER TO PERFORM COASTAL REJ ON SSS LL_COASTREJ_SSS = ', LL_COASTREJ_SSS
  WRITE(IOUNLOG,*) ' PARAMETER (KM) FOR COASTAL REJ ON INS NN_COASTREJ_INS = ', NN_COASTREJ_INS
  WRITE(IOUNLOG,*) ' PARAMETER (KM) FOR COASTAL REJ ON SLA NN_COASTREJ_SLA = ', NN_COASTREJ_SLA
  WRITE(IOUNLOG,*) ' PARAMETER (KM) FOR COASTAL REJ ON SST NN_COASTREJ_SST = ', NN_COASTREJ_SST
  WRITE(IOUNLOG,*) ' PARAMETER (KM) FOR COASTAL REJ ON SSS NN_COASTREJ_SSS = ', NN_COASTREJ_SSS

! ---
  LL_HUBERQC = .FALSE.
  LL_HUBERQC_SLA = .FALSE.
  LL_HUBERQC_INS = .FALSE.
  LL_HUBERQC_SST = .FALSE.
  LL_HUBERQC_SSS = .FALSE.
  LL_HUBERQC_INS_VERBOSE = .FALSE.
  ITER_HUBQC = 10

  CALL POSNAM(IOUNNAM,'HUBERLST')
  READ(IOUNNAM,HUBERLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' HUBER NORM QUALITYCHECK NAMELIST INPUT: '
  WRITE(IOUNLOG,*) ' WHETHER TO USE HUBER NORM VARQC LL_HUBERQC = ', LL_HUBERQC
  WRITE(IOUNLOG,*) ' WHETHER TO USE HUBER NORM VARQC ON SLA LL_HUBERQC_SLA = ', LL_HUBERQC_SLA
  WRITE(IOUNLOG,*) ' WHETHER TO USE HUBER NORM VARQC ON INS LL_HUBERQC_SLA = ', LL_HUBERQC_INS
  WRITE(IOUNLOG,*) ' WHETHER TO USE HUBER NORM VARQC ON SST LL_HUBERQC_SLA = ', LL_HUBERQC_SST
  WRITE(IOUNLOG,*) ' WHETHER TO USE HUBER NORM VARQC ON SSS LL_HUBERQC_SLA = ', LL_HUBERQC_SSS
  WRITE(IOUNLOG,*) ' VERBOSE OUTPUT FOR INS HUBER LL_HUBERQC_INS_VERBOSE = ', LL_HUBERQC_INS_VERBOSE
  WRITE(IOUNLOG,*) ' ITERATION WHERE TO START VARQC ITER_HUBQC = ', ITER_HUBQC
  WRITE(IOUNLOG,*) ' HUBER VARQC NON-SYMMETRIC COEFFS LL_HUBER_ASYMM = ', LL_HUBER_ASYMM
  WRITE(IOUNLOG,*) ' HUBER VARQC ADDITIONAL L05 NORM COEFFS LL_HUBER_L05   = ', LL_HUBER_L05


! ---
  NN_ICEBAL = 0
  CALL POSNAM(IOUNNAM,'BALLST')
  READ(IOUNNAM,BALLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' BALANCE OPERATOR NAMELIST INPUT: '
  WRITE(IOUNLOG,*) ' NUMBER OF EOS BAL_NNEOS = ', BAL_NNEOS
  WRITE(IOUNLOG,*) ' AML TIMESTEP RDT_AML    = ', RDT_AML
  WRITE(IOUNLOG,*) ' TYPE OF ICE BALANCE NN_ICEBAL = ', NN_ICEBAL

! ---
  LL_4DVAR = .FALSE.
  AHT0 = 600._R8
  RDT  = 3600._R8
  RDT_TRAJ = 86400._R8
  LL_VDIFF = .FALSE.
  KN_ZDFEXP=10
  IDB_COO = (/1,1,1/)
  LL_VVEL_NEMO = .TRUE.
  ZZ_VMIXC = 1._R8

  CALL POSNAM(IOUNNAM,'TLADLST')
  READ(IOUNNAM,TLADLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' 4DVAR NAMELIST INPUT: '
  WRITE(IOUNLOG,*) ' TURN ON SIMPLIFIED 4DVAR LL_4DVAR = ', LL_4DVAR
  WRITE(IOUNLOG,*) ' HORIZONTAL DIFFUSION  AHT0 = ', AHT0
  WRITE(IOUNLOG,*) ' 4DVAR TL MODEL TIMESTEP RDT = ', RDT
  WRITE(IOUNLOG,*) ' TRAJECTORY FIELDS TIMESTEP RDT_TRAJ = ', RDT_TRAJ
  WRITE(IOUNLOG,*) ' TRACER VERTICAL DIFFUSION LL_VDIFF = ', LL_VDIFF
  WRITE(IOUNLOG,*) ' EXPLICIT (1) OR IMPLICIT (2) VERT DIFF NN_VDIFF = ', NN_VDIFF
  WRITE(IOUNLOG,*) ' EXPLICIT VERTICAL DIFFUSION SUB-STEPS KN_ZDFEXP = ', KN_ZDFEXP
  WRITE(IOUNLOG,*) ' NUMBER OF OUT TIMESTEPS NTS_WRITE =',NTS_WRITE
  WRITE(IOUNLOG,*) ' OUT TIMESTEPS TS_WRITE =',TS_WRITE
  WRITE(IOUNLOG,*) ' TL MODEL   LL_TLMODEL =',LL_TLMODEL
  WRITE(IOUNLOG,*) ' AD MODEL   LL_ADMODEL =',LL_ADMODEL
  WRITE(IOUNLOG,*) ' TL MODEL DEBUGGING  LL_TLDEB =',LL_TLDEB
  WRITE(IOUNLOG,*) ' COORDINATES FOR DEBUG IDB_COO=',IDB_COO
  WRITE(IOUNLOG,*) ' TEST ADJOINT LL_ADTEST =',LL_ADTEST
  WRITE(IOUNLOG,*) ' USE SURFACE FLUXES LL_SRFFLX =',LL_SRFFLX
  WRITE(IOUNLOG,*) ' USE HORIZ ADVECTION LL_HADV =',LL_HADV
  WRITE(IOUNLOG,*) ' USE VERT. ADVECTION LL_VADV =',LL_VADV
  WRITE(IOUNLOG,*) ' USE HORIZ DIFFUSION LL_HDIFF=',LL_HDIFF
  WRITE(IOUNLOG,*) ' USE WEAKLY CONSTR. 4DVAR LL_WEAKLY =',LL_WEAKLY
  WRITE(IOUNLOG,*) ' EOFS OF MOD-ERROR NEOF_WW =',NEOF_WW
  WRITE(IOUNLOG,*) ' EOFS REGION OF MOD-ERROR NREGWW =',NREGW
  WRITE(IOUNLOG,*) ' MOD-ERROR EOFS SQUARED LSQEOFW =',LSQEOFW
  WRITE(IOUNLOG,*) ' TEMPORAL E-DECAY (IN ERROR TIMESTEPS) EDECAY =',EDECAY
  WRITE(IOUNLOG,*) ' POINTS FOR HORIZONT E-DECAY NPHOR =',NPHOR
  WRITE(IOUNLOG,*) ' HORIZONT E-DECAY (IN DEGREES ) WRADC =',WRADC
  WRITE(IOUNLOG,*) ' ADJOINT TEST ON WEAK-C FORMULATION LL_TEST_WEAK =',LL_TEST_WEAK
  WRITE(IOUNLOG,*) ' TIME-CONSTAN MODEL ERROR  LL_CONSTERR =',LL_CONSTERR
  WRITE(IOUNLOG,*) ' ADDITIVE SYSTEMATIC ERROR LL_SYSTERR =',LL_SYSTERR
  WRITE(IOUNLOG,*) ' USE VERT.VEL FROM NEMO OR COMPUTE LL_VVEL_NEMO =',LL_VVEL_NEMO
  WRITE(IOUNLOG,*) ' NO CORRELARIONS IN WEAK-CONSTR. LL_WC_NOCORR =',LL_WC_NOCORR
  WRITE(IOUNLOG,*) ' VERT. MIXING INFLATION ZZ_VMIXC =',ZZ_VMIXC
  WRITE(IOUNLOG,*) ' 3D-EOFS FOR MODEL ERRORS LL_WCEOF =',LL_WCEOF
  WRITE(IOUNLOG,*) ' NUMBER OF 3D-EOFS FOR MODEL ERRORS NN_WCEOF3D =',NN_WCEOF3D
  WRITE(IOUNLOG,*) ' DEGUG WEAK-CONSTRAINT LL_DEBUG_WEAKLY =',LL_DEBUG_WEAKLY
  WRITE(IOUNLOG,*) ' NUMBER OF 3D-EOFS, 2ND SET NN_WCEOF3D_2 =',NN_WCEOF3D_2
  WRITE(IOUNLOG,*) ' WEIGTH FOR DOUBLE SET OF 3D-EOFS, WCE_HW2 =',WCE_HW2

  !--- 

  LL_HYBRID = .FALSE.
  NN_ALPHA_CTL = 0
  ZALPHA = 1._R8
  REDNMC_H = 1._R8
  LSQUAREDEVA_H = .FALSE.
  NN_MLD_VLOC_H = 0
  LL_EOFS3D = .FALSE.
  LL_DIAHYBRID = .FALSE.
  LL_HYBRID_CR = .FALSE.

  CALL POSNAM(IOUNNAM,'HYBLST')
  READ(IOUNNAM,HYBLST)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' HYBRID NAMELIST INPUT (HYBLST): '
  WRITE(IOUNLOG,*) ' HYBRID FORMULATION              LL_HYBRID = ', LL_HYBRID
  WRITE(IOUNLOG,*) ' ALPHA IN CTL VECTOR          NN_ALPHA_CTL = ', NN_ALPHA_CTL
  WRITE(IOUNLOG,*) ' ALPHA VALUE (MULTIPLIER FOR v_c)   ZALPHA = ', ZALPHA
  WRITE(IOUNLOG,*) ' ALPHA VARIAN(MULTIPLIER FOR v_c) ZALPHA_VAR = ', ZALPHA_VAR
  WRITE(IOUNLOG,*) ' CONTROL VAR PRECONDITIONING LL_PRECON_ALPHA = ', LL_PRECON_ALPHA
  WRITE(IOUNLOG,*) ' ONLINE ESTIMATION OF ALPHA LL_ALPHA_ONLINE = ', LL_ALPHA_ONLINE
  WRITE(IOUNLOG,*) ' NUMBER OF LEADING EOFS               NEOF = ', NEOF
  WRITE(IOUNLOG,*) ' NUMBER OF EOF VERTICAL  LEVELS       NKMT = ', NKMT
  WRITE(IOUNLOG,*) ' NUMBER OF EOF REGIONS               NREGS = ', NREGS
  WRITE(IOUNLOG,*) ' NAME OF EOF FILE                 CFILEEOF = ', TRIM(CFILEEOF)
  WRITE(IOUNLOG,*) ' X-DIMENSION OF EOF GRID             EOGNX = ', EOGNX
  WRITE(IOUNLOG,*) ' Y-DIMENSION OF EOF GRID             EOGNY = ', EOGNY
  WRITE(IOUNLOG,*) ' Z-DIMENSION OF EOF GRID             EOGNZ = ', EOGNZ
  WRITE(IOUNLOG,*) ' COEFFICIENT FOR EIGENVALUES IN FILE REDNMC= ',REDNMC_H
  WRITE(IOUNLOG,*) ' WHETHER EIGENVALS ARE SQUARED LSQUAREDEVA_H = ', LSQUAREDEVA_H
  WRITE(IOUNLOG,*) ' MLD-DEPENDENT LOCALIZATION NN_MLD_VLOC_H = ', NN_MLD_VLOC_H
  WRITE(IOUNLOG,*) ' GRID-DEPENDENT INFLATION B LL_BGFACT_H   = ', LL_BGFACT_H
  WRITE(IOUNLOG,*) ' UNMASK EOFS LL_UNMASK_EOFS_H = ', LL_UNMASK_EOFS_H
  WRITE(IOUNLOG,*) ' USE 3D EOFS LL_EOFS3D = ', LL_EOFS3D
  WRITE(IOUNLOG,*) ' NUMBER OF 3D EOFS NN_EOFS3D = ', NN_EOFS3D
  WRITE(IOUNLOG,*) ' ROOT-SQUARE WEIGTH AEO = ', AEO
  WRITE(IOUNLOG,*) ' DIAGNOSTIC HYBRID INCREMENTS LL_DIAHYBRID = ', LL_DIAHYBRID
  WRITE(IOUNLOG,*) ' HYBRID CORRELATION LENGTH-SCALE LL_HYBRID_CR = ', LL_HYBRID_CR

  ROSH%EOGNX = EOGNX
  ROSH%EOGNY = EOGNY
  ROSH%EOGNZ = EOGNZ
  ROSH%NEOF = NEOF
  ROSH%NREG = NREGS
  ROSH%KMT  = NKMT
  ROSH%EOF_FILE = CFILEEOF
  ROSH%DEP_MAX = RMD_DEP_MAX

  LL_ALPHA_CTL = ( NN_ALPHA_CTL .EQ. 1 .OR. NN_ALPHA_CTL .EQ. 2)

  CLOSE(IOUNNAM)
  WRITE(IOUNLOG,*) ' ----------------------------------------'

RETURN
END SUBROUTINE DEF_NML
