SUBROUTINE DIFFTIME(COPT,CDATE1,CDATE2,IDIFFER,IRETC,LWRN)

!
! DRIVING ROUTINE FOR DIFFDATE
! A.STORTO
!

USE TIMEFINC

IMPLICIT NONE


CHARACTER,INTENT(IN) :: COPT
CHARACTER(LEN=*),INTENT(INOUT) :: CDATE1,CDATE2
INTEGER,INTENT(OUT) :: IDIFFER,IRETC
LOGICAL,INTENT(IN) :: LWRN

INTEGER :: IDAYS,IHOURS,IMINS,ISEC,DATE1,DATE2
LOGICAL :: LNOEXIT
INTEGER :: IDATETEMP,IDATEARR,ISIGNPN,IDATE1(6),IDATE2(6)
INTEGER :: IRET,IL1,IL2
CHARACTER(LEN=10) :: CSTRING

LNOEXIT=LWRN
IRETC=0

CALL TOUPPERDT(COPT)

IDATE1=0
IDATE2=0

IL1=LEN_TRIM(CDATE1)
IL2=LEN_TRIM(CDATE2)

IF(IL1.LT.8 .OR. IL2.LT.8) CALL WRLNG(LNOEXIT,0,IRETC)

READ(CDATE1(1:4),*) IDATE1(1)
READ(CDATE1(5:6),*) IDATE1(2)
READ(CDATE1(7:8),*) IDATE1(3)
READ(CDATE2(1:4),*) IDATE2(1)
READ(CDATE2(5:6),*) IDATE2(2)
READ(CDATE2(7:8),*) IDATE2(3)

SELECT CASE(COPT)

      CASE('D')   ! DAYS

           ! NOTHING TO DO

      CASE('H')   ! HOURS

           IF(IL1.LT.10 .OR. IL2.LT.10) CALL WRLNG(LNOEXIT,0,IRETC)
           READ(CDATE1(9:10),*) IDATE1(4)
           READ(CDATE2(9:10),*) IDATE2(4)

      CASE('M')   ! MINUTES

           IF(IL1.LT.12 .OR. IL2.LT.12) CALL WRLNG(LNOEXIT,0,IRETC)

           READ(CDATE1(9:10),*) IDATE1(4)
           READ(CDATE1(10:11),*) IDATE1(5)
           READ(CDATE2(9:10),*) IDATE2(4)
           READ(CDATE2(10:10),*) IDATE2(5)

      CASE('S')   ! SECONDS

           IF(IL1.LT.14 .OR. IL2.LT.14) CALL WRLNG(LNOEXIT,0,IRETC)

      CASE DEFAULT

           WRITE(0,*) '*** FROM DIFFTIME:'
           WRITE(0,*) 'ILLEGAL OPTION ',COPT

           IRETC=-1
           IF(LNOEXIT) THEN
              WRITE(0,*) 'CONTINUING...'
           ELSE
              STOP 'EXITING'
           ENDIF

ENDSELECT

IRET=CHECK_TIME(IDATE1,0)
IF(IRET.NE.0) IRETC=IRET
IF(IRET.NE.0 .AND. .NOT.LNOEXIT) STOP 'EXITING'

IRET=CHECK_TIME(IDATE2,0)
IF(IRET.NE.0) IRETC=IRET
IF(IRET.NE.0 .AND. .NOT.LNOEXIT) STOP 'EXITING'

!..... COMMON CALL TO DIFFDATE

DATE1=IDATE1(3) + IDATE1(2)*100 + IDATE1(1)*10000
DATE2=IDATE2(3) + IDATE2(2)*100 + IDATE2(1)*10000

IF ( DATE1 .GT. DATE2 ) THEN

 ISIGNPN=1
 IDATETEMP=DATE2
 IDATEARR=DATE1

ELSE

 ISIGNPN=-1
 IDATETEMP=DATE1
 IDATEARR=DATE2

END IF

 IDAYS = 0

 DO WHILE (IDATETEMP .LT. IDATEARR )

  CALL PLUSDAY(IDATETEMP)
  IDAYS=IDAYS+1

 END DO

 IHOURS = IDATE1(4) - IDATE2(4)
 IMINS = IDATE1(5) - IDATE2(5)
 ISEC = IDATE1(6) - IDATE2(6)

!... COMPUTE SOLUTION IN THE RIGHT UNIT

SELECT CASE(COPT)

      CASE('D')   ! DAYS

           IDIFFER=ISIGNPN*IDAYS

      CASE('H')   ! HOURS

           IDIFFER=ISIGNPN*IDAYS*24 + IHOURS

      CASE('M')   ! MINUTES

           IDIFFER=ISIGNPN*IDAYS*24*60 + IHOURS*60 + IMINS

      CASE('S')   ! SECONDS

           ! ONLY THE CASE INTEGER>=INTEGER*4 IS TREATED                  !
           IF(IDAYS.GT.24000 .AND. HUGE(IDIFFER).LE.2147483647) THEN
                 WRITE(0,*) '*** DIFFTIME: WARNING ***'
                 WRITE(0,*) 'INTEGER*4 MAY BE INSUFFICIENT TO CONTAIN ',&
                 & 'DIFFTIME RESULT'
                 WRITE(0,*) '  COMPILE INDEED WITH 8-BYTES PRECISION ',&
                       'FOR INTEGERS'
           ENDIF
           IDIFFER = ISEC + IMINS*60 + IHOURS*3600 + (ISIGNPN*IDAYS*3600*24)

END SELECT

END SUBROUTINE DIFFTIME
