MODULE MOD_GCDIST

!.. GIVEN THE COORDINATES (DEGREES) OF 2 POINTS
!.. GCDIST RETURNS THE GREAT-CIRCLE DISTANCE IN KILOMETERS
!..
!.. ADAPTED TO FORTRAN90 FROM
!.. BOWDITCH, N.; "AMERICAN PRACTICAL NAVIGATOR, VOL. I."; DEFENSE MAPPING
!.. AGENCY HYDROGRAPHIC CENTER, 1977. PAGES 1258-1263.
!..
!.. ANDREA STORTO, 2009

USE SET_KND

PUBLIC GCDIST

#ifdef NO_DOUBLEPREC
INTERFACE GCDIST
  MODULE PROCEDURE GCDIST_R4
END INTERFACE GCDIST
#else
INTERFACE GCDIST
  MODULE PROCEDURE GCDIST_R8, GCDIST_R4
END INTERFACE GCDIST
#endif

CONTAINS

SUBROUTINE GCDIST_R8(LATS,LONS,LATE,LONE,DIST)

IMPLICIT NONE

REAL(R8),INTENT(IN)  :: LATS,LONS,LATE,LONE
REAL(R8),INTENT(OUT) :: DIST
REAL(R8) ::  RPD,PI,PI2T,DPR,PIO2
REAL(R8)             :: ZLATS,ZLONS,ZLATE,ZLONE
REAL(R8)             :: ZW,ZC1,ZC2,LL,DLO

ZLATS=LATS
ZLATE=LATE
ZLONS=LONS
ZLONE=LONE


PI=2._R8*ASIN(1._R8)
PI2T = 2._R8*PI
PI2T = PI*0.5_R8
RPD=PI/180._R8
DPR=180._R8/PI

IF(ZLONS.LT.0._R8) ZLONS = ZLONS+360._R8
IF(ZLONE.LT.0._R8) ZLONE = ZLONE+360._R8

DLO = (ZLONE-ZLONS)*RPD

IF(DLO.LT.-PI) DLO=DLO+PI2T
IF(DLO.GT.PI)  DLO=DLO-PI2T

ZLATS=ZLATS*RPD
ZLATE=ZLATE*RPD

IF(ZLATS.EQ.ZLATE .AND. DLO .EQ. 0._R8) THEN
   DIST=0._R8
   RETURN
ENDIF

LL = ZLATE - ZLATS

ZC1 = PIO2 - ZLATS
ZC2 = PIO2 - ZLATE

DIST = ((1._R8-COS(DLO))*0.5_R8)*COS(ZLATS)*COS(ZLATE) +&
     & ((1._R8-COS(LL))*0.5_R8)

ZW = 1._R8 - 2._R8*DIST
IF( ZW .GT. 1._R8 ) ZW = 1._R8
IF( ZW .LT.-1._R8 ) ZW =-1._R8

DIST = ACOS(ZW)*DPR*111.12000071117_R8

END SUBROUTINE GCDIST_R8

!========================================================

SUBROUTINE GCDIST_R4(LATS,LONS,LATE,LONE,DIST)

IMPLICIT NONE

REAL(R4),INTENT(IN)  :: LATS,LONS,LATE,LONE
REAL(R4),INTENT(OUT) :: DIST
REAL(R4) ::  RPD,PI,PI2T,DPR,PIO2
REAL(R4)             :: ZLATS,ZLONS,ZLATE,ZLONE
REAL(R4)             :: ZW,ZC1,ZC2,LL,DLO

ZLATS=LATS
ZLATE=LATE
ZLONS=LONS
ZLONE=LONE


PI=2._R4*ASIN(1._R4)
PI2T = 2._R4*PI
PI2T = PI*0.5_R4
RPD=PI/180._R4
DPR=180._R4/PI

IF(ZLONS.LT.0._R4) ZLONS = ZLONS+360._R4
IF(ZLONE.LT.0._R4) ZLONE = ZLONE+360._R4

DLO = (ZLONE-ZLONS)*RPD

IF(DLO.LT.-PI) DLO=DLO+PI2T
IF(DLO.GT.PI)  DLO=DLO-PI2T

ZLATS=ZLATS*RPD
ZLATE=ZLATE*RPD

IF(ZLATS.EQ.ZLATE .AND. DLO .EQ. 0._R4) THEN
   DIST=0._R4
   RETURN
ENDIF

LL = ZLATE - ZLATS

ZC1 = PIO2 - ZLATS
ZC2 = PIO2 - ZLATE

DIST = ((1._R4-COS(DLO))*0.5_R4)*COS(ZLATS)*COS(ZLATE) +&
     & ((1._R4-COS(LL))*0.5_R4)

ZW = 1._R4 - 2._R4*DIST
IF( ZW .GT. 1._R4 ) ZW = 1._R4
IF( ZW .LT.-1._R4 ) ZW =-1._R4

DIST = ACOS(ZW)*DPR*111.12000071117_R4

END SUBROUTINE GCDIST_R4

END MODULE MOD_GCDIST
