!-- GENERIC TRACEBACK CALLS HERE

SUBROUTINE GENTRBK_DUMMY
END SUBROUTINE GENTRBK_DUMMY

#ifdef __INTEL_COMPILER
SUBROUTINE INTEL_TRBK()
USE IFCORE
CALL TRACEBACKQQ('CALLING TRACEBACK FROM INTEL_TRBK()', USER_EXIT_CODE=-1)
#ifdef LINUX
CALL LINUX_TRBK() ! SEE IFSAUX/UTILITIES/LINUXTRBK.C
#endif
END SUBROUTINE INTEL_TRBK
#endif

#ifndef VPP
SUBROUTINE ERRTRA
END SUBROUTINE ERRTRA
#endif

#ifdef NECSX
SUBROUTINE NECSX_TRBK(CDMESS)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CDMESS
CALL MESPUT(CDMESS, LEN(CDMESS), 1)
CALL DBX_TRBK()
END SUBROUTINE NECSX_TRBK

SUBROUTINE NECSX_TRBK_FL(CDMESS, CDFILENAME, KLINENO)
IMPLICIT NONE
INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
CHARACTER(LEN=*), INTENT(IN) :: CDMESS
CHARACTER(LEN=*), INTENT(IN) :: CDFILENAME
INTEGER(KIND=JPIM), INTENT(IN) :: KLINENO
CHARACTER(LEN=LEN(CDMESS)+LEN(CDFILENAME)+30) CLOCAL
WRITE(CLOCAL,'(A," AT ",A,":",I6.6)') TRIM(CDMESS),TRIM(CDFILENAME),KLINENO
CALL NECSX_TRBK(TRIM(CLOCAL))
END SUBROUTINE NECSX_TRBK_FL
#endif
