SUBROUTINE GETSSTMB(SST)

USE GRD_STR
USE SET_KND
USE NETCDF

IMPLICIT NONE

REAL(R8), INTENT(OUT) :: SST(GRD%IM,GRD%JM,12)
INTEGER(I4) :: STAT, NCID,IDVAR

       STAT = NF90_OPEN('sstbias.nc',&
              & NF90_NOWRITE, NCID)
       IF(STAT.NE.0) THEN
         WRITE(*,*) 'PROBLEMS OPENING SSTBIAS.NC'
         CALL ABOR1('NETCDF FILE NOT FOUND')
       ENDIF
       STAT = NF90_INQ_VARID (NCID, 'sstm', IDVAR)
       IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
       STAT = NF90_GET_VAR (NCID, IDVAR, SST ,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,12/))
       IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
       STAT = NF90_CLOSE(NCID)
       IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

RETURN
END SUBROUTINE GETSSTMB
