SUBROUTINE INI_BAL

 USE SET_KND
 USE GRD_STR
 USE BAL
 USE RUN, ONLY : ZNOML
 USE MYNETCDF
 USE IOUNITS

IMPLICIT NONE

  INTEGER(I4)    :: K,I,J
  REAL(R8)       :: ZDZ

  BAL_LNM = ZNOML
  ALLOCATE( DHDZ(GRD%KM) )

  ZDZ=0._R8
  DHDZ = GRD%DZ
  DO K=1,GRD%KM
      ZDZ=ZDZ+GRD%DZ(K)
      IF( ZDZ .LT. BAL_LNM ) THEN
          NLEVS=K
      ENDIF
  ENDDO
  NLEVS=NLEVS+1
  DHDZ(NLEVS) = SUM( GRD%DZ(1:NLEVS) ) - BAL_LNM
  WRITE(IOUNLOG,*) ' INI_BAL : NO MOTION LEVEL = ', NLEVS, BAL_LNM

  IF( BAL_NNEOS .EQ. 2 .OR. BAL_NNEOS .EQ. 3) THEN
    WRITE(IOUNLOG,*) ' INI_BAL : READING BACKGROUND T/S'
    ALLOCATE( BAL_TEMB(GRD%IM,GRD%JM,GRD%KM) )
    ALLOCATE( BAL_SALB(GRD%IM,GRD%JM,GRD%KM) )
    CALL GETNCVAR('BACKGROUND.nc','votemper',GRD%IM,GRD%JM,GRD%KM,BAL_TEMB)
    CALL GETNCVAR('BACKGROUND.nc','vosaline',GRD%IM,GRD%JM,GRD%KM,BAL_SALB)
  ENDIF

END SUBROUTINE INI_BAL
