INTERFACE
SUBROUTINE IO_OBS(CFILE,IOPT,NOBS,NLEVS,NPREDS,NPQ,NPQ2,&
& NIND, INO, OTYPE, PAR, PLNO, INST, EVE, KTY, &
& PRIND, PROF, TDIST, LON, LAT, DPT, TIM, &
& VAL, BIA, IB, JB, KB, RB, PQ, &
& TRACK, KSAT, BOT, FLG, &
& FLC, INC, BAC, ERR, RES, B_A, TB, SB, BCP,BGERR, SD1, SD2, MOI, MOJ )

  USE SET_KND
  USE NETCDF
  IMPLICIT NONE

  INTEGER(I4), INTENT(IN) :: IOPT,NOBS,NLEVS,NPREDS,NPQ,NPQ2
  CHARACTER(LEN=*), INTENT(IN) :: CFILE

  INTEGER(I4), PARAMETER :: MAXVAR = 99
  INTEGER(I4) :: NCID,VARID(MAXVAR),DIMIDS,&
  & DIMIDS8(2),DIMIDS16(2),DIMIDS2(2),DIMIDSBC(2),DIMIDSIJ(2),DIMIDSPQ(2)
  INTEGER(I4) :: X_DIMID, IN, C1_DIMID, C2_DIMID, L_DIMID, B_DIMID, Q_DIMID, Q2_DIMID
 
  REAL(R8), DIMENSION(NOBS),  OPTIONAL :: &
  & LON, LAT, DPT, VAL, BIA, &
  & INC, BAC, ERR, RES, B_A, BGERR, &
  & RB
  REAL(DP), DIMENSION(NOBS),  OPTIONAL :: TDIST, TIM
  REAL(R8), DIMENSION(NOBS,NLEVS),  OPTIONAL :: TB, SB
  REAL(R8), DIMENSION(NOBS,NPREDS),  OPTIONAL :: BCP
  INTEGER(I4), DIMENSION(NOBS),  OPTIONAL :: &
  & NIND, INO, OTYPE, PAR, INST, EVE, KTY, PRIND, PROF, &
  & KB, KSAT, BOT, FLG, FLC, TRACK, SD1, SD2
  INTEGER(I4), DIMENSION(NOBS,NPQ),  OPTIONAL :: IB, JB, MOI, MOJ
  REAL(R8), DIMENSION(NOBS,NPQ2),    OPTIONAL :: PQ
  CHARACTER(LEN=8), DIMENSION(NOBS),  OPTIONAL :: &
  & PLNO

END SUBROUTINE IO_OBS
END INTERFACE
