MODULE RECFILTER

!.. MODULE RECFILTER ..
!
!
!   CONTAINS ALL THE SUBROUTINES INVOLVING
!   RECURSIVE FILTER SETUP AND COMPUTATIONS
!
!   ADOPTED FROM MFSVAR (DOBRICIC, PINARDI)
!   AND RECODED IN A MODULAR WAY
!   TO PERMIT MORE FLEXIBLE DEFINITION OF CORRELATION
!   RADIUS (CR), I.E. OF RF ALPHA COEFFICIENTS,
!   FOR INSTANCE:
!
!   - VERTICALLY-VARYING CORRELATION LENGTH-SCALE
!   - MERIDIONALLY-VARYING ZONAL CORRELATION LENGTH-SCALE
!     (I.E. INCREASE THE RATIO OF ZONAL AND MERIDIONAL
!     CORRELATION SCALE WHEN CLOSER TO EQUATOR)
!   - INDEPENDENT DEFINITION OF LENGTH-SCALE FOR T,S
!     (E.G. ALLOW LARGER SALINITY LENGTH-SCALE AT AMAZON
!     RIVER MOUTH AND ARTIC AREAS WITHOUT ALTERING
!     THE VALUES FOR TEMPERATURE)
!   - ALLOWS SMOOTHED LOCAL VARIATIONS OF CR
!
!   NOTE:
!   -> TARGET ARRAYS CONTAIN DATA FOR X=(T,S), WHILE SUBSCRIPTED
!      _T AND _S ARRAYS POINT TO THEIR RESPECTIVE PART, FOR CONSISTENCY
!      WITH THE OPENMP PARALLELIZATION WITHIN THE RECURSIVE FILTER ROUTINES.
!   -> LOCALLY VARYING CR ARE USED (BY DEFAULT) AFTER
!      THE FIRST PASS OF RC, AS IT SIMULATES A
!      QUALITY-DEPENDING SMOOTHER
!
!   === THE FOLLOWING ROUTINES ARE CONTAINED IN THIS MODULE ===
!
!   SUBROUTINE SETUPRFCR
!   SUBROUTINE READ_CRF1
!   SUBROUTINE READ_CRF2
!   SUBROUTINE COMPSC
!   SUBROUTINE COMPALPHA
!   SUBROUTINE COMPALPHA2
!   SUBROUTINE DEFEXTGRD
!   SUBROUTINE REARRALPHA
!   SUBROUTINE REARRALPHA2
!   SUBROUTINE RCFL_X(IM,JM,KM,FLD)
!   SUBROUTINE RCFL_Y(IM,JM,KM,FLD)
!   SUBROUTINE RCFL_X_AD(IM,JM,KM,FLD)
!   SUBROUTINE RCFL_Y_AD(IM,JM,KM,FLD)
!   SUBROUTINE RCFL_X_2D(IM,JM,FLD)
!   SUBROUTINE RCFL_Y_2D(IM,JM,FLD)
!   SUBROUTINE RCFL_X_AD_2D(IM,JM,FLD)
!   SUBROUTINE RCFL_Y_AD_2D(IM,JM,FLD)
!   SUBROUTINE RCFL_Y_OLD(IM,JM,KM,L_JMAX,L_AL,L_BT,FLD,L_JNX,L_JMX)
!   SUBROUTINE RCFL_Y_AD_OLD(IM,JM,KM,L_JMAX,L_AL,L_BT,FLD,L_JNX,L_JMX)
!
!   ===========================================================
!
!   ANDREA STORTO : 2009-06-23

USE SET_KND
USE IOUNITS, ONLY : IOUNLOG,IOUNERR,IOUNOUT

IMPLICIT NONE

SAVE
PUBLIC

! WHETHER RF HAVE BEEN INITIALISED
LOGICAL :: LLRFINIT=.FALSE.

! GLOBALLY-AVERAGED CORRELATION RADIUS (AS A SCALAR OR AS A FUNCTION OF Z)
REAL(KIND=R8), ALLOCATABLE, TARGET :: ZGA_CRAD(:)

! T, S POINTERS
REAL(KIND=R8), POINTER :: ZGA_CRAD_T(:), ZGA_CRAD_S(:)

! WHETHER WE USE A VERTICALLY-VARYING CR
LOGICAL :: LLVVCR=.FALSE.

! WHETHER WE USE INDEPENDENT RF FOR T,S
LOGICAL :: LLTSAPART=.FALSE.

! WHETHER TO RUN RF ON SURFACE FIELDS (SSH)
LOGICAL :: LL_NOSRF_RF = .FALSE.

! DEGREES OF FREEDOMS OF CR ON THE VERTICAL
INTEGER(KIND=I4) :: NTOTV

! NUMBER OF PASSES OF THE RF
INTEGER(KIND=I4) :: RF_NTR=4

! SCALING FACTOR FOR EXTENDED POINTS
REAL(KIND=R8) :: RF_EFC

! MAXIMUM NUMBER OF EXTENDED POINTS
INTEGER(KIND=I4) :: IMAX,JMAX
INTEGER(KIND=I4) :: IMAXF,JMAXF
INTEGER(KIND=I4) :: IMAXZ,JMAXZ

! MAX. NO. OF EXTENDED PNTS AT EACH LEVEL
INTEGER(KIND=I4), ALLOCATABLE :: IMX(:),JMX(:)
INTEGER(KIND=I4), ALLOCATABLE :: IMXF(:),JMXF(:)
INTEGER(KIND=I4) :: IMXZ, JMXZ

! POINTER FOR EXTENDED GRID
INTEGER(KIND=I4), ALLOCATABLE :: INX(:,:,:),JNX(:,:,:)
INTEGER(KIND=I4), ALLOCATABLE :: INXF(:,:,:),JNXF(:,:,:)
INTEGER(KIND=I4), ALLOCATABLE :: INXZ(:,:),JNXZ(:,:)

! EXTENDED POINTS
INTEGER(KIND=I4), ALLOCATABLE :: ISTPNS(:,:,:),JSTPNS(:,:,:)
INTEGER(KIND=I4), ALLOCATABLE :: ISTPNSF(:,:,:),JSTPNSF(:,:,:)
INTEGER(KIND=I4), ALLOCATABLE :: ISTPNSZ(:,:),JSTPNSZ(:,:)

! SCALING FACTORS
REAL(KIND=R8), ALLOCATABLE :: SCXNS(:,:,:),SCYNS(:,:,:)
REAL(KIND=R8), ALLOCATABLE :: SCXNSF(:,:,:),SCYNSF(:,:,:)
REAL(KIND=R8), ALLOCATABLE :: SCXNZ(:,:),SCYNZ(:,:)

! ALPHA COEFFICIENTS
REAL(KIND=R8), ALLOCATABLE :: ALXNS(:,:,:),BTXNS(:,:,:),&
                            & ALYNS(:,:,:),BTYNS(:,:,:)
REAL(KIND=R8), ALLOCATABLE :: GMXNS(:,:,:),DLXNS(:,:,:),&
                            & GMYNS(:,:,:),DLYNS(:,:,:)

REAL(KIND=R8), ALLOCATABLE :: ALXNZ(:,:),BTXNZ(:,:),&
                            & ALYNZ(:,:),BTYNZ(:,:)

! REARRANGED ALPHA COEFFICIENTS
REAL(KIND=R8), ALLOCATABLE :: RF_AEX(:,:,:),RF_BEX(:,:,:),&
                            & RF_AEY(:,:,:),RF_BEY(:,:,:)
REAL(KIND=R8), ALLOCATABLE :: RF_GEX(:,:,:),RF_DEX(:,:,:),&
                            & RF_GEY(:,:,:),RF_DEY(:,:,:)

REAL(KIND=R8), ALLOCATABLE :: RF_AEXZ(:,:),RF_BEXZ(:,:),&
                            & RF_AEYZ(:,:),RF_BEYZ(:,:)

REAL(KIND=R8), ALLOCATABLE :: RFF_AEX(:,:,:),RFF_BEX(:,:,:),&
                            & RFF_AEY(:,:,:),RFF_BEY(:,:,:)
REAL(KIND=R8), ALLOCATABLE :: RFF_GEX(:,:,:),RFF_DEX(:,:,:),&
                            & RFF_GEY(:,:,:),RFF_DEY(:,:,:)

! NORMALIZATION FACTOR
REAL(KIND=R8), ALLOCATABLE :: FCT(:,:,:)

! LENGTH-SCALE USED ONLY IF CONSTANT ALL OVER !
REAL(KIND=R8) :: RF_L

INTEGER(KIND=I4) :: RFKCOUNT(8)=0
LOGICAL, PARAMETER :: LLPPT=.FALSE.

! RECURSIVE FILTER SUMMER REVISION
LOGICAL :: LLRFSR=.FALSE.

REAL(KIND=R8),ALLOCATABLE,DIMENSION(:,:,:) :: SR_SCXT,SR_SCYT,SR_GALXT,SR_GALYT,&
                        & SR_GBTXT,SR_GBTYT,SR_SCXS,SR_SCYS,SR_GALXS,SR_GALYS,SR_GBTXS,&
                        & SR_GBTYS

REAL(KIND=R8),ALLOCATABLE,DIMENSION(:,:) :: SR_SCXZ,SR_SCYZ,SR_GALXZ,SR_GALYZ,&
                        & SR_GBTXZ,SR_GBTYZ

LOGICAL :: LLDEBRCFLX=.FALSE.

LOGICAL, ALLOCATABLE :: LLMSR(:,:,:), LLMSR2(:,:), LLMSRM(:,:)

LOGICAL :: LLRFCBOUNDED=.TRUE.

REAL(KIND=R8) :: ZRFMAXC=0.99_R8

LOGICAL :: LLPRINTRCFLC=.FALSE.

INTEGER(KIND=I4) :: NNRFSR=1

INTEGER(KIND=I4) :: RF_IMAX, RF_JMAX

REAL(KIND=R8), ALLOCATABLE, DIMENSION(:,:) :: NEWDX, NEWDY

REAL(KIND=R8), ALLOCATABLE, DIMENSION(:,:,:) :: &
& CRX,CRY

REAL(KIND=R8), ALLOCATABLE, DIMENSION(:,:,:) :: &
& CRFX,CRFY

REAL(KIND=R8), ALLOCATABLE, DIMENSION(:,:) :: &
& CRMX,CRMY

LOGICAL :: LLRFMASK=.TRUE.

LOGICAL :: LL_RFLV=.TRUE.
REAL(KIND=R8)          :: RF_CRMN=20000._R8, RF_CRMX=1200000._R8
INTEGER(KIND=I4)       :: RF_NRES=20
INTEGER(KIND=I4)       :: RF_NCR=100
REAL(KIND=R8)          :: RF_CORRAD_MFACT=1000.
LOGICAL :: LL_READCOMPSC_LV, LL_WRITECOMPSC_LV

INTEGER(KIND=I4)       :: RCF_TYPE = 1

END MODULE RECFILTER
