MODULE RUN

!.. RUN MODULE FOR VARIOUS INFO
!..
!..
!..

USE SET_KND
USE OBSDEF
USE IOUNITS, ONLY : IOUNERR

IMPLICIT NONE

PUBLIC
SAVE

LOGICAL :: LL_BGFACT
LOGICAL :: LL_DENSLEVS
LOGICAL :: LL_UNMASK_EOFS
LOGICAL :: LL_SSH_UNBALANCED
LOGICAL :: LL_TQ2_UNBALANCED
LOGICAL :: LL_WRITE_SLA_BIAS
LOGICAL :: LL_RESTART_FILE
LOGICAL :: LL_SSS_BCORR
LOGICAL :: LL_PROJDOWN
CHARACTER(LEN=200) :: CINSTRING
INTEGER(I4) :: NN_ICEBAL
INTEGER(I4) :: NCONF
INTEGER(I4) :: NGRID_ID
INTEGER(I4) :: NN_INTERPM
INTEGER(I4) :: NN_DENSREC = 0
INTEGER(I4) :: IO_OBSFORMAT
INTEGER(I4) :: IANDATE,IANTIME,IANTW
INTEGER(I4) :: IANYY,IANMM,IANDD,IANHH,IANMI
INTEGER(I4) :: NTSTEPS
INTEGER(I4) :: RES_ITER
INTEGER(I4) :: IDOUBLEDOM
INTEGER(I4) :: NN_DOMSTART
INTEGER(I4),PARAMETER :: MAXT=165
INTEGER(I4) :: NN_SLABC_BY = 2
INTEGER(I4) :: NN_INS_SST
INTEGER(I4) :: NN_REG_REJ = 0
LOGICAL :: LL_HUBER_ASYMM, LL_HUBER_L05
INTEGER(I4), PARAMETER :: NHUBOUT = 6749
REAL(R8) :: RLIM_HUBERQC_SLA(NOSLASATS,2)
REAL(R8) :: RLIM_HUBERQC_SST(NOSSTSATS,2)
REAL(R8) :: RLIM_HUBERQC_SSS(NOSSSSATS,2)
REAL(R8) :: RLIM_HUBERQC_INS(NOINSITU,NOPARAMS,2)
REAL(R8) :: RLIM_HUBERQC_SLA2(NOSLASATS,2)
REAL(R8) :: RLIM_HUBERQC_SST2(NOSSTSATS,2)
REAL(R8) :: RLIM_HUBERQC_SSS2(NOSSSSATS,2)
REAL(R8) :: RLIM_HUBERQC_INS2(NOINSITU,NOPARAMS,2)
REAL(R8) :: ZZ_SLA_BIAS =0._R8
LOGICAL :: LL_CORRAD_2D
LOGICAL :: LL_HUBERQC_INS_VERBOSE
INTEGER(I4) :: NN_MLD_VLOC
LOGICAL :: LL_HUBERQC
LOGICAL :: LL_HUBERQC_SLA, LL_HUBERQC_INS, LL_HUBERQC_SST, LL_HUBERQC_SSS
LOGICAL :: LL_INIT_HUBER = .FALSE.
LOGICAL :: LL_OBSS_TSP = .FALSE.
INTEGER(I4) :: ITER_HUBQC
INTEGER(I4) :: CVM_S,CVM_E,CVB
REAL(R8) :: ZMDT_CLS
REAL(DP) :: ZANSS
REAL(DP) :: ZJULIAN,ZJULSTART,ZJULEND,ZANJUL1950
REAL(DP) :: ZJUL1950, ZJULSTARTMM
REAL(R8) :: SLA_REPERR_INFLAT
CHARACTER(LEN=300)  :: CARGS
CHARACTER(LEN=12) :: CDATETIME
CHARACTER(LEN=8 ) :: CDATE
CHARACTER(LEN=4 ) :: CTIME
LOGICAL           :: LL_KEEP_SURFACE
LOGICAL           :: LL_ICOADS
LOGICAL           :: LL_DRIFTER_SST
LOGICAL           :: LL_SLABCORR
LOGICAL           :: LL_LSBC
LOGICAL           :: LL_NOPSABORT
LOGICAL           :: LLSLAATCORR
LOGICAL           :: LLOBSSTAT
LOGICAL           :: LLVARMDT
LOGICAL           :: LLEVEFORMV
LOGICAL           :: LL_ICEINIT = .FALSE.
LOGICAL           :: LL_ICEREJ
LOGICAL           :: LL_ICEBGFILT
LOGICAL           :: LL_ICEANFILT
LOGICAL           :: LL_ICERFMASK
LOGICAL           :: LL_ICEREJ_DCOAST
LOGICAL           :: LL_WRITE_OBS_SCREEN
LOGICAL           :: LL_WRITECORRBIN
LOGICAL           :: LL_BOUNDANAL
LOGICAL           :: LL_HRINTERP
LOGICAL           :: LLSHAPIROANL
LOGICAL           :: LL_BOTTOMFILTER
LOGICAL           :: LL_IAU
LOGICAL           :: LL_VERTCHECK
LOGICAL           :: LL_VTHINNING
INTEGER(I4)       :: NN_VERTMESH
LOGICAL           :: LL_VAVERAGING
LOGICAL           :: LL_NOFGAT
LOGICAL           :: LLONLYOBSPP
LOGICAL           :: LL_SAVETHINOUTSLA
LOGICAL           :: LL_COASTREJ_INS,LL_COASTREJ_SLA,LL_COASTREJ_SST,LL_COASTREJ_SSS
INTEGER(I4)       :: NN_COASTREJ_INS,NN_COASTREJ_SLA,NN_COASTREJ_SST,NN_COASTREJ_SSS
INTEGER(I4)       :: NN_ITERSHAP
REAL(R8) :: ZANMAXTEM, ZANMAXSAL
REAL(R8) :: ZMIN_ICEDIST
REAL(R8) :: ZICEINFLDIST, RHO0
REAL(DP) :: RTIMES1950(MAXT)
REAL(R8) :: ZVARMDT_RATIOSD = 1._R8
INTEGER(I4) :: KLEVNM
INTEGER(I4) :: ANATSTEP
CHARACTER(LEN=3 ) :: COBSOPT
CHARACTER(LEN=3 ) :: CINS_FMT
CHARACTER(LEN=4 ) :: CICOADS_FMT
REAL(R8) :: ZNOML,REDNMC
REAL(R8),ALLOCATABLE :: ZRCOEFF(:,:,:)
LOGICAL           :: LLCORRSSH
LOGICAL           :: LLLATINT_TAB
LOGICAL           :: LL_TWCENTERED
INTEGER, PARAMETER :: NLATINTS = 18
INTEGER, DIMENSION(NLATINTS) :: JLT_ST, JLT_EN
INTEGER(I4) :: NSUBDOMAINS
LOGICAL     :: LLFORMBGE = .FALSE.
LOGICAL     :: LL_ONEPROC103 = .FALSE.
LOGICAL     :: LL_READALLBIN103 = .FALSE.
LOGICAL     :: LL_VARLNM = .FALSE.
LOGICAL     :: LL_UNBIAS_SLA = .TRUE.
LOGICAL     :: LL_UNBIAS_SLA_LAT = .FALSE.
LOGICAL     :: LL_NIGHT_ONLY_AMSR2_AVHHR = .FALSE.
LOGICAL     :: PRINT_NIGHT_OBSERVATION_ONLY = .FALSE.
LOGICAL     :: LL_UNBIAS_SLA_AT = .FALSE.
LOGICAL     :: LL_IBERR = .FALSE.
LOGICAL :: LHA_ERR

CHARACTER(LEN=300) :: CGRIDPATH

END MODULE RUN
