MODULE OBSDEF

USE SET_KND
IMPLICIT NONE

!... GENERAL
INTEGER(I4), PARAMETER :: NOFAMS=6              ! NUMBER OF OBS FAMILIES
INTEGER(I4), PARAMETER :: NNINS=1              ! INDEX INSITU
INTEGER(I4), PARAMETER :: NNSLA=2              ! INDEX SLA
INTEGER(I4), PARAMETER :: NNSST=3              ! INDEX SST
INTEGER(I4), PARAMETER :: NNSSS=4              ! INDEX SSS
INTEGER(I4), PARAMETER :: NNSIC=5              ! INDEX SIC
INTEGER(I4), PARAMETER :: NNSIT=6              ! INDEX SIT

CHARACTER(LEN=3), PARAMETER :: CCFAMS(NOFAMS) = (/&
& 'INS', 'SLA', 'SST', 'SSS','SIC','SIT' /)

!... DIMENSIONS
INTEGER(I4), PARAMETER :: NOPARAMS=3            ! NUMBER OF PARAMS
INTEGER(I4), PARAMETER :: NOASSIMPARAMS=2       ! NUMBER OF PARAMS
INTEGER(I4), PARAMETER :: NOINSITU=4            ! NUMBER OF INSITU OBS TYPES

!... OBS PARAMETER
INTEGER(I4), PARAMETER :: KKSAL=1               ! SALINITY
INTEGER(I4), PARAMETER :: KKTEMP=2              ! TEMPERATURE
INTEGER(I4), PARAMETER :: KKPOTEMP=3            ! POTENTIAL TEMPERATURE
INTEGER(I4), PARAMETER :: KKSLA=4               ! SEA-LEVEL ANOMALY
INTEGER(I4), PARAMETER :: KKSST=5               ! SEA-SURFACE TEMPERATURE
INTEGER(I4), PARAMETER :: KKSSS=6               ! SEA-SURFACE SALINITY
INTEGER(I4), PARAMETER :: KKPRE=7               ! SEA PRESSURE
INTEGER(I4), PARAMETER :: KKHCDR=8              ! HORIZONTAL CURRENT DIRECTION
INTEGER(I4), PARAMETER :: KKHCSP=9              ! HORIZONTAL CURRENT SPEED
INTEGER(I4), PARAMETER :: KKHCUC=10             ! HORIZONTAL CURRENT U-COMPONENT
INTEGER(I4), PARAMETER :: KKHCVC=11             ! HORIZONTAL CURRENT V-COMPONENT
INTEGER(I4), PARAMETER :: KKSSH=12              ! SEA-SURFACE HEIGHT
INTEGER(I4), PARAMETER :: KKT2M=13              ! TEMPERATURE AT 2M
INTEGER(I4), PARAMETER :: KKQ2M=14              ! HUMIDITY AT 2M
INTEGER(I4), PARAMETER :: KKSIC=15              ! SIC
INTEGER(I4), PARAMETER :: KKSIT=16              ! SIT
!... OBS TYPE
! ICOADS OBS
INTEGER(I4), PARAMETER :: KKBUCKET = 100        ! BUCKET
INTEGER(I4), PARAMETER :: KKINLET  = 101        ! INLET
INTEGER(I4), PARAMETER :: KKTHERMIS= 102        ! TRAILING THERMISTOR
INTEGER(I4), PARAMETER :: KKCHULL  = 103        ! HULL CONTACT SENSOR
INTEGER(I4), PARAMETER :: KKTHULL  = 104        ! THROUGH HULL SENSOR
INTEGER(I4), PARAMETER :: KKRADTHER= 105        ! RADIATION THERMOMETER
INTEGER(I4), PARAMETER :: KKBAITHER= 106        ! BAIT TANKS THERMOMETER
INTEGER(I4), PARAMETER :: KKOTHERS = 107        ! OTHERS
INTEGER(I4), PARAMETER :: KKIMPLBCK= 110        ! IMPLIED BUCKET
INTEGER(I4), PARAMETER :: KKMECHSEN= 111        ! MECHANICAL SENSOR
INTEGER(I4), PARAMETER :: KKELECSEN= 112        ! ELECTRONIC SENSOR
! WOD
INTEGER(I4), PARAMETER :: KKOSD    = 201        ! OCEAN STATION DATA
! EN3 AND CORA
INTEGER(I4), PARAMETER :: KKXBT    = 401        ! XBT/MBT
INTEGER(I4), PARAMETER :: KKTESAC  = 741        ! TESAC
INTEGER(I4), PARAMETER :: KKARGO   = 831        ! ARGO
INTEGER(I4), PARAMETER :: KKBUOY   = 820        ! BUOYS

! AIR OBSERVATIONS (ECMWF MARS OBSTYPE CODE)
INTEGER(I4), PARAMETER :: KKSYNSA  = -109       ! SYNOP SHIP ABBREVIATED
INTEGER(I4), PARAMETER :: KKSYNS   = -111       ! SYNOP SHIP 
INTEGER(I4), PARAMETER :: KKSYNREC = -112       ! SYNOP RECORD
INTEGER(I4), PARAMETER :: KKSYNAU  = -113       ! SYNOP AUTO
INTEGER(I4), PARAMETER :: KKSYNAUR = -114       ! SYNOP AUTO RECORD

INTEGER(I4), PARAMETER :: KKSYNRED = -119       ! SYNOP SHIP REDUCED
INTEGER(I4), PARAMETER :: KKRCOADS = -120       ! REDUCED COADS
INTEGER(I4), PARAMETER :: KKDRIBUS = -121       ! DRIBU SURFACE
INTEGER(I4), PARAMETER :: KKBATHYS = -122       ! BATHY SURFACE
INTEGER(I4), PARAMETER :: KKTESACS = -123       ! TESAC SURFACE
INTEGER(I4), PARAMETER :: KKMOORIN = -124       ! TESAC SURFACE

!... OBS TYPE -- DUMMY VERSION
INTEGER(I4), PARAMETER :: KSXBT    =   1        ! XBT/MBT
INTEGER(I4), PARAMETER :: KSTESAC  =   2        ! TESAC
INTEGER(I4), PARAMETER :: KSARGO   =   3        ! ARGO
INTEGER(I4), PARAMETER :: KSBUOY   =   4        ! BUOYS
INTEGER(I4), PARAMETER :: KSAIR2   =   5        ! T/Q AT 2M

CHARACTER(LEN=6), PARAMETER :: CINSNAME(4)=(/'XBT   ','TESAC ','ARGO  ','BUOY  '/)

!***   SATELLITE CONSTANTS

INTEGER(I4), PARAMETER :: NOSLASATS = 14

CHARACTER(LEN=9), PARAMETER :: CSLASATID(NOSLASATS) = (/&
& 'ERS1         ', 'ERS2         ', 'ENVISAT      ',&
& 'GFO          ', 'JASON1       ', 'JASON2       ',&
& 'TP           ', 'CRYOSAT2     ', 'GEOSAT       ',& 
& 'ALTIKA       ', 'HY2A         ', 'JASON3       ',&
& 'SENT3A       ', 'SENT3B       '/)

INTEGER(I4), PARAMETER :: CURSAT=999999

INTEGER(I4), PARAMETER :: &
& ISLASATSTART(NOSLASATS)=(/ 199210,199505,200210,200001,200204,200810,199209,201101,198611,201303,201404,201604,201604,201801/)

INTEGER(I4), PARAMETER :: &
& ISLASATEND  (NOSLASATS)=(/ 199505,200210,201204,200810,201306,CURSAT,200510,CURSAT,198812,CURSAT,CURSAT,CURSAT,CURSAT,CURSAT /)

INTEGER(I4), PARAMETER :: NOSSTSATS = 10

CHARACTER(LEN=9), PARAMETER :: CSSTSATID(NOSSTSATS) = (/&
& 'AMSR-E       ', 'TMI          ', 'SST MW-OI    ',&
& 'AMSR-E SWATH ', 'TMI SWATH    ', 'REYNOLDS OI  ',&
& 'COPERNICUSL3S', 'COPERNICUS L3', 'AMSR-2       ',&
& 'METOP-A AVHRR' /)

INTEGER(I4), PARAMETER :: NOSSSSATS = 3

CHARACTER(LEN=9), PARAMETER :: CSSSSATID(NOSSSSATS) = (/&
& 'AQUARIUS ', 'SMOS     ','SAC-D    ' /)

INTEGER(I4), PARAMETER :: NOSICSATS = 2

CHARACTER(LEN=9), PARAMETER :: CSICSATID(NOSICSATS) = (/&
& 'OSISAF   ','HADISST  ' /)

INTEGER(I4), PARAMETER :: NOSITSATS = 5

CHARACTER(LEN=9), PARAMETER :: CSITSATID(NOSITSATS) = (/&
& 'CRYO2    ','SMOS     ','CS2SMOS  ','PIOMAS   ','GIOMAS   '/)

END MODULE OBSDEF
