MODULE RDFIELD

USE SET_KND
USE GRD_STR

IMPLICIT NONE

INTERFACE READFIELD
  MODULE PROCEDURE READFIELD_4D,READFIELD_3D,READFIELD_2D,READFIELD_1D
END INTERFACE READFIELD

CONTAINS

SUBROUTINE READFIELD_4D(CFILE,NDIMS,CVARNAME,F3D,LOP,LCL,NCID)

USE SET_KND

USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILE,CVARNAME
INTEGER(I4)      , INTENT(IN)  :: NDIMS(4)
INTEGER(I4)      , INTENT(INOUT)  :: NCID
INTEGER(I4)                    :: STAT, IDVAR,K,ITIME
REAL(R8),INTENT(OUT)  ::  F3D(NDIMS(1),NDIMS(2),NDIMS(3),NDIMS(4))
REAL(R4)                ::  X3D(NDIMS(1),NDIMS(2),NDIMS(3),NDIMS(4))
LOGICAL,INTENT(IN) :: LOP,LCL

IF(LOP) THEN
STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
ENDIF
STAT = NF90_INQ_VARID (NCID, CVARNAME, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,X3D,START=(/GRD%I0,GRD%J0,1,1/),COUNT=(/GRD%IM,GRD%JM,NDIMS(3),NDIMS(4)/))
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
F3D = REAL(X3D,KIND=R8)
IF(LCL) STAT = NF90_CLOSE(NCID)

RETURN
END SUBROUTINE READFIELD_4D

SUBROUTINE READFIELD_3D(CFILE,NDIMS,CVARNAME,F3D,LOP,LCL,NCID)

USE SET_KND

USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILE,CVARNAME
INTEGER(I4)      , INTENT(IN)  :: NDIMS(3)
INTEGER(I4)      , INTENT(INOUT)  :: NCID
INTEGER(I4)                    :: STAT, IDVAR,K,ITIME
REAL(R8),INTENT(OUT)  ::  F3D(NDIMS(1),NDIMS(2),NDIMS(3))
REAL(R4)                ::  X3D(NDIMS(1),NDIMS(2),NDIMS(3))
LOGICAL,INTENT(IN) :: LOP,LCL

IF(LOP) THEN
STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    WRITE(*,*) 'FIRST GUESS FILE OPENED'
ENDIF
STAT = NF90_INQ_VARID (NCID, CVARNAME, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,X3D,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,NDIMS(3)/))
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
F3D = REAL(X3D,KIND=R8)
IF(LCL) STAT = NF90_CLOSE(NCID)

RETURN
END SUBROUTINE READFIELD_3D

SUBROUTINE READFIELD_2D(CFILE,NDIMS,CVARNAME,F3D,LOP,LCL,NCID)

USE SET_KND

USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILE,CVARNAME
INTEGER(I4)      , INTENT(IN)  :: NDIMS(2)
INTEGER(I4)      , INTENT(INOUT)  :: NCID
INTEGER(I4)                    :: STAT, IDVAR,K,ITIME
REAL(R8),INTENT(OUT)  ::  F3D(NDIMS(1),NDIMS(2))
REAL(R4)                ::  X3D(NDIMS(1),NDIMS(2))
LOGICAL,INTENT(IN) :: LOP,LCL

IF(LOP) THEN
STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    WRITE(*,*) 'FIRST GUESS FILE OPENED'
ENDIF
STAT = NF90_INQ_VARID (NCID, CVARNAME, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,X3D,START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/))
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
F3D = REAL(X3D,KIND=R8)
IF(LCL) STAT = NF90_CLOSE(NCID)

RETURN
END SUBROUTINE READFIELD_2D

SUBROUTINE READFIELD_1D(CFILE,NDIMS,CVARNAME,F3D,LOP,LCL,NCID)

USE SET_KND

USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILE,CVARNAME
INTEGER(I4)      , INTENT(IN)  :: NDIMS
INTEGER(I4)      , INTENT(INOUT)  :: NCID
INTEGER(I4)                    :: STAT, IDVAR,K,ITIME
REAL(R8),INTENT(OUT)  ::  F3D(NDIMS)
REAL(R4)                ::  X3D(NDIMS)
LOGICAL,INTENT(IN) :: LOP,LCL

IF(LOP) THEN
STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    WRITE(*,*) 'FIRST GUESS FILE OPENED'
ENDIF
STAT = NF90_INQ_VARID (NCID, CVARNAME, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,X3D)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
F3D = REAL(X3D,KIND=R8)
IF(LCL) STAT = NF90_CLOSE(NCID)

RETURN
END SUBROUTINE READFIELD_1D

END MODULE RDFIELD
