MODULE WRITECORR

USE SET_KND
USE READFG
USE RUN
USE IOUNITS
USE GRD_STR
USE MYFRTPROF

IMPLICIT NONE

LOGICAL, PRIVATE, SAVE :: LLWCINIT=.FALSE.

CHARACTER(LEN=60) :: CANFILES(MAXFILES)
INTEGER(I4) :: NANFILES
INTEGER(I4) :: NJPI, NJPJ
INTEGER(I4), ALLOCATABLE :: NCID(:)
LOGICAL :: LLMPA

CONTAINS

SUBROUTINE SETANFILES(NTF)

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NTF
INTEGER(I4) :: JF

IF(NTF.GT.MAXFILES) THEN
   WRITE(IOUNERR,*) &
   & 'NUMBER OF ANALYSIS FILES EXCEEDS MAXIMUM ALLOWED'
   WRITE(IOUNERR,*) 'MAX ALLOWED =',MAXFILES,',  ACTUAL NO =',NTF
   CALL ABOR1('TOO MANY AN FILES')
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// SETUP ANALYSIS FILENAMES'

IF(NTF.LE.0) THEN
      NANFILES=1
      CANFILES(1) = 'OPA_ANALYSIS.nc'
ELSE
      NANFILES=NTF
      DO JF=1,NANFILES
         WRITE(CANFILES(JF),'(A,I4.4,A)') 'OPA_ANALYSIS_',JF-1,'.nc'
      ENDDO
ENDIF

LLMPA = (NANFILES.GT.1)

WRITE(IOUNLOG,*) ' NUMBER OF AN FILES:',NANFILES
WRITE(IOUNLOG,*) ' MULTI-PROC FILES  :',LLMPA
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' -------- NAMES OF AN FILES --------'
DO JF=1,NANFILES
   WRITE(IOUNLOG,*) JF,' '//TRIM(CANFILES(JF))
ENDDO
WRITE(IOUNLOG,*)

CALL FLUSH(IOUNLOG)
END SUBROUTINE SETANFILES

!==============================================

SUBROUTINE WRITECORRLOC(F3T,F3S,LLNIC)

USE GRD_STR
USE NETCDF

IMPLICIT NONE

CHARACTER(LEN=2) :: CVARNAME(4)
LOGICAL, INTENT(IN) :: LLNIC
INTEGER(I4)                    :: STAT,IDVAR(4),K,JF,JI,JJ,JK
REAL(R8),INTENT(INOUT)  ::  F3T(GRD%IM,GRD%JM,GRD%KM)
REAL(R8),INTENT(INOUT)  ::  F3S(GRD%IM,GRD%JM,GRD%KM)
REAL(R8) ::  F3BT(GRD%IM,GRD%JM,GRD%KM)
REAL(R8) ::  F3BS(GRD%IM,GRD%JM,GRD%KM)
REAL(R8) ::  PSAL(GRD%IM,GRD%JM,GRD%KM)
REAL(R8) ::  F3B2

INTEGER(I4) :: X,Y,Z,MAXX,MAXY,MNZ,ISTARTX,ISTARTY,&
             & IENDX,IENDY,ILX,ILY,JVAR

CALL MYFRTPROF_WALL('WRITECORRLOC: WRITE ANALYSIS CORRECTIONS',0)

CALL SETANFILES(NFGFILES)
ALLOCATE(NCID(NANFILES))

MAXX=MAXVAL(KDSL(1:NFGFILES,1))
MAXY=MAXVAL(KDSL(1:NFGFILES,2))
MNZ=GRD%KM

CVARNAME(1) = 'tn'
CVARNAME(2) = 'tb'
CVARNAME(3) = 'sn'
CVARNAME(4) = 'sb'

IF(LLNIC) WRITE(IOUNLOG,*) 'NO 3DVAR CORRECTIONS OVER ICE'

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(SHARED), PRIVATE(JF,ISTARTX,ISTARTY,IENDX,IENDY,ILX,ILY,&
!$OMP & STAT,IDVAR,JVAR,F3B2,JI,JJ,JK)
!$OMP DO SCHEDULE(STATIC,1)
#endif
DO JF=1,NANFILES

   ISTARTX=KDPF(JF,1)
   ISTARTY=KDPF(JF,2)
   IENDX=KDPL(JF,1)
   IENDY=KDPL(JF,2)
   ILX=KDSL(JF,1)
   ILY=KDSL(JF,2)

#ifndef SHARED_MEMORY
   WRITE(IOUNLOG,*) 'FILE ',CANFILES(JF), &
   & ISTARTX, ISTARTY, MAXX, MAXY, ISTARTX+MAXX-1, ISTARTY+MAXY-1,&
   & ILX, ILY
   CALL FLUSH(IOUNLOG)
#endif

   NCID(JF) = 900+JF
   STAT = NF90_OPEN(CANFILES(JF), NF90_WRITE, NCID(JF))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

   DO JVAR=1,4
     STAT = NF90_INQ_VARID (NCID(JF), CVARNAME(JVAR)(1:2), IDVAR(JVAR))
     IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
   ENDDO

   ! READ NOW FIELDS
   STAT = NF90_GET_VAR (NCID(JF),IDVAR(1),F3BT(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
  
   STAT = NF90_GET_VAR (NCID(JF),IDVAR(3),F3BS(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

   IF(LLNIC) THEN
       DO JJ=ISTARTY,IENDY
         DO JI=ISTARTX,IENDX
           F3B2 = MAX(F3BS(JI,JJ,1),0.001_R8)
           F3B2 = (-0.0575 + 1.710523E-3 * SQRT( F3B2 )   &
                  -2.154996E-4 *   F3B2   ) *F3B2
           IF(F3BT(JI,JJ,1) .LT. F3B2) THEN
               F3T(JI,ISTARTY,:) = 0._R8
               F3S(JI,ISTARTY,:) = 0._R8
           ENDIF
         ENDDO
       ENDDO
   ENDIF

   PSAL(ISTARTX:IENDX,ISTARTY:IENDY,:) = &
 & F3BS(ISTARTX:IENDX,ISTARTY:IENDY,:)+F3S(ISTARTX:IENDX,ISTARTY:IENDY,:)

   DO JK=1,GRD%KM
       DO JJ=ISTARTY,IENDY
         DO JI=ISTARTX,IENDX
           IF( PSAL(JI,JJ,JK) .LT. 0.1_R8 ) PSAL(JI,JJ,JK) = 0.1_R8
         ENDDO
       ENDDO
   ENDDO

   STAT = NF90_PUT_VAR(NCID(JF),IDVAR(1),&
   & F3BT(ISTARTX:IENDX,ISTARTY:IENDY,:)+F3T(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
   STAT = NF90_PUT_VAR(NCID(JF),IDVAR(2),&
   & F3BT(ISTARTX:IENDX,ISTARTY:IENDY,:)+F3T(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

   STAT = NF90_PUT_VAR(NCID(JF),IDVAR(3),&
   & PSAL(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
   STAT = NF90_PUT_VAR(NCID(JF),IDVAR(4),&
   & PSAL(ISTARTX:IENDX,ISTARTY:IENDY,:),&
   & START=(/1,1,1/),COUNT=(/ILX,ILY,GRD%KM/))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

   STAT = NF90_CLOSE(NCID(JF))
   IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
ENDDO
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif
CALL MYFRTPROF_WALL('WRITECORRLOC: WRITE ANALYSIS CORRECTIONS',1)

END SUBROUTINE WRITECORRLOC

!==============================================

SUBROUTINE WRITECORRLOCBIN(F3T,F3S)

USE GRD_STR

IMPLICIT NONE

INTEGER(I4)                    :: JF
REAL(R8),INTENT(INOUT)  ::  F3T(GRD%IM,GRD%JM,GRD%KM)
REAL(R8),INTENT(INOUT)  ::  F3S(GRD%IM,GRD%JM,GRD%KM)
REAL(R8)                ::  FTMP(NJPI, NJPJ, GRD%KM)
CHARACTER(LEN=200)      ::  CFT

INTEGER(I4) :: MAXX,MAXY,MNZ,ISTARTX,ISTARTY,&
             & IENDX,IENDY,ILX,ILY

CALL MYFRTPROF_WALL('WRITECORRLOCBIN: WRITE ANALYSIS CORRECTIONS',0)

CALL SETANFILES(NFGFILES)
ALLOCATE(NCID(NANFILES))

MAXX=MAXVAL(KDSL(1:NFGFILES,1))
MAXY=MAXVAL(KDSL(1:NFGFILES,2))
MNZ=GRD%KM

FTMP = 0._R8

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(SHARED), PRIVATE(JF,ISTARTX,ISTARTY,IENDX,IENDY,ILX,ILY,CFT)
!$OMP DO SCHEDULE(STATIC,1)
#endif
DO JF=1,NANFILES

   ISTARTX=KDPF(JF,1)
   ISTARTY=KDPF(JF,2)
   IENDX=KDPL(JF,1)
   IENDY=KDPL(JF,2)
   ILX=KDSL(JF,1)
   ILY=KDSL(JF,2)

   NCID(JF) = 900+JF

   IF(ISTARTX+NJPI-1 .GT. GRD%IM) THEN
     IF(ISTARTY+NJPJ-1 .GT. GRD%JM) THEN
       FTMP(1:NJPI-1,1:NJPJ-1,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-2,ISTARTY:ISTARTY+NJPJ-2,:)
       FTMP(NJPI,1:NJPJ-1,:) = F3T(3,1:NJPJ-1,:)
     ELSE
       FTMP(1:NJPI-1,:,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-2,ISTARTY:ISTARTY+NJPJ-1,:)
       FTMP(NJPI,:,:) = F3T(3,:,:)
     ENDIF
   ELSE
     IF(ISTARTY+NJPJ-1 .GT. GRD%JM) THEN
       FTMP(:,1:NJPJ-1,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-1,ISTARTY:ISTARTY+NJPJ-2,:)
     ELSE
       FTMP(:,:,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-1,ISTARTY:ISTARTY+NJPJ-1,:)
     ENDIF
   ENDIF
     
   WRITE(CFT,'(A,I4.4,A)') 'tem_anincr_',JF-1,'.bin'
   OPEN(UNIT=NCID(JF),FILE=CFT,STATUS='NEW',&
   & FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
   WRITE( NCID(JF) ) FTMP
   CLOSE( NCID(JF) )

   IF(ISTARTX+NJPI-1 .GT. GRD%IM) THEN
     IF(ISTARTY+NJPJ-1 .GT. GRD%JM) THEN
       FTMP(1:NJPI-1,1:NJPJ-1,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-2,ISTARTY:ISTARTY+NJPJ-2,:)
       FTMP(NJPI,1:NJPJ-1,:) = F3T(3,1:NJPJ-1,:)
     ELSE
       FTMP(1:NJPI-1,:,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-2,ISTARTY:ISTARTY+NJPJ-1,:)
       FTMP(NJPI,:,:) = F3T(3,:,:)
     ENDIF
   ELSE
     IF(ISTARTY+NJPJ-1 .GT. GRD%JM) THEN
       FTMP(:,1:NJPJ-1,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-1,ISTARTY:ISTARTY+NJPJ-2,:)
     ELSE
       FTMP(:,:,:) = &
       & F3T(ISTARTX:ISTARTX+NJPI-1,ISTARTY:ISTARTY+NJPJ-1,:)
     ENDIF
   ENDIF


   WRITE(CFT,'(A,I4.4,A)') 'sal_anincr_',JF-1,'.bin'
   OPEN(UNIT=NCID(JF),FILE=CFT,STATUS='NEW',&
   & FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
   WRITE( NCID(JF) ) FTMP
   CLOSE( NCID(JF) )

ENDDO
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

CALL MYFRTPROF_WALL('WRITECORRLOCBIN: WRITE ANALYSIS CORRECTIONS',1)

END SUBROUTINE WRITECORRLOCBIN

END MODULE WRITECORR
