MODULE OBSHANDLING

!.. OBSHANDLING CONTAINS DEFINITION FOR OBSERVATIONS HANDLING
!.. ALSO SETS DEFAULT VALUES, OVERWRITTEN WITHIN DEF_NML
!..
!.. ANDREA STORTO, *INGV* 2009

USE SET_KND
USE OBSDEF

PUBLIC

!... 1. FLAGS FOR IN-LINE QUALITY CHECK
!       OF INS DATA USING UKMO FLAGS

! WHETHER TO CHECK QF OF POSITION
LOGICAL, SAVE :: INS_LQC_POS     = .TRUE.
! WHETHER TO CHECK QF OF DATE TIME
LOGICAL, SAVE :: INS_LQC_TIME    = .TRUE.
! WHETHER TO CHECK QF OF SALINITY
LOGICAL, SAVE :: INS_LQC_SAL     = .TRUE.
! WHETHER TO CHECK QF OF TEMPERATURE
LOGICAL, SAVE :: INS_LQC_TEMP    = .TRUE.
! WHETHER TO CHECK QF OF PRESSURE
LOGICAL, SAVE :: INS_LQC_PRE     = .TRUE.
! WHETHER TO CHECK QF OF TEMPERATURE PROFILE
LOGICAL, SAVE :: INS_LQC_PROF_T  = .TRUE.
! WHETHER TO CHECK QF OF SALINITY PROFILE
LOGICAL, SAVE :: INS_LQC_PROF_S  = .TRUE.
! WHETHER TO CHECK QF OF PRESSURE PROFILE
LOGICAL, SAVE :: INS_LQC_PROF_P  = .TRUE.
! WHETHER TO CHECK QF OF TIME
LOGICAL, SAVE :: INS_CHK_TIME    = .TRUE.
! WHETHER TO CHECK ARGO GREY LIST
LOGICAL, SAVE :: INS_ARG_GREYL   = .TRUE.

!... 2. OBSERVATIONS THINNING

! WHETHER TO THIN SLA
LOGICAL, SAVE :: LTHIN_SLA  = .TRUE.
! WHETHER TO THIN INS
LOGICAL, SAVE :: LTHIN_INS  = .TRUE.
! WHETHER TO THIN SST
LOGICAL, SAVE :: LTHIN_SST  = .TRUE.
! WHETHER TO THIN SSS
LOGICAL, SAVE :: LTHIN_SSS  = .TRUE.
! WHETHER TO THIN SIC
LOGICAL, SAVE :: LTHIN_SIC  = .TRUE.
! WHETHER TO THIN SIT
LOGICAL, SAVE :: LTHIN_SIT  = .TRUE.

! METHOD FOR INS THINNING
CHARACTER, SAVE :: CINSTHINOPT  = 'A'
! WHETHER TO PERFORM TWO-ITERATION THINNING
LOGICAL, SAVE :: LDOUBLETHIN = .TRUE.
! THINNING BOX SIZE IN GRID-POINTS FOR SLA
REAL(R8), SAVE :: RTHIND_SLA_X=3.5_R8, RTHIND_SLA_Y=3.5_R8
! THINNING BOX SIZE IN GRID-POINTS FOR INS
REAL(R8), SAVE :: RTHIND_INS_X=3.5_R8, RTHIND_INS_Y=3.5_R8,&
                & RTHIND_INS_Z=3.5_R8
! THINNING BOX SIZE IN GRID-POINTS FOR SST
REAL(R8), SAVE :: RTHIND_SST_X=3.5_R8, RTHIND_SST_Y=3.5_R8
! THINNING BOX SIZE IN GRID-POINTS FOR SSS
REAL(R8), SAVE :: RTHIND_SSS_X=3.5_R8, RTHIND_SSS_Y=3.5_R8
! THINNING BOX SIZE IN GRID-POINTS FOR SIC
REAL(R8), SAVE :: RTHIND_SIC_X=1._R8, RTHIND_SIC_Y=1._R8
! THINNING BOX SIZE IN GRID-POINTS FOR SIT
REAL(R8), SAVE :: RTHIND_SIT_X=1._R8, RTHIND_SIT_Y=1._R8

!... 3. BACKGROUND QUALITY CHECK

! WHETHER TO PERFORM BGQC ON SLA
LOGICAL, SAVE :: LLBGQC_SLA = .TRUE.
! WHETHER TO PERFORM BGQC ON INS
LOGICAL, SAVE :: LLBGQC_INS = .TRUE.
! WHETHER TO PERFORM BGQC ON SST
LOGICAL, SAVE :: LLBGQC_SST = .TRUE.
! WHETHER TO PERFORM BGQC ON SSS
LOGICAL, SAVE :: LLBGQC_SSS = .TRUE.
! WHETHER TO PERFORM BGQC ON SIC
LOGICAL, SAVE :: LLBGQC_SIC = .TRUE.
! WHETHER TO PERFORM BGQC ON SIT
LOGICAL, SAVE :: LLBGQC_SIT = .TRUE.

! ALFA COEFFICIENT FOR SLA
REAL(R8), SAVE :: RALFA_SLA=2.0_R8
! ALFA COEFFICIENT FOR INS
REAL(R8), SAVE :: RALFA_INS=2.0_R8
! ALFA COEFFICIENT FOR SST
REAL(R8), SAVE :: RALFA_SST=2.0_R8
! ALFA COEFFICIENT FOR SSS
REAL(R8), SAVE :: RALFA_SSS=2.0_R8
! ALFA COEFFICIENT FOR SIC
REAL(R8), SAVE :: RALFA_SIC=8.0_R8
! ALFA COEFFICIENT FOR SIT
REAL(R8), SAVE :: RALFA_SIT=8.0_R8
! BACKGROUND ERROR FOR SSH
REAL(R8), SAVE :: RBGERR_SSH=0.10_R8
! BACKGROUND ERROR FOR SALINITY
REAL(R8), SAVE :: RBGERR_SAL=0.2_R8
! BACKGROUND ERROR FOR TEMPER.
REAL(R8), SAVE :: RBGERR_TEM=1.00_R8
! BACKGROUND ERROR FOR S-S TEMPER.
REAL(R8), SAVE :: RBGERR_SST=0.50_R8
! BACKGROUND ERROR FOR S-S SALIN.
REAL(R8), SAVE :: RBGERR_SSS=0.2_R8
! BACKGROUND ERROR FOR SIC
REAL(R8), SAVE :: RBGERR_SIC=0.1_R8
! BACKGROUND ERROR FOR SIT
REAL(R8), SAVE :: RBGERR_SIT=0.1_R8

! WHETHER TO USE STATIC BACKGROUND-ERRORS
LOGICAL, SAVE :: LLUSEBGERR = .TRUE.
LOGICAL, SAVE :: LL_READ_BGE= .FALSE.

!... 4. MAX DEPTH FOR OBS
REAL(R8), SAVE :: ZMAXDEP(NOINSITU)

!... 5. ERRORS DEFINITION
!
LOGICAL :: LLUSEMDTERR
REAL(R8) :: SST_ERRS(NOSSTSATS)
REAL(R8) :: SSS_ERRS(NOSSSSATS)
REAL(DP) :: ZTIME_WEIGTH
LOGICAL :: LL_SST_REPRERR

!... 6. SLA PRE-PROCESSING
LOGICAL :: LLFILTERSLA
INTEGER(I4) :: NLANC_KN
REAL(R8) :: ZLANC_CL

!... 7. PERTURBATIONS
LOGICAL :: LLPERTOBS
INTEGER(I4) :: NSEED
REAL(R8) :: ZRFACT

!... 8. SST PROCESSING
LOGICAL, SAVE :: LLSSTMODBIAS=.FALSE.

!... 9. CLIMATOLOGY CHECK
LOGICAL, SAVE :: LLCLCK_INS = .TRUE.
LOGICAL, SAVE :: LLCLCK_SST = .TRUE.
LOGICAL, SAVE :: LLCLCK_SSS = .TRUE.
REAL(R8) :: CLIMLIM(3) = (/2._R8, 7._R8, 7._R8/)

!...10. ERRORS FOR SLA SATELLITES
REAL(R8) :: SLA_ERR(NOSLASATS) = (/ 0.05_R8,  0.05_R8,  0.05_R8,  0.10_R8, 0.03_R8, &
         & 0.03_R8,  0.03_R8,  0.03_R8,  0.12_R8, 0.05_R8, 0.10_R8, 0.03_R8, 0.03_R8,&
         & 0.03_R8 /)

!...11. DEFINITION FOR SLA FILES
CHARACTER(LEN=2) :: CSLA_OPT
CHARACTER(LEN=3) :: CSLA_FMT
LOGICAL :: LL_SLA_CORRECTIVE_MAP

!... 12. VARIOUS
LOGICAL :: LL_NEWINSERR = .FALSE.
LOGICAL :: LL_INSREPERR_IRREG = .FALSE.
REAL(R8) :: ICOSST_DEF_ERR = 0.78_R8
INTEGER(I4) :: NN_OBS_RET = 0

!...10. ERRORS FOR SIC/SIT SATELLITES
REAL(R8) :: COEFF_SIC_ERR=1._R8,COEFF_SIT_ERR_SMOS=1._R8,COEFF_SIT_ERR_CRYO=1._R8,COEFF_SIT_ERR_CRYOSMOS=1._R8,&
        & COEFF_SIT_ERR_PIOMAS=1._R8,COEFF_SIT_ERR_GIOMAS=1._R8


END MODULE OBSHANDLING
