SUBROUTINE OBS_SLA2E_AD

 USE SET_KND
 USE GRD_STR
 USE OBS_STR
 USE RUN, ONLY : RTIMES1950, KLEVNM, RHO0,NTSTEPS,LLVARMDT,NCONF
 USE OCEANTOOLS , ONLY : RHO_UNESCOAD
 USE MYNETCDF
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE TLAD_VARS

 IMPLICIT NONE

 INTEGER(I4)   ::  I, JP, K, KSTEP, JVL, JTSTEP,I2,OBS_K,KBOT
 INTEGER(I4)   ::  XIND1
 REAL(R8) :: ZC, TB, SB, S_AD, T_AD, RTDIFF,NO(SLA%NO)

 CALL MYFRTPROF_WALL('OBS_SLA2E_AD: ADJOINT OF SLA OPERATOR',0)

 IF( SLA%NO .EQ. 0 ) THEN
   CALL MYFRTPROF_WALL('OBS_SLA2E_AD: ADJOINT OF SLA OPERATOR',1)
   RETURN
 ENDIF

IF(NCONF .NE. 202 ) THEN
 CYOBS : DO K=1,SLA%NO

  IF( .NOT. LL_4DVAR .OR. ( LL_4DVAR .AND. SLA%TATS(K) .EQ. TLAD_TS )) THEN

  OBS%K=OBS%K+1
  OBS_K=OBS%K
  IF( LL_4DVAR ) OBS_K = SLA%OBIN(K)

    DO JP=1,NPQ
      GRD%ETA_AD(SLA%IB(K,JP),SLA%JB(K,JP)) = &
      & GRD%ETA_AD(SLA%IB(K,JP),SLA%JB(K,JP)) + SLA%PQ(K,JP) *OBS%GRA(OBS_K)
    ENDDO

  ENDIF

 ENDDO CYOBS
ENDIF

IF(LLVARMDT .OR. NCONF.EQ.202) THEN
  CYOBS2 : DO K=1,SLA%NO
    IF( .NOT. LL_4DVAR .OR. ( LL_4DVAR .AND. SLA%TATS(K) .EQ. TLAD_TS )) THEN
      OBS_K = K
      IF( LL_4DVAR ) OBS_K = SLA%OBIN(K)
      DO JP=1,NPQ
        GRD%CMDT_AD(SLA%IB(K,JP),SLA%JB(K,JP)) = &
        & GRD%CMDT_AD(SLA%IB(K,JP),SLA%JB(K,JP)) + SLA%PQ(K,JP)*OBS%GRA(OBS_K)
      ENDDO
    ENDIF
  ENDDO CYOBS2
ENDIF

CALL MYFRTPROF_WALL('OBS_SLA2E_AD: ADJOINT OF SLA OPERATOR',1)
END SUBROUTINE OBS_SLA2E_AD
