SUBROUTINE PREP_EXTGRID1

USE SET_KND
USE RECFILTER
USE GRD_STR
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE IOUNITS, ONLY : IOUNOUT,IOUNLOG
USE LBCLNK

IMPLICIT NONE
CALL MYFRTPROF_WALL('PREP_EXTGRID1: PREPARE GRID EXTENSION',0)

  ALLOCATE(SR_SCXT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_SCYT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GALXT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GALYT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GBTXT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GBTYT(GRD%IM,GRD%JM,GRD%KM),&
       & SR_SCXS(GRD%IM,GRD%JM,GRD%KM),&
       & SR_SCYS(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GALXS(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GALYS(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GBTXS(GRD%IM,GRD%JM,GRD%KM),&
       & SR_GBTYS(GRD%IM,GRD%JM,GRD%KM) )

  CALL LBC_LNK( SR_SCXT )
  CALL LBC_LNK( SR_SCYT )
  CALL LBC_LNK( SR_SCXS )
  CALL LBC_LNK( SR_SCYS )
  CALL LBC_LNK( SR_GALXT )
  CALL LBC_LNK( SR_GALYT )
  CALL LBC_LNK( SR_GALXS )
  CALL LBC_LNK( SR_GALYS )
  CALL LBC_LNK( SR_GBTXT )
  CALL LBC_LNK( SR_GBTYT )
  CALL LBC_LNK( SR_GBTXS )
  CALL LBC_LNK( SR_GBTYS )

  !... READ COEFFS
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'READ_RFC: READ RF COEFFS...'
  CALL READ_RFC(GRD%IM,GRD%JM,GRD%KM,SR_SCXT,SR_SCYT,SR_GALXT,SR_GALYT,&
  & SR_GBTXT,SR_GBTYT,SR_SCXS,SR_SCYS,SR_GALXS,SR_GALYS,SR_GBTXS,SR_GBTYS)
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)
  CALL FLUSH(IOUNOUT)

  ALLOCATE( CRTX(GRD%IM,GRD%JM,GRD%KM),CRTY(GRD%IM,GRD%JM,GRD%KM),&
        & CRSX(GRD%IM,GRD%JM,GRD%KM),CRSY(GRD%IM,GRD%JM,GRD%KM) )

  CALL READ_CR(GRD%IM,GRD%JM,GRD%KM,CRTX,CRTY,CRSX,CRSY)

  CALL LBC_LNK( CRTX )
  CALL LBC_LNK( CRTY )
  CALL LBC_LNK( CRSX )
  CALL LBC_LNK( CRSY )

CALL MYFRTPROF_WALL('PREP_EXTGRID1: PREPARE GRID EXTENSION',1)

END SUBROUTINE PREP_EXTGRID1
