SUBROUTINE PREPSSS
!
! REJECTIONS CRITERIA FOR SSS OBSERVATIONS
!
USE SET_KND
USE OBS_STR
USE IOUNITS
!
IMPLICIT NONE

INTEGER(I4) :: JO

#include "obs_events.h"

IF( SSS%NO .EQ. 0 ) RETURN

CYOBS : DO JO=1,SSS%NO
  IF(SSS%FLC(JO) .NE. 1 ) CYCLE CYOBS
  IF ( ABS( SSS%LAT(JO) ) .GT. 55._R8 ) THEN
      SSS%FLC(JO) = 0
      SSS%EVE(JO) = KEVE_GEOR
  ENDIF
  IF ( ( ABS(SSS%BCP(JO,7)) .GT. 1._R8 .OR.  ABS(SSS%BCP(JO,6)) .GT. 1._R8 ) .AND. SSS%KSAT(JO) .EQ. 3) THEN
      SSS%FLC(JO) = 0
      SSS%EVE(JO) = KEVE_SSSR
  ENDIF
END DO CYOBS

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' PREPSSS : SPECIFIC REJECTIONS OF SSS DATA '
WRITE(IOUNLOG,*) ' TOTAL OBS     =', SSS%NO
WRITE(IOUNLOG,*) ' OBS GEOG REJ   =', COUNT(SSS%EVE(1:SSS%NO).EQ.KEVE_GEOR)
WRITE(IOUNLOG,*) ' OBS PRED REJ   =', COUNT(SSS%EVE(1:SSS%NO).EQ.KEVE_SSSR)
WRITE(IOUNLOG,*) ' GOOD OBS       =', COUNT(SSS%FLC(1:SSS%NO).EQ.1)

END SUBROUTINE PREPSSS
