SUBROUTINE RDDNS(I,J,K,DENS, MLD)

  USE SET_KND
  USE GRD_STR
  USE NETCDF

  IMPLICIT NONE

  INTEGER(I4), INTENT(IN)    :: I, J, K
  REAL(R8), INTENT(OUT)      :: DENS(I,J,K), MLD(I,J)

  INTEGER(I4)                :: STAT, NCID, IDVAR
  LOGICAL :: LEX1, LEX2

    INQUIRE(FILE='vodensit.nc',EXIST=LEX1)
    INQUIRE(FILE='somxl010.nc',EXIST=LEX2)

    IF( COUNT( (/LEX1, LEX2/) ) .LT. 2 ) THEN
       CALL RDDNS2(I,J,K,DENS, MLD)
       RETURN
    ENDIF

    STAT = NF90_OPEN('vodensit.nc', NF90_NOWRITE, NCID)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_INQ_VARID (NCID, 'vodensit', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_GET_VAR (NCID,IDVAR,DENS,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,GRD%KM/))
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_CLOSE(NCID)

    STAT = NF90_OPEN('somxl010.nc', NF90_NOWRITE, NCID)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_INQ_VARID (NCID, 'somxl010', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_GET_VAR (NCID,IDVAR,MLD,START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/))
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_CLOSE(NCID)

! ----------------------------------------------------------------

END SUBROUTINE RDDNS
