SUBROUTINE RDFDF(I,J,K,T,S)

  USE SET_KND
  USE GRD_STR
  USE NETCDF

  IMPLICIT NONE

  INTEGER(I4), INTENT(IN)    :: I, J, K
  REAL(R8), INTENT(OUT)      :: T(I,J,K)
  REAL(R8), INTENT(OUT)      :: S(I,J,K)

  INTEGER(I4)                :: STAT, NCID, IDVAR

    STAT = NF90_OPEN('flowdep.nc', NF90_NOWRITE, NCID)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_INQ_VARID (NCID, 'votemper', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_GET_VAR (NCID,IDVAR,T,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,GRD%KM/))
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_INQ_VARID (NCID, 'vosaline', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_GET_VAR (NCID,IDVAR,S,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,GRD%KM/))
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
    STAT = NF90_CLOSE(NCID)

! ----------------------------------------------------------------

END SUBROUTINE RDFDF
