SUBROUTINE READ_AQUARIUS(CFILE,MAXSS,NO,ZDATA,&
           & ZTIME,ZLLON,ZLLAT)

USE SET_KND
USE NETCDF
USE IOUNITS

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CFILE
INTEGER(I4), INTENT(IN) :: MAXSS
INTEGER(I4), INTENT(OUT) :: NO
REAL(R8), INTENT(OUT), DIMENSION(MAXSS) :: ZDATA,&
           & ZTIME,ZLLON,ZLLAT
REAL(R4), ALLOCATABLE :: ZTLO(:,:),ZTTI(:),ZTLA(:,:),ZTVA(:,:)
INTEGER(I4) :: STAT,IDVAR,IDF,JJ,JB,NN
INTEGER(I4),PARAMETER :: NBEAMS=3

WRITE(IOUNOUT,*) ' :: OPENING AQUARIUS FILE '//TRIM(CFILE)
WRITE(IOUNLOG,*) ' :: OPENING AQUARIUS FILE '//TRIM(CFILE)

STAT=NF90_OPEN(CFILE,NF90_NOWRITE, IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID(IDF, 'lon', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQUIRE_DIMENSION(IDF, IDVAR, LEN = NN)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

ALLOCATE(ZTLO(NN,NBEAMS),ZTTI(NN),ZTLA(NN,NBEAMS),ZTVA(NN,NBEAMS))

STAT = NF90_INQ_VARID (IDF, 'lon', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZTLO)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQ_VARID (IDF, 'lat', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZTLA)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQ_VARID (IDF, 'time', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZTTI)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQ_VARID (IDF, 'sss', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZTVA)

STAT=NF90_CLOSE(IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

NO=0
DO JJ=1,NN
   DO JB=1,3
      IF( ZTVA(JJ,JB).LT.40._R4 .AND. ZTVA(JJ,JB).GT.0._R4 ) THEN
         NO = NO + 1
         ZDATA(NO) = REAL(ZTVA(JJ,JB),KIND=R8)
         ZTIME(NO) = REAL(ZTTI(JJ),KIND=R8)
         ZLLON(NO) = REAL(ZTLO(JJ,JB),KIND=R8)
         ZLLAT(NO) = REAL(ZTLA(JJ,JB),KIND=R8)
      ENDIF
   ENDDO
ENDDO

DEALLOCATE(ZTLO,ZTLA,ZTVA,ZTTI)
RETURN

END SUBROUTINE READ_AQUARIUS
