SUBROUTINE READ_REMSS_SWATH_AMSRE_NC(CFILE,MAXOBS,NTOBS,ZDATA,&
          & ZLLON,ZLLAT,ZTIME,ZERRS,LLCORRDA)

USE SET_KND
USE NETCDF
USE IOUNITS

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CFILE
LOGICAL, INTENT(IN) :: LLCORRDA
INTEGER(I4), INTENT(IN) :: MAXOBS
INTEGER(I4), INTENT(OUT) :: NTOBS
REAL   (R8), DIMENSION(MAXOBS), INTENT(OUT) :: ZDATA,&
          & ZLLON,ZLLAT,ZTIME,ZERRS

INTEGER(I4) :: NX, NY
REAL(R8),ALLOCATABLE :: ZOLON(:,:),ZOLAT(:,:),ZOSST(:,:)
REAL(DP),ALLOCATABLE :: ZOTIM(:,:)
REAL(R8),ALLOCATABLE :: ZODA(:,:)
REAL(DP) :: ZREFTIME
INTEGER(I4),ALLOCATABLE :: NPROXC(:,:),NREJFL(:,:),NDIFFTIME(:,:)
INTEGER(I4),ALLOCATABLE :: NDAMPL(:,:),NOERR(:,:)
INTEGER(I4) :: STAT,IDVAR,IDF,JX,JY,IDIFFER,IRET,NTIME

WRITE(IOUNOUT,*) ' :: OPENING SWATH_AMSRE-SST FILE '//TRIM(CFILE)
WRITE(IOUNLOG,*) ' :: OPENING SWATH_AMSRE-SST FILE '//TRIM(CFILE)

STAT=NF90_OPEN(CFILE,NF90_NOWRITE, IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID(IDF, 'ni', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION(IDF, IDVAR, LEN = NX)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID(IDF, 'nj', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION(IDF, IDVAR, LEN = NY)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

ALLOCATE(ZOLON(NX,NY),ZOLAT(NX,NY),ZOSST(NX,NY),ZOTIM(NX,NY),&
       & ZODA(NX,NY),NPROXC(NX,NY),NREJFL(NX,NY),NDIFFTIME(NX,NY),&
       & NDAMPL(NX,NY),NOERR(NX,NY))

STAT = NF90_INQ_VARID (IDF, 'lon', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOLON)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'LON'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'lat', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOLAT)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'LAT'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'sea_surface_temperature', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOSST)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'SST'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'rejection_flag', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NREJFL)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'REJ'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'time', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NTIME)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'TIM'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'SSES_standard_deviation_error', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NOERR)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'ERR'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'sst_dtime', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NDIFFTIME)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'DTIME'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'diurnal_amplitude', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NDAMPL)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'DAM'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_VARID (IDF, 'proximity_confidence', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,NPROXC)
IF (STAT /= NF90_NOERR) THEN
   WRITE(IOUNERR,*) 'CON'
   CALL HANDLE_ERR(STAT)
ENDIF

STAT=NF90_CLOSE(IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

ZOSST = (ZOSST*0.01_R4)
ZODA = (REAL(NDAMPL,KIND=R8)*0.02_R8) + 1._R8

CALL DIFFTIME('D','19810101','19500101',IDIFFER,IRET,.FALSE.)

ZREFTIME = REAL(IDIFFER,KIND=R8) + REAL(NTIME,KIND=R8)/&
         & REAL(24*60*60,KIND=R8)

NTOBS=0

IF(LLCORRDA) THEN
 DO JY=1,NY,5
  DO JX=1,NX,5
        IF(ZOSST(JX,JY).GE.-3._R4 .AND. NREJFL(JX,JY).EQ.0 .AND.&
           & NPROXC(JX,JY).EQ.4.AND.ZODA(JX,JY).GT. -0.01_R8) THEN
          NTOBS=NTOBS+1
          IF(NTOBS.GT.MAXOBS) &
          & CALL ABOR1('READ_REMSS_MWOISST: MAXOBS TO INCREASE')
          ZDATA(NTOBS) = REAL(ZOSST(JX,JY),KIND=R8) - ZODA(JX,JY)
          ZLLON(NTOBS) = REAL(ZOLON(JX,JY),KIND=R8)
          ZLLAT(NTOBS) = REAL(ZOLAT(JX,JY),KIND=R8)
          ZERRS(NTOBS) = REAL(NOERR(JX,JY),KIND=R8)*0.01_R8 + 1._R8
          ZTIME(NTOBS) = ZREFTIME + REAL(NDIFFTIME(JX,JY),KIND=DP)/&
                       & REAL(24*60*60,KIND=DP)
        ENDIF
  ENDDO
 ENDDO
ELSE
 DO JY=1,NY,6
  DO JX=1,NX,6
        IF(ZOSST(JX,JY).GE.-3._R4 .AND. NREJFL(JX,JY).EQ.0 .AND.&
           & NPROXC(JX,JY).EQ.4) THEN
          NTOBS=NTOBS+1
          IF(NTOBS.GT.MAXOBS) &
          & CALL ABOR1('READ_REMSS_MWOISST: MAXOBS TO INCREASE')
          ZDATA(NTOBS) = REAL(ZOSST(JX,JY),KIND=R8)
          ZLLON(NTOBS) = REAL(ZOLON(JX,JY),KIND=R8)
          ZLLAT(NTOBS) = REAL(ZOLAT(JX,JY),KIND=R8)
          ZERRS(NTOBS) = REAL(NOERR(JX,JY),KIND=R8)*0.01_R8 + 1._R8
          ZTIME(NTOBS) = ZREFTIME + REAL(NDIFFTIME(JX,JY),KIND=DP)/&
                       & REAL(24*60*60,KIND=DP)
        ENDIF
  ENDDO
 ENDDO
ENDIF

WRITE(IOUNLOG,*) ' --> FOUND ',NTOBS,' OBSERVATIONS'

END SUBROUTINE READ_REMSS_SWATH_AMSRE_NC
