SUBROUTINE READOBSA103

USE SET_KND
USE ALLOCOBS
USE OBS_STR
USE READOBAS103
USE OCEANTOOLS
USE RUN

IMPLICIT NONE

INTEGER(I4) :: NOBSBF(NOFAMS)

CALL GETOASN(NOBSBF)

INS%NO = NOBSBF(NNINS)
INS%NC = NOBSBF(NNINS)
SLA%NO = NOBSBF(NNSLA)
SLA%NC = NOBSBF(NNSLA)
SST%NO = NOBSBF(NNSST)
SST%NC = NOBSBF(NNSST)
SSS%NO = NOBSBF(NNSSS)
SSS%NC = NOBSBF(NNSSS)

WRITE(IOUNLOG,*) ' *** ',INS%NO,SLA%NO,SST%NO,SSS%NO
CALL FLUSH(IOUNLOG)

IF( INS%NO .GT. 0 ) &
CALL ALLOCINS(INS%NO,.TRUE.)

IF( SLA%NO .GT. 0 ) &
CALL ALLOCSLA(SLA%NO,.TRUE.)

RHO0=RHO_UNESCO(35.0_R8 ,0.0_R8 ,0.0_R8 ,.FALSE.)

IF( SST%NO .GT. 0 ) &
CALL ALLOCSST(SST%NO,.TRUE.)

IF( SSS%NO .GT. 0 ) &
CALL ALLOCSSS(SSS%NO,.TRUE.)

CALL GETOASOBS

END SUBROUTINE READOBSA103
