SUBROUTINE READ_GTSPP(CFILENAME,IOUN,MAXOBS,&
         & NTOTOBS,OBSTYPE,OBSPAR,OBSDEP,OBSVAL,OBSTIME,&
         & OBSLON,OBSLAT,OBSPROF,OBSPLAT)

!
! -> READ IN OBSERVATIONS FROM GTSPP IN
!    CMCC SIMPLIFIED MEDS FORMAT (CSMF) / ASCII
!
!    ANDREA STORTO _2012-03_
!

USE SET_KND
USE OBSDEF
USE RUN
USE NETCDF
USE CALENDAR, ONLY : TIME_DIFF,YMDS2JU

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILENAME
INTEGER(I4),INTENT(IN) :: IOUN, MAXOBS
INTEGER(I4),INTENT(OUT):: NTOTOBS

!... OBS STORAGE
INTEGER(I4), DIMENSION(MAXOBS),INTENT(OUT) :: &
OBSTYPE, OBSPAR, OBSPROF
REAL   (DP), DIMENSION(MAXOBS),INTENT(OUT) :: &
OBSTIME
REAL   (R8), DIMENSION(MAXOBS),INTENT(OUT) :: &
OBSDEP,  OBSVAL, OBSLON, OBSLAT
CHARACTER(LEN=8 ), DIMENSION(MAXOBS),INTENT(OUT) :: OBSPLAT
INTEGER(I4), PARAMETER :: NUNT=161
INTEGER(I4) :: KB

INTEGER :: NOK, KPROF
INTEGER :: WMOCT, NENCD, NGROU
INTEGER :: IAUX1, IAUX2, IAUX3, IAUX4
REAL    :: LON, LAT
REAL    :: ZAUX1, ZAUX2
CHARACTER(LEN=10) :: CRUISE
CHARACTER(LEN=10) :: CHAR10
CHARACTER(LEN=10) :: C_ACCS, C_DBID, C_PLAT
CHARACTER(LEN= 2) :: C_MT
INTEGER :: IDATE, ITIME
REAL(DP):: ZTIME
INTEGER :: OBSN
INTEGER :: JO, KSTAT
INTEGER :: IERR
INTEGER, PARAMETER :: MAXO = 7500
INTEGER, DIMENSION(MAXO) :: NPAR, OFLG
REAL   , DIMENSION(MAXO) :: DEPT, OVAL

LOGICAL :: LFIRST

OPEN(UNIT=NUNT, FILE=CFILENAME)

KSTAT=0
IERR=0
KB=0
KPROF=0

CYST : DO WHILE (IERR .EQ. 0)

  READ(NUNT,FMT='(I9,X,A10,X,2F9.3,X,I4,X,I3,X,I1)',&
  & IOSTAT=IERR) &
  & IAUX1,CHAR10,ZAUX1,ZAUX2,IAUX2,IAUX3,IAUX4

  IF(IERR.NE.0) EXIT CYST

  NOK=IAUX1
  CRUISE=CHAR10
  LON=ZAUX1
  LAT=ZAUX2
  WMOCT=IAUX2
  NENCD=IAUX3
  NGROU=IAUX4

  KSTAT=KSTAT+1
  LFIRST=.TRUE.
  READ(NUNT,'(A2,X,A10,X,A10,X,A10)') C_MT, C_ACCS, C_DBID, C_PLAT
  READ(NUNT,*) IDATE, ITIME, ZTIME, OBSN
  IF( ZTIME .LT. ZJULSTART .OR. ZTIME .GT. ZJULEND ) CYCLE CYST
  DO JO=1,OBSN
     READ(NUNT,'(I3, 2F9.3,X,I4.4)') NPAR(JO),DEPT(JO),OVAL(JO),OFLG(JO)
     IF( NPAR(JO) .EQ. KKTEMP .OR. NPAR(JO) .EQ. KKSAL ) THEN
         KB=KB+1
         IF( LFIRST ) THEN
             LFIRST = .FALSE.
             KPROF=KPROF+1
         ENDIF
         OBSTYPE(KB) = NENCD
         OBSPAR (KB) = NPAR(JO)
         OBSPROF(KB) = KPROF
         OBSDEP (KB) = DEPT(JO)
         OBSVAL (KB) = OVAL(JO)
         OBSTIME(KB) = ZTIME
         OBSLON (KB) = LON
         OBSLAT (KB) = LAT
         OBSPLAT(KB)(1:8) = ADJUSTL( C_PLAT(1:8) )
     ENDIF
  ENDDO

ENDDO CYST

CLOSE(UNIT=NUNT)

NTOTOBS=KB

END SUBROUTINE READ_GTSPP
