SUBROUTINE READ_CRZ(NX,NY,CXTO,CYTO)

  USE NETCDF
  USE SET_KND
  USE IOUNITS
  USE DRWN
  USE GRD_STR
  USE MYNETCDF
  IMPLICIT NONE

  INTEGER(I4), INTENT(IN) :: NX, NY

  INTEGER :: NCID,VARID(2)

  REAL(R8), DIMENSION(NX,NY),INTENT(OUT) :: CXTO,CYTO

  CALL CHECK( NF90_OPEN('Corrad_onx_z.nc', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'sossheig', VARID(1)) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(1),CXTO,START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  WRITE(IOUNLOG,*) ' CORRAD ON X READ'
  CALL FLUSH(IOUNLOG)

  CALL CHECK( NF90_OPEN('Corrad_ony_z.nc', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'sossheig', VARID(1)) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(1),CYTO,START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  WRITE(IOUNLOG,*) ' CORRAD ON Y READ'
  CALL FLUSH(IOUNLOG)

END SUBROUTINE READ_CRZ
