#undef SHARED_MEMORY
SUBROUTINE READFGFIELDS(SAL,TEM,ETA)

USE SET_KND
USE IOUNITS, ONLY : IOUNERR,IOUNOUT,IOUNLOG
USE GRD_STR, ONLY : GRD
USE READFG
USE RUN, ONLY : NTSTEPS, LL_RESTART_FILE, NSUBDOMAINS, NCONF, LLONLYOBSPP
USE MPIREL
USE MYNETCDF

IMPLICIT NONE

REAL(R8),DIMENSION(GRD%IM,GRD%JM,GRD%KM,NFGTSTEPS), INTENT(OUT) :: SAL,TEM
REAL(R8),DIMENSION(GRD%IM,GRD%JM,NFGTSTEPS), INTENT(OUT) :: ETA
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:,:) :: W4D
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:)   :: W3D

INTEGER(I4) :: ISTARTX,ISTARTY,IENDX,IENDY
INTEGER(I4) :: ISX,ISY,IEX,IEY
INTEGER(I4) :: JF,MNX,MNY,MNZ,MYT
INTEGER(I4) :: MAXX,MAXY
INTEGER(I4) :: TSFIRST, JT
INTEGER(I4) :: JR,KR

CHARACTER(LEN=8) :: CVARS(7)
CHARACTER(LEN=100) :: CFGFILES_open, CAUX

IF( LL_RESTART_FILE ) THEN
  CVARS(1)(1:2) = 'tn'
  CVARS(2)(1:2) = 'sn'
  CVARS(3)(1:4) = 'sshn'
ELSE
  CVARS(1)(1:8) = 'votemper'
  CVARS(2)(1:8) = 'vosaline'
  CVARS(3)(1:8) = 'sossheig'
ENDIF

#ifdef SHARED_MEMORY
INTEGER(I4) ::  OMP_GET_THREAD_NUM
#endif

!AS  AS VECTOR (DE-)ALLOCATION WITHIN OPENMP PARALLEL REGIONS
!AS  MIGHT FAIL DEPENDING ON THE OPENMP IMPLEMENTATION/VERSION,
!AS  MAXIMUM SIZE OF LOCAL DOMAIN ARE FOUND ON TOP OF THE READING

MAXX=MAXVAL(KDSL(1:NFGFILES,1))
MAXY=MAXVAL(KDSL(1:NFGFILES,2))
MNZ=GRD%KM

WRITE(IOUNLOG,*) '  CHECK --- NFGFILES = ',NFGFILES
WRITE(IOUNLOG,*) '  MAXVALUES FOR LOCAL DOMAIN SIZE =',MAXX,MAXY

ALLOCATE ( W4D(MAXX,MAXY,MNZ,NFGTSTEPS),&
         & W3D(MAXX,MAXY,NFGTSTEPS))

TIMESTEPS : DO JT = 1,NTSTEPS
 IF (LL_FGASSIM(JT) ) THEN
     TSFIRST =  JT
     EXIT TIMESTEPS
 ENDIF
ENDDO TIMESTEPS

IF(LMPION) THEN
  OPEN(901,FILE='FIRSTGUESS_READING.OUT.'//TRIM(CMPIDOM))
ELSE
  OPEN(901,FILE='FIRSTGUESS_READING.OUT')
ENDIF

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(PRIVATE),SHARED(TEM,SAL,ETA,KDNS,KDNE,&
!$OMP & KDLS,KDLE,KDSL,CFGFILES,MAXX,MAXY,NFGTSTEPS,MNZ,NCIDFG)
MYT=OMP_GET_THREAD_NUM() + 1
!$OMP DO SCHEDULE(DYNAMIC,1)
#else
MYT=1
#endif

DO JF=1,NFGFILES

  IF( LMPION .AND. NSUBDOMAINS .EQ. 0) THEN

        IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_tn.nc'
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(1)),GRD%IM,GRD%JM,GRD%KM,TSFIRST,NFGTSTEPS,TEM)
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_sn.nc'
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(2)),GRD%IM,GRD%JM,GRD%KM,TSFIRST,NFGTSTEPS,SAL)
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_sshn.nc'
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(3)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,ETA)
        ELSE
          IF(LL_READBYREC) THEN
            KR=0
            DO JR=TSFIRST,NFGTSTEPS
              KR=KR+1
              WRITE(CAUX,'(A,I4.4,A)') TRIM(CBGDIR)//'/'//'OPA_FIRSTGUESS_record_',JR,'.nc'
              CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(1)),GRD%IM,GRD%JM,GRD%KM,TEM(:,:,:,KR))
              CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(2)),GRD%IM,GRD%JM,GRD%KM,SAL(:,:,:,KR))
              CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(3)),GRD%IM,GRD%JM,       ETA(:,:,  KR))
            ENDDO
          ELSE
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(1)),GRD%IM,GRD%JM,GRD%KM,TSFIRST,NFGTSTEPS,TEM)
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(2)),GRD%IM,GRD%JM,GRD%KM,TSFIRST,NFGTSTEPS,SAL)
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(3)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,ETA)
          ENDIF
        ENDIF

  ELSE

   ISTARTX=KDNS(JF,1)-MP_XST(MYPROC)+1
   ISTARTY=KDNS(JF,2)-MP_YST(MYPROC)+1
   IENDX=KDNE(JF,1)-MP_XST(MYPROC)+1
   IENDY=KDNE(JF,2)-MP_YST(MYPROC)+1
   ISX=KDLS(JF,1)
   ISY=KDLS(JF,2)
   IEX=KDLE(JF,1)
   IEY=KDLE(JF,2)

   MNX=KDSL(JF,1)
   MNY=KDSL(JF,2)

   WRITE(IOUNLOG,*) ' === LOCAL SIZE FOR DOMAIN',JF,' CALLED BY THREAD',MYT,&
   & ':',MNX,MNY,MNZ,NFGTSTEPS
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) '    N   VAR          FILE         MNX  MAXX '; CALL FLUSH(IOUNLOG)
   WRITE(IOUNLOG,*) ' ',JF, ' TEM ',TRIM(CFGFILES(JF)),MNX,MAXX ; CALL FLUSH(IOUNLOG)


   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
      WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_tn.nc'
   ELSE
      WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF
   CALL READFG4DF(TRIM(CFGFILES_open),TRIM(CVARS(1)),MNX,MNY,MNZ,TSFIRST,NFGTSTEPS,MAXX,MAXY,&
   &  W4D,.TRUE.,.TRUE. ,NCIDFG(JF) )

   WRITE(IOUNLOG,*) ' LAYOUT FOR DOMAIN',JF,':',ISTARTX,IENDX,ISTARTY,IENDY
   WRITE(IOUNLOG,*) ' WHICH IS IN FILE:',ISX,IEX,ISY,IEY
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) ' TEMP - LOCAL TO GLOBAL COPY'
   WRITE(IOUNLOG,*) ' LOCAL : ',SHAPE(W4D),SIZE(W4D)
   WRITE(IOUNLOG,*) ' GLOBAL: ',SHAPE(TEM),SIZE(TEM)
   CALL FLUSH(IOUNLOG)
   TEM(ISTARTX:IENDX,ISTARTY:IENDY,:,:) = W4D(ISX:IEX,ISY:IEY,:,:)

   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) ' ',JF, ' SAL ',TRIM(CFGFILES(JF)),MNX,MAXX ; CALL FLUSH(IOUNLOG)
   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
     WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_sn.nc'
   ELSE
     WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF

   CALL READFG4DF(TRIM(CFGFILES_open),TRIM(CVARS(2)),MNX,MNY,MNZ,TSFIRST,NFGTSTEPS,MAXX,MAXY,&
   &  W4D,.TRUE.,.TRUE.,NCIDFG(JF) )
   WRITE(IOUNLOG,*) ' SAL  - LOCAL TO GLOBAL COPY'
   WRITE(IOUNLOG,*) ' LOCAL : ',SHAPE(W4D),SIZE(W4D)
   WRITE(IOUNLOG,*) ' GLOBAL: ',SHAPE(TEM),SIZE(TEM)
   CALL FLUSH(IOUNLOG)
   SAL(ISTARTX:IENDX,ISTARTY:IENDY,:,:) = W4D(ISX:IEX,ISY:IEY,:,:)
   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) ' ABOUT TO READ SSH'
   CALL FLUSH(IOUNLOG)

   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
     WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_sshn.nc'
   ELSE
     WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF

!   IF(.TRUE. .AND. LLONLYOBSPP ) THEN
!      W3D = 0._R8
!   ELSE
      CALL READFGETAB(TRIM(CFGFILES_open),TRIM(CVARS(3)),MNX,MNY,&
      & TSFIRST,NFGTSTEPS,MAXX,MAXY,&
      & W3D,.TRUE.,.TRUE.,NCIDFG(JF) )
      WRITE(IOUNLOG,*) ' DONE'
      WRITE(IOUNLOG,*) ' ETA  - LOCAL TO GLOBAL COPY'
      CALL FLUSH(IOUNLOG)
!   ENDIF
   ETA(ISTARTX:IENDX,ISTARTY:IENDY,:) = W3D(ISX:IEX,ISY:IEY,:)
   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

  ENDIF

ENDDO
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

DEALLOCATE( W4D,W3D )
CLOSE(901)

END SUBROUTINE READFGFIELDS
