SUBROUTINE REDCHECK

!
! REDUNDANCY CHECK ARGO VS GTSPP
! WHEN NEAR-REAL-TIME CONFIGURATION
!
! A.S. 2012

USE SET_KND
USE OBS_STR, ONLY : INS

IMPLICIT NONE

INTEGER(I4) :: JO, JO2

#include "obs_events.h"

CYO : DO JO=1,INS%NO

  IF( INS%DSRC(JO) .EQ. 'ARG' .OR. INS%FLC(JO) .NE. 1) CYCLE CYO

  CYO2 : DO JO2=1,INS%NO

     IF( INS%FLC(JO2) .NE. 1 .OR. JO .EQ. JO2 ) CYCLE CYO2

     IF(  INS%DSRC(JO2) .EQ. 'ARG' .AND. &
          ABS(INS%LON(JO)-INS%LON(JO2)) .LT. 0.03_R8 .AND. &
          ABS(INS%LAT(JO)-INS%LAT(JO2)) .LT. 0.03_R8 .AND. &
          ABS(INS%TIM(JO)-INS%TIM(JO2)) .LT. 0.03_DP ) THEN

          INS%FLC(JO) = 0
          INS%EVE(JO) = KEVE_REDC

     ENDIF

  ENDDO CYO2

ENDDO CYO

END SUBROUTINE REDCHECK
