SUBROUTINE REPEVE

!.. REPORT EVENTS FOR SLA AND INS
!.. OPTIONALLY WRITE A LATLON FILE
!..
!.. ANDREA STORTO, 2009

USE SET_KND
USE OBS_STR, ONLY : INS, SLA, SST, SSS, SIC, SIT
USE OBSDEF
USE IOUNITS, ONLY : IOUNLOG,IOUNOUT
USE RUN    , ONLY : LLEVEFORMV

IMPLICIT NONE

INTEGER(I4) :: JO, NFAULTS

#include "obs_events.h"

NFAULTS = 0

IF(LLEVEFORMV) THEN
  OPEN(701,FILE='SLA_EVE.GEO')
  OPEN(702,FILE='INS_EVE.GEO')
  OPEN(703,FILE='SST_EVE.GEO')
  OPEN(704,FILE='SSS_EVE.GEO')
  OPEN(705,FILE='SIC_EVE.GEO')
  OPEN(706,FILE='SIT_EVE.GEO')
  WRITE(701,'(A)') '#GEO'
  WRITE(701,'(A)') '#FORMAT LLV'
  WRITE(701,'(A)') '#DATA'
  WRITE(702,'(A)') '#GEO'
  WRITE(702,'(A)') '#FORMAT LLV'
  WRITE(702,'(A)') '#DATA'
  WRITE(703,'(A)') '#GEO'
  WRITE(703,'(A)') '#FORMAT LLV'
  WRITE(703,'(A)') '#DATA'
  WRITE(704,'(A)') '#GEO'
  WRITE(704,'(A)') '#FORMAT LLV'
  WRITE(704,'(A)') '#DATA'
  WRITE(705,'(A)') '#GEO'
  WRITE(705,'(A)') '#FORMAT LLV'
  WRITE(705,'(A)') '#DATA'
  WRITE(706,'(A)') '#GEO'
  WRITE(706,'(A)') '#FORMAT LLV'
  WRITE(706,'(A)') '#DATA'
ENDIF


! SLA PART
IF(SLA%NO .GT. 0) THEN
  DO JO=1,SLA%NO
     KCOUNT(SLA%EVE(JO),1) = KCOUNT(SLA%EVE(JO),1) + 1
     IF(LLEVEFORMV) WRITE(701,'(2(F8.3,X),I2)') &
     & SLA%LON(JO),SLA%LAT(JO),SLA%EVE(JO)
     IF(SLA%NO.LT.10) THEN
       WRITE(IOUNOUT,*) SLA%VAL(JO),SLA%BAC(JO),SLA%RES(JO)
     ENDIF
  ENDDO
ENDIF

! INS PART
IF(INS%NO .GT. 0) THEN
  DO JO=1,INS%NO
   IF( INS%FLG(JO) .NE. 1 .OR. INS%EVE(JO).LT.0 .OR. INS%EVE(JO).GT.KNOEVE &
   & .OR. INS%KTY(JO).LT.1 .OR. INS%KTY(JO).GT.(NOFAMS+1)) THEN
     NFAULTS = NFAULTS + 1
     INS%FLC(JO)=0
   ELSE
     KCOUNT(INS%EVE(JO),2) = KCOUNT(INS%EVE(JO),2) + 1
     IF(LLEVEFORMV) WRITE(702,'(2(F8.3,X),I2)') &
     & INS%LON(JO),INS%LAT(JO),INS%EVE(JO)
     KCOUNT(INS%EVE(JO),2+INS%KTY(JO)) = KCOUNT(INS%EVE(JO),2+INS%KTY(JO))+1
     IF(INS%NO.LT.10) THEN
       WRITE(IOUNOUT,*) INS%VAL(JO),INS%BAC(JO),INS%RES(JO)
     ENDIF
   ENDIF
  ENDDO
ENDIF

! SST PART
IF(SST%NO .GT. 0) THEN
  DO JO=1,SST%NO
     KCOUNT(SST%EVE(JO),8) = KCOUNT(SST%EVE(JO),8) + 1
     IF(LLEVEFORMV) WRITE(703,'(2(F8.3,X),I2)') &
     & SST%LON(JO),SST%LAT(JO),SST%EVE(JO)
     IF(SST%NO.LT.10) THEN
       WRITE(IOUNOUT,*) SST%VAL(JO),SST%BAC(JO),SST%RES(JO)
     ENDIF
  ENDDO
ENDIF

! SSS PART
IF(SSS%NO .GT. 0) THEN
  DO JO=1,SSS%NO
     KCOUNT(SSS%EVE(JO),9) = KCOUNT(SSS%EVE(JO),9) + 1
     IF(LLEVEFORMV) WRITE(704,'(2(F8.3,X),I2)') &
     & SSS%LON(JO),SSS%LAT(JO),SSS%EVE(JO)
     IF(SSS%NO.LT.10) THEN
       WRITE(IOUNOUT,*) SSS%VAL(JO),SSS%BAC(JO),SSS%RES(JO)
     ENDIF
  ENDDO
ENDIF

! SIC PART
IF(SIC%NO .GT. 0) THEN
  DO JO=1,SIC%NO
     KCOUNT(SIC%EVE(JO),10) = KCOUNT(SIC%EVE(JO),10) + 1
     IF(LLEVEFORMV) WRITE(705,'(2(F8.3,X),I2)') &
     & SIC%LON(JO),SIC%LAT(JO),SIC%EVE(JO)
     IF(SIC%NO.LT.10) THEN
       WRITE(IOUNOUT,*) SIC%VAL(JO),SIC%BAC(JO),SIC%RES(JO)
     ENDIF
  ENDDO
ENDIF

! SIT PART
IF(SIT%NO .GT. 0) THEN
  DO JO=1,SIT%NO
     KCOUNT(SIT%EVE(JO),11) = KCOUNT(SIT%EVE(JO),11) + 1
     IF(LLEVEFORMV) WRITE(706,'(2(F8.3,X),I2)') &
     & SIT%LON(JO),SIT%LAT(JO),SIT%EVE(JO)
     IF(SIT%NO.LT.10) THEN
       WRITE(IOUNOUT,*) SIT%VAL(JO),SIT%BAC(JO),SIT%RES(JO)
     ENDIF
  ENDDO
ENDIF

! SUM UP
DO JO=0,KNOEVE
     KCOUNTT(JO) = SUM( KCOUNT(JO,:) )
ENDDO

CALL FLUSH(IOUNLOG)
WRITE(IOUNLOG,'(A)')
WRITE(IOUNLOG,'(A)')
WRITE(IOUNLOG,'(A)') '  STATUS OF OBSERVATIONS BEFORE MINIMIZATION'
WRITE(IOUNLOG,'(A)')
WRITE(IOUNLOG,'(A)') &
& '  -----------------------------------------------------------------------------------------------------------------'
WRITE(IOUNLOG,'(A)') &
& '  EVENT      SLA   ALLINS      XBT    TESAC     ARGO    BUOYS    AIR2M      SST      SSS     SIC      SIT     TOTAL'
DO JO=0,KNOEVE
    WRITE(IOUNLOG,'(I7,12(X,I8))')JO,KCOUNT(JO,1),KCOUNT(JO,2),&
    & KCOUNT(JO,3:7),KCOUNT(JO,8),KCOUNT(JO,9),KCOUNT(JO,10),KCOUNT(JO,11),KCOUNTT(JO)
ENDDO
WRITE(IOUNLOG,'(A)') &
& '  ------------------------------------------------------------------------------------------------------------------'
WRITE(IOUNLOG,'(A,12(X,I8))')'  TOTAL',SUM(KCOUNT(:,1)),&
& SUM(KCOUNT(:,2)),SUM(KCOUNT(:,3)),SUM(KCOUNT(:,4)),&
& SUM(KCOUNT(:,5)),SUM(KCOUNT(:,6)),SUM(KCOUNT(:,7)),SUM(KCOUNT(:,8)),SUM(KCOUNT(:,9)),SUM(KCOUNT(:,10)),SUM(KCOUNT(:,11)),SUM(KCOUNTT)
WRITE(IOUNLOG,'(A,2(X,I8),45X,X,I8,X,I8,X,I8) &
& ')' OBS',SLA%NO,INS%NO,SST%NO,SSS%NO,SLA%NO+INS%NO+SST%NO+SSS%NO+SIC%NO+SIT%NO
WRITE(IOUNLOG,'(A)') &
& '  --------------------------------------------------------------------------------------'
WRITE(IOUNLOG,'(A)')
WRITE(IOUNLOG,'(A)') '  LEGEND:'
DO JO=0,KNOEVE
    WRITE(IOUNLOG,'(X,X,I2,A,A)') JO,': ',TRIM(CSTREVE(JO))
ENDDO
CALL FLUSH(IOUNLOG)

WRITE(IOUNLOG,*) ' UNSUPPORTED EVENTS : ', NFAULTS
CALL FLUSH(IOUNLOG)

IF(LLEVEFORMV) THEN
     CLOSE(701)
     CLOSE(702)
     CLOSE(703)
     CLOSE(704)
     CLOSE(705)
     CLOSE(706)
ENDIF

END SUBROUTINE REPEVE
