SUBROUTINE RES_INC

!-----------------------------------------------------------------------
!                                                                      !
! INITIALISE FOR ADJOINT CALCULATIONS                                  !
!                                                                      !
! VERSION 1: S.DOBRICIC 2006                                           !
!-----------------------------------------------------------------------

 USE SET_KND
 USE GRD_STR
 USE OBS_STR
 USE BMD_STR
 USE CTL_STR
 USE RUN
 USE WEAKLY
 USE HYBRID
 USE TRACK_CORREL
 USE PROF_CORREL
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL

 IMPLICIT NONE

 INTEGER(I4) :: IJ, JO
 REAL(R8) :: ZJ

 CALL MYFRTPROF_WALL('RES_INC: RESET RESIDUALS',0)

 IF(NCONF .NE. 202 ) THEN
     PSV_AD = 0._R8
     IF(LL_HYBRID_CR) PSVF_AD = 0._R8
  ENDIF

  IF(LLVARMDT .OR. NCONF .EQ. 202) GRD%CMDT_AD = 0._R8

  IF(LL_WEAKLY) THEN
     IF(LL_WCEOF) THEN
       WROE_AD = 0._R8
       IF ( NN_WCEOF3D_2 .GT. 0 ) THEN
         WROE_AD_2 = 0._R8
       ENDIF
     ELSE
       ROW_AD = 0._R8
     ENDIF
     WW_AD  = 0._R8
  ENDIF

  IF(LL_HYBRID .AND. LL_ALPHA_CTL) ALPHA_AD = 0._R8

  ! SLA PART
  IF( SLA%NO .GT. 0 ) THEN
   IF( NN_TRACK_CORREL.GT.0 ) THEN
    CALL GRASLA_CORREL(SLA%NC,OBS%GRA(1:SLA%NC))
   ELSEIF ( LL_HUBERQC .AND. LL_HUBERQC_SLA .AND. CTL%KITER .GT. ITER_HUBQC ) THEN
    DO JO=1,SLA%NO
      IF( OBS%AMO(JO).GT.ABS(OBS%AHUB(JO,1)) .AND. OBS%AMO(JO).LE.ABS(OBS%AHUB2(JO,1)) ) THEN
          OBS%GRA(JO) = OBS%AHUB(JO,1) / OBS%ERR(JO)
      ELSEIF ( OBS%AMO(JO).LT.-ABS(OBS%AHUB(JO,2)) .AND. OBS%AMO(JO).GE.-ABS(OBS%AHUB2(JO,2)) ) THEN
          OBS%GRA(JO) = -OBS%AHUB(JO,2) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).GT.ABS(OBS%AHUB2(JO,1)) ) THEN
           ZJ = 2._R8*OBS%AHUB(JO,1)*SQRT(OBS%AHUB2(JO,1))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(OBS%AMO(JO))) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).LT.-ABS(OBS%AHUB2(JO,2)) ) THEN
           ZJ = -2._R8*OBS%AHUB(JO,2)*SQRT(OBS%AHUB2(JO,2))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(ABS(OBS%AMO(JO)))) / OBS%ERR(JO)
      ELSE
          OBS%GRA(JO) = OBS%AMO(JO) / OBS%ERR(JO)
      ENDIF
    ENDDO
   ELSE
    OBS%GRA(1:SLA%NO) = OBS%AMO(1:SLA%NO) / OBS%ERR(1:SLA%NO)
   ENDIF
  ENDIF

  ! INS PART
  IF( INS%NO .GT. 0 ) THEN
   IF( NN_PROF_CORREL.GT.0 .AND. .NOT. LL_PROFCORR_ONLYP ) THEN
    CALL GRAINS_CORREL(INS%NC,OBS%GRA((SLA%NC+1):(SLA%NC+INS%NC)))
   ELSEIF ( LL_HUBERQC .AND. LL_HUBERQC_INS .AND. CTL%KITER .GT. ITER_HUBQC ) THEN
    DO JO=SLA%NC+1,SLA%NC+INS%NO
      IF( OBS%AMO(JO).GT.ABS(OBS%AHUB(JO,1)) .AND.  OBS%AMO(JO).LE.ABS(OBS%AHUB2(JO,1)) ) THEN
          OBS%GRA(JO) = OBS%AHUB(JO,1) / OBS%ERR(JO)
      ELSEIF ( OBS%AMO(JO).LT.-ABS(OBS%AHUB(JO,2)) .AND.  OBS%AMO(JO).GE.-ABS(OBS%AHUB2(JO,2)) ) THEN
          OBS%GRA(JO) = -OBS%AHUB(JO,2) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).GT.ABS(OBS%AHUB2(JO,1)) ) THEN
           ZJ = 2._R8*OBS%AHUB(JO,1)*SQRT(OBS%AHUB2(JO,1))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(OBS%AMO(JO))) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).LT.-ABS(OBS%AHUB2(JO,2)) ) THEN
           ZJ = -2._R8*OBS%AHUB(JO,2)*SQRT(OBS%AHUB2(JO,2))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(ABS(OBS%AMO(JO)))) / OBS%ERR(JO)
      ELSE
          OBS%GRA(JO) = OBS%AMO(JO) / OBS%ERR(JO)
      ENDIF
    ENDDO
   ELSE
    OBS%GRA((SLA%NC+1):(SLA%NC+INS%NC)) = OBS%AMO((SLA%NC+1):(SLA%NC+INS%NC)) / &
    & OBS%ERR((SLA%NC+1):(SLA%NC+INS%NC))
   ENDIF
  ENDIF

  ! SST/SSS PART
  IF( (SST%NO+SSS%NO) .GT. 0 ) THEN
   IF ( LL_HUBERQC .AND. (LL_HUBERQC_SST .OR. LL_HUBERQC_SSS) .AND. CTL%KITER .GT. ITER_HUBQC ) THEN
    DO JO=SLA%NC+INS%NC+1,SLA%NC+INS%NO+SST%NO+SSS%NO
      IF( OBS%AMO(JO).GT.ABS(OBS%AHUB(JO,1)) .AND.  OBS%AMO(JO).LE.ABS(OBS%AHUB2(JO,1)) ) THEN
          OBS%GRA(JO) = OBS%AHUB(JO,1) / OBS%ERR(JO)
      ELSEIF ( OBS%AMO(JO).LT.-ABS(OBS%AHUB(JO,2)) .AND.  OBS%AMO(JO).GE.-ABS(OBS%AHUB2(JO,2)) ) THEN
          OBS%GRA(JO) = -OBS%AHUB(JO,2) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).GT.ABS(OBS%AHUB2(JO,1)) ) THEN
           ZJ = 2._R8*OBS%AHUB(JO,1)*SQRT(OBS%AHUB2(JO,1))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(OBS%AMO(JO))) / OBS%ERR(JO)
      ELSEIF( OBS%AMO(JO).LT.-ABS(OBS%AHUB2(JO,2)) ) THEN
           ZJ = -2._R8*OBS%AHUB(JO,2)*SQRT(OBS%AHUB2(JO,2))
           OBS%GRA(JO) = 0.5_R8*(ZJ/SQRT(ABS(OBS%AMO(JO)))) / OBS%ERR(JO)
      ELSE
          OBS%GRA(JO) = OBS%AMO(JO) / OBS%ERR(JO)
      ENDIF
    ENDDO
   ELSE
    OBS%GRA((INS%NC+SLA%NC+1):(OBS%NO)) = OBS%AMO((SLA%NC+INS%NC+1):(OBS%NO)) / &
    & OBS%ERR((INS%NC+SLA%NC+1):(OBS%NO))
   ENDIF
  ENDIF

  IF( SIC%NO .GT. 0 ) THEN
    OBS%GRA((SLA%NC+INS%NC+SST%NO+SSS%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO)) = OBS%AMO((SLA%NC+INS%NC+SST%NO+SSS%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO)) / &
    & OBS%ERR((SLA%NC+INS%NC+SST%NO+SSS%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO))
  ENDIF
 
   IF( SIT%NO .GT. 0 ) THEN
    OBS%GRA((SLA%NC+INS%NC+SST%NO+SSS%NO+SIC%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO+SIT%NO)) = OBS%AMO((SLA%NC+INS%NC+SST%NO+SSS%NO+SIC%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO+SIT%NO))/ &
    & OBS%ERR((SLA%NC+INS%NC+SST%NO+SSS%NO+SIC%NO+1):(INS%NC+SLA%NC+SST%NO+SSS%NO+SIC%NO+SIT%NO))
  ENDIF



 CALL MYFRTPROF_WALL('RES_INC: RESET RESIDUALS',1)
END SUBROUTINE RES_INC
