SUBROUTINE SETMPPNEIGHB

USE SET_KND
USE IOUNITS, ONLY : IOUNERR,IOUNOUT,IOUNLOG
USE NETCDF
USE READFG
USE RUN
USE MPIREL

IMPLICIT NONE

INTEGER(I4) :: JF, IAUX, IAUX2(7), IERR

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// SETUP MPP NEIGHBOURS'

IF(.NOT.LLMPF) THEN
    NONO(1)=-1
    NOSO(1)=-1
    NOEA(1)=-1
    NOWE(1)=-1
ELSE
     OPEN(712,FILE='mppinit.dat',STATUS='OLD',IOSTAT=IERR)
     IF(IERR.NE.0) CALL ABOR1('SETMPPNEIGHB: CANNOT OPEN MPPINIT.DAT')
     DO JF=1,NSUBDOMAINS
        READ(712,*,IOSTAT=IERR) IAUX,NOWE(JF),NOEA(JF),NONO(JF),NOSO(JF),IAUX2(1:7)
        IF(IERR.NE.0) CALL ABOR1('SETMPPNEIGHB: CANNOT READ MPPINIT.DAT')
     ENDDO
     CLOSE(712)
ENDIF

NOWE=NOWE+1
NOEA=NOEA+1
NONO=NONO+1
NOSO=NOSO+1

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' MPPINIT FILE READING'
WRITE(IOUNLOG,*) ' DOM     :: NONO,NOSO,NOEA,NOWE'
DO JF=1,NSUBDOMAINS
  WRITE(IOUNLOG,*) ' DOM ',JF, ' :: ',NONO(JF),NOSO(JF),NOEA(JF),NOWE(JF)
ENDDO

CALL FLUSH(IOUNLOG)
END SUBROUTINE SETMPPNEIGHB
