SUBROUTINE SU_MPRF

  USE MPI
  USE SET_KND
  USE MYMPI

  IMPLICIT NONE

  INTEGER(I4) :: IERR, NDIV, NRES

  CALL MPI_INIT(IERR)
  CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPROC,IERR)
  CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NNPROCS,IERR)

  ALLOCATE( MJSA(NNPRCS), MJEA(NNPRCS), MISA(NNPRCS), MIEA(NNPRCS) ) 
  ALLOCATE( MICA(NNPRCS), MJCA(NNPRCS) )

  NDIV=GRD%JM/NNPROCS
  NRES=MOD(GRD%JM,NNPROCS)
  MJCA(:)=NDIV
  DO JI=1,NRES
      MJCA(JI)=MJCA(JI)+1
  ENDDO
   
  NDIV=GRD%IM/NNPROCS
  NRES=MOD(GRD%IM,NNPROCS)
  MJCA(:)=NDIV
  DO JI=1,NRES
      MICA(JI)=MICA(JI)+1
  ENDDO

  MISA(1)=1
  MIEA(1)=MICA(1)
  MJSA(1)=1
  MJEA(1)=MJCA(1)

  DO JI=2,NNPROCS
     MISA(JI)=MIEA(JI-1)+1
     MIEA(JI)=MIEA(JI-1)+MICA(JI)
     MJSA(JI)=MJEA(JI-1)+1
     MJEA(JI)=MJEA(JI-1)+MJCA(JI)
  ENDDO 

  MIS = MISA(MYID)
  MIE = MIEA(MYID)
  MJS = MJSA(MYID)
  MJE = MJEA(MYID)
  MIC = MICA(MYID)
  MJC = MJCA(MYID)

  WRITE(IOUNLOG,*) ' MPI LAYOUT FOR RECURSIVE FILTERS '

END SUBROUTINE SU_MPRF
