SUBROUTINE SULOGF

!............SULOGF................................
!
! SET AND OPEN AUXILIARY UNITS ACCORDING TO NO OF PROCESSES
!

USE SET_KND, ONLY : I4
USE IOUNITS, ONLY : IOUNLOG,IOUNERR,IOUNCOST,IOUNOUT
USE MPIREL,  ONLY : LMPION, MYPROC, NIOMASTER, CMPIDOM
USE RUN,  ONLY : CINSTRING


IMPLICIT NONE

INTEGER(KIND=I4) :: IERR
CHARACTER(LEN=30) :: CLOGNAME, CCOSTNAME

CLOGNAME = 'LOG_3DVAR'
CCOSTNAME = 'COST.DAT'

IF(LMPION) THEN
     IF(MYPROC.EQ.NIOMASTER) THEN
        OPEN(UNIT=IOUNLOG,FILE=CLOGNAME,IOSTAT=IERR)
        IF(IERR.NE.0) THEN
           WRITE(IOUNERR,*) &
           & 'CANNOT OPEN LOGFILE, LMPION=',LMPION,' MYPROC=',MYPROC
           CALL ABOR1('LOGFILE OPENING PROBLEM')
        ENDIF
        OPEN(UNIT=IOUNCOST,FILE=CCOSTNAME,IOSTAT=IERR)
        IF(IERR.NE.0) THEN
           WRITE(IOUNERR,*) &
           & 'CANNOT OPEN COSTFILE, LMPION=',LMPION,' MYPROC=',MYPROC
           CALL ABOR1('COSTFILE OPENING PROBLEM')
        ENDIF
     ELSE
        OPEN(UNIT=IOUNLOG,FILE=TRIM(CLOGNAME)//'.'//TRIM(CMPIDOM),IOSTAT=IERR)
        OPEN(UNIT=IOUNCOST,FILE=TRIM(CCOSTNAME)//'.'//TRIM(CMPIDOM),IOSTAT=IERR)
     ENDIF
ELSE
     OPEN(UNIT=IOUNLOG,FILE=CLOGNAME,IOSTAT=IERR)
     IF(IERR.NE.0) THEN
        WRITE(IOUNERR,*) &
        & 'CANNOT OPEN LOGFILE, LMPION=',LMPION,' MYPROC=',MYPROC
        CALL ABOR1('LOGFILE OPENING PROBLEM')
     ENDIF
     OPEN(UNIT=IOUNCOST,FILE=CCOSTNAME,IOSTAT=IERR)
     IF(IERR.NE.0) THEN
        WRITE(IOUNERR,*) &
        & 'CANNOT OPEN COSTFILE, LMPION=',LMPION,' MYPROC=',MYPROC
        CALL ABOR1('COSTFILE OPENING PROBLEM')
     ENDIF
ENDIF

!... GREETINGS
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ****************************************'
WRITE(IOUNLOG,*) ' ****************************************'
WRITE(IOUNLOG,*) '       OCENOGRAPHIC VARIATIONAL JOB'
WRITE(IOUNLOG,*) ' ****************************************'
WRITE(IOUNLOG,*) ' ****************************************'
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) CINSTRING

WRITE(IOUNOUT,*)
WRITE(IOUNOUT,*) ' ****************************************'
WRITE(IOUNOUT,*) ' ****************************************'
WRITE(IOUNOUT,*) '       OCENOGRAPHIC VARIATIONAL JOB'
WRITE(IOUNOUT,*) ' ****************************************'
WRITE(IOUNOUT,*) ' ****************************************'
WRITE(IOUNOUT,*)
WRITE(IOUNOUT,*) CINSTRING

END SUBROUTINE SULOGF
