SUBROUTINE SURF_LV

!.. SETUP OF RECURSIVE FILTER ..!
!
!   ALL THE ROUTINES ARE INCLUDED
!   IN THE MODULE RECFILTER

USE SET_KND
USE GRD_STR
USE RECFILTER
USE RUN
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE IOUNITS, ONLY : IOUNOUT,IOUNLOG
USE MYNETCDF

IMPLICIT NONE
INTEGER(KIND=I4) :: NX,NY,NZ

CALL MYFRTPROF_WALL('SURF_LV: RECURSIVE FILTER SETUP',0)

  WRITE(IOUNOUT,*) ' ENTERING SURF_LV'
  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' ENTERING SURF_LV'

  !... SETUP CONFIGURATION

  NX=GRD%IM
  NY=GRD%JM
  NZ=GRD%KM

  LLRFINIT=.TRUE.
  LLTSAPART = .TRUE.

  !... CALCULATE GEOGRAPHICAL SCALING FACTOR
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: SCALING FACTOR...'
  CALL COMPSC_LV
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)
  IF( NCONF .EQ. 104 ) THEN
    CALL MYFRTPROF_WALL('SURF_LV: RECURSIVE FILTER SETUP',1)
    RETURN
  ENDIF

  !... CALCULATE ALPHA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: COMPUTE ALPHAS...'
  IF (NCONF .NE. 202) CALL COMPALPHA_LV
  IF (LLVARMDT .OR. NCONF .EQ. 202) CALL COMPALPHA_LVM
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  !... DEFINE EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: EXTENDED GRID...'
  IF (NCONF .NE. 202) CALL DEFEXTGRD_LV
  IF (LLVARMDT .OR. NCONF .EQ. 202) CALL DEFEXTGRD_LVM
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  !... REARRANGE ALPHAS ACCORDING TO EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: REARRANGE ALPHAS...'
  IF (NCONF .NE. 202) CALL REARRALPHA_LV
  IF (LLVARMDT .OR. NCONF .EQ. 202) CALL REARRALPHA_LVM
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

CALL MYFRTPROF_WALL('SURF_LV: RECURSIVE FILTER SETUP',1)

END SUBROUTINE SURF_LV
