SUBROUTINE SURF

!.. SETUP OF RECURSIVE FILTER ..!
!
!   ALL THE ROUTINES ARE INCLUDED
!   IN THE MODULE RECFILTER

USE SET_KND
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE IOUNITS, ONLY : IOUNOUT,IOUNLOG

IMPLICIT NONE
CALL MYFRTPROF_WALL('SURF: RECURSIVE FILTER SETUP',0)

  !... SETUP CONFIGURATION
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: SETTING DIMENSIONS...'
  CALL SETUPRFCR
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)

  !... READ-IN CORRELATION LENGTH-SCALE UNLESS
  !    GLOBALLY CONSTANT
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: READING CR DATA...'
  CALL READ_CRF1

  !... CALCULATE GEOGRAPHICAL SCALING FACTOR
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: SCALING FACTOR...'
  CALL COMPSC
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)

  !... CALCULATE ALPHA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: COMPUTE ALPHAS...'
  CALL COMPALPHA
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)

  !... DEFINE EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: EXTENDED GRID...'
  CALL DEFEXTGRD
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)

  !... REARRANGE ALPHAS ACCORDING TO EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: REARRANGE ALPHAS...'
  CALL REARRALPHA
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNLOG)

CALL MYFRTPROF_WALL('SURF: RECURSIVE FILTER SETUP',1)
RETURN
END SUBROUTINE SURF
