PROGRAM TIMEADD

IMPLICIT NONE

CHARACTER(LEN=14) :: CDD1, CDD2, CARG, CDD
CHARACTER :: COPT
INTEGER :: IDIFF,IRET,ILL,II

CALL GETARG(1,CARG)
IF(CARG(1:2) .NE. '-D' .AND. CARG(1:2) .NE. '-H' &
   & .AND. CARG(1:2) .NE. '-M' &
   & .AND. CARG(1:2) .NE. '-S') CALL USAGE
COPT=CARG(2:2)

CALL GETARG(2,CDD1)
CALL GETARG(3,CDD)
READ(CDD,*) IDIFF

CALL ADDTIME(COPT,CDD1,CDD2,IDIFF,IRET,.TRUE.)
IF(IRET.NE.0) CALL USAGE

WRITE(6,'(A)') TRIM(CDD2)

CONTAINS

SUBROUTINE USAGE

WRITE(*,*)
WRITE(*,*) 'USAGE :   TIMEADD -D|-H|-M|-S DATE1 INCR'
WRITE(*,*)
WRITE(*,*) '          -D : DAYS ; -H HOURS ; -M MINUTES ; -S SECONDS'
WRITE(*,*)
STOP
END SUBROUTINE USAGE

END PROGRAM TIMEADD
