PROGRAM TIMEDIFF

IMPLICIT NONE

CHARACTER(LEN=14) :: CDD1, CDD2, CARG,CF
CHARACTER :: COPT
INTEGER :: IDIFF,IRET,ILL

CALL GETARG(1,CARG)
IF(CARG(1:2) .NE. '-D' .AND. CARG(1:2) .NE. '-H' &
   & .AND. CARG(1:2) .NE. '-M' &
   & .AND. CARG(1:2) .NE. '-S') CALL USAGE
COPT=CARG(2:2)

CALL GETARG(2,CDD1)
CALL GETARG(3,CDD2)

CALL DIFFTIME(COPT,CDD1,CDD2,IDIFF,IRET,.TRUE.)
IF(IRET.NE.0) CALL USAGE

ILL=INT( LOG(REAL(ABS(IDIFF)))/LOG(REAL(10)) ) + 1
IF(IDIFF.LT.0) ILL=ILL+1
WRITE(CF,'(A,I2.2,A)') '(I',ILL,')'
WRITE(6,CF) IDIFF

CONTAINS

SUBROUTINE USAGE

WRITE(*,*)
WRITE(*,*) 'USAGE :   TIMEDIFF -D|-H|-M|-S DATE1 DATE2'
WRITE(*,*)
WRITE(*,*) '          -D : DAYS ; -H HOURS ; -M MINUTES ; -S SECONDS'
WRITE(*,*)
STOP
END SUBROUTINE USAGE

END PROGRAM TIMEDIFF
