SUBROUTINE UNBIAS_SLA_AT

 USE SET_KND
 USE GRD_STR
 USE OBS_STR
 USE IOUNITS
 USE RUN, ONLY : LL_UNBIAS_SLA_AT, ZZ_SLA_BIAS
 USE MPIREL

 IMPLICIT NONE

 INTEGER(I4)   ::  K, KK
 REAL(R8) :: ZBIAS
 INTEGER(I4)   ::  I1, I, ITER,FLAG
  REAL(R8)      ::  SUMT, SUMI, TIMP, DXX, DYY, DSM

#include "obs_events.h"
K=0
KK=0
ZBIAS=0._R8


IF(SLA%NO.LE.0) RETURN

   SLA%BIA(:) = 0.0
   DSM = 100.
   I1 = 1
    DO K=2,SLA%NO

      DXX = 6371.*3.14/180. * (SLA%LON(K)-SLA%LON(K-1)) * &
            COS(SLA%LAT(K)*3.14/180.)
      DYY = 6371.*3.14/180. * (SLA%LAT(K)-SLA%LAT(K-1))
  IF((SQRT(DXX**2+DYY**2).GT.DSM) .AND. K.GT.I1)THEN
    SUMT = 0.0
    SUMI = 0.0
    DO I=I1,K-1
    IF(SLA%FLC(I).EQ.1)THEN
      SUMT = SUMT + SLA%RES(I)
      SUMI = SUMI + 1.0
     ENDIF
    ENDDO
     IF(SUMI.GT.0.) SUMT = SUMT/SUMI
      DO I=I1,K-1
       SLA%RES(I) = SLA%RES(I) - SUMT
       SLA%BIA(I) = SUMT
    ENDDO
     TIMP = SLA%TIM(K)
     I1 = K
  ELSE IF(K.EQ.SLA%NO .AND. K.GE.I1)THEN
     SUMT = 0.0
     SUMI = 0.0
   DO I=I1,K
     IF(SLA%FLC(I).EQ.1)THEN
      SUMT = SUMT + SLA%RES(I)
      SUMI = SUMI + 1.0
     ENDIF
    ENDDO
     IF(SUMI.GT.0.) SUMT = SUMT/SUMI
    DO I=I1,K
     SLA%RES(I) = SLA%RES(I) - SUMT
     SLA%BIA(I) = SUMT
    ENDDO
  ENDIF
 ENDDO

 ZZ_SLA_BIAS = 0._R8
 IF( LL_UNBIAS_SLA_AT ) THEN
  WRITE(IOUNLOG,*) ' THE ALONG TRACK BIAS IS REMOVED'
 ELSE
  WRITE(IOUNLOG,*) ' THE BIAS IS NOT REMOVED'
 ENDIF

 CALL FLUSH(IOUNLOG)

END SUBROUTINE UNBIAS_SLA_AT
