SUBROUTINE UNBIAS_SLA

 USE SET_KND
 USE GRD_STR
 USE OBS_STR
 USE IOUNITS
 USE RUN, ONLY : LL_UNBIAS_SLA, ZZ_SLA_BIAS
 USE MPIREL

 IMPLICIT NONE

 INTEGER(I4)   ::  K, KK
 REAL(R8) :: ZBIAS

#include "obs_events.h"

KK=0
ZBIAS=0._R8

IF(SLA%NO.LE.0) RETURN

 CYOBS : DO K=1,SLA%NO

    IF( SLA%FLC(K) .EQ. 1 ) THEN
        ZBIAS = ZBIAS + SLA%RES(K)
        KK = KK + 1
    ENDIF

 ENDDO CYOBS

 IF( LMPION ) THEN
    CALL MPPSUM( KK )
    CALL MPPSUM( ZBIAS )
 ENDIF

 IF( KK .GT. 0 ) ZBIAS = ZBIAS/REAL(KK)

 WRITE(IOUNLOG,*) ' OVERALL SLA OBS/BIAS : ',KK,ZBIAS

 IF( LL_UNBIAS_SLA ) THEN
  WRITE(IOUNLOG,*) ' THE BIAS IS REMOVED'
  CYOBS2 : DO K=1,SLA%NO

    IF( SLA%FLC(K) .EQ. 1 ) THEN
      SLA%RES(K) = SLA%RES(K) - ZBIAS
      SLA%BIA(K) =  SLA%BIA(K) + ZBIAS
    ENDIF

  ENDDO CYOBS2
  ZZ_SLA_BIAS = ZBIAS
 ELSE
  WRITE(IOUNLOG,*) ' THE BIAS IS NOT REMOVED'
  ZZ_SLA_BIAS = 0._R8
 ENDIF

 CALL FLUSH(IOUNLOG)

END SUBROUTINE UNBIAS_SLA
