SUBROUTINE VER_HORF_AD

!-----------------------------------------------------------------------
!                                                                      !
! APPLY VERTICAL EOFS AND HORIZONTAL FILTER - ADJOINT                  !
!                                                                      !
! VERSION 1: S.DOBRICIC 2006                                           !
! VERSION 2: S.DOBRICIC 2007                                           !
!     SYMMETRIC CALCULATION IN PRESENCE OF COASTAL BOUNDARIES          !
!     ETA, TEM, AND SAL ARE HERE TEMPORARY ARRAYS                      !
!-----------------------------------------------------------------------


 USE SET_KND
 USE GRD_STR
 USE EOF_STR
 USE DRV_STR
 USE CTL_STR
 USE RECFILTER
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE DEBUGTMP
 USE LBCLNK

 IMPLICIT NONE

 INTEGER(I4)    :: K, NTOTV2
 CHARACTER(LEN=20) :: CFILE

 CALL MYFRTPROF_WALL('VER_HORF_AD: ADJ OF CONTROL TO PHYSICAL SPACE',0)

    DT_CSTRIN='START VER_HORF_AD' ; IF( LL_DEBUGTMP ) CALL CALLDT

 IF( LL_NOSRF_RF ) THEN
    NTOTV2 = 2*GRD%KM*COUNT( (/LL_TS,LL_UV/) )
 ELSE
    NTOTV2 = NTOTV
 ENDIF

! ---
! SCALE FOR BOUNDARIES
   PSVF_AD = PSVF_AD * FCT

   DT_CSTRIN='AFTER RESCALING AD' ; IF( LL_DEBUGTMP ) CALL CALLDT

 IF(DRV%MASK(DRV%KTR) .GT. 1) THEN

! ---
! LOAD TEMPORARY ARRAYS
    PSVF = PSVF_AD

! ---
! X DIRECTION
    CALL RCFLF_X( GRD%IM, GRD%JM, NTOTV2, PSVF )
    IF( LL_LBCLNK ) CALL LBC_LNK( PSVF )

   DT_CSTRIN='AFTER RCFL_X' ; IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! SCALE BY THE SCALING FACTOR
    PSVF= PSVF*SCXNSF
    DT_CSTRIN='AFTER X SCAL' ; IF( LL_DEBUGTMP ) CALL CALLDT


! ---
! Y DIRECTION
    CALL RCFLF_Y( GRD%IM,GRD%JM,NTOTV2,PSVF )
    DT_CSTRIN='AFTER RCFL_Y' ; IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! SCALE BY THE SCALING FACTOR
    PSVF = PSVF * SCYNSF
    DT_CSTRIN='AFTER Y SCAL' ; IF( LL_DEBUGTMP ) CALL CALLDT

 ENDIF

! ---
! SCALE BY THE SCALING FACTOR
    PSVF_AD = PSVF_AD * SCYNSF
    DT_CSTRIN='AFTER Y SCALE' ; IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! Y DIRECTION
    CALL RCFLF_Y_AD( GRD%IM,GRD%JM,NTOTV2,PSVF_AD )
    DT_CSTRIN='AFTER RCFL_Y_AD';IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! SCALE BY THE SCALING FACTOR
    PSVF_AD = PSVF_AD*SCXNSF
    DT_CSTRIN='AFTER X SCALE';IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! X DIRECTION
    IF( LL_LBCLNK ) CALL LBC_LNK( PSVF_AD )
    CALL RCFLF_X_AD(GRD%IM,GRD%JM,NTOTV2 ,PSVF_AD )
    DT_CSTRIN='AFTER RCFL_Y_AD';IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! AVERAGE
 IF(DRV%MASK(DRV%KTR) .GT. 1) THEN
    PSVF_AD = (PSVF_AD + PSVF) * 0.5_R8
 ENDIF

    DT_CSTRIN='AFTER AVERAGE';IF( LL_DEBUGTMP ) CALL CALLDT

! ---
! VERTICAL EOFS
    CALL VEOFF_AD

    DT_CSTRIN='AFTER VEOF_AD'; IF( LL_DEBUGTMP ) CALL CALLDT

 CALL MYFRTPROF_WALL('VER_HORF_AD: ADJ OF CONTROL TO PHYSICAL SPACE',1)
END SUBROUTINE VER_HORF_AD
