SUBROUTINE WRANINC(IM,JM,KM,LON,LAT,DEP,SAL,TEM,LLTS,LLS,LL2,LLI,&
& SSH,T2M,Q2M,SIC,SIT,ICU,ICV)
USE SET_KND
USE NETCDF
USE MPIREL
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: IM, JM, KM
REAL(R8), INTENT(IN) :: LON(IM,JM),LAT(IM,JM),DEP(KM)
REAL(R8), INTENT(IN) :: SAL(IM,JM,KM),TEM(IM,JM,KM)
LOGICAL, INTENT(IN) :: LLTS,LLS,LL2,LLI
REAL(R8), INTENT(IN), OPTIONAL :: SSH(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: T2M(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: Q2M(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: SIC(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: SIT(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: ICU(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: ICV(IM,JM)
INTEGER(I4) :: NCID,DIMIDS1(1),DIMIDS2(2),DIMIDS3(3)
INTEGER(I4) :: VARID(12),X_DIMID,Y_DIMID,Z_DIMID

LOGICAL :: LL_SSH, LL_TQ2, LL_ICE,LL_TS
  LL_TS = LLTS
  LL_SSH = LLS
  LL_TQ2 = LL2
  LL_ICE = LLI
  WRITE(*,*) 'LL_SSH : ',LL_SSH
  WRITE(*,*) 'LL_TQ2 : ',LL_TQ2

  IF( LL_SSH .AND. .NOT. PRESENT(SSH) ) CALL ABOR1('LL_SSH BUT NO SSH FIELD')
  IF( LL_TQ2 .AND. (.NOT. PRESENT(T2M) .OR. .NOT. PRESENT(Q2M) ) ) &
  & CALL ABOR1('LL_TQ2 BUT NO 2M FIELDS')
  IF( LL_ICE .AND. (.NOT. PRESENT(SIC) .OR. .NOT. PRESENT(SIT) ) ) &
  & CALL ABOR1('LL_ICE BUT NO 2M FIELDS')

  IF(LMPION) THEN
     CALL CHECK( NF90_CREATE('ANINCR.NC'//'.'//TRIM(CMPIDOM), NF90_CLOBBER, NCID) )
  ELSE
     CALL CHECK( NF90_CREATE('ANINCR.NC', NF90_CLOBBER, NCID) )
  ENDIF
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS3=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  DIMIDS2=  (/X_DIMID, Y_DIMID /)
  DIMIDS1=  (/Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lon',NF90_REAL, DIMIDS2, VARID(1)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lat',NF90_REAL, DIMIDS2, VARID(2)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'deptht',NF90_REAL, DIMIDS1, VARID(3)) )
  IF( LL_TS ) THEN
    CALL CHECK( NF90_DEF_VAR(NCID, 'INCSALINE',NF90_REAL, DIMIDS3, VARID(4)) )
    CALL CHECK( NF90_DEF_VAR(NCID, 'INCTEMPER',NF90_REAL, DIMIDS3, VARID(5)) )
  ENDIF
  IF( LL_SSH ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCSSHEIG',NF90_REAL, DIMIDS2, VARID(6)) )
  IF( LL_TQ2 ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCATTAML',NF90_REAL, DIMIDS2, VARID(7)) )
  IF( LL_TQ2 ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCATQAML',NF90_REAL, DIMIDS2, VARID(8)) )
  IF( LL_ICE ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCLEADFR',NF90_REAL, DIMIDS2, VARID(9)) )
  IF( LL_ICE ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCICETHI',NF90_REAL, DIMIDS2, VARID(10)) )
  !IF( LL_ICE ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCICVELU',NF90_REAL, DIMIDS2, VARID(11)) )
  !IF( LL_ICE ) CALL CHECK( NF90_DEF_VAR(NCID, 'INCICVELV',NF90_REAL, DIMIDS2, VARID(12)) )

  CALL CHECK( NF90_PUT_ATT(NCID, VARID(1), 'units','degrees_east') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(2), 'units','degrees_north') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(3), 'units','m') )
  IF( LL_TS ) THEN
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'units','psu') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'units','degc') )
  ENDIF
  IF( LL_SSH ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(6), 'units','m') )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(7), 'units','K') )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(8), 'units','Kg/Kg') )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(9), 'units','0-1') )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(10),'units','m') )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(11),'units','m/s') )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(12),'units','m/s') )

  CALL CHECK( NF90_PUT_ATT(NCID, VARID(1), 'longname','Longitude') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(2), 'longname','Latitude') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(3), 'longname','Depth') )
  IF( LL_TS ) THEN
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'longname','Salinity Increment') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'longname','Temperature Increment') )
  ENDIF
  IF( LL_SSH ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(6), 'longname','Sea level Increment') )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(7), 'longname','Air temperature at 2m') )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(8), 'longname','Specific humidity at 2m') )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(9), 'longname','Sea-ice concentration') )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(10),'longname','Sea-ice thickness') )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(11),'longname','Sea-ice u-velocity') )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(12),'longname','Sea-ice v-velocity') )
  IF( LL_TS ) THEN
        CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'missing_value',1.E+20_R8) )
        CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'missing_value',1.E+20_R8) )
  ENDIF
  IF( LL_SSH ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(6), 'missing_value',1.E+20_R8) )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(7), 'missing_value',1.E+20_R8) )
  IF( LL_TQ2 ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(8), 'missing_value',1.E+20_R8) )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(9), 'missing_value',1.E+20_R8) )
  IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(10),'missing_value',1.E+20_R8) )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(11),'missing_value',1.E+20_R8) )
  !IF( LL_ICE ) CALL CHECK( NF90_PUT_ATT(NCID, VARID(12),'missing_value',1.E+20_R8) )
  CALL CHECK( NF90_PUT_ATT(NCID, NF90_GLOBAL, 'Product',&
  & 'Global OceanVar Variational Analysis') )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(1), LON) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(2), LAT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(3), DEP) )
  IF( LL_TS ) THEN
        CALL CHECK( NF90_PUT_VAR(NCID, VARID(4), SAL) )
        CALL CHECK( NF90_PUT_VAR(NCID, VARID(5), TEM) )
  ENDIF
  IF( LL_SSH ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(6), SSH) )
  IF( LL_TQ2 ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(7), T2M) )
  IF( LL_TQ2 ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(8), Q2M) )
  IF( LL_ICE ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(9), SIC) )
  IF( LL_ICE ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(10),SIT) )
  !IF( LL_ICE ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(11),ICU) )
  !IF( LL_ICE ) CALL CHECK(NF90_PUT_VAR(NCID, VARID(12),ICV) )
  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE WRANINC
