SUBROUTINE WRANINCAD(IM,JM,KM,KT,LON,LAT,DEP,SAL,TEM)
USE SET_KND
USE NETCDF
USE MPIREL
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: IM, JM, KM, KT
REAL(R8), INTENT(IN) :: LON(IM,JM),LAT(IM,JM),DEP(KM)
REAL(R8), INTENT(IN) :: SAL(IM,JM,KM),TEM(IM,JM,KM)
INTEGER(I4) :: NCID,DIMIDS1(1),DIMIDS2(2),DIMIDS3(3)
INTEGER(I4) :: VARID(5),X_DIMID,Y_DIMID,Z_DIMID
CHARACTER(LEN=6) :: CKT

WRITE(CKT,'(I6.6)') KT

  IF(LMPION) THEN
     CALL CHECK( NF90_CREATE('ANINAD_'//CKT//'.NC'//'.'//TRIM(CMPIDOM), NF90_CLOBBER, NCID) )
  ELSE
     CALL CHECK( NF90_CREATE('ANINAD_'//CKT//'.NC', NF90_CLOBBER, NCID) )
  ENDIF
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS3=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  DIMIDS2=  (/X_DIMID, Y_DIMID /)
  DIMIDS1=  (/Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lon',NF90_REAL, DIMIDS2, VARID(1)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lat',NF90_REAL, DIMIDS2, VARID(2)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'deptht',NF90_REAL, DIMIDS1, VARID(3)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'INCSALINE',NF90_REAL, DIMIDS3, VARID(4)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'INCTEMPER',NF90_REAL, DIMIDS3, VARID(5)) )

  CALL CHECK( NF90_PUT_ATT(NCID, VARID(1), 'units','degrees_east') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(2), 'units','degrees_north') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(3), 'units','m') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'units','psu') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'units','degc') )

  CALL CHECK( NF90_PUT_ATT(NCID, VARID(1), 'longname','Longitude') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(2), 'longname','Latitude') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(3), 'longname','Depth') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'longname','Salinity Increment') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'longname','Temperature Increment') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(4), 'missing_value',1.E+20_R8) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID(5), 'missing_value',1.E+20_R8) )
  CALL CHECK( NF90_PUT_ATT(NCID, NF90_GLOBAL, 'Product',&
  & 'Global OceanVar Variational Analysis') )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(1), LON) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(2), LAT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(3), DEP) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(4), SAL) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(5), TEM) )
  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE WRANINCAD
