SUBROUTINE WRITENCOBSS(NO,NPI,OOTY,OOPA,OINS,OLON,OLAT,OTIME,&
     & ODEP,OVAL,OERR,ORES,OBIA,OI,OJ,OK,OB,EV,TD,BAC)
USE SET_KND
USE NETCDF
USE MPIREL
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: NO,NPI
INTEGER(I4), INTENT(IN), DIMENSION(NO) :: OOTY,OOPA,OINS,OK,EV
INTEGER(I4), INTENT(IN), DIMENSION(NO,NPI) :: OI,OJ
REAL(R8), INTENT(IN), DIMENSION(NO) :: OLON,OLAT,OTIME,&
     & ODEP,OVAL,OERR,ORES,OBIA,OB,TD,BAC
INTEGER(I4) :: NCID,DIMIDS1(1),DIMIDS2(2)
INTEGER(I4) :: VARID(19),X_DIMID, P_DIMID

  IF( LMPION ) THEN
     CALL CHECK( NF90_CREATE('OBSSTAT_SCREEN.NC'//'.'//TRIM(CMPIDOM), &
     & NF90_64BIT_OFFSET, NCID) )
  ELSE
     CALL CHECK( NF90_CREATE('OBSSTAT_SCREEN.NC', NF90_64BIT_OFFSET, NCID) )
  ENDIF
  CALL CHECK( NF90_DEF_DIM(NCID, 'OBS', NO, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'NPQ', NPI, P_DIMID) )
  DIMIDS1=  (/X_DIMID /)
  DIMIDS2=  (/X_DIMID, P_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, 'LON',NF90_REAL, DIMIDS1, VARID(1)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'LAT',NF90_REAL, DIMIDS1, VARID(2)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'TIME',NF90_DOUBLE, DIMIDS1, VARID(3)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'DEPTH',NF90_REAL, DIMIDS1, VARID(4)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'VALUE',NF90_REAL, DIMIDS1, VARID(5)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'ERROR',NF90_REAL, DIMIDS1, VARID(6)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'OMG',NF90_REAL, DIMIDS1, VARID(7)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'TYPE',NF90_INT, DIMIDS1, VARID(9)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'PARAM',NF90_INT, DIMIDS1, VARID(10)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'INST',NF90_INT, DIMIDS1, VARID(11)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BIAS',NF90_REAL, DIMIDS1, VARID(12)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'IB',NF90_INT, DIMIDS2, VARID(13)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'JB',NF90_INT, DIMIDS2, VARID(14)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'KB',NF90_INT, DIMIDS1, VARID(15)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BGERR',NF90_REAL, DIMIDS1, VARID(16)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'EVE',NF90_INT, DIMIDS1, VARID(17)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'TDIST',NF90_DOUBLE, DIMIDS1, VARID(18)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BAC',NF90_REAL, DIMIDS1, VARID(19)) )
  CALL CHECK( NF90_PUT_ATT(NCID, NF90_GLOBAL, 'Product',&
  & 'Global OceanVar Variational Analysis') )

  CALL CHECK( NF90_ENDDEF(NCID) )

  CALL CHECK( NF90_PUT_VAR(NCID, VARID(1), OLON) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(2), OLAT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(3), OTIME) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(4), ODEP) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(5), OVAL) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(6), OERR) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(7), ORES) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(12), OBIA) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(16), OB) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(9), OOTY) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(10), OOPA) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(11), OINS) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(13), OI) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(14), OJ) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(15), OK) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(17), EV) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(18), TD) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(19), BAC) )
  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE WRITENCOBSS
