SUBROUTINE WRITECORR2D(CVARNAME,F3D,LOP,LCL,NCID)

USE GRD_STR
USE SET_KND
USE RUN

USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CVARNAME
LOGICAL,INTENT(IN) :: LOP,LCL
INTEGER(I4),INTENT(INOUT)   :: NCID
INTEGER(I4)                    :: STAT,IDVAR,K
REAL(R8),INTENT(IN)  ::  F3D(GRD%IM,GRD%JM)
REAL(R8)  ::  F3D2(GRD%IM,GRD%JM)

INTEGER(I4) :: X,Y,Z

    WHERE(ABS(F3D) > 1.+10_R8)
      F3D2 = 1.E+20_R8
    ELSEWHERE
      F3D2 = F3D
    ENDWHERE

   IF(LOP) THEN
    STAT = NF90_OPEN('OPA_ANALYSIS.NC', NF90_WRITE, NCID)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
   ENDIF

      STAT = NF90_INQ_DIMID (NCID, 'x', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
      STAT = NF90_INQUIRE_DIMENSION (NCID, IDVAR, LEN = X)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
      STAT = NF90_INQ_DIMID (NCID, 'y', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
      STAT = NF90_INQUIRE_DIMENSION (NCID, IDVAR, LEN = Y)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
      STAT = NF90_INQ_DIMID (NCID, 'z', IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
      STAT = NF90_INQUIRE_DIMENSION (NCID, IDVAR, LEN = Z)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

    IF(X.NE.GRD%IM .OR. Y.NE.GRD%JM .OR. Z .NE. GRD%KM) THEN
       WRITE(IOUNERR,*) ' DIMENSION MISMATCH BETWEEN GRID AND FIRST GUESS:'
       WRITE(IOUNERR,*) ' ON X :',X, GRD%IM,' ON Y :', Y,GRD%JM
       WRITE(IOUNERR,*) ' ON Z :',Z, GRD%KM
       CALL ABOR1('FIRST GUESS DIMENSION MISMATCH')
    ENDIF

     STAT = NF90_INQ_VARID (NCID, CVARNAME, IDVAR)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

      STAT = NF90_PUT_VAR (NCID,IDVAR,F3D)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

   IF(LCL) THEN
    STAT = NF90_CLOSE(NCID)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
   ENDIF

RETURN
END SUBROUTINE WRITECORR2D
