SUBROUTINE WRITENCOBS(NO,NPI,KM,NF,OOTY,OOPA,OINS,OLON,OLAT,OTIME,&
     & ODEP,OVAL,OERR,ORES,OOMA,OBIA,OI,OJ,OK,OB,OP,OT,OS,NOF,INCR,PERT,BAC)
USE SET_KND
USE NETCDF
USE MPIREL
USE RUN
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: NO,NPI,KM,NF
INTEGER(I4), INTENT(IN), DIMENSION(NO) :: OOTY,OOPA,OINS,OK
INTEGER(I4), INTENT(IN), DIMENSION(NO,NPI) :: OI,OJ
REAL(DP), INTENT(IN), DIMENSION(NO) :: OTIME
REAL(R8), INTENT(IN), DIMENSION(NO) :: OLON,OLAT,&
     & ODEP,OVAL,OERR,ORES,OOMA,OBIA,OB,INCR,PERT,BAC
REAL(R8), INTENT(IN), DIMENSION(NO,NPI*2) :: OP
REAL(R8), INTENT(IN), DIMENSION(NO,KM ) :: OT, OS
INTEGER(I4), INTENT(IN), DIMENSION(NF) :: NOF

INTEGER(I4) :: NCID,DIMIDS1(1),DIMIDS2(2)
INTEGER(I4) :: DIMIDS2B(2)
INTEGER(I4) :: DIMIDS2C(2)
INTEGER(I4) :: VARID(23),X_DIMID, P_DIMID, P2_DIMID, K_DIMID, T_DIMID

  IF( LMPION ) THEN
     CALL CHECK( NF90_CREATE('OBSSTAT.NC'//'.'//TRIM(CMPIDOM), &
     & NF90_64BIT_OFFSET, NCID) )
  ELSE
     CALL CHECK( NF90_CREATE('OBSSTAT.NC', NF90_64BIT_OFFSET, NCID) )
  ENDIF
  CALL CHECK( NF90_DEF_DIM(NCID, 'OBS', NO, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'NPQ', NPI, P_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'NPQ2', NPI*2, P2_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'KM', KM , K_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'TYPES', NF , T_DIMID) )
  DIMIDS1=  (/X_DIMID /)
  DIMIDS2=  (/X_DIMID, P_DIMID /)
  DIMIDS2B=  (/X_DIMID, P2_DIMID /)
  DIMIDS2C=  (/X_DIMID, K_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, 'NOBS',NF90_INT, (/T_DIMID/) , VARID(20)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'LON',NF90_REAL, DIMIDS1, VARID(1)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'LAT',NF90_REAL, DIMIDS1, VARID(2)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'TIME',NF90_REAL, DIMIDS1, VARID(3)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'DEPTH',NF90_REAL, DIMIDS1, VARID(4)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'VALUE',NF90_REAL, DIMIDS1, VARID(5)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'ERROR',NF90_REAL, DIMIDS1, VARID(6)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'OMG',NF90_REAL, DIMIDS1, VARID(7)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'OMA',NF90_REAL, DIMIDS1, VARID(8)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'TYPE',NF90_INT, DIMIDS1, VARID(9)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'PARAM',NF90_INT, DIMIDS1, VARID(10)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'INST',NF90_INT, DIMIDS1, VARID(11)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BIAS',NF90_REAL, DIMIDS1, VARID(12)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'IB',NF90_INT, DIMIDS2, VARID(13)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'JB',NF90_INT, DIMIDS2, VARID(14)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'KB',NF90_INT, DIMIDS1, VARID(15)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BGERR',NF90_REAL, DIMIDS1, VARID(16)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'PQ',NF90_REAL, DIMIDS2B, VARID(17)) )
  IF( NCONF .NE. 202 .AND. LL_OBSS_TSP) THEN
    CALL CHECK( NF90_DEF_VAR(NCID, 'TB',NF90_REAL, DIMIDS2C, VARID(18)) )
    CALL CHECK( NF90_DEF_VAR(NCID, 'SB',NF90_REAL, DIMIDS2C, VARID(19)) )
  ENDIF
  CALL CHECK( NF90_DEF_VAR(NCID, 'INC',NF90_REAL, DIMIDS1, VARID(21)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'PERT',NF90_REAL, DIMIDS1, VARID(22)) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'BAC',NF90_REAL, DIMIDS1, VARID(23)) )
  CALL CHECK( NF90_PUT_ATT(NCID, NF90_GLOBAL, 'Product',&
  & 'Global OceanVar Variational Analysis') )

  CALL CHECK( NF90_ENDDEF(NCID) )

  CALL CHECK( NF90_PUT_VAR(NCID, VARID(1), OLON) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(2), OLAT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(3), OTIME) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(4), ODEP) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(5), OVAL) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(6), OERR) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(7), ORES) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(8), OOMA) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(12), OBIA) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(16), OB) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(9), OOTY) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(10), OOPA) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(11), OINS) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(13), OI) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(14), OJ) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(15), OK) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(17), OP) )
  IF( NCONF .NE. 202 .AND. LL_OBSS_TSP ) THEN
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(18), OT) )
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(19), OS) )
  ENDIF
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(20), NOF) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(21), INCR) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(22), PERT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID(23), BAC) )
  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE WRITENCOBS
