SUBROUTINE WRMDT(IM,JM,LON,LAT,MDT,ANI,ERR,ZMV,ZAVE,ZFACT)

USE SET_KND
USE NETCDF

IMPLICIT NONE

INTEGER, INTENT(IN) :: IM, JM
REAL(R8), INTENT(IN) :: LON(IM,JM)
REAL(R8), INTENT(IN) :: LAT(IM,JM)
REAL(R8), INTENT(IN) :: MDT(IM,JM)
REAL(R8), INTENT(IN) :: ANI(IM,JM)
REAL(R8), INTENT(IN) :: ERR(IM,JM)
REAL(R8), INTENT(IN) :: ZMV,ZAVE,ZFACT
INTEGER :: NCID,DIMIDS1(2),VAR1,X_DIMID,Y_DIMID,VAR2,VAR3,VARO,VARA

  CALL CHECK( NF90_CREATE('ANA_MDT.nc', NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lon', NF90_REAL, DIMIDS1, VARO) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARO, 'units','degrees_east') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARO, 'long_name','longitude') )
  CALL CHECK( NF90_DEF_VAR(NCID, 'nav_lat', NF90_REAL, DIMIDS1, VARA) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARA, 'units','degrees_north') )
  CALL CHECK( NF90_PUT_ATT(NCID, VARA, 'long_name','latitude') )
  CALL CHECK( NF90_DEF_VAR(NCID, 'mdt', NF90_REAL, DIMIDS1, VAR1) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR1, 'units','m') )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR1, 'missing_value',ZMV) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR1, 'long_name','Analysed MDT') )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR1, 'subtracted_spatial_average',ZAVE) )
  CALL CHECK( NF90_DEF_VAR(NCID, 'mdt_ai', NF90_REAL, DIMIDS1, VAR2) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR2, 'units','m') )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR2, 'missing_value',ZMV) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR2, 'long_name','MDT Analysis increments') )
  CALL CHECK( NF90_DEF_VAR(NCID, 'mdt_err', NF90_REAL, DIMIDS1, VAR3) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR3, 'units','m') )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR3, 'missing_value',ZMV) )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR3, 'long_name','MDT Error') )
  CALL CHECK( NF90_PUT_ATT(NCID, VAR3, 'reduction_factor',ZFACT) )
  CALL CHECK( NF90_PUT_ATT(NCID, NF90_GLOBAL, 'Production','Variational analysis') )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARO, LON) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARA, LAT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VAR1, MDT) )
  CALL CHECK( NF90_PUT_VAR(NCID, VAR2, ANI) )
  CALL CHECK( NF90_PUT_VAR(NCID, VAR3, ERR) )
  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE WRMDT
