SUBROUTINE READ_NCEOF_NOSLA(CFIN,NX,NY,NR,NX2,NY2,NZ,NEOF,EIVAL,EIVEC,NREG,LLSQ)
USE SET_KND
USE GRD_STR
USE NETCDF
IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CFIN
INTEGER(KIND=I4), INTENT(IN) :: NX,NY,NR,NX2,NY2,NZ,NEOF
REAL(KIND=R8), INTENT(OUT) :: EIVAL(NR,NEOF),EIVEC(NR,NZ,NEOF)
INTEGER(KIND=I4), INTENT(OUT) :: NREG(NX2,NY2)
INTEGER(KIND=I4) :: NC, VARID
LOGICAL :: LLSQ

EIVAL(:,:)=0._R8
EIVEC(:,:,:)=0._R8
CALL CHECK( NF90_OPEN(CFIN, NF90_NOWRITE, NC ) )

CALL CHECK( NF90_INQ_VARID(NC,'eigenvectors',VARID ) )
CALL CHECK( NF90_GET_VAR(NC,VARID,EIVEC,START=(/1,1,1/),COUNT=(/NR,NZ-1,NEOF/)) )
CALL CHECK( NF90_INQ_VARID(NC,'eigenvalues',VARID ) )
CALL CHECK( NF90_GET_VAR(NC,VARID,EIVAL) )

CALL CHECK( NF90_INQ_VARID(NC,'nreg',VARID ) )
IF( NX2 .EQ. GRD%IM .AND. NY2 .EQ. GRD%JM ) THEN
    CALL CHECK( NF90_GET_VAR(NC,VARID,NREG,&
    & START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/)) )
ELSE
    CALL CHECK( NF90_GET_VAR(NC,VARID,NREG) )
ENDIF

CALL CHECK( NF90_CLOSE( NC ) )

IF(LLSQ) THEN
     EIVAL=SQRT(EIVAL)
ENDIF

END SUBROUTINE READ_NCEOF_NOSLA
