SUBROUTINE UNBIAS_SLA_LAT

!.. SLA LAT-DEPENDENT BIAS

USE SET_KND
!USE OBSDEF
USE OBS_STR
!USE MYNETCDF
USE IOUNITS
!USE OBSHANDLING
!USE MYFRTPROF
USE MPIREL
USE RUN

IMPLICIT NONE

REAL(R8), ALLOCATABLE :: ZSLABIAS(:)
REAL(R8), ALLOCATABLE :: MEANN(:),SUMDEN(:)

INTEGER(I4) :: K,STAT,DIV,MAXX
INTEGER(I4) :: INTOT,ILATST,IINCR,JLAT
INTEGER(I4) :: KINTLAT,IAUX

!#include "grids.h"



IF(LL_UNBIAS_SLA_LAT) THEN

 WRITE(IOUNLOG,*) 'LATITUDINAL UNBIAS'

! OPEN(381,FILE='sla_bias_lat.dat',STATUS='OLD',IOSTAT=STAT)
!  IF(STAT.NE.0) CALL ABOR1('UNBIAS SLA: CANNOT OPEN sla_bias_lat.dat')
!  READ(381,*,IOSTAT=STAT) ILATST,IINCR,INTOT
!  IF(STAT.NE.0) CALL ABOR1('UNBIAS SLA: CANNOT OPEN sla_bias_lat.dat')
!  ALLOCATE(ZSLABIAS(INTOT))
!  DO JLAT=1,INTOT
!     READ(381,*,IOSTAT=STAT) IAUX, ZSLABIAS(JLAT)
!     IF(STAT.NE.0) CALL ABOR1('UNBIAS SLA: CANNOT OPEN sla_bias_lat.dat')
!  ENDDO
!  CLOSE(381)

DIV=5
MAXX=NINT(180./REAL(DIV))+1
ALLOCATE(MEANN(MAXX))
ALLOCATE(SUMDEN(MAXX))
MEANN=0._R8
SUMDEN=0._R8
DO K=1,SLA%NO
        IF(SLA%FLC(K).EQ.0 ) CYCLE 
        KINTLAT= NINT((SLA%LAT(K)-(-90.))/REAL(DIV)) +1
        MEANN(KINTLAT)=MEANN(KINTLAT)+SLA%RES(K)
        SUMDEN(KINTLAT)=SUMDEN(KINTLAT)+1
ENDDO
WHERE(SUMDEN .GE. 1) MEANN=MEANN/SUMDEN
WHERE(SUMDEN .LT. 20) MEANN=0.
CYOBS : DO K=1,SLA%NO
IF(SLA%FLC(K).EQ.0 ) CYCLE CYOBS
    KINTLAT= NINT((SLA%LAT(K)-(-90.))/REAL(DIV)) +1
    SLA%RES(K)=SLA%RES(K) - MEANN(KINTLAT)
    SLA%BIA(K)=SLA%BIA(K)+MEANN(KINTLAT)
ENDDO CYOBS    

!CYOBS : DO K=1,SLA%NO
!    KINTLAT=NINT( (SLA%LAT(K)-REAL(ILATST))/REAL(IINCR) )+1
!    IF(KINTLAT.LT.1.OR.KINTLAT.GT.INTOT) THEN
!      WRITE(IOUNERR,*) 'LATITUDE=',SLA%LAT(K),',  KINTLAT=',KINTLAT
!      WRITE(IOUNERR,*) 'UNSUPPORTED SLA BIAS VALUES'
!      CALL ABOR1('UNBIAS SLA: BIAS SLA UNDETERMINED')
!    ENDIF
!   ! WRITE(IOUNLOG,*) 'SLA RES ',SLA%RES(K)
!    SLA%RES(K)=SLA%RES(K) - ZSLABIAS(KINTLAT)
!   ! WRITE(IOUNLOG,*) 'SLA RES LATER',SLA%RES(K)
!    SLA%BIA(K)=SLA%BIA(K)+ZSLABIAS(KINTLAT)
!ENDDO CYOBS

IF (ALLOCATED(ZSLABIAS)) DEALLOCATE(ZSLABIAS)
IF (ALLOCATED(MEANN)) DEALLOCATE(MEANN)
IF (ALLOCATED(SUMDEN)) DEALLOCATE(SUMDEN)

ENDIF

END SUBROUTINE UNBIAS_SLA_LAT
