SUBROUTINE ABOR1(CDTEXT) ! A.S. DUMMY ABORT ALLOWS INLINING
IMPLICIT NONE
INTEGER, PARAMETER :: IOUNOUT = 6
INTEGER, PARAMETER :: IOUNLOG = IOUNOUT
CHARACTER(LEN=*), INTENT(IN) :: CDTEXT
WRITE(IOUNOUT,'(1X,A)') CDTEXT
CALL FLUSH(IOUNLOG)
CALL FLUSH(IOUNOUT)
CALL ABORT
END SUBROUTINE ABOR1
