SUBROUTINE HANDLE_ERR(ERRCODE)
  USE NETCDF
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: ERRCODE

  IF(ERRCODE /= NF90_NOERR) THEN
     PRINT *, 'ERROR: ', TRIM(NF90_STRERROR(ERRCODE))
     CALL ABOR1('ABORT CALLED BY NETCDF ERROR HANDLING ROUTINE')
  ENDIF

END SUBROUTINE HANDLE_ERR
