MODULE READFG

!... MODULE READFG - NEW MANAGEMENT OF FIRST-GUESS FILES

!... READ FIRST GUESS FIELDS, HANDLING THE CASE
!... OF MULTIPLE FILES (MULTI-PROCS OPA) AND
!... SHARED-MEMORY CONFIGURATION.

!... WITH ANY 3D-VAR PROCESSOR CONFIGURATION (I.E. SINGLE OR MULTI-THREADED)
!... THIS MODULE ALLOWS THE READING OF OPA FILES, EITHER IN CASE
!... OF ONE BIG FILE OR IN CASE OF SUB-DOMAIN FILES

!... ANDREA.STORTO *INGV*, 2009-08-26

USE SET_KND

IMPLICIT NONE

SAVE
PUBLIC

INTEGER(I4), PARAMETER :: MAXFILES=999
INTEGER(I4) :: NFGFILES
INTEGER(I4) :: NFGTSTEPS
CHARACTER(LEN=60) :: CFGFILES(MAXFILES)
LOGICAL,PARAMETER :: LLAYOUTFILE=.TRUE.
LOGICAL :: LLMPF=.FALSE.
INTEGER(I4), DIMENSION(MAXFILES,2) :: KDPF,KDPL,KDHSS,KDHSE,KDSL,KDNS,KDNE,KDLS,KDLE
INTEGER(I4), DIMENSION(MAXFILES) :: NCIDFG
LOGICAL    , DIMENSION(MAXFILES) :: LOPFG,LCLFG

!================================================================

END MODULE READFG
