MODULE MYNETCDF

USE SET_KND, ONLY : R8, I4
USE NETCDF

IMPLICIT NONE
PRIVATE

PUBLIC :: WRITE_VARNCDF, GETNCVAR, GETNCDIM

INTERFACE WRITE_VARNCDF
  MODULE PROCEDURE WRITE_VARNCDF_R1D, WRITE_VARNCDF_R2D, WRITE_VARNCDF_R3D, &
  &                WRITE_VARNCDF_I1D, WRITE_VARNCDF_I2D, WRITE_VARNCDF_I3D
END INTERFACE WRITE_VARNCDF

INTERFACE GETNCVAR
  MODULE PROCEDURE GETNCVAR2,GETNCVAR3,GETNCVAI1,GETNCVAI2,GETNCVAR1,GETNCVAI3
END INTERFACE GETNCVAR

CONTAINS

SUBROUTINE WRITE_VARNCDF_R1D(CFILE,IM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM
REAL(R8), INTENT(IN) :: VAR(IM)
INTEGER(I4) :: NCID,DIMIDS1,VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  DIMIDS1= X_DIMID
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R1D

SUBROUTINE WRITE_VARNCDF_R2D(CFILE,IM,JM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM
REAL(R8), INTENT(IN) :: VAR(IM,JM)
INTEGER(I4) :: NCID,DIMIDS1(2),VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R2D

SUBROUTINE WRITE_VARNCDF_R3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM, KM
REAL(R8), INTENT(IN) :: VAR(IM,JM,KM)
INTEGER(I4) :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,Z_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R3D

SUBROUTINE WRITE_VARNCDF_I1D(CFILE,IM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM
INTEGER(I4), INTENT(IN) :: VAR(IM)
INTEGER(I4) :: NCID,DIMIDS1,VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  DIMIDS1= X_DIMID
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I1D

SUBROUTINE WRITE_VARNCDF_I2D(CFILE,IM,JM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM
INTEGER(I4), INTENT(IN) :: VAR(IM,JM)
INTEGER(I4) :: NCID,DIMIDS1(2),VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I2D

SUBROUTINE WRITE_VARNCDF_I3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM, KM
INTEGER(I4), INTENT(IN) :: VAR(IM,JM,KM)
INTEGER(I4) :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,Z_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I3D

SUBROUTINE GETNCDIM(CF,CD,ND)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CD
  INTEGER(I4), INTENT(OUT) :: ND
  INTEGER(I4) :: NCID, DID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_DIMID(NCID,CD,DID) )
  CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DID,LEN=ND) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCDIM

SUBROUTINE GETNCVAI1(CF,CV,JPI,VV)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI
  INTEGER(I4), DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI1

SUBROUTINE GETNCVAI2(CF,CV,JPI,JPJ,VV)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ
  INTEGER(I4), DIMENSION(JPI,JPJ), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI2

SUBROUTINE GETNCVAR1(CF,CV,JPI,VV)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI
  REAL(R8), DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR1

SUBROUTINE GETNCVAR2(CF,CV,JPI,JPJ,VV)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ
  REAL(R8), DIMENSION(JPI,JPJ), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR2

SUBROUTINE GETNCVAI3(CF,CV,JPI,JPJ,JPK,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK
  INTEGER(I4), DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI3

SUBROUTINE GETNCVAR3(CF,CV,JPI,JPJ,JPK,VV)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK
  REAL(R8), DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR3

END MODULE MYNETCDF
