MODULE ALLOCOBS2

USE SET_KND
USE OBS_STR, ONLY : INS_T, SLA_T, SST_T, SSS_T, NPQ, NPRD_SLA, NPRD_SST, NPRD_SSS

IMPLICIT NONE

CONTAINS

SUBROUTINE ALLOCINS2(NIN,LINIT,INB)

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NIN
LOGICAL    , INTENT(IN) :: LINIT
TYPE(INS_T) :: INB

  WRITE(IOUNLOG,*) ' ** ALLOCATING INSITU OBS VECTOR **'
  WRITE(IOUNLOG,*) '    NUMBER OF OBS IS  ',NIN
  WRITE(IOUNLOG,*) '    INITIALIZATION IS ',LINIT

  ALLOCATE(INB%INO(NIN),INB%FLG(NIN),INB%FLC(NIN),INB%PAR(NIN))
  ALLOCATE(INB%LON(NIN),INB%LAT(NIN),INB%DPT(NIN),INB%TIM(NIN))
  ALLOCATE(INB%VAL(NIN),INB%BAC(NIN),INB%INC(NIN),INB%TDIST(NIN))
  ALLOCATE(INB%BIA(NIN),INB%ERR(NIN),INB%EVE(NIN),INB%KTY(NIN))
  ALLOCATE(INB%RES(NIN),INB%B_A(NIN),INB%OTYPE(NIN),INB%PROF(NIN),INB%PRIND(NIN))
  ALLOCATE(INB%IB(NIN,NPQ),INB%JB(NIN,NPQ),INB%KB(NIN),INB%PLNO(NIN),INB%DSRC(NIN))
  ALLOCATE(INB%RB(NIN),INB%BGERR(NIN))
  ALLOCATE(INB%PQ(NIN,2*NPQ))
  ALLOCATE(INB%INST(NIN))
  ALLOCATE(INB%NIND(NIN))

  IF(LINIT) THEN
    INB%FLG(:)=1
    INB%FLC(:)=0
    INB%EVE(:)=0
    INB%BIA(:)=0._R8
    INB%ERR(:)=100._R8
  ENDIF

END SUBROUTINE ALLOCINS2

SUBROUTINE ALLOCSLA2(NIN,LINIT,SLB)

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NIN
LOGICAL    , INTENT(IN) :: LINIT
TYPE(SLA_T) :: SLB

  ALLOCATE(SLB%LON(NIN),&
        &SLB%INO(NIN),&
        &SLB%NIND(NIN),&
        &SLB%LAT(NIN),&
        &SLB%VAL(NIN),&
        &SLB%TDIST(NIN),&
        &SLB%FLG(NIN),&
        &SLB%FLC(NIN),&
        &SLB%KSAT(NIN),&
        &SLB%EVE(NIN),&
        &SLB%BOT(NIN),&
        &SLB%INC(NIN),&
        &SLB%BAC(NIN),&
        &SLB%BIA(NIN),&
        &SLB%ERR(NIN),&
        &SLB%RES(NIN),&
        &SLB%B_A(NIN),&
        &SLB%IB (NIN,NPQ),&
        &SLB%JB (NIN,NPQ),&
        &SLB%PQ (NIN,NPQ),&
        &SLB%TRACK(NIN),&
        &SLB%BGERR(NIN),&
        &SLB%DPT(NIN),&
        &SLB%TB(NIN,KM),&
        &SLB%SB(NIN,KM),&
        &SLB%BCP(NIN,NPRD_SLA),&
        &SLB%TIM(NIN))

  IF(LINIT) THEN
    SLB%FLG(:) = 1
    SLB%FLC(:) = 0
    SLB%EVE(:) = 0
    SLB%BIA(:) = 0._R8
    SLB%ERR(:)=100._R8
  ENDIF

END SUBROUTINE ALLOCSLA2

SUBROUTINE ALLOCSST2(NIN,LINIT,SSTB)

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NIN
LOGICAL    , INTENT(IN) :: LINIT
TYPE(SST_T) :: SSTB

ALLOCATE(SSTB%LON(NIN),&
        &SSTB%LAT(NIN),&
        &SSTB%NIND(NIN),&
        &SSTB%VAL(NIN),&
        &SSTB%TDIST(NIN),&
        &SSTB%FLG(NIN),&
        &SSTB%FLC(NIN),&
        &SSTB%KSAT(NIN),&
        &SSTB%EVE(NIN),&
        &SSTB%INC(NIN),&
        &SSTB%BAC(NIN),&
        &SSTB%BIA(NIN),&
        &SSTB%ERR(NIN),&
        &SSTB%RES(NIN),&
        &SSTB%B_A(NIN),&
        &SSTB%IB (NIN,NPQ),&
        &SSTB%JB (NIN,NPQ),&
        &SSTB%PQ (NIN,NPQ),&
        &SSTB%TRACK(NIN),&
        &SSTB%BGERR(NIN),&
        &SSTB%BCP(NIN,NPRD_SST),&
        &SSTB%TIM(NIN))

IF(LINIT) THEN
   SSTB%FLG(:) = 1
   SSTB%FLC(:) = 0
   SSTB%EVE(:) = 0
   SSTB%BIA(:) = 0._R8
   SSTB%ERR(:) = 100._R8
ENDIF

END SUBROUTINE ALLOCSST2

SUBROUTINE ALLOCSSS2(NIN,LINIT,SSSB)

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NIN
LOGICAL    , INTENT(IN) :: LINIT
TYPE(SSS_T) :: SSSB

ALLOCATE(SSSB%LON(NIN),&
        &SSSB%LAT(NIN),&
        &SSSB%NIND(NIN),&
        &SSSB%VAL(NIN),&
        &SSSB%TDIST(NIN),&
        &SSSB%FLG(NIN),&
        &SSSB%FLC(NIN),&
        &SSSB%KSAT(NIN),&
        &SSSB%EVE(NIN),&
        &SSSB%INC(NIN),&
        &SSSB%BAC(NIN),&
        &SSSB%BIA(NIN),&
        &SSSB%ERR(NIN),&
        &SSSB%RES(NIN),&
        &SSSB%B_A(NIN),&
        &SSSB%IB (NIN,NPQ),&
        &SSSB%JB (NIN,NPQ),&
        &SSSB%PQ (NIN,NPQ),&
        &SSSB%TRACK(NIN),&
        &SSSB%BGERR(NIN),&
        &SSSB%BCP(NIN,NPRD_SSS),&
        &SSSB%TIM(NIN))

IF(LINIT) THEN
   SSSB%FLG(:) = 1
   SSSB%FLC(:) = 0
   SSSB%EVE(:) = 0
   SSSB%BIA(:) = 0._R8
   SSSB%ERR(:) = 100._R8
ENDIF

END SUBROUTINE ALLOCSSS2

END MODULE ALLOCOBS2
