SUBROUTINE SETFGFILES(NTF)

USE SET_KND
USE READFG

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NTF
INTEGER(I4) :: JF

IF(NTF.GT.MAXFILES) THEN
   WRITE(IOUNERR,*) &
   & 'MOD_READFG: NUMBER OF FIRST GUESS FILES EXCEEDS MAXIMUM ALLOWED'
   WRITE(IOUNERR,*) 'MAX ALLOWED =',MAXFILES,',  ACTUAL NO =',NTF
   CALL ABOR1('MOD_READFG: TOO MANY FG FILES')
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// SETUP FIRST-GUESS FILENAMES'

IF(NTF.LE.0) THEN
   NFGFILES=1
   CFGFILES(1) = 'OPA_FIRSTGUESS.nc'
ELSE
   NFGFILES=NTF
   DO JF=1,NFGFILES
      WRITE(CFGFILES(JF),'(A,I4.4,A)') 'OPA_FIRSTGUESS_',JF-1,'.nc'
   ENDDO
ENDIF

LLMPF = (NFGFILES.GT.1)

WRITE(IOUNLOG,*) ' NUMBER OF FG FILES:',NFGFILES
WRITE(IOUNLOG,*) ' MULTI-PROC FILES  :',LLMPF
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' -------- NAMES OF FG FILES --------'
DO JF=1,NFGFILES
   WRITE(IOUNLOG,*) JF,' '//TRIM(CFGFILES(JF))
ENDDO
WRITE(IOUNLOG,*)

CALL FLUSH(IOUNLOG)
END SUBROUTINE SETFGFILES
