#!/bin/ksh

#.. Collection of useful Korn functions
#.. especially intended for better handling of time
function splitdate {
	mess0="splitdate expects 1 YYYYMMDDHH argument"
        [[ $# -eq 1 ]] || \
	{ echo $mess0 ; exit 5 ; }
	arg=$1
        [[ ${#arg} -eq 10 ]] || \
	{ echo $mess0 ; exit 5 ; }
        lyyyy=`echo $arg | cut -c 1-4`
	lmm=`echo $arg | cut -c 5-6`
	ldd=`echo $arg | cut -c 7-8`
	lhh=`echo $arg | cut -c 9-10`
	lymd=${lyyyy}${lmm}${ldd}
        echo $lyyyy
        echo $lmm
        echo $ldd
        echo $lhh
        echo $lymd
        return
}

function whichseason {
        mess0="whichseason expects 1 MM argument"
        [[ $# -eq 1 ]] || \
	{ echo $mess0 ; exit 5 ; }
	arg=$1
        [[ ${#arg} -eq 2 ]] || \
	{ echo $mess0 ; exit 5 ; }
        mess1="whichseason cannot determine season for MM=$arg"
	case $arg in
        	01|02|03)  seas="win" ;;
        	04|05|06)  seas="spr" ;;
        	07|08|09)  seas="sum" ;;
        	10|11|12)  seas="aut" ;;
        	*)  echo $mess1 ; exit 3 ;;
	esac
	echo $seas
}

function whichseason2 {
        mess0="whichseason expects 1 MM argument"
        [[ $# -eq 1 ]] || \
        { echo $mess0 ; exit 5 ; }
        arg=$1
        [[ ${#arg} -eq 2 ]] || \
        { echo $mess0 ; exit 5 ; }
        mess1="whichseason cannot determine season for MM=$arg"
        case $arg in
                01|02|03|04|11|12)  seas="win" ;;
                05|06|07|08|09|10)  seas="sum" ;;
                *)  echo $mess1 ; exit 3 ;;
        esac
        echo $seas
}


