SUBROUTINE ASSIGN_SSSERR

!.. OBS ERRORS ASSIGNEMENT FOR SPACE-BORNE SSS OBS
!..
!.. ANDREA STORTO, 2009


USE SET_KND
USE OBSDEF
USE OBS_STR, ONLY : SSS
USE OBSHANDLING, ONLY : SSS_ERRS
USE MYFRTPROF

IMPLICIT NONE

INTEGER(I4) :: JK,ISAT
REAL(R8) :: ZLAT
REAL(R8) :: ZA, ZB ,ZC

CALL MYFRTPROF_WALL('ASSIGN_SSSERR: ASSIGN SSS OBS ERROR',0)

!... FOR SSS, CYCLE THE OBS

!... FIT OF 2ND ORDER POLYNOMIAL
!    TO AQUARIUS ERROR AS TB/PSU SENSITIVITY:
!    -- COEFFICIENTS --
ZA = 0.0002146429_R8
ZB = -0.0048428592_R8
ZC = 0.3894196575_R8

CYOBS : DO JK=1,SSS%NO

     ZLAT = ABS(SSS%LAT(JK))
     IF(SSS%FLC(JK) .EQ. 0 ) CYCLE CYOBS
     IF(SSS%KSAT(JK) .EQ. 1) THEN ! AQUARIUS
        SSS%ERR(JK) = SSS_ERRS(1) + ZA*ZLAT*ZLAT + ZB*ZLAT + ZC
     ELSEIF(SSS%KSAT(JK) .EQ. 3) THEN ! AQUARIUS
        SSS%ERR(JK) = 2.338E-01_R8 + ZLAT*3.171E-03_R8 + ZLAT*ZLAT*1.627E-04_R8
     ELSE
        SSS%ERR(JK) = SSS_ERRS(SSS%KSAT(JK))
     ENDIF

ENDDO CYOBS

CALL MYFRTPROF_WALL('ASSIGN_SSSERR: ASSIGN SSS OBS ERROR',1)
END SUBROUTINE ASSIGN_SSSERR
