SUBROUTINE BGPERT

!
! PERTURBATION OF BACKGROUND
!
! AS2017
!

 USE SET_KND
 USE DRV_STR
 USE GRD_STR
 USE EOF_STR
 USE CTL_STR
 USE RUN
 USE IOUNITS, ONLY : IOUNERR, IOUNLOG, IOUNOUT
 USE RANDOM_NUMBERS
 USE OBSHANDLING, ONLY : NSEED
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE TLAD_VARS
 USE TLAD

IMPLICIT NONE

INTEGER(I4)    ::  KSEED
TYPE(RANDOMNUMBERSTREAM) :: GOLUM
REAL(R8), ALLOCATABLE :: ZXR(:)
INTEGER(I4)    :: I

#include "wraninc.h"

CALL MYFRTPROF_WALL('BGPERT: BACKGROUND PERTURBATION',0)

WRITE(IOUNOUT,*) ' /// PERTURBING BACKGROUND'
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// PERTURBING BACKGROUND'
WRITE(IOUNLOG,*) ' /// SEED FOR RANDGEN :',NSEED
WRITE(IOUNLOG,*)

KSEED=NSEED
ALLOCATE(ZXR(CTL%N))
CALL INITIALIZE_RANDOM_NUMBERS(KSEED,GOLUM)
CALL GAUSSIAN_DISTRIBUTION(ZXR,GOLUM)

DO I=1,CTL%N
    CTL%X_C(I) = ZXR(I)
ENDDO
DEALLOCATE(ZXR)

CALL CNV_CTV

CALL VER_HOR

IF ( LL_WEAKLY ) CALL CTRL2ERR_TL(1)

IF ( LL_4DVAR .OR. LL_TLMODEL ) CALL TLMOD(1)

 IF(.NOT.LL_ICE) THEN

 IF( LL_SSH .AND. .NOT. LL_TQ2) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.TRUE.,.FALSE.,.FALSE.,SSH=GRD%ETA)
 ELSEIF( LL_TQ2 .AND. .NOT. LL_SSH ) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.FALSE.,.TRUE.,.FALSE.,T2M=GRD%T2M,Q2M=GRD%Q2M)
 ELSEIF( LL_TQ2 .AND. LL_SSH ) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.TRUE.,.TRUE.,.FALSE.,SSH=GRD%ETA,T2M=GRD%T2M,Q2M=GRD%Q2M)
 ELSE
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.FALSE.,.FALSE.,.FALSE.)
 ENDIF

 ELSE

 IF( LL_SSH .AND. .NOT. LL_TQ2) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.TRUE.,.FALSE.,.TRUE.,SSH=GRD%ETA,SIC=GRD%SIC,SIT=GRD%SIT,&
  & ICU=GRD%ICU, ICV=GRD%ICV)
 ELSEIF( LL_TQ2 .AND. .NOT. LL_SSH ) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.FALSE.,.TRUE.,.TRUE.,&
  & T2M=GRD%T2M,Q2M=GRD%Q2M,SIC=GRD%SIC,SIT=GRD%SIT,&
  & ICU=GRD%ICU, ICV=GRD%ICV)
 ELSEIF( LL_TQ2 .AND. LL_SSH ) THEN
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.TRUE.,.TRUE.,.TRUE.,SSH=GRD%ETA,&
  & T2M=GRD%T2M,Q2M=GRD%Q2M,SIC=GRD%SIC,SIT=GRD%SIT,&
  & ICU=GRD%ICU, ICV=GRD%ICV)
 ELSE
  CALL WRANINC(GRD%IM,GRD%JM,GRD%KM,GRD%LON,GRD%LAT,GRD%DEP,&
  & GRD%SAL,GRD%TEM,.FALSE.,.FALSE.,.TRUE.,SIC=GRD%SIC,SIT=GRD%SIT,&
  & ICU=GRD%ICU, ICV=GRD%ICV)
 ENDIF

 ENDIF

CALL MYFRTPROF_WALL('BGPERT: BACKGROUND PERTURBATION',1)

END SUBROUTINE BGPERT
