SUBROUTINE BIASCORR
!
! REJECTIONS CRITERIA FOR SSS OBSERVATIONS
!
USE SET_KND
USE OBS_STR
USE GRD_STR
USE IOUNITS
USE MYNETCDF
USE MPIREL
USE RUN, ONLY : IANMM, LL_SSS_BCORR
!
IMPLICIT NONE

INTEGER(I4),PARAMETER :: NZ=36, NPR=7
INTEGER(I4),PARAMETER :: NPR2=2*NPR+1
INTEGER(I4) :: JO, IRD, MM, KOK
REAL   (R8) :: XBP(NPR), SSS_BCC(NZ,NPR2)
REAL(R8), ALLOCATABLE :: SSTC(:,:,:)

#include "obs_events.h"

IF( SSS%NO .EQ. 0 .OR. .NOT. LL_SSS_BCORR ) RETURN

ALLOCATE( SSTC(GRD%IM,GRD%JM,12) )
CALL GETNCVAR('SSTC.nc','sst',GRD%IM,GRD%JM,12,SSTC)
MM=IANMM

!WRITE(1230+MYPROC,*),'XXX',GRD%IM,GRD%JM,MINVAL(SSS%IB(1:SSS%NO,:)),MAXVAL(SSS%IB(1:SSS%NO,:)),&
!MINVAL(SSS%JB(1:SSS%NO,:)),MAXVAL(SSS%JB(1:SSS%NO,:)),MYPROC

OPEN(1239,FILE='sss_bcc.dat')
DO JO=1,NZ
 READ(1239,*) SSS_BCC(JO,1:NPR2)
ENDDO
CLOSE(1239)

KOK=0
CYOBS : DO JO=1,SSS%NO
  IF(SSS%FLC(JO) .NE. 1 ) CYCLE CYOBS
  KOK=KOK+1
  IRD=INT( (SSS%LAT(JO)+90._R8) / 5._R8 ) + 1
  XBP(1) = SSS%BCP(JO,4)
  XBP(2) = SSS%BCP(JO,5)
  XBP(3) = SSS%BCP(JO,6)
  XBP(4) = SSS%BCP(JO,7)
  XBP(5) = SSS%BCP(JO,4) - (SSS%BCP(JO,1)-273.15_R8)
  XBP(6) = SSS%BCP(JO,5) - SSS%BCP(JO,3)
  XBP(7) = (SSS%BCP(JO,1)-273.15_R8) - OSUM(SSS%PQ(JO,1:4) ,&
  & SSTC(SSS%IB(JO,:),SSS%JB(JO,:),MM) )
  SSS%BIA(JO) = SSS_BCC(IRD,1) + SUM( XBP(1:7)*SSS_BCC(IRD,2:8) ) + &
  & + SUM( XBP(1:7)*XBP(1:7)*SSS_BCC(IRD,9:15) )
  ! CHECK
  IF ( .NOT. ABS( SSS%BIA(JO) ) .LT. 3._R8 ) THEN
     SSS%FLC(JO) = 0
     SSS%EVE(JO) = KEVE_SBCR
  ELSE
     SSS%RES(JO) = SSS%RES(JO) - SSS%BIA(JO)
  ENDIF
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(A2,2I4,3F11.6,I3,2F10.3)') '*',JO,IRD,SSS%BIA(JO),SSS%LAT(JO),SSS%LON(JO),MM,SSS%TIM(JO),OSUM(SSS%PQ(JO,1:4) , SSTC(SSS%IB(JO,:),SSS%JB(JO,:),MM) )
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(I4,8I5)') JO,SSS%IB(JO,:),SSS%JB(JO,:)
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(I4,4F12.6)') JO,SSTC(SSS%IB(JO,1),SSS%JB(JO,1),MM),&
!SSTC(SSS%IB(JO,2),SSS%JB(JO,2),MM),&
!SSTC(SSS%IB(JO,3),SSS%JB(JO,3),MM),&
!SSTC(SSS%IB(JO,4),SSS%JB(JO,4),MM)
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(I4,7F12.6)') JO,XBP
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(I4,15F12.6)') JO,SSS_BCC(IRD,1:15)
!  IF( KOK .LT. 10 ) WRITE(1230+MYPROC,'(I4,7F12.6)') JO,SSS%BCP(JO,1:7)
END DO CYOBS

DEALLOCATE( SSTC )

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' BIASCORR : SPECIFIC REJECTIONS OF SSS BIASCORR DATA '
WRITE(IOUNLOG,*) ' TOTAL OBS     =', SSS%NO
WRITE(IOUNLOG,*) ' OBS PRED REJ   =', COUNT(SSS%EVE(1:SSS%NO).EQ.KEVE_SBCR)
WRITE(IOUNLOG,*) ' GOOD OBS       =', COUNT(SSS%FLC(1:SSS%NO).EQ.1)

END SUBROUTINE BIASCORR
