SUBROUTINE BMD_TEST

USE SET_KND
USE GRD_STR
USE IOUNITS
USE ADTEST
USE BAL

IMPLICIT NONE

   INTEGER(I4) :: JI,JJ,JK,KK
   REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: GAT0,GAS0,GAT,GAS
   REAL(R8), ALLOCATABLE, DIMENSION(:    ) :: ZV1,ZV2,ZV3,ZV4
   REAL(R8) :: ZT1, ZT2
   INTEGER(I4) :: I,J,K
   I=902
   J=139
   K=1

   CALL INIT_RND
   
   WRITE(IOUNLOG,*) 'A',BAL_TEMB(I,J,K),BAL_SALB(I,J,K)

   ALLOCATE(GAT (GRD%IM,GRD%JM,GRD%KM))
   ALLOCATE(GAS (GRD%IM,GRD%JM,GRD%KM))
   ALLOCATE(GAT0(GRD%IM,GRD%JM,GRD%KM))
   ALLOCATE(GAS0(GRD%IM,GRD%JM,GRD%KM))

   CALL SRANDOM_FLD(GRD%TEM)
   CALL SRANDOM_FLD(GRD%SAL)
   GAT0 = GRD%TEM
   GAS0 = GRD%SAL
   WRITE(IOUNLOG,*) 'B',GAT0(I,J,K),GAS0(I,J,K)
   ALLOCATE( ZV1(GRD%IM*GRD%JM*GRD%KM*2) )
   ALLOCATE( ZV2(GRD%IM*GRD%JM*GRD%KM*2) )
   ALLOCATE( ZV3(GRD%IM*GRD%JM*GRD%KM  ) )
   ALLOCATE( ZV4(GRD%IM*GRD%JM*GRD%KM  ) )
   CALL DENS_TL
   GAT = GRD%DNS
   WRITE(IOUNLOG,*) 'C',GAT(I,J,K)
   GRD%DNS = 0._R8
   CALL SRANDOM_FLD(GRD%DNS)
   WRITE(IOUNLOG,*) 'D',GRD%DNS(I,J,K)
   GRD%TEM_AD = 0._R8
   GRD%SAL_AD = 0._R8
   CALL DENS_AD
   WRITE(IOUNLOG,*) 'E',GRD%TEM_AD(I,J,K),GRD%SAL_AD(I,J,K)
   KK=0
   DO JK=1,GRD%KM
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV1(KK) = GAT0(JI,JJ,JK)
         ZV2(KK) = GRD%TEM_AD(JI,JJ,JK)
         ZV3(KK) = GAT(JI,JJ,JK)
         ZV4(KK) = GRD%DNS(JI,JJ,JK)
       ENDDO
     ENDDO
   ENDDO
   DO JK=1,GRD%KM
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV1(KK) = GAS0(JI,JJ,JK)
         ZV2(KK) = GRD%SAL_AD(JI,JJ,JK)
       ENDDO
     ENDDO
   ENDDO
   ZT1 = DOT_PRODUCT(ZV3,ZV4)
   ZT2 = DOT_PRODUCT(ZV1,ZV2)
   WRITE(IOUNLOG,*) ' ADJOINT TEST FOR DENSITY'
   WRITE(IOUNLOG,*) ' FIRST  TERM = ',ZT1
   WRITE(IOUNLOG,*) ' SECOND TERM = ',ZT2
   WRITE(IOUNLOG,*) ' DIFFERENCE  = ',ZT1-ZT2
   WRITE(IOUNLOG,*) ' MACHINE EPS = ',EPSILON(ZT1)
   WRITE(IOUNLOG,*) ' REL. ERROR  = ',100._R8*ABS((ZT1-ZT2)/ZT1)
   WRITE(IOUNLOG,*) ' RESULT      = ',TEST_RES(ABS(ZT1-ZT2),EPSILON(ZT1))
   WRITE(IOUNLOG,*)
   WRITE(IOUNLOG,*)

   DEALLOCATE(ZV1,ZV2,ZV3,ZV4)

   CALL SRANDOM_FLD(GRD%TEM)
   CALL SRANDOM_FLD(GRD%SAL)
   GAT0 = GRD%TEM
   GAS0 = GRD%SAL
   WRITE(IOUNLOG,*) 'B',GAT0(I,J,K),GAS0(I,J,K)
   ALLOCATE( ZV1(GRD%IM*GRD%JM*GRD%KM*2) )
   ALLOCATE( ZV2(GRD%IM*GRD%JM*GRD%KM*2) )
   ALLOCATE( ZV3(GRD%IM*GRD%JM*2       ) )
   ALLOCATE( ZV4(GRD%IM*GRD%JM*2       ) )
   CALL GET_BYG
   GAT(:,:,1) = GRD%BX
   GAT(:,:,2) = GRD%BY
   WRITE(IOUNLOG,*) 'C',GAT(I,J,K)
   CALL SRANDOM_FLD(GRD%DNS)
   GRD%BX = GRD%DNS(:,:,1)
   GRD%BY = GRD%DNS(:,:,2)
   WRITE(IOUNLOG,*) 'D',GRD%DNS(I,J,K)
   GRD%TEM_AD = 0._R8
   GRD%SAL_AD = 0._R8
   GRD%B_X    = 0._R8
   GRD%B_Y    = 0._R8
   CALL GET_BYG_AD
   WRITE(IOUNLOG,*) 'E',GRD%TEM_AD(I,J,K),GRD%SAL_AD(I,J,K)
   KK=0
   DO JK=1,GRD%KM
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV1(KK) = GAT0(JI,JJ,JK)
         ZV2(KK) = GRD%TEM_AD(JI,JJ,JK)
       ENDDO
     ENDDO
   ENDDO
   DO JK=1,GRD%KM
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV1(KK) = GAS0(JI,JJ,JK)
         ZV2(KK) = GRD%SAL_AD(JI,JJ,JK)
       ENDDO
     ENDDO
   ENDDO
   KK=0
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV3(KK) = GAT(JI,JJ,1)
         ZV4(KK) = GRD%DNS(JI,JJ,1)
       ENDDO
     ENDDO
     DO JJ=1,GRD%JM
       DO JI=1,GRD%IM
         KK=KK+1
         ZV3(KK) = GAT(JI,JJ,2)
         ZV4(KK) = GRD%DNS(JI,JJ,2)
       ENDDO
     ENDDO
   ZT1 = DOT_PRODUCT(ZV3,ZV4)
   ZT2 = DOT_PRODUCT(ZV1,ZV2)
   WRITE(IOUNLOG,*) ' ADJOINT TEST FOR BUOYANCY'
   WRITE(IOUNLOG,*) ' FIRST  TERM = ',ZT1
   WRITE(IOUNLOG,*) ' SECOND TERM = ',ZT2
   WRITE(IOUNLOG,*) ' DIFFERENCE  = ',ZT1-ZT2
   WRITE(IOUNLOG,*) ' MACHINE EPS = ',EPSILON(ZT1)
   WRITE(IOUNLOG,*) ' REL. ERROR  = ',100._R8*ABS((ZT1-ZT2)/ZT1)
   WRITE(IOUNLOG,*) ' RESULT      = ',TEST_RES(ABS(ZT1-ZT2),EPSILON(ZT1))
   WRITE(IOUNLOG,*)
   WRITE(IOUNLOG,*)

   DEALLOCATE(ZV1,ZV2,ZV3,ZV4,GAT0,GAS0,GAT,GAS)

CONTAINS

SUBROUTINE SRANDOM_FLD(ZZ)
   INTEGER(I4) :: JI,JJ,JK,KK
   REAL(R8) :: ZZT(GRD%IM*GRD%JM*GRD%KM)
   REAL(R8), INTENT(OUT) :: ZZ(GRD%IM,GRD%JM,GRD%KM)
   CALL RANDOM_NUMBER (ZZT)
   KK=0
   DO JK=1,GRD%KM
   DO JJ=1,GRD%JM
   DO JI=1,GRD%IM
    KK=KK+1
    ZZ(JI,JJ,JK) = (ZZT(KK)-0.5_R8)*3._R8
   ENDDO
   ENDDO
   ENDDO
END SUBROUTINE SRANDOM_FLD

END SUBROUTINE BMD_TEST
