SUBROUTINE CHECK_TIME

USE SET_KND
USE OBS_STR
USE IOUNITS
USE RUN

IMPLICIT NONE

INTEGER(I4) :: JOBS,KC(4)
REAL(DP)    :: MAXTDIST

#include "obs_events.h"

KC=0

MAXTDIST=REAL(IANTW,KIND=R8)/24._DP
IF ( LL_TWCENTERED ) MAXTDIST = MAXTDIST/2._DP

IF(INS%NO.GT.0) THEN
 DO JOBS=1,INS%NO
   IF(ABS(INS%TDIST(JOBS)).GT.MAXTDIST) THEN
      INS%FLC(JOBS)=0
      INS%EVE(JOBS)=KEVE_TDST
      KC(1)=KC(1)+1
   ENDIF
 ENDDO
ENDIF

IF(SLA%NO.GT.0) THEN
 DO JOBS=1,SLA%NO
   IF(ABS(SLA%TDIST(JOBS)).GT.MAXTDIST) THEN
      SLA%FLC(JOBS)=0
      SLA%EVE(JOBS)=KEVE_TDST
      KC(2)=KC(2)+1
   ENDIF
 ENDDO
ENDIF

IF(SST%NO.GT.0) THEN
 DO JOBS=1,SST%NO
   IF(ABS(SST%TDIST(JOBS)).GT.MAXTDIST) THEN
      SST%FLC(JOBS)=0
      SST%EVE(JOBS)=KEVE_TDST
      KC(3)=KC(3)+1
   ENDIF
 ENDDO
ENDIF

IF(SSS%NO.GT.0) THEN
 DO JOBS=1,SSS%NO
   IF(ABS(SSS%TDIST(JOBS)).GT.MAXTDIST) THEN
      SSS%FLC(JOBS)=0
      SSS%EVE(JOBS)=KEVE_TDST
      KC(4)=KC(4)+1
   ENDIF
 ENDDO
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) '*** NUMBER OF OBS OUT OF TIME WINDOW'
WRITE(IOUNLOG,*) 
WRITE(IOUNLOG,*) ' LIMIT IN DAYS :',MAXTDIST
WRITE(IOUNLOG,*) 
WRITE(IOUNLOG,*) ' INSITU :',KC(1)
WRITE(IOUNLOG,*) ' SLA    :',KC(2)
WRITE(IOUNLOG,*) ' SST    :',KC(3)
WRITE(IOUNLOG,*) ' SSS    :',KC(4)
WRITE(IOUNLOG,*) '____________________________________'
WRITE(IOUNLOG,*)

END SUBROUTINE CHECK_TIME
