  SUBROUTINE CHECK(STATUS)
    USE NETCDF
    IMPLICIT NONE
    INTEGER, INTENT ( IN) :: STATUS
    IF(STATUS /= NF90_NOERR) THEN
      PRINT *, TRIM(NF90_STRERROR(STATUS))
      CALL ABOR1('NETCDF LIBRARY ERROR')
    END IF
  END SUBROUTINE CHECK
