SUBROUTINE CORREL( NT, ZO, ZM, ZCO)
USE SET_KND
IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NT
REAL(R8), INTENT(IN), DIMENSION(NT) :: ZO,ZM
REAL(R8), INTENT(OUT) :: ZCO

REAL(R8) :: ZOB, ZMB

ZOB=SUM( ZO ) / REAL(NT)
ZMB=SUM( ZM ) / REAL(NT)

ZCO = SUM( (ZO-ZOB)*(ZM-ZMB) ) / &
    & SQRT( SUM( (ZO-ZOB)*(ZO-ZOB) )*SUM( (ZM-ZMB)*(ZM-ZMB) ) )

END SUBROUTINE CORREL
