SUBROUTINE DEALLBG

USE GRD_STR
USE MYFRTPROF
USE READFG

IMPLICIT NONE

 CALL MYFRTPROF_WALL('DEALLBG: DEALLOCATE BG FIELDS',0)

 DEALLOCATE( GRD%TEMB ) 
 DEALLOCATE( GRD%SALB ) 
 DEALLOCATE( GRD%ETAB ) 
 DEALLOCATE( LL_FGASSIM )
 IF(ALLOCATED(GRD%T2MB) ) DEALLOCATE(GRD%T2MB,GRD%Q2MB)

 CALL MYFRTPROF_WALL('DEALLBG: DEALLOCATE BG FIELDS',1)

END SUBROUTINE DEALLBG
