MODULE DEFPREC
!-
! $ID: DEF.PREC 20 2007-03-19 15:54:59Z MAFOIPSL $
!!--------------------------------------------------------------------
!! THE MODULE "DEFPREC" SET DEFAULT PRECISION FOR COMPUTATION
!!
!! THIS MODULE SHOULD BE USED BY EVERY MODULES
!! TO KEEP THE RIGHT PRECISION FOR EVERY VARIABLE
!!--------------------------------------------------------------------
!?INTEGERS OF KIND 1 ARE NOT SUPPORTED ON ALL COMPUTERS
!?INTEGER,PARAMETER :: I_1=SELECTED_INT_KIND(2)
  INTEGER,PARAMETER :: I_2=SELECTED_INT_KIND(4)
  INTEGER,PARAMETER :: I_4=SELECTED_INT_KIND(9)
  INTEGER,PARAMETER :: I_8=SELECTED_INT_KIND(13)
  INTEGER,PARAMETER :: R_4=SELECTED_REAL_KIND(6,37)
  INTEGER,PARAMETER :: R_8=SELECTED_REAL_KIND(13,300)
  INTEGER,PARAMETER :: I_STD=I_4, R_STD=R_8
!-----------------
END MODULE DEFPREC
