SUBROUTINE DIFFDATE(IDATE1,IDATE2,IRES)
!
! DIFFERENCE BETWEEN TWO DATES IN SECONDS
! A.STORTO -- APRIL_2007
!

USE TIMEFINC

IMPLICIT NONE

INTEGER :: IDATE1(6),DATE1,IDATE2(6),DATE2
INTEGER :: IDAYS,IHOURS,IMINS,ISEC
INTEGER :: IDATETEMP,IDATEARR,ISIGNPN
INTEGER :: IRES
CHARACTER(LEN=10) :: CSTRING

DATE1=IDATE1(3) + IDATE1(2)*100 + IDATE1(1)*10000
DATE2=IDATE2(3) + IDATE2(2)*100 + IDATE2(1)*10000

IF ( DATE1 .GT. DATE2 ) THEN

 ISIGNPN=1
 IDATETEMP=DATE2
 IDATEARR=DATE1

ELSE

 ISIGNPN=-1
 IDATETEMP=DATE1
 IDATEARR=DATE2

END IF

 IDAYS = 0

 DO WHILE (IDATETEMP .LT. IDATEARR )

  CALL PLUSDAY(IDATETEMP)
  IDAYS=IDAYS+1

 END DO

 IHOURS = IDATE1(4) - IDATE2(4)
 IMINS = IDATE1(5) - IDATE2(5)
 ISEC = IDATE1(6) - IDATE2(6)

 IRES = ISEC + IMINS*60 + IHOURS*3600 + (ISIGNPN*IDAYS*3600*24)

END

