SUBROUTINE DIFFTIMER(COPT,CDATE1,CDATE2,IDIFFER,IRETC,LWRN)

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
CHARACTER,INTENT(IN) :: COPT
CHARACTER(LEN=*),INTENT(INOUT) :: CDATE1,CDATE2
INTEGER(KIND=JPIM),INTENT(OUT) :: IDIFFER,IRETC
INTEGER :: IDIFFERL,IRETCL
LOGICAL,INTENT(IN) :: LWRN

CALL DIFFTIME(COPT,CDATE1,CDATE2,IDIFFERL,IRETCL,LWRN)
IDIFFER=INT(IDIFFERL,KIND=JPIM)
IRETC=INT(IRETCL,KIND=JPIM)
END SUBROUTINE DIFFTIMER
