SUBROUTINE INIT_HUBER

!.. INTERFACE FOR OBSERVATIONAL ERRORS DEFINITION
!..
!.. A.STORTO, 2009

USE SET_KND
USE OBSDEF
USE RUN
USE OBS_STR
USE MYNETCDF
USE IOUNITS
USE MPIREL
USE MYFRTPROF, ONLY : MYFRTPROF_WALL

IMPLICIT NONE

INTEGER(I4) :: KK, JO, KX1, KX2

CALL MYFRTPROF_WALL('INIT_HUBER: INITIALIZE HUBER NORM VARQC',0)

IF( LL_HUBER_ASYMM ) THEN
  IF( LL_HUBERQC_SLA ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sla',NOSLASATS,2,RLIM_HUBERQC_SLA)
  IF( LL_HUBERQC_INS ) CALL GETNCVAR('hubernorm_limits.nc','hnl_ins',NOINSITU,NOPARAMS,2,RLIM_HUBERQC_INS)
  IF( LL_HUBERQC_SST ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sst',NOSSTSATS,2,RLIM_HUBERQC_SST)
  IF( LL_HUBERQC_SSS ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sss',NOSSSSATS,2,RLIM_HUBERQC_SSS)
ELSE
  IF( LL_HUBERQC_SLA ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sla',NOSLASATS,RLIM_HUBERQC_SLA(:,1))
  IF( LL_HUBERQC_INS ) CALL GETNCVAR('hubernorm_limits.nc','hnl_ins',NOINSITU,NOPARAMS,RLIM_HUBERQC_INS(:,:,1))
  IF( LL_HUBERQC_SST ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sst',NOSSTSATS,RLIM_HUBERQC_SST(:,1))
  IF( LL_HUBERQC_SSS ) CALL GETNCVAR('hubernorm_limits.nc','hnl_sss',NOSSSSATS,RLIM_HUBERQC_SSS(:,1))
  RLIM_HUBERQC_SLA(:,2) = RLIM_HUBERQC_SLA(:,1)
  RLIM_HUBERQC_INS(:,:,2) = RLIM_HUBERQC_INS(:,:,1)
  RLIM_HUBERQC_SST(:,2) = RLIM_HUBERQC_SST(:,1)
  RLIM_HUBERQC_SSS(:,2) = RLIM_HUBERQC_SSS(:,1)
ENDIF

IF( LL_HUBER_L05 ) THEN
  IF( LL_HUBER_ASYMM ) THEN
    IF( LL_HUBERQC_SLA ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sla',NOSLASATS,2,RLIM_HUBERQC_SLA2)
    IF( LL_HUBERQC_INS ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_ins',NOINSITU,NOPARAMS,2,RLIM_HUBERQC_INS2)
    IF( LL_HUBERQC_SST ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sst',NOSSTSATS,2,RLIM_HUBERQC_SST2)
    IF( LL_HUBERQC_SSS ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sss',NOSSSSATS,2,RLIM_HUBERQC_SSS2)
  ELSE
    IF( LL_HUBERQC_SLA ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sla',NOSLASATS,RLIM_HUBERQC_SLA2(:,1))
    IF( LL_HUBERQC_INS ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_ins',NOINSITU,NOPARAMS,RLIM_HUBERQC_INS2(:,:,1))
    IF( LL_HUBERQC_SST ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sst',NOSSTSATS,RLIM_HUBERQC_SST2(:,1))
    IF( LL_HUBERQC_SSS ) CALL GETNCVAR('hubernorm_limits.nc','hnl2_sss',NOSSSSATS,RLIM_HUBERQC_SSS2(:,1))
    RLIM_HUBERQC_SLA2(:,2) = RLIM_HUBERQC_SLA2(:,1)
    RLIM_HUBERQC_INS2(:,:,2) = RLIM_HUBERQC_INS2(:,:,1)
    RLIM_HUBERQC_SST2(:,2) = RLIM_HUBERQC_SST2(:,1)
    RLIM_HUBERQC_SSS2(:,2) = RLIM_HUBERQC_SSS2(:,1)
  ENDIF
ELSE
    RLIM_HUBERQC_SLA2 = 9999._R8
    RLIM_HUBERQC_INS2 = 9999._R8
    RLIM_HUBERQC_SST2 = 9999._R8
    RLIM_HUBERQC_SSS2 = 9999._R8
ENDIF

IF(LL_HUBERQC_INS_VERBOSE .AND. LL_HUBERQC_INS) THEN
   DO KX2=1,NOPARAMS
     DO KX1=1,NOINSITU
        WRITE(IOUNLOG,'(A,I3,A,I3,A,2F8.3)') &
        & ' ::: HUB1  LIMITS, PAR ',KX2,' TYPE ',KX1, ' = ',RLIM_HUBERQC_INS(KX1,KX2,1), RLIM_HUBERQC_INS(KX1,KX2,2)
        WRITE(IOUNLOG,'(A,I3,A,I3,A,2F8.3)') &
        & ' ::: HUB05 LIMITS, PAR ',KX2,' TYPE ',KX1, ' = ',RLIM_HUBERQC_INS2(KX1,KX2,1), RLIM_HUBERQC_INS2(KX1,KX2,2)
     ENDDO
   ENDDO
ENDIF

KK=0
OBS%NHUB=0
OBS%AHUB=1.E+6_R8
OBS%AHUB2=1.E+6_R8

IF( LL_HUBERQC_SLA ) THEN
 CALL ABOR1('VARQC NOT IMPLEMENTED FOR SLAS')
!   DO JO=1,SLA%NO
!      KK=KK+1
!      KX1=SLA%KSAT(JO)
!      IF(OBS%AMO(KK).GT.RLIM_HUBERQC_SLA(KX1,1).AND.OBS%AMO(KK).LE.RLIM_HUBERQC_SLA2(KX1,1) )  OBS%NHUB(KK) = 1
!      IF(OBS%AMO(KK).LT.-RLIM_HUBERQC_SLA(KX1,2).AND.OBS%AMO(KK).LE.RLIM_HUBERQC_SLA2(KX1,2) ) OBS%NHUB(KK) = -1
!      IF(OBS%AMO(KK).GT.RLIM_HUBERQC_SLA2(KX1,1) ) OBS%NHUB(KK) = 2
!      IF(OBS%AMO(KK).LT.-RLIM_HUBERQC_SLA2(KX1,2) ) OBS%NHUB(KK) = -2
!      IF(ABS( OBS%AMO(KK) ) .GT. RLIM_HUBERQC_SLA(KX1) ) OBS%AHUB(KK)=RLIM_HUBERQC_SLA(KX1)
!   ENDDO
ELSE
   KK=SLA%NO
   IF( KK .GT. 0 ) THEN
     OBS%AHUB(1:KK,:) = 1.E+6_R8
     OBS%AHUB2(1:KK,:) = 1.E+6_R8
   ENDIF
ENDIF

IF( LL_HUBERQC_INS ) THEN
   IF(LL_HUBERQC_INS_VERBOSE) OPEN(NHUBOUT,FILE='huber_ins_verbose_'//TRIM(CMPIDOM)//'.out')
   DO JO=1,INS%NO
      KK=KK+1
      KX1=INS%KTY(JO)
      KX2=INS%PAR(JO)
      OBS%AHUB(KK,1)=ABS(RLIM_HUBERQC_INS(KX1,KX2,1))
      OBS%AHUB(KK,2)=ABS(RLIM_HUBERQC_INS(KX1,KX2,2))
      OBS%AHUB2(KK,1)=ABS(RLIM_HUBERQC_INS2(KX1,KX2,1))
      OBS%AHUB2(KK,2)=ABS(RLIM_HUBERQC_INS2(KX1,KX2,2))

      IF( LL_HUBERQC_INS_VERBOSE ) &
      WRITE(NHUBOUT,*) '* ',JO,KK,INS%LON(JO), &
      INS%LAT(JO),INS%IB(JO,1),INS%JB(JO,1),INS%VAL(JO),INS%BAC(JO),INS%ERR(JO),INS%INC(JO),INS%RES(JO),&
      OBS%AMO(KK), OBS%AHUB(KK,:), OBS%AHUB2(KK,:)

   ENDDO
   WRITE(IOUNLOG,*) ' NUMBER OF INS INITIALLY HUBER ',&
   & COUNT( INS%RES(1:INS%NO)/INS%ERR(1:INS%NO) .GT.  OBS%AHUB(SLA%NO+1:INS%NO,1) ) + &
   & COUNT( INS%RES(1:INS%NO)/INS%ERR(1:INS%NO) .LT. -OBS%AHUB(SLA%NO+1:INS%NO,2) ), &
   & ' OVER ',INS%NO
ELSE
   KK=KK+INS%NO
ENDIF


IF( LL_HUBERQC_SST ) THEN
 CALL ABOR1('VARQC NOT IMPLEMENTED FOR SSTS')
!   DO JO=1,SST%NO
!      KK=KK+1
!      KX1=SST%KSAT(JO)
!      IF( OBS%AMO(KK) .GT. RLIM_HUBERQC_SST(KX1) )  OBS%NHUB(KK) = 1
!      IF( OBS%AMO(KK) .LT. -RLIM_HUBERQC_SST(KX1) ) OBS%NHUB(KK) = -1
!      IF( ABS( OBS%AMO(KK) ) .GT. RLIM_HUBERQC_SST(KX1) ) OBS%AHUB(KK)=RLIM_HUBERQC_SST(KX1)
!   ENDDO
ELSE
   KK=KK+SST%NO
ENDIF

IF( LL_HUBERQC_SSS ) THEN
 CALL ABOR1('VARQC NOT IMPLEMENTED FOR SSSS')
!   DO JO=1,SSS%NO
!      KK=KK+1
!      KX1=SSS%KSAT(JO)
!      IF( OBS%AMO(KK) .GT. RLIM_HUBERQC_SSS(KX1) )  OBS%NHUB(KK) = 1
!      IF( OBS%AMO(KK) .LT. -RLIM_HUBERQC_SSS(KX1) ) OBS%NHUB(KK) = -1
!      IF( ABS( OBS%AMO(KK) ) .GT. RLIM_HUBERQC_SSS(KX1) ) OBS%AHUB(KK)=RLIM_HUBERQC_SSS(KX1)
!   ENDDO
ELSE
   KK=KK+SSS%NO
ENDIF

WRITE(IOUNLOG,* )
WRITE(IOUNLOG,* ) ' /// REPORT FOR INIT HUBER'
WRITE(IOUNLOG,* )
WRITE(IOUNLOG,* ) ' SLA OBS: TOTAL = ',SLA%NO
WRITE(IOUNLOG,* ) '        HUBERQC = ',LL_HUBERQC_SLA
WRITE(IOUNLOG,* ) ' INS OBS: TOTAL = ',INS%NO
WRITE(IOUNLOG,* ) '        HUBERQC = ',LL_HUBERQC_INS
WRITE(IOUNLOG,* ) ' SST OBS: TOTAL = ',SST%NO
WRITE(IOUNLOG,* ) '        HUBERQC = ',LL_HUBERQC_SST
WRITE(IOUNLOG,* ) ' SSS OBS: TOTAL = ',SSS%NO
WRITE(IOUNLOG,* ) '        HUBERQC = ',LL_HUBERQC_SSS
WRITE(IOUNLOG,* )

WRITE(IOUNLOG,* ) ' ///'
WRITE(IOUNLOG,* )

CALL MYFRTPROF_WALL('INIT_HUBER: INITIALIZE HUBER NORM VARQC',1)
END SUBROUTINE INIT_HUBER
