#undef SHARED_MEMORY
SUBROUTINE INT_PAR_SST_2

!-----------------------------------------------------------------------
!                                                                      !
! GET INTERPOLATION PARAMETERS FOR A GRID                              !
!                                                                      !
! VERSION 1: S.DOBRICIC 2006                                           !
!-----------------------------------------------------------------------

 USE SET_KND
 USE GRD_STR
 USE PHINTERP
 USE PHINTERP2
 USE RUN
 USE OBS_STR
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE IOUNITS

 IMPLICIT NONE

  INTEGER(I4)   ::  K, N_TOPEX, N_ERS, II, JJ,I2
  INTEGER(I4)   ::  I1, J1, KK, I, J, ITER, IAUX, JP
  INTEGER(I4)   ::  MSCOUNT
  REAL(R8)      ::  P1, Q1, P, Q, SUMT, SUMI, TIMP,NEWLON
  REAL(R8)      ::  MSK4, ZZSS

#include "obs_events.h"

 CALL MYFRTPROF_WALL('INT_PAR_SST_2: SST INTERPOLATION',0)

 IF(SST%NO.EQ.0) THEN
   CALL MYFRTPROF_WALL('INT_PAR_SST_2: SST INTERPOLATION',1)
   RETURN
 ENDIF

 SST%IB = 0
 SST%JB = 0

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(PRIVATE), SHARED(SST)
!$OMP DO SCHEDULE(DYNAMIC)
#endif
CYOBS0 : DO KK = 1,SST%NO

      IF( NN_INTERPM .EQ. 1 ) THEN
         CALL PREPINTERP(SST%LON(KK),SST%LAT(KK),SST%IB(KK,:),SST%JB(KK,:),SST%PQ(KK,:))
      ELSEIF ( NN_INTERPM .EQ. 2 ) THEN
         CALL PREPINTERP2(SST%LON(KK),SST%LAT(KK),SST%IB(KK,:),SST%JB(KK,:),SST%PQ(KK,:))
      ENDIF


ENDDO CYOBS0
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(SHARED), PRIVATE(KK,ZZSS,JP,MSK4)
!$OMP DO SCHEDULE(DYNAMIC)
#endif
CYOBS : DO KK = 1,SST%NO
       SST%FLC(KK) = 1

       SST%PQ(KK,1) = SST%PQ(KK,1) * GRD%MSK(SST%IB(KK,1),SST%JB(KK,1),1)
       SST%PQ(KK,2) = SST%PQ(KK,2) * GRD%MSK(SST%IB(KK,2),SST%JB(KK,2),1)
       SST%PQ(KK,3) = SST%PQ(KK,3) * GRD%MSK(SST%IB(KK,3),SST%JB(KK,3),1)
       SST%PQ(KK,4) = SST%PQ(KK,4) * GRD%MSK(SST%IB(KK,4),SST%JB(KK,4),1)

       IF( SUM(SST%PQ(KK,:)) .GT. 0._R8 ) THEN
          SST%PQ(KK,:) = SST%PQ(KK,:) / SUM(SST%PQ(KK,:))
       ELSE
          SST%PQ(KK,:) = 0._R8
       ENDIF

ENDDO CYOBS
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

! ---
! COUNT GOOD OBSERVATIONS
  SST%NC = COUNT(SST%FLC(1:SST%NO) .EQ. 1)

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' *** SST OBS AFTER INTERPOLATION SET-UP'
  WRITE(IOUNLOG,*) ' TOTAL NUMBER OF SST OBS           :',SST%NO
  WRITE(IOUNLOG,*) ' TOTAL NUMBER OF RETAINED SST  OBS :',SST%NC

CALL MYFRTPROF_WALL('INT_PAR_SST_2: SST INTERPOLATION',1)
END SUBROUTINE INT_PAR_SST_2
