SUBROUTINE IO_OBS(CFILE,IOPT,NOBS,NLEVS,NPREDS,NPQ,NPQ2,&
& NIND, INO, OTYPE, PAR, PLNO, INST, EVE, KTY, &
& PRIND, PROF, TDIST, LON, LAT, DPT, TIM, &
& VAL, BIA, IB, JB, KB, RB, PQ, &
& TRACK, KSAT, BOT, FLG, &
& FLC, INC, BAC, ERR, RES, B_A, TB, SB, BCP,BGERR, SD1, SD2, MOI, MOJ )

  USE SET_KND
  USE NETCDF
  IMPLICIT NONE

  INTEGER(I4), INTENT(IN) :: IOPT,NOBS,NLEVS,NPREDS,NPQ,NPQ2
  CHARACTER(LEN=*), INTENT(IN) :: CFILE

  INTEGER(I4), PARAMETER :: MAXVAR = 99
  INTEGER(I4) :: NCID,VARID(MAXVAR),DIMIDS,&
  & DIMIDS8(2),DIMIDS16(2),DIMIDS2(2),DIMIDSBC(2),DIMIDSIJ(2),DIMIDSPQ(2)
  INTEGER(I4) :: X_DIMID, IN, C1_DIMID, C2_DIMID, L_DIMID, B_DIMID, Q_DIMID, Q2_DIMID
  
  REAL(R8), DIMENSION(NOBS),  OPTIONAL :: &
  & LON, LAT, DPT, VAL, BIA, &
  & INC, BAC, ERR, RES, B_A, BGERR, &
  & RB

  REAL(DP), DIMENSION(NOBS),  OPTIONAL :: TDIST, TIM

  REAL(R8), DIMENSION(NOBS,NLEVS),  OPTIONAL :: TB, SB
  REAL(R8), DIMENSION(NOBS,NPREDS),  OPTIONAL :: BCP
  INTEGER(I4), DIMENSION(NOBS),  OPTIONAL :: &
  & NIND, INO, OTYPE, PAR, INST, EVE, KTY, PRIND, PROF, &
  & KB, KSAT, BOT, FLG, FLC, TRACK, SD1, SD2
  INTEGER(I4), DIMENSION(NOBS,NPQ),  OPTIONAL :: IB, JB, MOI, MOJ
  REAL(R8), DIMENSION(NOBS,NPQ2),    OPTIONAL :: PQ
  CHARACTER(LEN=8), DIMENSION(NOBS),  OPTIONAL :: &
  & PLNO

  INTEGER(I4) :: DIMID,NDIMC

  IF(IOPT.EQ.1) THEN

    CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'OBS', NOBS, X_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'LEVS', NLEVS, L_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'PREDS', NPREDS, B_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'NPQ', NPQ, Q_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'NPQ2', NPQ2, Q2_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'CHARLEN1', 8, C1_DIMID) )
    CALL CHECK( NF90_DEF_DIM(NCID, 'CHARLEN2', 16, C2_DIMID) )

    IN=0
    DIMIDS = X_DIMID
    DIMIDS8 = (/C1_DIMID, X_DIMID /)
    DIMIDS16= (/C2_DIMID, X_DIMID /)
    DIMIDS2 = (/X_DIMID, L_DIMID /)
    DIMIDSBC= (/X_DIMID, B_DIMID /)
    DIMIDSIJ= (/X_DIMID, Q_DIMID /)
    DIMIDSPQ= (/X_DIMID, Q2_DIMID /)

    IN=IN+1
    IF( PRESENT( NIND ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'NIND', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INO ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'INO', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( OTYPE ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'OTYPE', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PAR ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'PAR', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PLNO ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'PLNO', NF90_CHAR, DIMIDS8, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INST ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'INST', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( EVE ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'EVE', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KTY ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'KTY', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PRIND ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'PRIND', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PROF ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'PROF', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TDIST ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'TDIST', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( LON ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'LON', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( LAT ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'LAT', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( DPT ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'DPT', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TIM ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'TIM', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( VAL ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'VAL', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BIA ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'BIA', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( IB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'IB', NF90_INT, DIMIDSIJ, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( JB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'JB', NF90_INT, DIMIDSIJ, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'KB', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( RB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'RB', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PQ ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'PQ', NF90_DOUBLE, DIMIDSPQ, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TRACK ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'TRACK', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KSAT ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'KSAT', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BOT ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'BOT', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( FLG ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'FLG', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( FLC ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'FLC', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INC ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'INC', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BAC ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'BAC', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( ERR ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'ERR', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( RES ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'RES', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( B_A ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'B_A', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BGERR ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'BGERR', NF90_DOUBLE, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'TB', NF90_DOUBLE, DIMIDS2, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SB ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'SB', NF90_DOUBLE, DIMIDS2, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BCP ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'BCP', NF90_DOUBLE, DIMIDSBC, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SD1 ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'SD1', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SD2 ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'SD2', NF90_INT, DIMIDS, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( MOI ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'MOI', NF90_INT, DIMIDSIJ, VARID(IN)) )

    IN=IN+1
    IF( PRESENT( MOJ ) ) &
    CALL CHECK( NF90_DEF_VAR(NCID, 'MOJ', NF90_INT, DIMIDSIJ, VARID(IN)) )

    CALL CHECK( NF90_ENDDEF(NCID) )

  ELSEIF(IOPT .EQ. 2 .OR. IOPT .EQ. 3) THEN

    IF(IOPT .EQ. 2) THEN
      WRITE(*,*) ' OPENING FILE ',TRIM(CFILE),' IN READ MODE'
      CALL CHECK( NF90_OPEN(CFILE, NF90_NOWRITE, NCID) )
      WRITE(*,*) ' FILE OPENED', NCID
    ELSE
      WRITE(*,*) ' OPENING FILE ',TRIM(CFILE),' IN WRITE MODE'
      CALL CHECK( NF90_OPEN(CFILE, NF90_WRITE, NCID) )
      WRITE(*,*) ' FILE OPENED'
    ENDIF

    CALL CHECK( NF90_INQ_DIMID(NCID,'OBS',DIMID) )
    CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NDIMC) )
    IF( NDIMC .NE. NOBS ) THEN
        CALL ABOR1('IO_OBS : OBS DIMENSION MISMATCH')
    ENDIF
    CALL CHECK( NF90_INQ_DIMID(NCID,'NPQ',DIMID) )
    CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NDIMC) )
    IF( NDIMC .NE. NPQ ) THEN
        CALL ABOR1('IO_OBS : OBS DIMENSION MISMATCH')
    ENDIF
    CALL CHECK( NF90_INQ_DIMID(NCID,'NPQ2',DIMID) )
    CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NDIMC) )
    IF( NDIMC .NE. NPQ2 ) THEN
        CALL ABOR1('IO_OBS : OBS DIMENSION MISMATCH')
    ENDIF

    IN=0

    IN=IN+1
    IF( PRESENT( NIND ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'NIND', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INO ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'INO', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( OTYPE ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'OTYPE', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PAR ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'PAR', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PLNO ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'PLNO', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INST ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'INST', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( EVE ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'EVE', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KTY ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'KTY', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PRIND ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'PRIND', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PROF ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'PROF', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TDIST ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'TDIST', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( LON ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'LON', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( LAT ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'LAT', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( DPT ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'DPT', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TIM ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'TIM', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( VAL ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'VAL', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BIA ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'BIA', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( IB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'IB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( JB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'JB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'KB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( RB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'RB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( PQ ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'PQ', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TRACK ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'TRACK', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( KSAT ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'KSAT', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BOT ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'BOT', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( FLG ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'FLG', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( FLC ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'FLC', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( INC ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'INC', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BAC ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'BAC', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( ERR ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'ERR', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( RES ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'RES', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( B_A ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'B_A', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BGERR ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'BGERR', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( TB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'TB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SB ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'SB', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( BCP ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'BCP', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SD1 ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'SD1', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( SD2 ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'SD2', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( MOI ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'MOI', VARID(IN)) )

    IN=IN+1
    IF( PRESENT( MOJ ) ) &
    CALL CHECK( NF90_INQ_VARID(NCID, 'MOJ', VARID(IN)) )

  ELSE
    ! ERROR
  ENDIF

  IF(IOPT .EQ. 1 .OR. IOPT .EQ. 3) THEN

    IN=0

    IN=IN+1
    IF( PRESENT( NIND ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), NIND) )

    IN=IN+1
    IF( PRESENT( INO ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), INO) )

    IN=IN+1
    IF( PRESENT( OTYPE ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), OTYPE) )

    IN=IN+1
    IF( PRESENT( PAR ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), PAR) )

    IN=IN+1
    IF( PRESENT( PLNO ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), PLNO) )

    IN=IN+1
    IF( PRESENT( INST ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), INST) )

    IN=IN+1
    IF( PRESENT( EVE ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), EVE) )

    IN=IN+1
    IF( PRESENT( KTY ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), KTY) )

    IN=IN+1
    IF( PRESENT( PRIND ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), PRIND) )

    IN=IN+1
    IF( PRESENT( PROF ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), PROF) )

    IN=IN+1
    IF( PRESENT( TDIST ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), TDIST) )

    IN=IN+1
    IF( PRESENT( LON ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN) ,LON) )

    IN=IN+1
    IF( PRESENT( LAT ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), LAT) )

    IN=IN+1
    IF( PRESENT( DPT ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), DPT) )

    IN=IN+1
    IF( PRESENT( TIM ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), TIM) )

    IN=IN+1
    IF( PRESENT( VAL ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), VAL) )

    IN=IN+1
    IF( PRESENT( BIA ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), BIA) )

    IN=IN+1
    IF( PRESENT( IB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), IB) )

    IN=IN+1
    IF( PRESENT( JB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), JB) )

    IN=IN+1
    IF( PRESENT( KB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), KB) )

    IN=IN+1
    IF( PRESENT( RB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), RB) )

    IN=IN+1
    IF( PRESENT( PQ ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), PQ) )

    IN=IN+1
    IF( PRESENT( TRACK ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), TRACK) )

    IN=IN+1
    IF( PRESENT( KSAT ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), KSAT) )

    IN=IN+1
    IF( PRESENT( BOT ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), BOT) )

    IN=IN+1
    IF( PRESENT( FLG ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), FLG) )

    IN=IN+1
    IF( PRESENT( FLC ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), FLC) )

    IN=IN+1
    IF( PRESENT( INC ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), INC) )

    IN=IN+1
    IF( PRESENT( BAC ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), BAC) )

    IN=IN+1
    IF( PRESENT( ERR ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), ERR) )

    IN=IN+1
    IF( PRESENT( RES ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), RES) )

    IN=IN+1
    IF( PRESENT( B_A ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), B_A) )

    IN=IN+1
    IF( PRESENT( BGERR ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), BGERR) )

    IN=IN+1
    IF( PRESENT( TB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), TB) )

    IN=IN+1
    IF( PRESENT( SB ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), SB) )

    IN=IN+1
    IF( PRESENT( BCP ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), BCP) )

    IN=IN+1
    IF( PRESENT( SD1 ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), SD1) )

    IN=IN+1
    IF( PRESENT( SD2 ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), SD2) )

    IN=IN+1
    IF( PRESENT( MOI ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), MOI) )

    IN=IN+1
    IF( PRESENT( MOJ ) ) &
    CALL CHECK( NF90_PUT_VAR(NCID, VARID(IN), MOJ) )

 ELSE

    IN=0

    IN=IN+1
    IF( PRESENT( NIND ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), NIND) )

    IN=IN+1
    IF( PRESENT( INO ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), INO) )

    IN=IN+1
    IF( PRESENT( OTYPE ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), OTYPE) )

    IN=IN+1
    IF( PRESENT( PAR ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), PAR) )

    IN=IN+1
    IF( PRESENT( PLNO ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), PLNO) )

    IN=IN+1
    IF( PRESENT( INST ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), INST) )

    IN=IN+1
    IF( PRESENT( EVE ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), EVE) )

    IN=IN+1
    IF( PRESENT( KTY ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), KTY) )

    IN=IN+1
    IF( PRESENT( PRIND ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), PRIND) )

    IN=IN+1
    IF( PRESENT( PROF ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), PROF) )

    IN=IN+1
    IF( PRESENT( TDIST ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), TDIST) )

    IN=IN+1
    IF( PRESENT( LON ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN) ,LON) )

    IN=IN+1
    IF( PRESENT( LAT ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), LAT) )

    IN=IN+1
    IF( PRESENT( DPT ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), DPT) )

    IN=IN+1
    IF( PRESENT( TIM ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), TIM) )

    IN=IN+1
    IF( PRESENT( VAL ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), VAL) )

    IN=IN+1
    IF( PRESENT( BIA ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), BIA) )

    IN=IN+1
    IF( PRESENT( IB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), IB) )

    IN=IN+1
    IF( PRESENT( JB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), JB) )

    IN=IN+1
    IF( PRESENT( KB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), KB) )

    IN=IN+1
    IF( PRESENT( RB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), RB) )

    IN=IN+1
    IF( PRESENT( PQ ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), PQ) )

    IN=IN+1
    IF( PRESENT( TRACK ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), TRACK) )

    IN=IN+1
    IF( PRESENT( KSAT ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), KSAT) )

    IN=IN+1
    IF( PRESENT( BOT ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), BOT) )

    IN=IN+1
    IF( PRESENT( FLG ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), FLG) )

    IN=IN+1
    IF( PRESENT( FLC ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), FLC) )

    IN=IN+1
    IF( PRESENT( INC ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), INC) )

    IN=IN+1
    IF( PRESENT( BAC ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), BAC) )

    IN=IN+1
    IF( PRESENT( ERR ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), ERR) )

    IN=IN+1
    IF( PRESENT( RES ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), RES) )

    IN=IN+1
    IF( PRESENT( B_A ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), B_A) )

    IN=IN+1
    IF( PRESENT( BGERR ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), BGERR) )

    IN=IN+1
    IF( PRESENT( TB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), TB) )

    IN=IN+1
    IF( PRESENT( SB ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), SB) )

    IN=IN+1
    IF( PRESENT( BCP ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), BCP) )

    IN=IN+1
    IF( PRESENT( SD1 ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), SD1) )

    IN=IN+1
    IF( PRESENT( SD2 ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), SD2) )

    IN=IN+1
    IF( PRESENT( MOI ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), MOI) )

    IN=IN+1
    IF( PRESENT( MOJ ) ) &
    CALL CHECK( NF90_GET_VAR(NCID, VARID(IN), MOJ) )

 ENDIF

  CALL CHECK( NF90_CLOSE(NCID) )

END SUBROUTINE IO_OBS
