MODULE MYNETCDF

USE SET_KND
USE GRD_STR
USE NETCDF

IMPLICIT NONE
PRIVATE

PUBLIC :: WRITE_VARNCDF, GETNCVAR, GETNCDIM

INTERFACE WRITE_VARNCDF
  MODULE PROCEDURE WRITE_VARNCDF_R1D, WRITE_VARNCDF_R2D, WRITE_VARNCDF_R3D, &
  &                WRITE_VARNCDF_R4D, &
  &                WRITE_VARNCDF_I1D, WRITE_VARNCDF_I2D, WRITE_VARNCDF_I3D
END INTERFACE WRITE_VARNCDF

INTERFACE GETNCVAR
#ifdef NO_DOUBLEPREC
  MODULE PROCEDURE GETNCVAR2,GETNCVAR3,GETNCVAI1,GETNCVAI2,GETNCVAR1,GETNCVAI3,GETNCVAR4,GETNCVAR4R,GETNCVAR3R,GETNCVAR1_DP
#else
  MODULE PROCEDURE GETNCVAR2,GETNCVAR3,GETNCVAI1,GETNCVAI2,GETNCVAR1,GETNCVAI3,GETNCVAR4,GETNCVAR4R,GETNCVAR3R
#endif
END INTERFACE GETNCVAR

CONTAINS

SUBROUTINE WRITE_VARNCDF_R1D(CFILE,IM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM
REAL(R8), INTENT(IN) :: VAR(IM)
INTEGER(I4) :: NCID,DIMIDS1,VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  DIMIDS1= X_DIMID
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R1D

SUBROUTINE WRITE_VARNCDF_R2D(CFILE,IM,JM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM
REAL(R8), INTENT(IN) :: VAR(IM,JM)
INTEGER(I4) :: NCID,DIMIDS1(2),VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R2D

SUBROUTINE WRITE_VARNCDF_R3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM, KM
REAL(R8), INTENT(IN) :: VAR(IM,JM,KM)
INTEGER(I4) :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,Z_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R3D

SUBROUTINE WRITE_VARNCDF_R4D(CFILE,IM,JM,KM,TM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM, KM,TM
REAL(R8), INTENT(IN) :: VAR(IM,JM,KM,TM)
INTEGER(I4) :: NCID,DIMIDS1(4),VARID,X_DIMID,Y_DIMID,Z_DIMID, T_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'time', NF90_UNLIMITED, T_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID, T_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R4D


SUBROUTINE WRITE_VARNCDF_I1D(CFILE,IM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM
INTEGER(I4), INTENT(IN) :: VAR(IM)
INTEGER(I4) :: NCID,DIMIDS1,VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  DIMIDS1= X_DIMID
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I1D

SUBROUTINE WRITE_VARNCDF_I2D(CFILE,IM,JM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM
INTEGER(I4), INTENT(IN) :: VAR(IM,JM)
INTEGER(I4) :: NCID,DIMIDS1(2),VARID,X_DIMID,Y_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I2D

SUBROUTINE WRITE_VARNCDF_I3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
USE SET_KND
USE NETCDF
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER(I4), INTENT(IN) :: IM, JM, KM
INTEGER(I4), INTENT(IN) :: VAR(IM,JM,KM)
INTEGER(I4) :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,Z_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I3D

SUBROUTINE GETNCDIM(CF,CD,ND)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CD
  INTEGER(I4), INTENT(OUT) :: ND
  INTEGER(I4) :: NCID, DID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_DIMID(NCID,CD,DID) )
  CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DID,LEN=ND) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCDIM

SUBROUTINE GETNCVAI1(CF,CV,JPI,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI
  INTEGER(I4), DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI1

SUBROUTINE GETNCVAI2(CF,CV,JPI,JPJ,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ
  INTEGER(I4), DIMENSION(JPI,JPJ), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1/),COUNT=(/JPI,JPJ/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI2

SUBROUTINE GETNCVAR1(CF,CV,JPI,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI
  REAL(R8), DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR1

SUBROUTINE GETNCVAR1_DP(CF,CV,JPI,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI
  REAL(DP), DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR1_DP

SUBROUTINE GETNCVAR2(CF,CV,JPI,JPJ,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ
  REAL(R8), DIMENSION(JPI,JPJ), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1/),COUNT=(/JPI,JPJ/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR2

SUBROUTINE GETNCVAI3(CF,CV,JPI,JPJ,JPK,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK
  INTEGER(I4), DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1,1/),COUNT=(/JPI,JPJ,JPK/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI3

SUBROUTINE GETNCVAR3(CF,CV,JPI,JPJ,JPK,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK
  REAL(R8), DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1,1/),COUNT=(/JPI,JPJ,JPK/) ) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR3

SUBROUTINE GETNCVAR3R(CF,CV,JPI,JPJ,JPTS,JPK,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK,JPTS
  REAL(R8), DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1,JPTS/),COUNT=(/JPI,JPJ,JPK/) ))
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR3R

SUBROUTINE GETNCVAR4(CF,CV,JPI,JPJ,JPK,JPT,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK,JPT
  REAL(R8), DIMENSION(JPI,JPJ,JPK,JPT), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1,1,1/),COUNT=(/JPI,JPJ,JPK,JPT/)))
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR4

SUBROUTINE GETNCVAR4R(CF,CV,JPI,JPJ,JPK,JPTS,JPT,VV)
USE SET_KND
USE NETCDF
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER(I4), INTENT(IN) :: JPI,JPJ,JPK,JPT,JPTS
  REAL(R8), DIMENSION(JPI,JPJ,JPK,JPT), INTENT(OUT) :: VV
  INTEGER(I4) :: NCID, VID
  INTEGER(I4) :: I1, J1
  I1=1 ; J1=1
  IF( JPI .EQ. GRD%IM ) I1=GRD%I0
  IF( JPJ .EQ. GRD%JM ) J1=GRD%J0
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV,START=(/I1,J1,1,JPTS/),COUNT=(/JPI,JPJ,JPK,JPT/)))
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR4R

END MODULE MYNETCDF
