MODULE DEBUGTMP

USE GRD_STR
USE CTL_STR
USE SET_KND
USE NETCDF
USE IOUNITS
USE RECFILTER
USE EXTGRID
USE MPIREL

IMPLICIT NONE

SAVE
PRIVATE

INTEGER(I4) :: DTNCID, DTVARID, DNVARID, NT,JDIFF=0
INTEGER(I4), PUBLIC :: IDB_X, IDB_Y, IDB_Z
LOGICAL :: INIT=.FALSE.
LOGICAL, PUBLIC :: LL_DEBUGTMP=.FALSE.
LOGICAL, PUBLIC :: LL_ONEPOINT=.TRUE.
LOGICAL, PUBLIC :: LL_FLDPRINT=.FALSE.

CHARACTER(LEN=30), PUBLIC :: DT_CSTRIN
PUBLIC :: CALLDT

CONTAINS

!SUBROUTINE CALLDTV(ZVAR,
!END SUBROUTINE CALLDTV

SUBROUTINE CALLDT(NIN)

IMPLICIT NONE
INTEGER(I4), OPTIONAL :: NIN
INTEGER(I4) :: IUN
LOGICAL :: LLOP

IF(.NOT. LL_DEBUGTMP) RETURN

IUN = 1091+MYPROC

IF(PRESENT(NIN))THEN
  IF(NIN.EQ.1) THEN
   IF(LL_ONEPOINT) THEN
    WRITE(IUN,'(A,2F13.5)') 'FINAL: ',GRD%TEM(IDB_X,IDB_Y,IDB_Z),GRD%SAL(IDB_X,IDB_Y,IDB_Z)
    CLOSE(IUN)
   ENDIF
   IF(LL_FLDPRINT) THEN
    CALL DTWRITECL
   ENDIF
   RETURN
  ENDIF
ENDIF

IF(LL_ONEPOINT) THEN
   IF(NWRAPS.GT.0) JDIFF=NWRAPS-1
   INQUIRE(FILE=IUN,OPENED=LLOP)
   IF( .NOT. LLOP ) THEN
     OPEN(IUN,FILE='debug_report_'//TRIM(CMPIDOM)//'.dat')
   ENDIF
   WRITE(IUN,'(I3,A,A,5F13.5)') CTL%KITER,': ',TRIM(DT_CSTRIN),GRD%TEM(IDB_X+JDIFF,IDB_Y,IDB_Z),GRD%SAL(IDB_X+JDIFF,IDB_Y,IDB_Z), GRD%RO(IDB_X+JDIFF,IDB_Y,IDB_Z), GRD%TEM_AD(IDB_X+JDIFF,IDB_Y,IDB_Z), GRD%RO_AD(IDB_X+JDIFF,IDB_Y,IDB_Z)
   IF(LL_TQ2) WRITE(IUN,'(I3,A,A,4F13.5)') CTL%KITER,'S:',TRIM(DT_CSTRIN),GRD%T2M(IDB_X+JDIFF,IDB_Y),GRD%Q2M(IDB_X+JDIFF,IDB_Y), GRD%T2M_AD(IDB_X+JDIFF,IDB_Y), GRD%Q2M_AD(IDB_X+JDIFF,IDB_Y)
   IF(LL_ICE) WRITE(IUN,'(I3,A,A,4F13.5)') CTL%KITER,'I:',TRIM(DT_CSTRIN),GRD%SIC(IDB_X+JDIFF,IDB_Y),GRD%SIT(IDB_X+JDIFF,IDB_Y), GRD%SIC_AD(IDB_X+JDIFF,IDB_Y), GRD%SIT_AD(IDB_X+JDIFF,IDB_Y)
   IF(LL_ICE) WRITE(IUN,'(I3,A,A,4F13.5)') CTL%KITER,'IV:',TRIM(DT_CSTRIN),GRD%ICU(IDB_X+JDIFF,IDB_Y),GRD%ICV(IDB_X+JDIFF,IDB_Y), GRD%ICU_AD(IDB_X+JDIFF,IDB_Y), GRD%ICV_AD(IDB_X+JDIFF,IDB_Y)
   WRITE(IUN,'(I3,A,A,10E12.3)') CTL%KITER,' MM ',TRIM(DT_CSTRIN),MAXVAL(ABS(GRD%TEM)),MAXVAL(ABS(GRD%SAL)),MAXVAL(ABS(GRD%RO)),&
   & MAXVAL(ABS(GRD%TEM_AD)),MAXVAL(ABS(GRD%SAL_AD)),MAXVAL(ABS(GRD%RO_AD)),&
   & MAXVAL(ABS(GRD%T2M)), MAXVAL(ABS(GRD%Q2M)), MAXVAL(ABS(GRD%T2M_AD)), MAXVAL(ABS(GRD%Q2M_AD))
   CALL FLUSH(IUN)
   IF (.NOT. LL_FLDPRINT) RETURN
ENDIF

IF(.NOT.INIT) THEN 
  CALL DTWRITEIN
  INIT=.TRUE.
  NT=0
ENDIF

NT=NT+1
CALL DTWRITE

END SUBROUTINE CALLDT

SUBROUTINE DTWRITEIN

IMPLICIT NONE

INTEGER(I4) :: DIMIDS1(4),X_DIMID,Y_DIMID,Z_DIMID,I_DIMID,&
& C_DIMID,DIMIDS30(2)

  CALL CHECK( NF90_CREATE('debug_temp.nc', NF90_CLOBBER, DTNCID) )
  CALL CHECK( NF90_DEF_DIM(DTNCID, 'x', GRD%IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(DTNCID, 'y', GRD%JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(DTNCID, 'z', GRD%KM, Z_DIMID) )
  CALL CHECK( NF90_DEF_DIM(DTNCID, 'charlen', 30, C_DIMID) )
  CALL CHECK( NF90_DEF_DIM(DTNCID, 'iters', NF90_UNLIMITED, I_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID, I_DIMID/)
  DIMIDS30= (/C_DIMID, I_DIMID /)
  CALL CHECK( NF90_DEF_VAR(DTNCID, 'temp',NF90_REAL,DIMIDS1,DTVARID) )
  CALL CHECK( NF90_PUT_ATT(DTNCID, DTVARID, 'units','degC') )
  CALL CHECK( NF90_PUT_ATT(DTNCID, DTVARID, 'long_name','Temperature') )
  CALL CHECK( NF90_DEF_VAR(DTNCID, 'name',NF90_CHAR,DIMIDS30,DNVARID) )
  CALL CHECK( NF90_ENDDEF(DTNCID) )

END SUBROUTINE DTWRITEIN

SUBROUTINE DTWRITE

  CHARACTER(LEN=30) :: CAUX

  WRITE(IOUNLOG,*) ' WRITING TEM AT NT=',NT
  CALL FLUSH(IOUNLOG)
  CALL CHECK( NF90_PUT_VAR(DTNCID, DTVARID, GRD%TEM,&
  & START=(/1,1,1,NT/),COUNT=(/GRD%IM,GRD%JM,GRD%KM,1/)) )

  WRITE(CAUX,'(I3,A,A)') CTL%KITER,': ',TRIM(DT_CSTRIN)
  WRITE(IOUNLOG,*) ' WRITING STRING ', TRIM(CAUX)
  CALL FLUSH(IOUNLOG)
  CALL CHECK( NF90_PUT_VAR(DTNCID, DNVARID, CAUX,&
  & START=(/1,NT/),COUNT=(/30,1/)) )

END SUBROUTINE DTWRITE

SUBROUTINE DTWRITECL

  CALL CHECK( NF90_CLOSE(DTNCID) )

END SUBROUTINE DTWRITECL

END MODULE DEBUGTMP
