MODULE BAL

USE SET_KND

IMPLICIT NONE

REAL(R8), ALLOCATABLE :: BAL_TEMB(:,:,:)
REAL(R8), ALLOCATABLE :: BAL_SALB(:,:,:)
REAL(R8), ALLOCATABLE :: DHDZ(:)

REAL(R8), PARAMETER :: RHO0 = 1020._R8
INTEGER(I4)    :: NLEVS
INTEGER(I4)    :: BAL_NNEOS = 0
INTEGER(I4)    :: BAL_LNM

END MODULE BAL
