MODULE IOUNITS

!! DEFINE UNITS NUMBERS
!!
!! AS

USE SET_KND, ONLY : I4

IMPLICIT NONE

!... STANDARD UNITS
INTEGER(KIND=I4), PARAMETER :: IOUNOUT=6
INTEGER(KIND=I4), PARAMETER :: IOUNERR=0
INTEGER(KIND=I4), PARAMETER :: IOUNIN=5

!... OTHER UNITS
INTEGER(KIND=I4), PARAMETER :: IOUNNAM=16     ! NAMELIST
INTEGER(KIND=I4), PARAMETER :: IOUNLOG=17     ! LOGFILE
INTEGER(KIND=I4), PARAMETER :: IOUNEOF=18     ! EOFS
INTEGER(KIND=I4), PARAMETER :: IOUNCOST=19    ! COST FUNCTION
INTEGER(KIND=I4), PARAMETER :: IOUNBLACK=20   ! BLACKLIST

END MODULE IOUNITS
