MODULE LBCLNK

USE SET_KND
USE GRD_STR

IMPLICIT NONE

LOGICAL, PARAMETER :: LL_LBCLNK = .FALSE.

INTERFACE LBC_LNK
    MODULE PROCEDURE LBC_LNK_3D, LBC_LNK_2D
END INTERFACE LBC_LNK

CONTAINS

SUBROUTINE LBC_LNK_3D(DATA)
IMPLICIT NONE
REAL(R8), INTENT(INOUT) :: DATA(:,:,:)
DATA(1,:,:)      = DATA(GRD%IM-1,:,:)
DATA(GRD%IM,:,:) = DATA(   2    ,:,:)
END SUBROUTINE LBC_LNK_3D

SUBROUTINE LBC_LNK_2D(DATA)
IMPLICIT NONE
REAL(R8), INTENT(INOUT) :: DATA(:,:)
DATA(1,:)      = DATA(GRD%IM-1,:)
DATA(GRD%IM,:) = DATA(   2    ,:)
END SUBROUTINE LBC_LNK_2D

END MODULE LBCLNK
