MODULE EXTGRID

!== MODULE TO EXTEND DOMAIN
!== TO ARTIFICIALLY SUPERIMPOSE
!== CYCLIC CONDITION ON GLOBAL DOMAINS
!==
!==
!== NOTE THAT WE CHOSE TO LEAVE ALL THE
!== PREPROCESSING AND SETUP ROUTINES AS THEY
!== ARE WITHOUT GRID EXTENSION (I.E. UP TO
!== THE MINIMIZATION EXCLUDED) AND ADD
!== THIS GRID EXTENSION IN A MODULAR
!== WAY THAT REARRANGES THE GRID AND THE OBS
!== VECTOR ACCORDINGLY, AND REVERT THE
!== ARRANGEMENT BACK TO THE PHYSICAL GRID
!== JUST AFTER THE MINIMIZATION ACHIEVEMENT.
!== IN THIS WAY WE CAN ADD/REMOVE GRID EXTENSION
!== FOR WHATEVER VERSION/CONFIGURATION/RESOLUTION.
!== THE REARRANGEMENT MAY BE MEMORY-DEMANDING
!== FOR HIGH-RESOLUTION DOMAINS.
!==
!== ANDREA.STORTO AT CMCC.IT - 25.05.2010

USE SET_KND
USE GRD_STR
USE IOUNITS
USE RUN
USE RECFILTER
USE EOF_STR
USE OBS_STR
USE DRV_STR
USE MYFRTPROF
USE MYNETCDF
USE BAL_AIRSEA
USE TLAD_VARS
USE BLKOCE_CORE
USE WEAKLY
USE HYBRID
USE EOFS3D
USE BAL

IMPLICIT NONE

SAVE

INTEGER(I4) :: NWRAPS
INTEGER(I4), PARAMETER :: MAXWRAPS = 99
LOGICAL :: LLEXTGRID
LOGICAL, PARAMETER :: LLDEBUG=.FALSE.
LOGICAL :: LLDUPLOBS
INTEGER(I4) :: OLD_IM, NEW_IM,FRST,LST,FRST2,LST2
INTEGER(I4) :: OLD_SLA_NO,OLD_INS_NO,OLD_SST_NO,OLD_SSS_NO
INTEGER(I4) :: OBS_DIFF
REAL(R8), ALLOCATABLE :: ZTEMP2(:,:), ZTEMP3(:,:,:)
REAL(R8), ALLOCATABLE :: OLD_LON(:,:)
REAL(R8), ALLOCATABLE :: OLD_LAT(:,:)
REAL(R8), ALLOCATABLE :: ZTEMP3B(:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP3BH(:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP3D(:,:,:)
#ifdef opt_huge_memory
REAL(R8), ALLOCATABLE :: ZTEMP3E(:,:,:)
#endif
REAL(R8), ALLOCATABLE :: ZTEMP3F(:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP4C(:,:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP3G(:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP3W(:,:,:)
REAL(R8), ALLOCATABLE :: ZTEMP4G(:,:,:,:)

INTEGER(I4) , ALLOCATABLE :: ITEMP2(:,:)
INTEGER(I4) , ALLOCATABLE :: ITEMP3(:,:,:)
INTEGER(I4) , ALLOCATABLE :: ITEMP3W(:,:,:)
LOGICAL :: LLINCALLED=.FALSE.
INTEGER(I4) :: KSV

INTERFACE WRAP
  MODULE PROCEDURE WRAP2DR,WRAP3DR,&
  & WRAP4DR,WRAP2DI,WRAP3DI
END INTERFACE WRAP

INTERFACE DEWRAP
  MODULE PROCEDURE DEWRAP2DR,DEWRAP3DR,&
  & DEWRAP4DR,DEWRAP2DI,DEWRAP3DI
END INTERFACE DEWRAP

CONTAINS

SUBROUTINE EXTGRID_INIT

OLD_IM = GRD%IM
NEW_IM = OLD_IM + NWRAPS*2 - 2
FRST = NWRAPS + 1
LST = NEW_IM - NWRAPS
FRST2 = NWRAPS
LST2 = LST + 1

LLINCALLED=.TRUE.

END SUBROUTINE EXTGRID_INIT

SUBROUTINE DOEXTGRID

!== MAIN SUBROUTINE FOR ADD EXTENSION OF GRID (A.S.)

IMPLICIT NONE

CALL MYFRTPROF_WALL('DOEXTGRID: GRID EXTENSION ROUTINE',0)

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// EXTENDING THE GRID ///'
WRITE(IOUNLOG,*)
WRITE(IOUNOUT,*) ' EXTENDING THE GRID:'

IF(.NOT.LLEXTGRID) THEN
  WRITE(IOUNLOG,*) ' DOEXTGRID: NOTHING TO DO'
  RETURN
ELSE
  WRITE(IOUNLOG,*) ' DOEXTGRID: NWRAPS = ',NWRAPS
ENDIF

IF(.NOT.LLINCALLED) CALL EXTGRID_INIT

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' == PARAMETERS == '
WRITE(IOUNLOG,*) ' OLD_IM',OLD_IM
WRITE(IOUNLOG,*) ' NEW_IM',NEW_IM
WRITE(IOUNLOG,*) ' FRST  ',FRST
WRITE(IOUNLOG,*) ' LST   ',LST
WRITE(IOUNLOG,*) ' FRST2 ',FRST2
WRITE(IOUNLOG,*) ' LST2  ',LST2

CALL FLUSH(IOUNLOG)

! FROM NOW ONWARDS GRD%IM AND %JM WILL BE DEFINITIVELY
! RELATED TO THE EXTENDED GRID.
GRD%IM = NEW_IM

ALLOCATE(ZTEMP2(OLD_IM,GRD%JM),ZTEMP3(OLD_IM,GRD%JM,GRD%KM))
ALLOCATE(OLD_LON(OLD_IM,GRD%JM))
ALLOCATE(OLD_LAT(OLD_IM,GRD%JM))
ALLOCATE(ZTEMP3B(OLD_IM,GRD%JM,ROS%NEOF))
ALLOCATE(ZTEMP3BH(OLD_IM,GRD%JM,ROSH%NEOF))
ALLOCATE(ZTEMP3D(OLD_IM,GRD%JM,NTOTV))
#ifdef opt_huge_memory
ALLOCATE(ZTEMP3E(OLD_IM,JMAX,NTOTV))
#endif
ALLOCATE(ZTEMP3F(OLD_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
ALLOCATE(ITEMP2(OLD_IM,GRD%JM))
ALLOCATE(ITEMP3(OLD_IM,GRD%JM,NTOTV))
ALLOCATE(ITEMP3W(OLD_IM,GRD%JM,MAXP))
ALLOCATE(ZTEMP3W(OLD_IM,GRD%JM,MAXP))
ALLOCATE(ZTEMP3G(OLD_IM,GRD%JM,NTS_TRAJ))

! LONGITUDE
ZTEMP2=GRD%LON
OLD_LON=GRD%LON
DEALLOCATE(GRD%LON)
ALLOCATE(GRD%LON(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%LON)
IF(LLDEBUG) &
CALL WRITE_VARNCDF('NEWLON.NC',NEW_IM,GRD%JM,GRD%LON,'NAV_LON','DEGREES_EAST',&
& 'LONGITUDE')

! LATITUDE
ZTEMP2=GRD%LAT
OLD_LAT=GRD%LAT
DEALLOCATE(GRD%LAT)
ALLOCATE(GRD%LAT(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%LAT)

! REGIONS
ITEMP2=GRD%REG
DEALLOCATE(GRD%REG)
ALLOCATE(GRD%REG(NEW_IM,GRD%JM))
CALL WRAP(ITEMP2,GRD%REG)

! MASK
ZTEMP3=GRD%MSK
DEALLOCATE(GRD%MSK)
ALLOCATE(GRD%MSK(NEW_IM,GRD%JM,GRD%KM))
CALL WRAP(ZTEMP3,GRD%MSK,GRD%JM,GRD%KM)

! MVLOC
IF(ALLOCATED(GRD%MVLOC) ) THEN
ZTEMP3F=GRD%MVLOC
DEALLOCATE(GRD%MVLOC)
ALLOCATE(GRD%MVLOC(NEW_IM,GRD%JM,ROS%KMT))
CALL WRAP(ZTEMP3F,GRD%MVLOC,GRD%JM,ROS%KMT)
ENDIF

! HGT
ZTEMP2=GRD%HGT
DEALLOCATE(GRD%HGT)
ALLOCATE(GRD%HGT(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%HGT)

! ICE
IF(LL_ICEINIT) THEN
ZTEMP2=GRD%ICE
DEALLOCATE(GRD%ICE)
ALLOCATE(GRD%ICE(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%ICE)
ENDIF

! DISTC
ZTEMP2=GRD%DISTC
DEALLOCATE(GRD%DISTC)
ALLOCATE(GRD%DISTC(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%DISTC)

! F
ZTEMP2=GRD%F
DEALLOCATE(GRD%F)
ALLOCATE(GRD%F(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%F)

! B_X
ZTEMP3=GRD%B_X
DEALLOCATE(GRD%B_X)
ALLOCATE(GRD%B_X(NEW_IM,GRD%JM,GRD%KM))
CALL WRAP(ZTEMP3,GRD%B_X,GRD%JM,GRD%KM)

! B_Y
ZTEMP3=GRD%B_Y
DEALLOCATE(GRD%B_Y)
ALLOCATE(GRD%B_Y(NEW_IM,GRD%JM,GRD%KM))
CALL WRAP(ZTEMP3,GRD%B_Y,GRD%JM,GRD%KM)

! DNS
ZTEMP3=GRD%DNS
DEALLOCATE(GRD%DNS)
ALLOCATE(GRD%DNS(NEW_IM,GRD%JM,GRD%KM))
CALL WRAP(ZTEMP3,GRD%DNS,GRD%JM,GRD%KM)

! BX
ZTEMP2=GRD%BX
DEALLOCATE(GRD%BX )
ALLOCATE(GRD%BX (NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%BX)

! BY
ZTEMP2=GRD%BY
DEALLOCATE(GRD%BY )
ALLOCATE(GRD%BY (NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%BY)

! MDT
ZTEMP2=GRD%MDT
DEALLOCATE(GRD%MDT)
ALLOCATE(GRD%MDT(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%MDT)

! SLA
ZTEMP2=GRD%SLA
DEALLOCATE(GRD%SLA)
ALLOCATE(GRD%SLA(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%SLA)

! DX
ZTEMP2=GRD%DX
DEALLOCATE(GRD%DX)
ALLOCATE(GRD%DX(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%DX)

! DY
ZTEMP2=GRD%DY
DEALLOCATE(GRD%DY)
ALLOCATE(GRD%DY(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%DY)

! DXDY
ZTEMP2=GRD%DXDY
DEALLOCATE(GRD%DXDY)
ALLOCATE(GRD%DXDY(NEW_IM,GRD%JM))
CALL WRAP(ZTEMP2,GRD%DXDY)

! MSR
ZTEMP3=GRD%MSR
DEALLOCATE(GRD%MSR)
ALLOCATE(GRD%MSR(NEW_IM,GRD%JM,GRD%KM))
CALL WRAP(ZTEMP3,GRD%MSR,GRD%JM,GRD%KM)

IF(NCONF.NE.202.AND.NCONF.NE.301) THEN
! RO
ZTEMP3B=GRD%RO
DEALLOCATE(GRD%RO)
ALLOCATE(GRD%RO(NEW_IM,GRD%JM,ROS%NEOF))
CALL WRAP(ZTEMP3B,GRD%RO,GRD%JM,ROS%NEOF)

! RO_AD
ZTEMP3B=GRD%RO_AD
DEALLOCATE(GRD%RO_AD)
ALLOCATE(GRD%RO_AD(NEW_IM,GRD%JM,ROS%NEOF))
CALL WRAP(ZTEMP3B,GRD%RO_AD,GRD%JM,ROS%NEOF)
ENDIF

IF( LL_HYBRID ) THEN

 ITEMP2=REGHH
 DEALLOCATE(REGHH)
 ALLOCATE(REGHH(NEW_IM,GRD%JM))
 CALL WRAP(ITEMP2,REGHH) 

 IF( LL_ALPHA_CTL ) THEN
   ITEMP2=ILAT_ALP
   DEALLOCATE(ILAT_ALP)
   ALLOCATE(ILAT_ALP(NEW_IM,GRD%JM))
   CALL WRAP(ITEMP2,ILAT_ALP)
 ENDIF

 ZTEMP3BH=GRD%ROH
 DEALLOCATE(GRD%ROH)
 ALLOCATE(GRD%ROH(NEW_IM,GRD%JM,ROSH%NEOF))
 CALL WRAP(ZTEMP3BH,GRD%ROH,GRD%JM,ROSH%NEOF)

 ZTEMP3BH=GRD%ROH_AD
 DEALLOCATE(GRD%ROH_AD)
 ALLOCATE(GRD%ROH_AD(NEW_IM,GRD%JM,ROSH%NEOF))
 CALL WRAP(ZTEMP3BH,GRD%ROH_AD,GRD%JM,ROSH%NEOF)

 IF(ALLOCATED(GRD%MVLOC_H) ) THEN
  ZTEMP3F=GRD%MVLOC_H
  DEALLOCATE(GRD%MVLOC_H)
  ALLOCATE(GRD%MVLOC_H(NEW_IM,GRD%JM,ROSH%KMT))
  CALL WRAP(ZTEMP3F,GRD%MVLOC_H,GRD%JM,ROSH%KMT)
 ENDIF

ENDIF

IF( LL_4DVAR .OR. LL_TLMODEL) THEN
 
 ALLOCATE(ZTEMP4G(OLD_IM,GRD%JM,GRD%KM,NTS_TRAJ))

 ZTEMP3=TMASK
 DEALLOCATE(TMASK)
 ALLOCATE(TMASK(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,TMASK,GRD%JM,GRD%KM)
 ZTEMP3=UMASK
 DEALLOCATE(UMASK)
 ALLOCATE(UMASK(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,UMASK,GRD%JM,GRD%KM)
 ZTEMP3=VMASK
 DEALLOCATE(VMASK)
 ALLOCATE(VMASK(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,VMASK,GRD%JM,GRD%KM)
 ZTEMP2=E1T
 DEALLOCATE(E1T)
 ALLOCATE(E1T(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E1T)
 ZTEMP2=E2T
 DEALLOCATE(E2T)
 ALLOCATE(E2T(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E2T)
 ZTEMP2=E1U
 DEALLOCATE(E1U)
 ALLOCATE(E1U(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E1U)
 ZTEMP2=E2U
 DEALLOCATE(E2U)
 ALLOCATE(E2U(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E2U)
 ZTEMP2=E1V
 DEALLOCATE(E1V)
 ALLOCATE(E1V(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E1V)
 ZTEMP2=E2V
 DEALLOCATE(E2V)
 ALLOCATE(E2V(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E2V)

 ZTEMP2=E1UR
 DEALLOCATE(E1UR)
 ALLOCATE(E1UR(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E1UR)
 ZTEMP2=E2VR
 DEALLOCATE(E2VR)
 ALLOCATE(E2VR(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,E2VR)

 ZTEMP2=AHTU
 DEALLOCATE(AHTU)
 ALLOCATE(AHTU(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,AHTU)
 ZTEMP2=AHTV
 DEALLOCATE(AHTV)
 ALLOCATE(AHTV(NEW_IM,GRD%JM))
 CALL WRAP(ZTEMP2,AHTV)

 ZTEMP3=UBT
 DEALLOCATE(UBT)
 ALLOCATE(UBT(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,UBT,GRD%JM,GRD%KM)
 ZTEMP3=VBT
 DEALLOCATE(VBT)
 ALLOCATE(VBT(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,VBT,GRD%JM,GRD%KM)
 ZTEMP3=WBT
 DEALLOCATE(WBT)
 ALLOCATE(WBT(NEW_IM,GRD%JM,GRD%KM))
 CALL WRAP(ZTEMP3,WBT,GRD%JM,GRD%KM)

 ZTEMP4G=UB
 DEALLOCATE(UB)
 ALLOCATE(UB(NEW_IM,GRD%JM,GRD%KM,NTS_TRAJ))
 CALL WRAP(ZTEMP4G,UB,GRD%JM,GRD%KM,NTS_TRAJ)
 ZTEMP4G=VB
 DEALLOCATE(VB)
 ALLOCATE(VB(NEW_IM,GRD%JM,GRD%KM,NTS_TRAJ))
 CALL WRAP(ZTEMP4G,VB,GRD%JM,GRD%KM,NTS_TRAJ)
 ZTEMP4G=WB
 DEALLOCATE(WB)
 ALLOCATE(WB(NEW_IM,GRD%JM,GRD%KM,NTS_TRAJ))
 CALL WRAP(ZTEMP4G,WB,GRD%JM,GRD%KM,NTS_TRAJ)

 IF(LL_VDIFF .OR.LL_ADTEST) THEN
   ZTEMP3=AVBT
   DEALLOCATE(AVBT)
   ALLOCATE(AVBT(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,AVBT,GRD%JM,GRD%KM)
   ZTEMP4G=AVTB
   DEALLOCATE(AVTB)
   ALLOCATE(AVTB(NEW_IM,GRD%JM,GRD%KM,NTS_TRAJ))
   CALL WRAP(ZTEMP4G,AVTB,GRD%JM,GRD%KM,NTS_TRAJ)
 ENDIF

 IF(LL_SRFFLX .OR.LL_ADTEST) THEN
   ZTEMP3G=SSTB
   DEALLOCATE(SSTB)
   ALLOCATE(SSTB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,SSTB,GRD%JM,NTS_TRAJ)
   ZTEMP3G=SSSB
   DEALLOCATE(SSSB)
   ALLOCATE(SSSB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,SSSB,GRD%JM,NTS_TRAJ)
   ZTEMP3G=CEB
   DEALLOCATE(CEB)
   ALLOCATE(CEB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,CEB,GRD%JM,NTS_TRAJ)
   ZTEMP3G=CHB
   DEALLOCATE(CHB)
   ALLOCATE(CHB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,CHB,GRD%JM,NTS_TRAJ)
   ZTEMP3G=Q10B
   DEALLOCATE(Q10B)
   ALLOCATE(Q10B(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,Q10B,GRD%JM,NTS_TRAJ)
   ZTEMP3G=WNDB
   DEALLOCATE(WNDB)
   ALLOCATE(WNDB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,WNDB,GRD%JM,NTS_TRAJ)
   ZTEMP3G=EMPB
   DEALLOCATE(EMPB)
   ALLOCATE(EMPB(NEW_IM,GRD%JM,NTS_TRAJ))
   CALL WRAP(ZTEMP3G,EMPB,GRD%JM,NTS_TRAJ)

   ZTEMP2=TEM0
   DEALLOCATE(TEM0)
   ALLOCATE(TEM0(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,TEM0)
   ZTEMP2=SAL0
   DEALLOCATE(SAL0)
   ALLOCATE(SAL0(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,SAL0)
   ZTEMP2=CE
   DEALLOCATE(CE)
   ALLOCATE(CE(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,CE)
   ZTEMP2=CH
   DEALLOCATE(CH)
   ALLOCATE(CH(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,CH)
   ZTEMP2=Q10
   DEALLOCATE(Q10)
   ALLOCATE(Q10(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,Q10)
   ZTEMP2=WND
   DEALLOCATE(WND)
   ALLOCATE(WND(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,WND)
   ZTEMP2=EMP
   DEALLOCATE(EMP)
   ALLOCATE(EMP(NEW_IM,GRD%JM))
   CALL WRAP(ZTEMP2,EMP)
 ENDIF

 DEALLOCATE(ZTEMP4G)
 JPI= NEW_IM; JPJ=GRD%JM ; JPK=GRD%KM
 JPIM1=JPI-1 ; JPJM1=JPJ-1 ; JPKM1 = JPK-1

 IF( LL_WEAKLY ) THEN
   IF( LL_REDUCED_GRID ) THEN

     ITEMP2=WWKI
     DEALLOCATE(WWKI)
     ALLOCATE(WWKI(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,WWKI)
     ITEMP2=WWKJ
     DEALLOCATE(WWKJ)
     ALLOCATE(WWKJ(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,WWKJ)
     ITEMP2=WWKI2
     DEALLOCATE(WWKI2)
     ALLOCATE(WWKI2(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,WWKI2)
     ITEMP2=WWKJ2
     DEALLOCATE(WWKJ2)
     ALLOCATE(WWKJ2(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,WWKJ2)
     ZTEMP2=WWPI
     DEALLOCATE(WWPI)
     ALLOCATE(WWPI(NEW_IM,GRD%JM))
     CALL WRAP(ZTEMP2,WWPI)
     ZTEMP2=WWPJ
     DEALLOCATE(WWPJ)
     ALLOCATE(WWPJ(NEW_IM,GRD%JM))
     CALL WRAP(ZTEMP2,WWPJ)

   ELSE

     ALLOCATE(ZTEMP4G(OLD_IM,NYLR_WW,2*NZLR_WW,NTS_WW) )

     ZTEMP4G=WW
     DEALLOCATE(WW)
     ALLOCATE(WW(NEW_IM,NYLR_WW,2*NZLR_WW,NTS_WW) )
     CALL WRAP(ZTEMP4G,WW,GRD%JM,2*GRD%KM,NTS_WW)

     ZTEMP4G=WW_AD
     DEALLOCATE(WW_AD)
     ALLOCATE(WW_AD(NEW_IM,NYLR_WW,2*NZLR_WW,NTS_WW) )
     CALL WRAP(ZTEMP4G,WW_AD,GRD%JM,2*GRD%KM,NTS_WW)

     ZTEMP4G=WWT
     DEALLOCATE(WWT)
     ALLOCATE(WWT(NEW_IM,NYLR_WW,2*NZLR_WW,NTS_WW) )
     CALL WRAP(ZTEMP4G,WWT,GRD%JM,2*GRD%KM,NTS_WW)

     ZTEMP3F=WWT2
     DEALLOCATE(WWT2)
     ALLOCATE(WWT2(NEW_IM,NYLR_WW,2*NZLR_WW) )
     CALL WRAP(ZTEMP3F,WWT2,GRD%JM,2*GRD%KM)

     NXLR_WW = NEW_IM

     IF(.NOT. LL_WCEOF ) THEN
     ITEMP2=WREG
     DEALLOCATE(WREG)
     ALLOCATE(WREG(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,WREG)

     ITEMP2=NP
     DEALLOCATE(NP)
     ALLOCATE(NP(NEW_IM,GRD%JM))
     CALL WRAP(ITEMP2,NP)

     ITEMP3W=NPI
     DEALLOCATE(NPI)
     ALLOCATE(NPI(NEW_IM,GRD%JM,MAXP))
     CALL WRAP(ITEMP3W,NPI,GRD%JM,MAXP)

     ITEMP3W=NPJ
     DEALLOCATE(NPJ)
     ALLOCATE(NPJ(NEW_IM,GRD%JM,MAXP))
     CALL WRAP(ITEMP3W,NPJ,GRD%JM,MAXP)

     ZTEMP3W=ZC
     DEALLOCATE(ZC)
     ALLOCATE(ZC(NEW_IM,GRD%JM,MAXP))
     CALL WRAP(ZTEMP3W,ZC,GRD%JM,MAXP)

     ZTEMP2=WLON
     DEALLOCATE(WLON)
     ALLOCATE(WLON(NEW_IM,GRD%JM))
     CALL WRAP(ZTEMP2,WLON)

     ZTEMP2=WLAT
     DEALLOCATE(WLAT)
     ALLOCATE(WLAT(NEW_IM,GRD%JM))
     CALL WRAP(ZTEMP2,WLAT)

     DEALLOCATE(ZTEMP4G)

     NWD = NXLR_WW* NYLR_WW* NEOF_WW* NTS_WW
     NN_WEAKLY = ROSW%NEOF * NXLR_WW * NYLR_WW * NTS_WW

     DEALLOCATE ( ROW, ROW_AD )
     ALLOCATE ( ROW   ( NWD ) )
     ALLOCATE ( ROW_AD( NWD ) )
     ROW    = 0._R8
     ROW_AD = 0._R8

     CALL PREP_HORI

     ENDIF

   ENDIF

   ZTEMP3=TERR
   DEALLOCATE(TERR)
   ALLOCATE(TERR(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,TERR,GRD%JM,GRD%KM)
   ZTEMP3=SERR
   DEALLOCATE(SERR)
   ALLOCATE(SERR(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,SERR,GRD%JM,GRD%KM)
   ZTEMP3=TERR_AD
   DEALLOCATE(TERR_AD)
   ALLOCATE(TERR_AD(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,TERR_AD,GRD%JM,GRD%KM)
   ZTEMP3=SERR_AD
   DEALLOCATE(SERR_AD)
   ALLOCATE(SERR_AD(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,SERR_AD,GRD%JM,GRD%KM)

   IF( LL_SYSTERR ) THEN
   ZTEMP3=TERR_B
   DEALLOCATE(TERR_B)
   ALLOCATE(TERR_B(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,TERR_B,GRD%JM,GRD%KM)
   ZTEMP3=SERR_B
   DEALLOCATE(SERR_B)
   ALLOCATE(SERR_B(NEW_IM,GRD%JM,GRD%KM))
   CALL WRAP(ZTEMP3,SERR_B,GRD%JM,GRD%KM)
   ENDIF

 ENDIF

ENDIF

IF( NCONF .NE. 202) THEN

#ifdef opt_huge_memory

! EVA
IF(ALLOCATED(ROS%EVA))THEN
ZTEMP3B=ROS%EVA
DEALLOCATE(ROS%EVA)
ALLOCATE(ROS%EVA(NEW_IM,GRD%JM,ROS%NEOF))
CALL WRAP(ZTEMP3B,ROS%EVA,GRD%JM,ROS%NEOF )
ENDIF

! EVC
IF(ALLOCATED(ROS%EVC))THEN
ALLOCATE(ZTEMP4C(OLD_IM,GRD%JM,ROS%KMT,ROS%NEOF))
ZTEMP4C=ROS%EVC
DEALLOCATE(ROS%EVC)
ALLOCATE(ROS%EVC(NEW_IM,GRD%JM,ROS%KMT,ROS%NEOF))
CALL WRAP(ZTEMP4C,ROS%EVC,GRD%JM,ROS%KMT,ROS%NEOF)
ENDIF

#endif

! PSV
ZTEMP3F=PSV
DEALLOCATE(PSV)
ALLOCATE(PSV(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
CALL WRAP(ZTEMP3F,PSV,GRD%JM,PSV3D*GRD%KM+PSV2D)

! PSV_AD
ZTEMP3F=PSV_AD
DEALLOCATE(PSV_AD)
ALLOCATE(PSV_AD(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
CALL WRAP(ZTEMP3F,PSV_AD,GRD%JM,PSV3D*GRD%KM+PSV2D)

NULLIFY(GRD%TEM)
NULLIFY(GRD%SAL)
NULLIFY(GRD%UVL)
NULLIFY(GRD%VVL)
NULLIFY(GRD%ETA)
NULLIFY(GRD%SST)
NULLIFY(GRD%SSS)
NULLIFY(GRD%T2M)
NULLIFY(GRD%Q2M)
NULLIFY(GRD%SIC)
NULLIFY(GRD%SIT)
NULLIFY(GRD%ICU)
NULLIFY(GRD%ICV)
NULLIFY(GRD%TEM_AD)
NULLIFY(GRD%SAL_AD)
NULLIFY(GRD%UVL_AD)
NULLIFY(GRD%VVL_AD)
NULLIFY(GRD%ETA_AD)
NULLIFY(GRD%SST_AD)
NULLIFY(GRD%SSS_AD)
NULLIFY(GRD%T2M_AD)
NULLIFY(GRD%Q2M_AD)
NULLIFY(GRD%SIC_AD)
NULLIFY(GRD%SIT_AD)
NULLIFY(GRD%ICU_AD)
NULLIFY(GRD%ICV_AD)

     KSV=0
     IF( LL_TS ) THEN
       GRD%TEM => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%TEM_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
       GRD%SAL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%SAL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
     ENDIF
     IF( LL_UV ) THEN
       GRD%UVL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%UVL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
       GRD%VVL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%VVL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
     ENDIF
     IF( LL_SSH) THEN
       GRD%ETA => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ETA_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_SST) THEN
       GRD%SST => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SST_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_SSS) THEN
       GRD%SSS => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SSS_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_TQ2) THEN
       GRD%T2M => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%T2M_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%Q2M => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%Q2M_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_ICE) THEN
       GRD%SIC => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SIC_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%SIT => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SIT_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%ICU => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ICU_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%ICV => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ICV_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF

ENDIF

    IF( LLRFSR .AND. NNRFSR .EQ. 2 ) THEN
        CALL ABOR1('EXTGRID: LLRFSR .AND. NNRFSR .EQ. 2 NOT YET SUPPORTED')
    ENDIF

    IF( LLRFSR .AND. NNRFSR .EQ. 1 .AND. NCONF .NE. 301 ) THEN

        ! SR_SCXT
        ZTEMP3=SR_SCXT
        DEALLOCATE(SR_SCXT)
        ALLOCATE(SR_SCXT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_SCXT,GRD%JM,GRD%KM)
        ! SR_SCYT
        ZTEMP3=SR_SCYT
        DEALLOCATE(SR_SCYT)
        ALLOCATE(SR_SCYT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_SCYT,GRD%JM,GRD%KM)
        ! SR_SCXS
        ZTEMP3=SR_SCXS
        DEALLOCATE(SR_SCXS)
        ALLOCATE(SR_SCXS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_SCXS,GRD%JM,GRD%KM)
        ! SR_SCYS
        ZTEMP3=SR_SCYS
        DEALLOCATE(SR_SCYS)
        ALLOCATE(SR_SCYS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_SCYS,GRD%JM,GRD%KM)

        ! SR_GALXT
        ZTEMP3=SR_GALXT
        DEALLOCATE(SR_GALXT)
        ALLOCATE(SR_GALXT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GALXT,GRD%JM,GRD%KM)
        ! SR_GALYT
        ZTEMP3=SR_GALYT
        DEALLOCATE(SR_GALYT)
        ALLOCATE(SR_GALYT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GALYT,GRD%JM,GRD%KM)
        ! SR_GALXS
        ZTEMP3=SR_GALXS
        DEALLOCATE(SR_GALXS)
        ALLOCATE(SR_GALXS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GALXS,GRD%JM,GRD%KM)
        ! SR_GALYS
        ZTEMP3=SR_GALYS
        DEALLOCATE(SR_GALYS)
        ALLOCATE(SR_GALYS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GALYS,GRD%JM,GRD%KM)

        ! SR_GBTXT
        ZTEMP3=SR_GBTXT
        DEALLOCATE(SR_GBTXT)
        ALLOCATE(SR_GBTXT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GBTXT,GRD%JM,GRD%KM)
        ! SR_GBTYT
        ZTEMP3=SR_GBTYT
        DEALLOCATE(SR_GBTYT)
        ALLOCATE(SR_GBTYT(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GBTYT,GRD%JM,GRD%KM)
        ! SR_GBTXS
        ZTEMP3=SR_GBTXS
        DEALLOCATE(SR_GBTXS)
        ALLOCATE(SR_GBTXS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GBTXS,GRD%JM,GRD%KM)
        ! SR_GBTYS
        ZTEMP3=SR_GBTYS
        DEALLOCATE(SR_GBTYS)
        ALLOCATE(SR_GBTYS(NEW_IM,GRD%JM,GRD%KM))
        CALL WRAP(ZTEMP3,SR_GBTYS,GRD%JM,GRD%KM)

    ENDIF

        IF( NCONF.NE.202.AND.NCONF.NE.301) THEN
          ! CRX
          ZTEMP3F=CRX
          DEALLOCATE(CRX)
          ALLOCATE(CRX(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
          CALL WRAP(ZTEMP3F,CRX,GRD%JM,PSV3D*GRD%KM+PSV2D)
          ! CRY
          ZTEMP3F=CRY
          DEALLOCATE(CRY)
          ALLOCATE(CRY(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
          CALL WRAP(ZTEMP3F,CRY,GRD%JM,PSV3D*GRD%KM+PSV2D)

          IF(LL_HYBRID_CR) THEN
            ! CRFX
            ZTEMP3F=CRFX
            DEALLOCATE(CRFX)
            ALLOCATE(CRFX(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
            CALL WRAP(ZTEMP3F,CRFX,GRD%JM,PSV3D*GRD%KM+PSV2D)
            ! CRFY
            ZTEMP3F=CRFY
            DEALLOCATE(CRFY)
            ALLOCATE(CRFY(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
            CALL WRAP(ZTEMP3F,CRFY,GRD%JM,PSV3D*GRD%KM+PSV2D)
          ENDIF

        ENDIF
  
        IF( LLVARMDT .OR. NCONF.EQ.202) THEN
          ! CRMX
          ZTEMP2=CRMX
          DEALLOCATE(CRMX)
          ALLOCATE(CRMX(NEW_IM,GRD%JM))
          CALL WRAP(ZTEMP2,CRMX)
          ! CRMY
          ZTEMP2=CRMY
          DEALLOCATE(CRMY)
          ALLOCATE(CRMY(NEW_IM,GRD%JM))
          CALL WRAP(ZTEMP2,CRMY)
        ENDIF

! VARMDT
IF(LLVARMDT .OR. NCONF.EQ.202) THEN
    ZTEMP2=GRD%CMDT
    DEALLOCATE(GRD%CMDT)
    ALLOCATE(GRD%CMDT(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,GRD%CMDT)

    ZTEMP2=GRD%CMDT_AD
    DEALLOCATE(GRD%CMDT_AD)
    ALLOCATE(GRD%CMDT_AD(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,GRD%CMDT_AD)

    ZTEMP2=GRD%CMDT_STDEV
    DEALLOCATE(GRD%CMDT_STDEV)
    ALLOCATE(GRD%CMDT_STDEV(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,GRD%CMDT_STDEV)
ENDIF

IF( DRV%BAL(DRV%KTR) .EQ. 1 ) THEN
    ZTEMP3=BAL_TEMB
    DEALLOCATE(BAL_TEMB)
    ALLOCATE(BAL_TEMB(NEW_IM,GRD%JM,GRD%KM))
    CALL WRAP(ZTEMP3,BAL_TEMB,GRD%JM,GRD%KM)

    ZTEMP3=BAL_SALB
    DEALLOCATE(BAL_SALB)
    ALLOCATE(BAL_SALB(NEW_IM,GRD%JM,GRD%KM))
    CALL WRAP(ZTEMP3,BAL_SALB,GRD%JM,GRD%KM)
ENDIF

IF( DRV%BA2(DRV%KTR) .EQ. 1 ) THEN

    ZTEMP2=ZTEM0
    DEALLOCATE(ZTEM0)
    ALLOCATE(ZTEM0(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZTEM0)

    ZTEMP2=ZCE
    DEALLOCATE(ZCE)
    ALLOCATE(ZCE(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZCE)

    ZTEMP2=ZCH
    DEALLOCATE(ZCH)
    ALLOCATE(ZCH(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZCH)

    ZTEMP2=ZQ10
    DEALLOCATE(ZQ10)
    ALLOCATE(ZQ10(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZQ10)

    ZTEMP2=ZWND
    DEALLOCATE(ZWND)
    ALLOCATE(ZWND(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZWND)

    ZTEMP2=ZBLH
    DEALLOCATE(ZBLH)
    ALLOCATE(ZBLH(NEW_IM,GRD%JM))
    CALL WRAP(ZTEMP2,ZBLH)

ENDIF


IF ( LL_EOFS3D ) THEN

 ! PSE
 ZTEMP3F=PSE
 DEALLOCATE(PSE)
 ALLOCATE(PSE(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
 CALL WRAP(ZTEMP3F,PSE,GRD%JM,PSV3D*GRD%KM+PSV2D)

 ! PSE_AD
 ZTEMP3F=PSE_AD
 DEALLOCATE(PSE_AD)
 ALLOCATE(PSE_AD(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
 CALL WRAP(ZTEMP3F,PSE_AD,GRD%JM,PSV3D*GRD%KM+PSV2D)

 IF( ALLOCATED(ZTEMP4C) ) DEALLOCATE(ZTEMP4C)
 ALLOCATE(ZTEMP4C(OLD_IM,GRD%JM,NEKMT,NN_EOFS3D))

 ZTEMP4C=EIVES
 DEALLOCATE(EIVES)
 ALLOCATE(EIVES(NEW_IM,GRD%JM,NEKMT,NN_EOFS3D))
 CALL WRAP(ZTEMP4C,EIVES,GRD%JM,NEKMT,NN_EOFS3D)

ENDIF

GRD%NPS = GRD%IM*GRD%JM*GRD%KM

WRITE(IOUNLOG,*) ' /// END OF GRID EXTENSION ///'
WRITE(IOUNLOG,*)
WRITE(IOUNOUT,*) '                     DONE!'

DEALLOCATE(ZTEMP2,ZTEMP3,ITEMP2,ITEMP3,ZTEMP3B,ZTEMP3D,ITEMP3W,&
& ZTEMP3W, ZTEMP3F,ZTEMP3G,ZTEMP3BH)

#ifdef opt_huge_memory
DEALLOCATE(ZTEMP4C,ZTEMP3E)
#endif
IF( ALLOCATED(ZTEMP4C) ) DEALLOCATE(ZTEMP4C)

CALL MYFRTPROF_WALL('DOEXTGRID: GRID EXTENSION ROUTINE',1)

END SUBROUTINE DOEXTGRID

!=======================================================

SUBROUTINE UNDOEXTGRID

!== MAIN SUBROUTINE FOR REMOVING EXTENSION OF GRID (A.S.)

IMPLICIT NONE

INTEGER(I4) :: KSV

CALL MYFRTPROF_WALL('UNDOEXTGRID: REMOVE GRID EXTENSION',0)

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// REMOVING GRID EXTENSION ///'
WRITE(IOUNLOG,*)
WRITE(IOUNOUT,*) ' REMOVING GRID EXTENSION:'

IF(.NOT.LLEXTGRID) THEN
  WRITE(IOUNLOG,*) ' UNDOEXTGRID: NOTHING TO DO'
  RETURN
ELSE
  WRITE(IOUNLOG,*) ' UNDOEXTGRID: NWRAPS = ',NWRAPS
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' == PARAMETERS == '
WRITE(IOUNLOG,*) ' OLD_IM',OLD_IM
WRITE(IOUNLOG,*) ' NEW_IM',NEW_IM
WRITE(IOUNLOG,*) ' FRST  ',FRST
WRITE(IOUNLOG,*) ' LST   ',LST
WRITE(IOUNLOG,*) ' FRST2 ',FRST2
WRITE(IOUNLOG,*) ' LST2  ',LST2

CALL FLUSH(IOUNLOG)

! FROM NOW ONWARDS GRD%IM WILL BE DEFINITIVELY
! RELATED TO THE ORIGINAL (I.E. PHYSICAL) GRID.
GRD%IM = OLD_IM

WRITE(IOUNLOG,*) ' ALLOCATING'
CALL FLUSH(IOUNLOG)

ALLOCATE(ZTEMP2(NEW_IM,GRD%JM),ZTEMP3(NEW_IM,GRD%JM,GRD%KM))
ALLOCATE(ZTEMP3B(NEW_IM,GRD%JM,ROS%NEOF))
ALLOCATE(ZTEMP3D(NEW_IM,GRD%JM,NTOTV))
#ifdef opt_huge_memory
ALLOCATE(ZTEMP3E(NEW_IM,JMAX,NTOTV))
#endif
ALLOCATE(ZTEMP3F(NEW_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
ALLOCATE(ITEMP2(NEW_IM,GRD%JM))
ALLOCATE(ITEMP3(NEW_IM,GRD%JM,NTOTV))

! LONGITUDE
ZTEMP2=GRD%LON
DEALLOCATE(GRD%LON)
ALLOCATE(GRD%LON(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%LON)

! LATITUDE
ZTEMP2=GRD%LAT
DEALLOCATE(GRD%LAT)
ALLOCATE(GRD%LAT(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%LAT)

! REGIONS
ITEMP2=GRD%REG
DEALLOCATE(GRD%REG)
ALLOCATE(GRD%REG(OLD_IM,GRD%JM))
CALL DEWRAP(ITEMP2,GRD%REG)

! MASK
ZTEMP3=GRD%MSK
DEALLOCATE(GRD%MSK)
ALLOCATE(GRD%MSK(OLD_IM,GRD%JM,GRD%KM))
CALL DEWRAP(ZTEMP3,GRD%MSK,GRD%JM,GRD%KM)

! MVLOC
ZTEMP3F=GRD%MVLOC
DEALLOCATE(GRD%MVLOC)
ALLOCATE(GRD%MVLOC(OLD_IM,GRD%JM,ROS%KMT))
CALL DEWRAP(ZTEMP3F,GRD%MVLOC,GRD%JM,ROS%KMT)

! HGT
ZTEMP2=GRD%HGT
DEALLOCATE(GRD%HGT)
ALLOCATE(GRD%HGT(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%HGT)

! ICE
IF(LL_ICEINIT) THEN
ZTEMP2=GRD%ICE
DEALLOCATE(GRD%ICE)
ALLOCATE(GRD%ICE(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%ICE)
ENDIF

! DISTC
ZTEMP2=GRD%DISTC
DEALLOCATE(GRD%DISTC)
ALLOCATE(GRD%DISTC(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%DISTC)

! F
ZTEMP2=GRD%F
DEALLOCATE(GRD%F)
ALLOCATE(GRD%F(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%F)

! B_X
ZTEMP3=GRD%B_X
DEALLOCATE(GRD%B_X)
ALLOCATE(GRD%B_X(OLD_IM,GRD%JM,GRD%KM))
CALL DEWRAP(ZTEMP3,GRD%B_X,GRD%JM,GRD%KM)

! B_Y
ZTEMP3=GRD%B_Y
DEALLOCATE(GRD%B_Y)
ALLOCATE(GRD%B_Y(OLD_IM,GRD%JM,GRD%KM))
CALL DEWRAP(ZTEMP3,GRD%B_Y,GRD%JM,GRD%KM)

! DNS
ZTEMP3=GRD%DNS
DEALLOCATE(GRD%DNS)
ALLOCATE(GRD%DNS(OLD_IM,GRD%JM,GRD%KM))
CALL DEWRAP(ZTEMP3,GRD%DNS,GRD%JM,GRD%KM)

! BX
ZTEMP2=GRD%BX
DEALLOCATE(GRD%BX )
ALLOCATE(GRD%BX (OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%BX)

! BY
ZTEMP2=GRD%BY
DEALLOCATE(GRD%BY )
ALLOCATE(GRD%BY (OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%BY)

! MDT
ZTEMP2=GRD%MDT
DEALLOCATE(GRD%MDT)
ALLOCATE(GRD%MDT(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%MDT)

! SLA
ZTEMP2=GRD%SLA
DEALLOCATE(GRD%SLA)
ALLOCATE(GRD%SLA(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%SLA)

! DX
ZTEMP2=GRD%DX
DEALLOCATE(GRD%DX)
ALLOCATE(GRD%DX(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%DX)

! DY
ZTEMP2=GRD%DY
DEALLOCATE(GRD%DY)
ALLOCATE(GRD%DY(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%DY)

! DXDY
ZTEMP2=GRD%DXDY
DEALLOCATE(GRD%DXDY)
ALLOCATE(GRD%DXDY(OLD_IM,GRD%JM))
CALL DEWRAP(ZTEMP2,GRD%DXDY)

! MSR
ZTEMP3=GRD%MSR
DEALLOCATE(GRD%MSR)
ALLOCATE(GRD%MSR(OLD_IM,GRD%JM,GRD%KM))
CALL DEWRAP(ZTEMP3,GRD%MSR,GRD%JM,GRD%KM)

IF( DRV%BAL(DRV%KTR) .EQ. 1 ) THEN
    ZTEMP3=BAL_TEMB
    DEALLOCATE(BAL_TEMB)
    ALLOCATE(BAL_TEMB(OLD_IM,GRD%JM,GRD%KM))
    CALL DEWRAP(ZTEMP3,BAL_TEMB,GRD%JM,GRD%KM)

    ZTEMP3=BAL_SALB
    DEALLOCATE(BAL_SALB)
    ALLOCATE(BAL_SALB(OLD_IM,GRD%JM,GRD%KM))
    CALL DEWRAP(ZTEMP3,BAL_SALB,GRD%JM,GRD%KM)
ENDIF

IF(NCONF .NE. 202) THEN
! RO
ZTEMP3B=GRD%RO
DEALLOCATE(GRD%RO)
ALLOCATE(GRD%RO(OLD_IM,GRD%JM,ROS%NEOF))
CALL DEWRAP(ZTEMP3B,GRD%RO,GRD%JM,ROS%NEOF)

! RO_AD
ZTEMP3B=GRD%RO_AD
DEALLOCATE(GRD%RO_AD)
ALLOCATE(GRD%RO_AD(OLD_IM,GRD%JM,ROS%NEOF))
CALL DEWRAP(ZTEMP3B,GRD%RO_AD,GRD%JM,ROS%NEOF)
ENDIF

CALL FLUSH(IOUNLOG)

IF(NCONF .NE. 202) THEN
#ifdef opt_huge_memory

! EVA
ZTEMP3B=ROS%EVA
DEALLOCATE(ROS%EVA)
ALLOCATE(ROS%EVA(OLD_IM,GRD%JM,ROS%NEOF))
CALL DEWRAP(ZTEMP3B,ROS%EVA,GRD%JM,ROS%NEOF )

! EVC
ALLOCATE(ZTEMP4C(NEW_IM,GRD%JM,ROS%KMT,ROS%NEOF))
ZTEMP4C=ROS%EVC
DEALLOCATE(ROS%EVC)
ALLOCATE(ROS%EVC(OLD_IM,GRD%JM,ROS%KMT,ROS%NEOF))
CALL DEWRAP(ZTEMP4C,ROS%EVC,GRD%JM,ROS%KMT,ROS%NEOF)

#endif
CALL FLUSH(IOUNLOG)

! PSV
ZTEMP3F=PSV
DEALLOCATE(PSV)
ALLOCATE(PSV(OLD_IM,GRD%JM,PSV3D*GRD%KM+PSV2D))
CALL DEWRAP(ZTEMP3F,PSV,GRD%JM,PSV3D*GRD%KM+PSV2D)
CALL FLUSH(IOUNLOG)

NULLIFY(GRD%TEM)
NULLIFY(GRD%SAL)
NULLIFY(GRD%UVL)
NULLIFY(GRD%VVL)
NULLIFY(GRD%ETA)
NULLIFY(GRD%SST)
NULLIFY(GRD%SSS)
NULLIFY(GRD%T2M)
NULLIFY(GRD%Q2M)
NULLIFY(GRD%SIC)
NULLIFY(GRD%SIT)
NULLIFY(GRD%ICU)
NULLIFY(GRD%ICV)
NULLIFY(GRD%TEM_AD)
NULLIFY(GRD%SAL_AD)
NULLIFY(GRD%UVL_AD)
NULLIFY(GRD%VVL_AD)
NULLIFY(GRD%ETA_AD)
NULLIFY(GRD%SST_AD)
NULLIFY(GRD%SSS_AD)
NULLIFY(GRD%T2M_AD)
NULLIFY(GRD%Q2M_AD)
NULLIFY(GRD%SIC_AD)
NULLIFY(GRD%SIT_AD)
NULLIFY(GRD%ICU_AD)
NULLIFY(GRD%ICV_AD)
CALL FLUSH(IOUNLOG)

     KSV=0
     IF( LL_TS ) THEN
       GRD%TEM => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%TEM_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
       GRD%SAL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%SAL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
     ENDIF
     IF( LL_UV ) THEN
       GRD%UVL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%UVL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
       GRD%VVL => PSV(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       GRD%VVL_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1:KSV+GRD%KM)
       KSV=KSV+GRD%KM
     ENDIF
     IF( LL_SSH) THEN
       GRD%ETA => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ETA_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_SST) THEN
       GRD%SST => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SST_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_SSS) THEN
       GRD%SSS => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SSS_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_TQ2) THEN
       GRD%T2M => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%T2M_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%Q2M => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%Q2M_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF
     IF( LL_ICE) THEN
       GRD%SIC => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SIC_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%SIT => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%SIT_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%ICU => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ICU_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
       GRD%ICV => PSV(1:GRD%IM,1:GRD%JM,KSV+1)
       GRD%ICV_AD => PSV_AD(1:GRD%IM,1:GRD%JM,KSV+1)
       KSV=KSV+1
     ENDIF

ENDIF

! VARMDT
IF(LLVARMDT .OR. NCONF .EQ. 202) THEN
    ZTEMP2=GRD%CMDT
    DEALLOCATE(GRD%CMDT)
    ALLOCATE(GRD%CMDT(OLD_IM,GRD%JM))
    CALL DEWRAP(ZTEMP2,GRD%CMDT)

    ZTEMP2=GRD%CMDT_AD
    DEALLOCATE(GRD%CMDT_AD)
    ALLOCATE(GRD%CMDT_AD(OLD_IM,GRD%JM))
    CALL DEWRAP(ZTEMP2,GRD%CMDT_AD)

    ZTEMP2=GRD%CMDT_STDEV
    DEALLOCATE(GRD%CMDT_STDEV)
    ALLOCATE(GRD%CMDT_STDEV(OLD_IM,GRD%JM))
    CALL DEWRAP(ZTEMP2,GRD%CMDT_STDEV)
ENDIF

GRD%NPS = GRD%IM*GRD%JM*GRD%KM

WRITE(IOUNLOG,*) ' /// END OF GRID EXTENSION ///'
WRITE(IOUNLOG,*)
WRITE(IOUNOUT,*) '                     DONE!'
CALL FLUSH(IOUNLOG)

DEALLOCATE(ZTEMP2,ZTEMP3,ITEMP2,ITEMP3,ZTEMP3B,ZTEMP3D,&
& ZTEMP3F)

#ifdef opt_huge_memory
DEALLOCATE(ZTEMP4C,ZTEMP3E)
#endif

CALL MYFRTPROF_WALL('UNDOEXTGRID: REMOVE GRID EXTENSION',1)

END SUBROUTINE UNDOEXTGRID

!=======================================================

SUBROUTINE WRAP2DR(ZLON,ZVAR)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:)
REAL(R8),INTENT(IN) :: ZLON(OLD_IM,GRD%JM)

ZVAR(FRST:LST,:) = ZLON(2:OLD_IM-1,:)
ZVAR(LST2:NEW_IM,:) = ZLON(2:NWRAPS+1,:)
ZVAR(1:FRST2,:) = ZLON(OLD_IM-NWRAPS:OLD_IM-1,:)

END SUBROUTINE WRAP2DR

!=======================================================

SUBROUTINE WRAP3DR(ZLON,ZVAR,I2A,I3A)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:,:)
INTEGER(I4),INTENT(IN) :: I2A,I3A
REAL(R8),INTENT(IN) :: ZLON(OLD_IM,I2A,I3A)

ZVAR(FRST:LST,:,:) = ZLON(2:OLD_IM-1,:,:)
ZVAR(LST2:NEW_IM,:,:) = ZLON(2:NWRAPS+1,:,:)
ZVAR(1:FRST2,:,:) = ZLON(OLD_IM-NWRAPS:OLD_IM-1,:,:)

END SUBROUTINE WRAP3DR

!=======================================================

SUBROUTINE WRAP4DR(ZLON,ZVAR,I2B,I3B,I4B)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:,:,:)
INTEGER(I4),INTENT(IN) :: I2B,I3B,I4B
REAL(R8),INTENT(IN) :: ZLON(OLD_IM,I2B,I3B,I4B)

ZVAR(FRST:LST,:,:,:) = ZLON(2:OLD_IM-1,:,:,:)
ZVAR(LST2:NEW_IM,:,:,:) = ZLON(2:NWRAPS+1,:,:,:)
ZVAR(1:FRST2,:,:,:) = ZLON(OLD_IM-NWRAPS:OLD_IM-1,:,:,:)

END SUBROUTINE WRAP4DR

!=======================================================

SUBROUTINE WRAP2DI(ZLON,ZVAR)
IMPLICIT NONE

INTEGER(I4), INTENT(INOUT) :: ZVAR(:,:)
INTEGER(I4),INTENT(IN) :: ZLON(OLD_IM,GRD%JM)

ZVAR(FRST:LST,:) = ZLON(2:OLD_IM-1,:)
ZVAR(LST2:NEW_IM,:) = ZLON(2:NWRAPS+1,:)
ZVAR(1:FRST2,:) = ZLON(OLD_IM-NWRAPS:OLD_IM-1,:)

END SUBROUTINE WRAP2DI

!=======================================================

SUBROUTINE WRAP3DI(ZLON,ZVAR,I2,I3)
IMPLICIT NONE

INTEGER(I4), INTENT(INOUT) :: ZVAR(:,:,:)
INTEGER(I4),INTENT(IN) :: I2,I3
INTEGER(I4),INTENT(IN) :: ZLON(OLD_IM,I2,I3)

ZVAR(FRST:LST,:,:) = ZLON(2:OLD_IM-1,:,:)
ZVAR(LST2:NEW_IM,:,:) = ZLON(2:NWRAPS+1,:,:)
ZVAR(1:FRST2,:,:) = ZLON(OLD_IM-NWRAPS:OLD_IM-1,:,:)

END SUBROUTINE WRAP3DI

!=======================================================

SUBROUTINE DEWRAP2DR(ZLON,ZVAR)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:)
REAL(R8),INTENT(IN) :: ZLON(NEW_IM,GRD%JM)

ZVAR(:,:) = ZLON(FRST2:LST2,:)

END SUBROUTINE DEWRAP2DR

!=======================================================

SUBROUTINE DEWRAP3DR(ZLON,ZVAR,I2C,I3C)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:,:)
INTEGER(I4),INTENT(IN) :: I2C,I3C
REAL(R8),INTENT(IN) :: ZLON(NEW_IM,I2C,I3C)

ZVAR(:,:,:) = ZLON(FRST2:LST2,:,:)

END SUBROUTINE DEWRAP3DR

!=======================================================

SUBROUTINE DEWRAP4DR(ZLON,ZVAR,I2D,I3D,I4D)
IMPLICIT NONE

REAL(R8), INTENT(INOUT) :: ZVAR(:,:,:,:)
INTEGER(I4),INTENT(IN) :: I2D,I3D,I4D
REAL(R8),INTENT(IN) :: ZLON(NEW_IM,I2D,I3D,I4D)

ZVAR(:,:,:,:) = ZLON(FRST2:LST2,:,:,:)

END SUBROUTINE DEWRAP4DR

!=======================================================

SUBROUTINE DEWRAP2DI(ZLON,ZVAR)
IMPLICIT NONE

INTEGER(I4),INTENT(INOUT) :: ZVAR(:,:)
INTEGER(I4),INTENT(IN) :: ZLON(NEW_IM,GRD%JM)

ZVAR(:,:) = ZLON(FRST2:LST2,:)

END SUBROUTINE DEWRAP2DI

!=======================================================

SUBROUTINE DEWRAP3DI(ZLON,ZVAR,I2E,I3E)
IMPLICIT NONE

INTEGER(I4), INTENT(INOUT) :: ZVAR(:,:,:)
INTEGER(I4),INTENT(IN) :: I2E,I3E
INTEGER(I4),INTENT(IN) :: ZLON(NEW_IM,I2E,I3E)

ZVAR(:,:,:) = ZLON(FRST2:LST2,:,:)

END SUBROUTINE DEWRAP3DI

!=======================================================

SUBROUTINE DOOBSREARR

! MAIN ROUTINE FOR REARRANGING OBS
! ACCORDING TO THE EXTENDED GRID
! WE SAVE THE NUMBER OF GOOD OBS
! SO THAT, AS LLRE04MIN IS REQUIRED,
! WE JUST DELETE LAST GOOD OBS
! FROM OBS VECTOR

IMPLICIT NONE

INTEGER(I4) :: I,K,NMAX

CALL MYFRTPROF_WALL('DOOBSREARR: REARRANGE OBS FOR EXTENDED GRID',0)

WRITE(IOUNOUT,*)
WRITE(IOUNLOG,*)
WRITE(IOUNOUT,*) ' REARRANGING OBS'
WRITE(IOUNLOG,*) ' /// REARRANGING OBS'

CALL FLUSH(IOUNLOG)

IF(.NOT.LLINCALLED) CALL EXTGRID_INIT

OBS_DIFF = NWRAPS - 1

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' == PARAMETERS == '
WRITE(IOUNLOG,*) ' OLD_IM',OLD_IM
WRITE(IOUNLOG,*) ' NEW_IM',NEW_IM
WRITE(IOUNLOG,*) ' FRST  ',FRST
WRITE(IOUNLOG,*) ' LST   ',LST
WRITE(IOUNLOG,*) ' FRST2 ',FRST2
WRITE(IOUNLOG,*) ' LST2  ',LST2
WRITE(IOUNLOG,*) ' OBS_DIFF',OBS_DIFF

IF(.NOT.LLDUPLOBS) WRITE(IOUNLOG,*) ' NO OBS DUPLICATION!'

! SLA OBSERVATIONS
   K=SLA%NO
   IF ( K .GT. 0 ) THEN
   NMAX=SIZE(SLA%FLC)
   DO I=1,SLA%NO

    IF(SLA%FLC(I).EQ.1)THEN

      IF(SLA%IB(I,1).GE.OLD_IM-NWRAPS .AND. LLDUPLOBS) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SLA%FLC(K) = 1
         SLA%BOT(K) = SLA%BOT(I)
         SLA%TDIST(K) = SLA%TDIST(I)
         SLA%LON  (K) = SLA%LON  (I)
         SLA%LAT  (K) = SLA%LAT  (I)
         SLA%TIM  (K) = SLA%TIM  (I)
         SLA%VAL  (K) = SLA%VAL  (I)
         SLA%BAC  (K) = SLA%BAC  (I)
         SLA%INC  (K) = SLA%INC  (I)
         SLA%BIA  (K) = SLA%BIA  (I)
         SLA%ERR  (K) = SLA%ERR  (I)
         SLA%RES  (K) = SLA%RES  (I)
         SLA%IB (K,:) = SLA%IB   (I,:)-(OLD_IM-NWRAPS)+1
         SLA%JB (K,:) = SLA%JB   (I,:)
         SLA%PQ (K,:) = SLA%PQ   (I,:)
         SLA%DPT  (K) = SLA%DPT  (I)
         IF ( NCONF .NE. 202 ) THEN
           SLA%TB (K,:) = SLA%TB   (I,:)
           SLA%SB (K,:) = SLA%SB   (I,:)
           SLA%BCP(K,:) = SLA%BCP  (I,:)
         ENDIF
         SLA%NIND (K) = SLA%NIND (I)
         SLA%INO  (K) = SLA%INO  (I)
         SLA%TRACK(K) = SLA%TRACK(I)
         SLA%EVE  (K) = SLA%EVE  (I)
         SLA%KSAT (K) = SLA%KSAT (I)
         SLA%B_A  (K) = SLA%B_A  (I)
         SLA%BGERR(K) = SLA%BGERR(I)
      ENDIF

      IF( SLA%IB(I,1).LE.NWRAPS+1 .AND. LLDUPLOBS .AND. &
        & SLA%IB(I,1)+LST2-2 .LT. NEW_IM ) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SLA%FLC(K) = 1
         SLA%BOT(K) = SLA%BOT(I)
         SLA%TDIST(K) = SLA%TDIST(I)
         SLA%LON  (K) = SLA%LON  (I)
         SLA%LAT  (K) = SLA%LAT  (I)
         SLA%TIM  (K) = SLA%TIM  (I)
         SLA%VAL  (K) = SLA%VAL  (I)
         SLA%BAC  (K) = SLA%BAC  (I)
         SLA%INC  (K) = SLA%INC  (I)
         SLA%BIA  (K) = SLA%BIA  (I)
         SLA%ERR  (K) = SLA%ERR  (I)
         SLA%RES  (K) = SLA%RES  (I)
         SLA%IB (K,:) = SLA%IB   (I,:)+LST2-2
         SLA%JB (K,:) = SLA%JB   (I,:)
         SLA%PQ (K,:) = SLA%PQ   (I,:)
         SLA%DPT  (K) = SLA%DPT  (I)
         IF ( NCONF .NE. 202 ) THEN
           SLA%TB (K,:) = SLA%TB   (I,:)
           SLA%SB (K,:) = SLA%SB   (I,:)
           SLA%BCP(K,:) = SLA%BCP  (I,:)
         ENDIF
         SLA%NIND (K) = SLA%NIND (I)
         SLA%INO  (K) = SLA%INO  (I)
         SLA%TRACK(K) = SLA%TRACK(I)
         SLA%EVE  (K) = SLA%EVE  (I)
         SLA%KSAT (K) = SLA%KSAT (I)
         SLA%B_A  (K) = SLA%B_A  (I)
         SLA%BGERR(K) = SLA%BGERR(I)
      ENDIF

      SLA%IB(I,:)=SLA%IB(I,:)+OBS_DIFF
      IF(ANY(SLA%IB(I,:).EQ.NEW_IM)) SLA%FLC(I)=0

    ENDIF
   ENDDO
   WRITE(IOUNOUT,*) ' ORIGINAL      SLA : ',SLA%NO
   WRITE(IOUNOUT,*) ' DUPLICATED    SLA : ',K-SLA%NO
   OLD_SLA_NO=COUNT(SLA%FLC(1:SLA%NO)==1)
   WRITE(IOUNOUT,*) ' ORIGINAL GOOD SLA : ',OLD_SLA_NO
   SLA%NO=K
   ENDIF


! SST OBSERVATIONS
   K=SST%NO
   IF ( K .GT. 0 ) THEN
   NMAX=SIZE(SST%FLC)
   DO I=1,SST%NO

    IF(SST%FLC(I).EQ.1)THEN

      IF(SST%IB(I,1).GE.OLD_IM-NWRAPS .AND. LLDUPLOBS) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SST%FLC(K) = 1
         SST%TDIST(K) = SST%TDIST(I)
         SST%LON  (K) = SST%LON  (I)
         SST%LAT  (K) = SST%LAT  (I)
         SST%TIM  (K) = SST%TIM  (I)
         SST%VAL  (K) = SST%VAL  (I)
         SST%BAC  (K) = SST%BAC  (I)
         SST%INC  (K) = SST%INC  (I)
         SST%BIA  (K) = SST%BIA  (I)
         SST%ERR  (K) = SST%ERR  (I)
         SST%RES  (K) = SST%RES  (I)
         SST%IB (K,:) = SST%IB   (I,:)-(OLD_IM-NWRAPS)+1
         SST%JB (K,:) = SST%JB   (I,:)
         SST%PQ (K,:) = SST%PQ   (I,:)
         SST%BCP(K,:) = SST%BCP  (I,:)
         SST%TRACK(K) = SST%TRACK(I)
         SST%EVE  (K) = SST%EVE  (I)
         SST%KSAT (K) = SST%KSAT (I)
         SST%B_A  (K) = SST%B_A  (I)
         SST%BGERR(K) = SST%BGERR(I)
         SST%NIND (K) = SST%NIND (I)
      ENDIF

      IF( SST%IB(I,1).LE.NWRAPS+1 .AND. LLDUPLOBS .AND. &
        & SST%IB(I,1)+LST2-2 .LT. NEW_IM ) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SST%FLC(K) = 1
         SST%TDIST(K) = SST%TDIST(I)
         SST%LON  (K) = SST%LON  (I)
         SST%LAT  (K) = SST%LAT  (I)
         SST%TIM  (K) = SST%TIM  (I)
         SST%VAL  (K) = SST%VAL  (I)
         SST%BAC  (K) = SST%BAC  (I)
         SST%INC  (K) = SST%INC  (I)
         SST%BIA  (K) = SST%BIA  (I)
         SST%ERR  (K) = SST%ERR  (I)
         SST%RES  (K) = SST%RES  (I)
         SST%IB (K,:) = SST%IB   (I,:)+LST2-2
         SST%JB (K,:) = SST%JB   (I,:)
         SST%PQ (K,:) = SST%PQ   (I,:)
         SST%BCP(K,:) = SST%BCP  (I,:)
         SST%TRACK(K) = SST%TRACK(I)
         SST%EVE  (K) = SST%EVE  (I)
         SST%KSAT (K) = SST%KSAT (I)
         SST%B_A  (K) = SST%B_A  (I)
         SST%BGERR(K) = SST%BGERR(I)
         SST%NIND (K) = SST%NIND (I)
      ENDIF

      SST%IB(I,:)=SST%IB(I,:)+OBS_DIFF
      IF(ANY(SST%IB(I,:).EQ.NEW_IM)) SST%FLC(I)=0

    ENDIF
   ENDDO
   WRITE(IOUNOUT,*) ' ORIGINAL      SST : ',SST%NO
   WRITE(IOUNOUT,*) ' DUPLICATED    SST : ',K-SST%NO
   OLD_SST_NO=COUNT(SST%FLC(1:SST%NO)==1)
   WRITE(IOUNOUT,*) ' ORIGINAL GOOD SST : ',OLD_SST_NO
   SST%NO=K
   ENDIF

! SSS OBSERVATIONS
   K=SSS%NO
   IF ( K .GT. 0 ) THEN
   NMAX=SIZE(SSS%FLC)
   DO I=1,SSS%NO

    IF(SSS%FLC(I).EQ.1)THEN

      IF(SSS%IB(I,1).GE.OLD_IM-NWRAPS .AND. LLDUPLOBS) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SSS%FLC(K) = 1
         SSS%TDIST(K) = SSS%TDIST(I)
         SSS%LON  (K) = SSS%LON  (I)
         SSS%LAT  (K) = SSS%LAT  (I)
         SSS%TIM  (K) = SSS%TIM  (I)
         SSS%VAL  (K) = SSS%VAL  (I)
         SSS%BAC  (K) = SSS%BAC  (I)
         SSS%INC  (K) = SSS%INC  (I)
         SSS%BIA  (K) = SSS%BIA  (I)
         SSS%ERR  (K) = SSS%ERR  (I)
         SSS%RES  (K) = SSS%RES  (I)
         SSS%IB (K,:) = SSS%IB   (I,:)-(OLD_IM-NWRAPS)+1
         SSS%JB (K,:) = SSS%JB   (I,:)
         SSS%PQ (K,:) = SSS%PQ   (I,:)
         SSS%TRACK(K) = SSS%TRACK(I)
         SSS%EVE  (K) = SSS%EVE  (I)
         SSS%KSAT (K) = SSS%KSAT (I)
         SSS%B_A  (K) = SSS%B_A  (I)
         SSS%BGERR(K) = SSS%BGERR(I)
         SSS%NIND (K) = SSS%NIND (I)
      ENDIF

      IF( SSS%IB(I,1).LE.NWRAPS+1 .AND. LLDUPLOBS .AND. &
        & SSS%IB(I,1)+LST2-2 .LT. NEW_IM ) THEN ! NEW OBS
         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         SSS%FLC(K) = 1
         SSS%TDIST(K) = SSS%TDIST(I)
         SSS%LON  (K) = SSS%LON  (I)
         SSS%LAT  (K) = SSS%LAT  (I)
         SSS%TIM  (K) = SSS%TIM  (I)
         SSS%VAL  (K) = SSS%VAL  (I)
         SSS%BAC  (K) = SSS%BAC  (I)
         SSS%INC  (K) = SSS%INC  (I)
         SSS%BIA  (K) = SSS%BIA  (I)
         SSS%ERR  (K) = SSS%ERR  (I)
         SSS%RES  (K) = SSS%RES  (I)
         SSS%IB (K,:) = SSS%IB   (I,:)+LST2-2
         SSS%JB (K,:) = SSS%JB   (I,:)
         SSS%PQ (K,:) = SSS%PQ   (I,:)
         SSS%TRACK(K) = SSS%TRACK(I)
         SSS%EVE  (K) = SSS%EVE  (I)
         SSS%KSAT (K) = SSS%KSAT (I)
         SSS%B_A  (K) = SSS%B_A  (I)
         SSS%BGERR(K) = SSS%BGERR(I)
         SSS%NIND (K) = SSS%NIND (I)
      ENDIF

      SSS%IB(I,:)=SSS%IB(I,:)+OBS_DIFF
      IF(ANY(SSS%IB(I,:).EQ.NEW_IM)) SSS%FLC(I)=0

    ENDIF
   ENDDO
   WRITE(IOUNOUT,*) ' ORIGINAL      SSS : ',SSS%NO
   WRITE(IOUNOUT,*) ' DUPLICATED    SSS : ',K-SSS%NO
   OLD_SSS_NO=COUNT(SSS%FLC(1:SSS%NO)==1)
   WRITE(IOUNOUT,*) ' ORIGINAL GOOD SSS : ',OLD_SSS_NO
   SSS%NO=K
   ENDIF


! INS OBSERVATIONS
   K=INS%NO
   IF ( K .GT. 0 ) THEN
   NMAX=SIZE(INS%FLC)
   WRITE(IOUNLOG,*) ' SIZE OF INSITU VECTOR IS ',NMAX ; CALL FLUSH(IOUNLOG)
   DO I=1,INS%NO

    IF(INS%FLC(I).EQ.1)THEN

      IF(INS%IB(I,1).GE.OLD_IM-NWRAPS .AND. LLDUPLOBS) THEN ! NEW OBS

         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         INS%FLC(K) = 1
         INS%TDIST(K) = INS%TDIST(I)
         INS%OTYPE(K) = INS%OTYPE(I)
         INS%PAR  (K) = INS%PAR  (I)
         INS%PLNO (K) = INS%PLNO (I)
         INS%KTY  (K) = INS%KTY  (I)
         INS%LON  (K) = INS%LON  (I)
         INS%LAT  (K) = INS%LAT  (I)
         INS%DPT  (K) = INS%DPT  (I)
         INS%TIM  (K) = INS%TIM  (I)
         INS%VAL  (K) = INS%VAL  (I)
         INS%BAC  (K) = INS%BAC  (I)
         INS%INC  (K) = INS%INC  (I)
         INS%BIA  (K) = INS%BIA  (I)
         INS%ERR  (K) = INS%ERR  (I)
         INS%RES  (K) = INS%RES  (I)
         INS%IB (K,:) = INS%IB   (I,:)-(OLD_IM-NWRAPS)+1
         INS%JB (K,:) = INS%JB   (I,:)
         INS%PQ (K,:) = INS%PQ   (I,:)
         INS%KB   (K) = INS%KB   (I)
         INS%BGERR(K) = INS%BGERR(I)
         INS%RB   (K) = INS%RB   (I)
         INS%PROF (K) = INS%PROF (I)
         INS%B_A  (K) = INS%B_A  (I)
         INS%EVE  (K) = INS%EVE  (I)
         INS%INST (K) = INS%INST (I)
         INS%INO  (K) = INS%INO  (I)
         INS%FLG  (K) = INS%FLG  (I)
         INS%NIND (K) = INS%NIND (I)
         INS%DSRC (K) = INS%DSRC (I)
      ENDIF

      IF(INS%IB(I,1).LE.NWRAPS+1 .AND. LLDUPLOBS .AND. &
       & INS%IB(I,1)+LST2-2 .LT. NEW_IM ) THEN ! NEW OBS

         K=K+1
         IF(K.GT.NMAX) CALL ABOR1('DOOBSREARR: NMAX SHOULD BE INCREASED')
         INS%FLC(K) = 1
         INS%TDIST(K) = INS%TDIST(I)
         INS%OTYPE(K) = INS%OTYPE(I)
         INS%PAR  (K) = INS%PAR  (I)
         INS%PLNO (K) = INS%PLNO (I)
         INS%KTY  (K) = INS%KTY  (I)
         INS%LON  (K) = INS%LON  (I)
         INS%LAT  (K) = INS%LAT  (I)
         INS%DPT  (K) = INS%DPT  (I)
         INS%TIM  (K) = INS%TIM  (I)
         INS%VAL  (K) = INS%VAL  (I)
         INS%BAC  (K) = INS%BAC  (I)
         INS%INC  (K) = INS%INC  (I)
         INS%BIA  (K) = INS%BIA  (I)
         INS%ERR  (K) = INS%ERR  (I)
         INS%RES  (K) = INS%RES  (I)
         INS%IB (K,:) = INS%IB   (I,:)+LST2-2
         INS%JB (K,:) = INS%JB   (I,:)
         INS%PQ (K,:) = INS%PQ   (I,:)
         INS%KB   (K) = INS%KB   (I)
         INS%BGERR(K) = INS%BGERR(I)
         INS%RB   (K) = INS%RB   (I)
         INS%PROF (K) = INS%PROF (I)
         INS%B_A  (K) = INS%B_A  (I)
         INS%EVE  (K) = INS%EVE  (I)
         INS%INST (K) = INS%INST (I)
         INS%INO  (K) = INS%INO  (I)
         INS%FLG  (K) = INS%FLG  (I)
         INS%NIND (K) = INS%NIND (I)
         INS%DSRC (K) = INS%DSRC (I)
      ENDIF

      INS%IB(I,:)=INS%IB(I,:)+OBS_DIFF
      IF(ANY(INS%IB(I,:).EQ.NEW_IM) ) INS%FLC(I)=0

    ENDIF
   ENDDO
   WRITE(IOUNOUT,*) ' ORIGINAL      INS : ',INS%NO
   WRITE(IOUNOUT,*) ' DUPLICATED    INS : ',K-INS%NO
   OLD_INS_NO=COUNT(INS%FLC(1:INS%NO)==1)
   !! OLD_INS_NO=INS%NO
   WRITE(IOUNOUT,*) ' ORIGINAL GOOD INS : ',OLD_INS_NO
   INS%NO=K
   ENDIF

WRITE(IOUNOUT,*) '                 DONE!'

CALL FLUSH(IOUNLOG)
CALL FLUSH(IOUNOUT)

CALL MYFRTPROF_WALL('DOOBSREARR: REARRANGE OBS FOR EXTENDED GRID',1)

END SUBROUTINE DOOBSREARR

!=======================================================

SUBROUTINE UNDOOBSREARR

IMPLICIT NONE
INTEGER(I4) :: I
INTEGER(I4) :: NSLA, NINS, NSST, NSSS, K

SLA%NO = OLD_SLA_NO
INS%NO = OLD_INS_NO
SST%NO = OLD_SST_NO
SSS%NO = OLD_SSS_NO
OBS%NO = OLD_INS_NO+OLD_SLA_NO+OLD_SST_NO+OLD_SSS_NO

DO I=1,INS%NO
    IF(INS%FLC(I).EQ.1)THEN
      INS%IB(I,:)=INS%IB(I,:) - OBS_DIFF
    ENDIF
ENDDO

DO I=1,SLA%NO
    IF(SLA%FLC(I).EQ.1)THEN
      SLA%IB(I,:)=SLA%IB(I,:) - OBS_DIFF
    ENDIF
ENDDO

DO I=1,SST%NO
    IF(SST%FLC(I).EQ.1)THEN
      SST%IB(I,:)=SST%IB(I,:) - OBS_DIFF
    ENDIF
ENDDO

DO I=1,SSS%NO
    IF(SSS%FLC(I).EQ.1)THEN
      SSS%IB(I,:)=SSS%IB(I,:) - OBS_DIFF
    ENDIF
ENDDO

NSLA = 0
NINS = 0
NSST = 0
NSSS = 0

IF( SLA%NO .GT. 0 ) &
NSLA   = COUNT(SLA%FLC(1:SLA%NO)==1)
IF( INS%NO .GT. 0 ) &
NINS   = COUNT(INS%FLC(1:INS%NO)==1)
IF( SST%NO .GT. 0 ) &
NSST   = COUNT(SST%FLC(1:SST%NO)==1)
IF( SSS%NO .GT. 0 ) &
NSSS   = COUNT(SSS%FLC(1:SSS%NO)==1)
OBS%NO = NSLA+NINS+NSST+NSSS

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ====== TOTAL NUMBER OF OBS ',&
               & 'AFTER THE MINIMIZATION ======'
WRITE(IOUNOUT,*) ' NUMBER OF OBSERVATIONS: ', OBS%NO
WRITE(IOUNOUT,*) '           OF WHICH SLA: ',NSLA
WRITE(IOUNOUT,*) '                    INS: ',NINS
WRITE(IOUNOUT,*) '                    SST: ',NSST
WRITE(IOUNOUT,*) '                    SSS: ',NSSS
WRITE(IOUNLOG,*) ' NUMBER OF OBSERVATIONS: ', OBS%NO
WRITE(IOUNLOG,*) '           OF WHICH SLA: ',NSLA
WRITE(IOUNLOG,*) '                    INS: ',NINS
WRITE(IOUNLOG,*) '                    SST: ',NSST
WRITE(IOUNLOG,*) '                    SSS: ',NSSS

CALL FLUSH(IOUNLOG)

K=0

! SLA OBSERVATIONS
   DO I=1,SLA%NO
    IF(SLA%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SLA%INC(I)
     OBS%RES(K) = SLA%RES(I)
     OBS%ERR(K) = SLA%ERR(I)
    ENDIF
   ENDDO

! INS OBSERVATIONS
   DO I=1,INS%NO
    IF(INS%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = INS%INC(I)
     OBS%RES(K) = INS%RES(I)
     OBS%ERR(K) = INS%ERR(I)
    ENDIF
   ENDDO

! SST OBSERVATIONS
   DO I=1,SST%NO
    IF(SST%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SST%INC(I)
     OBS%RES(K) = SST%RES(I)
     OBS%ERR(K) = SST%ERR(I)
    ENDIF
   ENDDO

! SSS OBSERVATIONS
   DO I=1,SSS%NO
    IF(SSS%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SSS%INC(I)
     OBS%RES(K) = SSS%RES(I)
     OBS%ERR(K) = SSS%ERR(I)
    ENDIF
   ENDDO

END SUBROUTINE UNDOOBSREARR

!=======================================================

END MODULE EXTGRID
