MODULE BAL_AIRSEA

USE SET_KND
USE MYNETCDF
USE GRD_STR
USE BMD_STR
USE RUN

IMPLICIT NONE

LOGICAL, PRIVATE, SAVE :: LL_INIT = .FALSE.

REAL(R8) , ALLOCATABLE, DIMENSION(:,:) :: &
& ZTEM0,ZCE,ZCH,ZBLH,ZQ10,ZWND,ZTAML,ZQAML

REAL(R8) :: RDT_AML

CONTAINS

!------------------------------------------------------------------

SUBROUTINE BAL2M_TL

USE MPIREL

IMPLICIT NONE
REAL(R8) :: ZTAML,ZQAML

IF(.NOT.LL_INIT) THEN
   CALL ABOR1('BAL2M_TL CALLED WITHOUT MODULE INITIALIZATION')
ENDIF

IF( .NOT. LL_TQ2_UNBALANCED ) THEN
   GRD%T2M = 0._R8
   GRD%Q2M = 0._R8
ENDIF

CALL SRFBAL_TL(RDT_AML,ZTEM0,GRD%TEM(:,:,1),ZCE,ZCH,ZBLH,ZQ10,ZWND,GRD%T2M,GRD%Q2M)

END SUBROUTINE BAL2M_TL

!------------------------------------------------------------------

SUBROUTINE BAL2M_AD

USE MPIREL

IMPLICIT NONE
REAL(R8),ALLOCATABLE, DIMENSION(:,:) :: SST_AD

ALLOCATE( SST_AD(GRD%IM,GRD%JM) )
SST_AD = 0._R8

CALL SRFBAL_AD(RDT_AML,ZTEM0,SST_AD,ZCE,ZCH,ZBLH,ZQ10,ZWND,GRD%T2M_AD,GRD%Q2M_AD)

GRD%TEM_AD(:,:,1) = GRD%TEM_AD(:,:,1) + SST_AD

DEALLOCATE( SST_AD )

END SUBROUTINE BAL2M_AD

!------------------------------------------------------------------

SUBROUTINE INIT_BAL_AS

IMPLICIT NONE

CHARACTER(LEN=99) :: CF
REAL(R8), PARAMETER :: ZBLHMIN = 100._R8

ALLOCATE(ZTEM0(GRD%IM,GRD%JM),ZCE(GRD%IM,GRD%JM),&
& ZCH(GRD%IM,GRD%JM),ZBLH(GRD%IM,GRD%JM),&
& ZQ10(GRD%IM,GRD%JM),ZWND(GRD%IM,GRD%JM) )

CF='amlb.nc'
CALL GETNCVAR(CF,'sosstsst',GRD%IM,GRD%JM,ZTEM0)
CALL GETNCVAR(CF,'sotrcfce',GRD%IM,GRD%JM,ZCE)
CALL GETNCVAR(CF,'sotrcfch',GRD%IM,GRD%JM,ZCH)
CALL GETNCVAR(CF,'sotrcfq1',GRD%IM,GRD%JM,ZQ10)
CALL GETNCVAR(CF,'sowindsp',GRD%IM,GRD%JM,ZWND)
CALL GETNCVAR(CF,'sopblhgt',GRD%IM,GRD%JM,ZBLH)

WHERE( ZBLH .LT. ZBLHMIN ) ZBLH = ZBLHMIN

LL_INIT= .TRUE.

END SUBROUTINE INIT_BAL_AS

!------------------------------------------------------------------

END MODULE BAL_AIRSEA
