MODULE READOBAS103

! MODULE FOR READING OBSERVATIONS
! FROM ASCII FILE
!
! A.STORTO 01.10.2010

USE IOUNITS
USE SET_KND
USE OBSDEF
USE OBS_STR
USE GRD_STR
USE RUN

IMPLICIT NONE

INTEGER(I4), PARAMETER :: IOBASUN = 219
REAL   (R8), PARAMETER :: PNOERR = -999._R8

CONTAINS

SUBROUTINE GETOASN(IOBS)

! GET THE OBSERVATIONS AMOUNT BY TYPE

IMPLICIT NONE

INTEGER(I4), INTENT(OUT) :: IOBS(NOFAMS)
INTEGER(I4) :: IERR, IFAILED, IFAM
CHARACTER(LEN=999) :: CSTR

IOBS = 0
IFAILED = 0

OPEN(IOBASUN,FILE='OBSIN.DAT',STATUS='OLD',IOSTAT=IERR)
IF(IERR .NE. 0) THEN
   WRITE(IOUNERR,*) 'OPENING OBSIN.DAT RETURNED ',IERR
   CALL ABOR1('PROBLEMS OPENING OBSIN.DAT')
ENDIF

READ(IOBASUN,*,IOSTAT=IERR) IOBS(1:NOFAMS)
IF(IERR.NE.0) THEN
   WRITE(IOUNERR,*) 'READING OBSIN.DAT RETURNED ',IERR
   CALL ABOR1('PROBLEMS READING OBSIN.DAT')
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' *** REPORT FROM GETOASN'
WRITE(IOUNLOG,*) '-----------------------------------'
WRITE(IOUNLOG,*) ' NUMBER OF INSITU OBS ',IOBS(NNINS)
WRITE(IOUNLOG,*) ' NUMBER OF SLA    OBS ',IOBS(NNSLA)
WRITE(IOUNLOG,*) ' NUMBER OF SST    OBS ',IOBS(NNSST)
WRITE(IOUNLOG,*) ' NUMBER OF SSS    OBS ',IOBS(NNSSS)
WRITE(IOUNLOG,*) '-----------------------------------'
WRITE(IOUNLOG,*) ' NUMBER OF FAILED OBS ',IFAILED
WRITE(IOUNLOG,*) ' TOTAL NUMBER OF  OBS ',SUM(IOBS)
WRITE(IOUNLOG,*)

REWIND(IOBASUN)
CLOSE(IOBASUN)
END SUBROUTINE GETOASN

SUBROUTINE GETOASOBS

! GET THE OBSERVATIONAL DATA

IMPLICIT NONE

INTEGER(I4) :: IERR, IFAILED, IFAM
INTEGER(I4) :: IOBS(NOFAMS)
INTEGER(I4) :: KK, ITYPE, IINST, IPAR, INO, IAUX
REAL(R8)    :: ZLON, ZLAT, ZDPT, ZTIM, ZVAL, ZERR

IOBS = 0
IFAILED = 0

OPEN(IOBASUN,FILE='OBSIN.DAT',STATUS='OLD',IOSTAT=IERR)
IF(IERR .NE. 0) THEN
   WRITE(IOUNERR,*) 'OPENING OBSIN.DAT RETURNED ',IERR
   CALL ABOR1('PROBLEMS OPENING OBSIN.DAT')
ENDIF
READ(IOBASUN,*,IOSTAT=IERR) IOBS(1:NOFAMS)

DO KK=1,IOBS(NNINS)
             WRITE(IOUNLOG,*) ' POPULATING OBS NUMBER ', KK
             CALL FLUSH(IOUNLOG)
             INS%FLC (KK) = 1
             INS%FLG (KK) = 1
             INS%NIND(KK) = KK
             INS%PLNO(KK) = 'ASCIIOBS'
             INS%INO (KK) = 1
             INS%INST(KK) = 1
             INS%EVE (KK) = 0
             INS%PROF(KK) = KK
             READ(IOBASUN,*,IOSTAT=IERR) INS%OTYPE(KK), INS%PAR(KK), &
             & INS%KTY(KK), INS%TDIST(KK), INS%LON(KK), INS%LAT(KK), INS%DPT(KK), &
             & INS%TIM(KK), INS%VAL(KK), INS%BIA(KK), INS%IB(KK,:), INS%JB(KK,:), &
             & INS%KB(KK), INS%RB(KK),&
             & INS%PQ(KK,:), &
             & INS%BAC(KK), INS%RES(KK)
ENDDO

DO KK=1,IOBS(NNSLA)
             SLA%FLC (KK) = 1
             SLA%FLG (KK) = 1
             SLA%EVE (KK) = 0
             SLA%NIND(KK) = KK
             SLA%INO (KK) = KK
             SLA%TRACK(KK)= KK
             READ(IOBASUN,*,IOSTAT=IERR) SLA%KSAT(KK), SLA%TDIST(KK), &
             & SLA%LON(KK), SLA%LAT(KK), SLA%BOT, &
             & SLA%TIM(KK), SLA%VAL(KK), SLA%BIA(KK), SLA%IB(KK,:), SLA%JB(KK,:), &
             & SLA%PQ(KK,:), &
             & SLA%BAC(KK), SLA%RES(KK), SLA%BCP(KK,1:NPRD_SLA), &
             & SLA%TB(KK,1:GRD%KM),SLA%SB(KK,1:GRD%KM)
ENDDO

DO KK=1,IOBS(NNSST)
             SST%FLC (KK) = 1
             SST%FLG (KK) = 1
             SST%EVE (KK) = 0
             SST%NIND(KK) = KK
             SST%TRACK(KK)= KK
             READ(IOBASUN,*,IOSTAT=IERR) SST%KSAT(KK), SST%TDIST(KK), &
             & SST%LON(KK), SST%LAT(KK), SST%ERR, &
             & SST%TIM(KK), SST%VAL(KK), SST%BIA(KK), SST%IB(KK,:), SST%JB(KK,:), &
             & SST%PQ (KK,:), &
             & SST%BAC(KK), SST%RES(KK), SST%BCP(KK,1:NPRD_SST)
ENDDO

DO KK=1,IOBS(NNSSS)
             SSS%FLC (KK) = 1
             SSS%FLG (KK) = 1
             SSS%EVE (KK) = 0
             SSS%NIND(KK) = KK
             SSS%TRACK(KK)= KK
             READ(IOBASUN,*,IOSTAT=IERR) SSS%KSAT(KK), SSS%TDIST(KK), &
             & SSS%LON(KK), SSS%LAT(KK), SSS%ERR, &
             & SSS%TIM(KK), SSS%VAL(KK), SSS%BIA(KK), SSS%IB(KK,:), SSS%JB(KK,:), &
             & SSS%PQ (KK,:), &
             & SSS%BAC(KK), SSS%RES(KK)
ENDDO

CLOSE(IOBASUN)

WRITE(IOUNLOG,*) ' FAILED OBS = ', IFAILED
WRITE(IOUNLOG,*) ' INSITU OBS = ', KK

END SUBROUTINE GETOASOBS

END MODULE READOBAS103
