MODULE STATS

!.. PROVIDE BASIC STATISTICS COMPUTATIONAL ROUTINES
USE SET_KND
IMPLICIT NONE

PRIVATE

INTERFACE MEAN
MODULE PROCEDURE MEAN_I1, MEAN_I2, MEAN_I3,&
               & MEAN_R1, MEAN_R2, MEAN_R3
END INTERFACE MEAN

INTERFACE STDEV
MODULE PROCEDURE STDEV_I1, STDEV_I2, STDEV_I3,&
               & STDEV_R1, STDEV_R2, STDEV_R3
END INTERFACE STDEV

PUBLIC :: MEAN,STDEV

CONTAINS

REAL(R8) FUNCTION MEAN_I1(I1,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I1(:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(I1,MASK=MASK),KIND=R8)/REAL(SIZE(I1),KIND=R8)
ELSE
   RES=REAL(SUM(I1),KIND=R8)/REAL(SIZE(I1),KIND=R8)
ENDIF
MEAN_I1=RES
END FUNCTION MEAN_I1

REAL(R8) FUNCTION MEAN_R1(R1,MASK)
IMPLICIT NONE
REAL(R8), INTENT(IN) :: R1(:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(R1,MASK=MASK),KIND=R8)/REAL(SIZE(R1),KIND=R8)
ELSE
   RES=REAL(SUM(R1),KIND=R8)/REAL(SIZE(R1),KIND=R8)
ENDIF
MEAN_R1=RES
END FUNCTION MEAN_R1

REAL(R8) FUNCTION MEAN_I2(I2,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I2(:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(I2,MASK=MASK),KIND=R8)/REAL(SIZE(I2),KIND=R8)
ELSE
   RES=REAL(SUM(I2),KIND=R8)/REAL(SIZE(I2),KIND=R8)
ENDIF
MEAN_I2=RES
END FUNCTION MEAN_I2

REAL(R8) FUNCTION MEAN_R2(R2,MASK)
IMPLICIT NONE
REAL(R8), INTENT(IN) :: R2(:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(R2,MASK=MASK),KIND=R8)/REAL(SIZE(R2),KIND=R8)
ELSE
   RES=REAL(SUM(R2),KIND=R8)/REAL(SIZE(R2),KIND=R8)
ENDIF
MEAN_R2=RES
END FUNCTION MEAN_R2

REAL(R8) FUNCTION MEAN_I3(I3,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I3(:,:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(I3,MASK=MASK),KIND=R8)/REAL(SIZE(I3),KIND=R8)
ELSE
   RES=REAL(SUM(I3),KIND=R8)/REAL(SIZE(I3),KIND=R8)
ENDIF
MEAN_I3=RES
END FUNCTION MEAN_I3

REAL(R8) FUNCTION MEAN_R3(R3,MASK)
IMPLICIT NONE
REAL(R8), INTENT(IN) :: R3(:,:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=REAL(SUM(R3,MASK=MASK),KIND=R8)/REAL(SIZE(R3),KIND=R8)
ELSE
   RES=REAL(SUM(R3),KIND=R8)/REAL(SIZE(R3),KIND=R8)
ENDIF
MEAN_R3=RES
END FUNCTION MEAN_R3

!================================================================

REAL(R8) FUNCTION STDEV_I1(I1,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I1(:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(I1,MASK=MASK)
   RES=REAL(SUM((I1-RES)*(I1-RES),MASK=MASK),KIND=R8)/REAL(SIZE(I1),KIND=R8)
ELSE
   RES=MEAN(I1)
   RES=REAL(SUM((I1-RES)*(I1-RES)),KIND=R8)/REAL(SIZE(I1),KIND=R8)
ENDIF
STDEV_I1=SQRT(RES)
END FUNCTION STDEV_I1

REAL(R8) FUNCTION STDEV_R1(R1,MASK)
IMPLICIT NONE
REAL(R8)   , INTENT(IN) :: R1(:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(R1,MASK=MASK)
   RES=REAL(SUM((R1-RES)*(R1-RES),MASK=MASK),KIND=R8)/REAL(COUNT(MASK),KIND=R8)
ELSE
   RES=MEAN(R1)
   RES=REAL(SUM((R1-RES)*(R1-RES)),KIND=R8)/REAL(SIZE(R1),KIND=R8)
ENDIF
STDEV_R1=SQRT(RES)
END FUNCTION STDEV_R1

REAL(R8) FUNCTION STDEV_I2(I2,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I2(:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(I2,MASK=MASK)
   RES=REAL(SUM((I2-RES)*(I2-RES),MASK=MASK),KIND=R8)/REAL(SIZE(I2),KIND=R8)
ELSE
   RES=MEAN(I2)
   RES=REAL(SUM((I2-RES)*(I2-RES)),KIND=R8)/REAL(SIZE(I2),KIND=R8)
ENDIF
STDEV_I2=SQRT(RES)
END FUNCTION STDEV_I2

REAL(R8) FUNCTION STDEV_R2(R2,MASK)
IMPLICIT NONE
REAL(R8)   , INTENT(IN) :: R2(:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(R2,MASK=MASK)
   RES=REAL(SUM((R2-RES)*(R2-RES),MASK=MASK),KIND=R8)/REAL(SIZE(R2),KIND=R8)
ELSE
   RES=MEAN(R2)
   RES=REAL(SUM((R2-RES)*(R2-RES)),KIND=R8)/REAL(SIZE(R2),KIND=R8)
ENDIF
STDEV_R2=SQRT(RES)
END FUNCTION STDEV_R2

REAL(R8) FUNCTION STDEV_I3(I3,MASK)
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: I3(:,:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(I3,MASK=MASK)
   RES=REAL(SUM((I3-RES)*(I3-RES),MASK=MASK),KIND=R8)/REAL(SIZE(I3),KIND=R8)
ELSE
   RES=MEAN(I3)
   RES=REAL(SUM((I3-RES)*(I3-RES)),KIND=R8)/REAL(SIZE(I3),KIND=R8)
ENDIF
STDEV_I3=SQRT(RES)
END FUNCTION STDEV_I3

REAL(R8) FUNCTION STDEV_R3(R3,MASK)
IMPLICIT NONE
REAL(R8)   , INTENT(IN) :: R3(:,:,:)
LOGICAL, INTENT(IN),OPTIONAL :: MASK(:,:,:)
REAL(R8) :: RES
IF(PRESENT(MASK)) THEN
   RES=MEAN(R3,MASK=MASK)
   RES=REAL(SUM((R3-RES)*(R3-RES),MASK=MASK),KIND=R8)/REAL(SIZE(R3),KIND=R8)
ELSE
   RES=MEAN(R3)
   RES=REAL(SUM((R3-RES)*(R3-RES)),KIND=R8)/REAL(SIZE(R3),KIND=R8)
ENDIF
STDEV_R3=SQRT(RES)
END FUNCTION STDEV_R3


END MODULE STATS
