SUBROUTINE MPRFTOALL(COPT,VAR)

USE MPI
USE SET_KND

IF( COPT .EQ. 'X' ) THEN
  DO JP=1,NNPROCS
    CALL MPI_BCAST(VAR(:,MJSA(JP):MJEA(JP),:),MJCA(JP),MPI_DOUBLE,&
    & JP-1,MPICOMM,IERR)
  ENDDO
ELSEIF( COPT .EQ. 'Y' ) THEN
  DO JP=1,NNPROCS
    CALL MPI_BCAST(VAR(MISA(JP):MIEA(JP),:,:),MICA(JP),MPI_DOUBLE,&
    & JP-1,MPICOMM,IERR)
  ENDDO
ELSE
  CALL ABOR1('WRONG OPTION IN MPRFTOALL')
ENDIF

END SUBROUTINE MPRFTOALL
