SUBROUTINE OBS_VEC2

!-----------------------------------------------------------------------
!                                                                      !
! CREATE THE OBSERVATIONAL VECTOR                                      !
!                                                                      !
! VERSION 1: ANDREA STORTO, 2009, FORM OBS VECTOR FOR COBSOPT 'NEW'    !
!-----------------------------------------------------------------------


 USE SET_KND
 USE OBS_STR
 USE IOUNITS, ONLY : IOUNERR, IOUNLOG, IOUNOUT
 USE RANDOM_NUMBERS
 USE OBSHANDLING, ONLY : LLPERTOBS,NSEED,ZRFACT
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE RUN, ONLY : IDOUBLEDOM
 USE MPIREL
 USE CERES
 USE EXTGRID, ONLY : LLEXTGRID

 IMPLICIT NONE

  INTEGER(I4)    ::  K, I, KP,IGR
  INTEGER(I4)    ::  NINS,NSLA,NSST,NSSS
  REAL(R8), ALLOCATABLE :: ZXR(:)
  REAL(R8), DIMENSION(NOFAMS) :: ZINNMIN, ZINNMAX
  LOGICAL :: LLREO4MIN
  INTEGER(I4)    ::  KSEED
  TYPE(RANDOMNUMBERSTREAM) :: GOLUM

! DEFINE OBSERVATIONAL VECTOR

  CALL MYFRTPROF_WALL('OBS_VEC2: FORM OBS VECTOR',0)
  LLREO4MIN=.TRUE.

  IF(.NOT.LLREO4MIN .AND. LLEXTGRID .AND. IDOUBLEDOM .LT. 2)&
  & CALL ABOR1('LLEXTGRID CANNOT PROCEED IF NOT LLRE04MIN')

  IF (LLREO4MIN .AND. IDOUBLEDOM .LT. 2) THEN
    WRITE(IOUNLOG,*) ' CALLING REO4MIN ' ; CALL FLUSH(IOUNLOG)
    CALL REO4MIN
    WRITE(IOUNLOG,*) ' CALLED REO4MIN ' ; CALL FLUSH(IOUNLOG)
  ENDIF

    NSLA = 0
    NINS = 0
    NSST = 0
    NSSS = 0

    IF( SLA%NO .GT. 0 ) &
    NSLA   = COUNT(SLA%FLC(1:SLA%NO)==1)
    IF( INS%NO .GT. 0 ) &
    NINS   = COUNT(INS%FLC(1:INS%NO)==1)
    IF( SST%NO .GT. 0 ) &
    NSST   = COUNT(SST%FLC(1:SST%NO)==1)
    IF( SSS%NO .GT. 0 ) &
    NSSS   = COUNT(SSS%FLC(1:SSS%NO)==1)
    OBS%NO = NSLA+NINS+NSST+NSSS

    WRITE(IOUNLOG,*)
    WRITE(IOUNLOG,*) ' ====== TOTAL NUMBER OF OBS ',&
                   & 'ENTERING THE MINIMIZATION ======'
    WRITE(IOUNOUT,*) ' NUMBER OF OBSERVATIONS: ', OBS%NO
    WRITE(IOUNOUT,*) '           OF WHICH SLA: ',NSLA
    WRITE(IOUNOUT,*) '                    INS: ',NINS
    WRITE(IOUNOUT,*) '                    SST: ',NSST
    WRITE(IOUNOUT,*) '                    SSS: ',NSSS
    WRITE(IOUNLOG,*) ' NUMBER OF OBSERVATIONS: ', OBS%NO
    WRITE(IOUNLOG,*) '           OF WHICH SLA: ',NSLA
    WRITE(IOUNLOG,*) '                    INS: ',NINS
    WRITE(IOUNLOG,*) '                    SST: ',NSST
    WRITE(IOUNLOG,*) '                    SSS: ',NSSS

   CALL FLUSH(IOUNLOG)
   ! PRINTOUT MINUMUM AND MAXIMUM INNOVATIONS PER OBS TYPE
   ZINNMIN = 0._R8
   ZINNMAX = 0._R8
   IGR=0

   IGR=IGR+1
   IF( NINS .GT. 0 ) THEN
     ZINNMIN(IGR) = MINVAL( INS%RES( 1:INS%NO )*REAL( INS%FLC(1:INS%NO), KIND=R8 ) )
     ZINNMAX(IGR) = MAXVAL( INS%RES( 1:INS%NO )*REAL( INS%FLC(1:INS%NO), KIND=R8 ) )
   ENDIF

   IGR=IGR+1
   IF( NSLA .GT. 0 ) THEN
     ZINNMIN(IGR) = MINVAL( SLA%RES( 1:SLA%NO )*REAL( SLA%FLC(1:SLA%NO), KIND=R8 ) )
     ZINNMAX(IGR) = MAXVAL( SLA%RES( 1:SLA%NO )*REAL( SLA%FLC(1:SLA%NO), KIND=R8 ) )
   ENDIF

   IGR=IGR+1
   IF( NSST .GT. 0 ) THEN
     ZINNMIN(IGR) = MINVAL( SST%RES( 1:SST%NO )*REAL( SST%FLC(1:SST%NO), KIND=R8 ) )
     ZINNMAX(IGR) = MAXVAL( SST%RES( 1:SST%NO )*REAL( SST%FLC(1:SST%NO), KIND=R8 ) )
   ENDIF

   IGR=IGR+1
   IF( NSSS .GT. 0 ) THEN
     ZINNMIN(IGR) = MINVAL( SSS%RES( 1:SSS%NO )*REAL( SSS%FLC(1:SSS%NO), KIND=R8 ) )
     ZINNMAX(IGR) = MAXVAL( SSS%RES( 1:SSS%NO )*REAL( SSS%FLC(1:SSS%NO), KIND=R8 ) )
   ENDIF

   WRITE(IOUNLOG,*)
   WRITE(IOUNLOG,*) '  *** MIN AND MAX INNOVATIONS '
   WRITE(IOUNLOG,*) '  SLA: ',ZINNMIN(2),ZINNMAX(2)
   WRITE(IOUNLOG,*) '  INS: ',ZINNMIN(1),ZINNMAX(1)
   WRITE(IOUNLOG,*) '  SST: ',ZINNMIN(3),ZINNMAX(3)
   WRITE(IOUNLOG,*) '  SSS: ',ZINNMIN(4),ZINNMAX(4)
   WRITE(IOUNLOG,*)

   IF (OBS%NO .LE. 0 ) THEN
    IF(LL_CERES) THEN
      WRITE(IOUNOUT,*) 'NO CONVENTIONAL OBSERVATIONS'
      WRITE(IOUNLOG,*) 'NO CONVENTIONAL OBSERVATIONS'
    ELSE
      IF( .NOT. LLUSEMPI ) THEN
        CALL ABOR1('NO OBSERVATIONS AND NOTHING TO MINIMIZE - ABORTING')
      ELSE
        WRITE(IOUNOUT,*) 'NO OBSERVATIONS AND NOTHING TO MINIMIZE'
        WRITE(IOUNLOG,*) 'NO OBSERVATIONS AND NOTHING TO MINIMIZE'
      ENDIF
     ENDIF
   ENDIF

   ALLOCATE ( OBS%INC(OBS%NO), OBS%AMO(OBS%NO), OBS%RES(OBS%NO))
   ALLOCATE ( OBS%ERR(OBS%NO), OBS%GRA(OBS%NO))
   ALLOCATE ( OBS%AHUB(OBS%NO,2), OBS%NHUB(OBS%NO), OBS%AHUB2(OBS%NO,2) )
   ALLOCATE ( OBS%PERT(OBS%NO) )
   OBS%PERT = 0._R8
   K=0
   KP=0

IF(LLPERTOBS) THEN
    WRITE(IOUNOUT,*) ' /// PERTURBING OBSERVATIONS'
    WRITE(IOUNLOG,*)
    WRITE(IOUNLOG,*) ' /// PERTURBING OBSERVATIONS'
    WRITE(IOUNLOG,*) ' /// SEED FOR RANDGEN :',NSEED
    WRITE(IOUNLOG,*)
    KSEED=NSEED
    ALLOCATE(ZXR(OBS%NO))
    CALL INITIALIZE_RANDOM_NUMBERS(KSEED,GOLUM)
    CALL GAUSSIAN_DISTRIBUTION(ZXR,GOLUM)
ENDIF

! SLA OBSERVATIONS
   DO I=1,SLA%NO
    IF(SLA%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SLA%INC(I)
     OBS%RES(K) = SLA%RES(I)
     OBS%ERR(K) = SLA%ERR(I)
    ENDIF
   ENDDO

! INS OBSERVATIONS
   DO I=1,INS%NO
    IF(INS%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = INS%INC(I)
     OBS%RES(K) = INS%RES(I)
     OBS%ERR(K) = INS%ERR(I)
    ENDIF
   ENDDO

! SST OBSERVATIONS
   DO I=1,SST%NO
    IF(SST%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SST%INC(I)
     OBS%RES(K) = SST%RES(I)
     OBS%ERR(K) = SST%ERR(I)
    ENDIF
   ENDDO

! SSS OBSERVATIONS
   DO I=1,SSS%NO
    IF(SSS%FLC(I).EQ.1)THEN
     K=K+1
     OBS%INC(K) = SSS%INC(I)
     OBS%RES(K) = SSS%RES(I)
     OBS%ERR(K) = SSS%ERR(I)
    ENDIF
   ENDDO

!.... EVENTUALLY PERTURB OBSERVATIONS

IF(LLPERTOBS) THEN

    DO I=1,OBS%NO
        OBS%RES(I) = OBS%RES(I) + ZXR(I)*OBS%ERR(I)*ZRFACT
        OBS%PERT(I) = ZXR(I)*OBS%ERR(I)*ZRFACT
    ENDDO

    K=0
    ! SLA OBSERVATIONS
    DO I=1,SLA%NO
     IF(SLA%FLC(I).EQ.1)THEN
      K=K+1
      SLA%RES(I)=SLA%RES(I)+ZXR(K)*OBS%ERR(K)*ZRFACT
      SLA%VAL(I)=SLA%VAL(I)+ZXR(K)*OBS%ERR(K)*ZRFACT
     ENDIF
    ENDDO

    ! INS OBSERVATIONS
    DO I=1,INS%NO
     IF(INS%FLC(I).EQ.1)THEN
      K=K+1
      INS%RES(I)=INS%RES(I)+ZXR(K)*OBS%ERR(K)*ZRFACT
      INS%VAL(I)=INS%VAL(I)+ZXR(K)*OBS%ERR(K)*ZRFACT
     ENDIF
    ENDDO

    ! SST OBSERVATIONS
    DO I=1,SST%NO
     IF(SST%FLC(I).EQ.1)THEN
      K=K+1
      SST%RES(I)=SST%RES(I)+ZXR(K)*SST%ERR(K)*ZRFACT
      SST%VAL(I)=SST%VAL(I)+ZXR(K)*SST%ERR(K)*ZRFACT
     ENDIF
    ENDDO

    ! SSS OBSERVATIONS
    DO I=1,SSS%NO
     IF(SSS%FLC(I).EQ.1)THEN
      K=K+1
      SSS%RES(I)=SSS%RES(I)+ZXR(K)*SSS%ERR(K)*ZRFACT
      SSS%VAL(I)=SSS%VAL(I)+ZXR(K)*SSS%ERR(K)*ZRFACT
     ENDIF
    ENDDO

    DEALLOCATE(ZXR)
ENDIF

CALL MYFRTPROF_WALL('OBS_VEC2: FORM OBS VECTOR',1)
END SUBROUTINE OBS_VEC2
