SUBROUTINE OBSERRORS

!.. INTERFACE FOR OBSERVATIONAL ERRORS DEFINITION
!..
!.. A.STORTO, 2009

USE SET_KND
USE OBS_STR
USE DRV_STR
USE RUN
USE MYFRTPROF, ONLY : MYFRTPROF_WALL

IMPLICIT NONE

CALL MYFRTPROF_WALL('OBSERRORS: ASSIGN OBS ERROR',0)

!... FOR SLA:
IF(SLA%NO .GT. 0) &
CALL ASSIGN_SLAERR

!... FOR INS:
IF(INS%NO .GT. 0 .AND. NN_INS_SST .NE. 1) &
CALL ASSIGN_INSERR
IF(INS%NO .GT. 0 .AND. NN_INS_SST .EQ. 1) &
CALL ASSIGN_ICOERR

!... FOR SST:
IF(SST%NO .GT. 0) &
CALL ASSIGN_SSTERR

!... FOR SSS:
IF(SSS%NO .GT. 0) &
CALL ASSIGN_SSSERR

CALL MYFRTPROF_WALL('OBSERRORS: ASSIGN OBS ERROR',1)
END SUBROUTINE OBSERRORS
