SUBROUTINE OBSOP_AD

!-----------------------------------------------------------------------
!                                                                      !
! APPLY OBSERVATIONAL OPERATORS - ADJOINT
!                                                                      !
! VERSION 1: S.DOBRICIC 2006                                           !
!-----------------------------------------------------------------------


 USE SET_KND
 USE OBS_STR
 USE RUN, ONLY : COBSOPT
 USE GRD_STR, ONLY : LL_SSH
 USE MYFRTPROF, ONLY : MYFRTPROF_WALL
 USE WEAKLY

 IMPLICIT NONE

 CALL MYFRTPROF_WALL('OBSOP_AD: ADJOINT OF OBS OPERATOR',0)
 OBS%K = 0

IF(COBSOPT.EQ.'MFS') THEN

! SATELLITE OBSERVATIONS OF SLA
  CALL OBS_SLA_AD

! ARGO OBSERVATIONS
  CALL OBS_ARG_AD

! XBT OBSERVATIONS
  CALL OBS_XBT_AD

! GLIDER OBSERVATIONS
  CALL OBS_GLD_AD

! VELOCITY OBSERVATIONS
  CALL OBS_VEL_AD

! TRAJECTORY OBSERVATIONS
  IF(TRJ%NO.GT.0) CALL OBS_TRJ_AD

ELSEIF(COBSOPT.EQ.'GLO' .OR. COBSOPT.EQ.'ASC' ) THEN

  IF( LL_WEAKLY ) THEN
    TERR_AD = 0._R8
    SERR_AD = 0._R8
    WRITE(IOUNLOG,*) 'LHT0',MINVAL(TERR_AD), MAXVAL(TERR_AD)
    WRITE(IOUNLOG,*) 'LHS0',MINVAL(SERR_AD), MAXVAL(SERR_AD)
  ENDIF

! SATELLITE OBSERVATIONS OF SLA
  IF ( LL_SSH ) THEN
    CALL OBS_SLA2E_AD
  ELSE
    CALL OBS_SLA2_AD
  ENDIF

  IF( LL_WEAKLY ) THEN
    WRITE(IOUNLOG,*) 'LHT1',MINVAL(TERR_AD), MAXVAL(TERR_AD)
    WRITE(IOUNLOG,*) 'LHS1',MINVAL(SERR_AD), MAXVAL(SERR_AD)
  ENDIF

! INS OBSERVATIONS
  CALL OBS_INS_AD

! SST OBSERVATIONS
  IF ( SST%NO .GT. 0 ) CALL OBS_SST_AD

! SSS OBSERVATIONS
  IF ( SSS%NO .GT. 0 ) CALL OBS_SSS_AD

  IF( LL_WEAKLY ) THEN
    WRITE(IOUNLOG,*) 'LHT2',MINVAL(TERR_AD), MAXVAL(TERR_AD)
    WRITE(IOUNLOG,*) 'LHS2',MINVAL(SERR_AD), MAXVAL(SERR_AD)
  ENDIF

ELSE

  CALL ABOR1('COBSOPT OPTION IN OBSOP '//COBSOPT//' UNSUPPORTED')

ENDIF
 CALL MYFRTPROF_WALL('OBSOP_AD: ADJOINT OF OBS OPERATOR',1)
END SUBROUTINE OBSOP_AD
