SUBROUTINE OBSSTATS(CSTR,LLCHECK)

USE SET_KND
USE OBSDEF
USE OBS_STR
USE IOUNITS
USE MPIREL
USE RUN, ONLY : LL_DRIFTER_SST

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CSTR
INTEGER(I4) :: JO, IT, IP
INTEGER(I4) :: COUN(NOINSITU+1,14)
INTEGER(I4) :: COUNT(14), CDR
REAL   (R8) :: MEAN(NOINSITU+1,14)
REAL   (R8) :: MEANT(14), MDR, EDR
REAL   (R8) :: STDE(NOINSITU+1,14)
REAL   (R8) :: STDET(14), SDR
LOGICAL, INTENT(IN) :: LLCHECK

#include "obs_events.h"

COUN=0
COUNT=0
MEAN=0._R8
STDE=0._R8
MEANT=0._R8
STDET=0._R8

DO JO=1,INS%NO
   IF(INS%FLC(JO).EQ.1 .AND. INS%FLG(JO).EQ.1) THEN
      IF(LLCHECK) THEN
       IF(.NOT.ABS(INS%RES(JO)).LT.100.) THEN
         INS%RES(JO)=-999._R8
         INS%BAC(JO)=-999._R8
         INS%FLC(JO)=0
         INS%EVE(JO)=keve_MASK
       ENDIF
      ENDIF
      IT=INS%KTY(JO)
      IP=INS%PAR(JO)
      COUN(IT,IP) = COUN(IT,IP) + 1
      COUNT(IP) = COUNT(IP) + 1
      MEAN(IT,IP)  = MEAN(IT,IP) + INS%RES(JO)
      MEANT(IP)  = MEANT(IP) + INS%RES(JO)
   ENDIF
ENDDO

WHERE(COUN.GT.0) MEAN = MEAN/REAL(COUN)
WHERE(COUNT.GT.0) MEANT = MEANT/REAL(COUNT)

DO JO=1,INS%NO
   IF(INS%FLC(JO).EQ.1 .AND. INS%FLG(JO).EQ.1) THEN
      IT=INS%KTY(JO)
      IP=INS%PAR(JO)
      STDE(IT,IP)  = STDE(IT,IP) + &
      & (INS%RES(JO)-MEAN(IT,IP))*(INS%RES(JO)-MEAN(IT,IP))
      STDET(IP)  = STDET(IP) + &
      & (INS%RES(JO)-MEANT(IP))*(INS%RES(JO)-MEANT(IP))
   ENDIF
ENDDO

WHERE(COUN.GT.1) STDE = SQRT(STDE/REAL(COUN-1))
WHERE(COUNT.GT.1) STDET = SQRT(STDET/REAL(COUNT-1))

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' OBS STATISTICS '
WRITE(IOUNLOG,*) TRIM(CSTR)
WRITE(IOUNLOG,*) '------------------------------------------'
DO JO=1,NOINSITU
  WRITE(IOUNLOG,*) ' ** GROUP    : ',JO, ' '//CINSNAME(JO)
  WRITE(IOUNLOG,*) ' TEMPERATURE : AMOUNT, BIAS, STDEV'
  WRITE(IOUNLOG,*) COUN(JO,KKTEMP), MEAN(JO,KKTEMP), STDE(JO,KKTEMP)
  WRITE(IOUNLOG,*) ' SALINITY    : AMOUNT, BIAS, STDEV'
  WRITE(IOUNLOG,*) COUN(JO,KKSAL), MEAN(JO,KKSAL), STDE(JO,KKSAL)
ENDDO

WRITE(IOUNLOG,*) ' ** ALL TYPES:'
WRITE(IOUNLOG,*) ' TEMPERATURE : AMOUNT, BIAS, STDEV'
WRITE(IOUNLOG,*) COUNT(KKTEMP), MEANT(KKTEMP), STDET(KKTEMP)
WRITE(IOUNLOG,*) ' SALINITY    : AMOUNT, BIAS, STDEV'
WRITE(IOUNLOG,*) COUNT(KKSAL), MEANT(KKSAL), STDET(KKSAL)

IF(COUNT(KKT2M)+COUNT(KKQ2M).GT.0) THEN
  WRITE(IOUNLOG,*) 
  WRITE(IOUNLOG,*) ' ** AIR TYPES:'
  WRITE(IOUNLOG,*) ' T2M         : AMOUNT, BIAS, STDEV'
  WRITE(IOUNLOG,*) COUNT(KKT2M), MEANT(KKT2M), STDET(KKT2M)
  WRITE(IOUNLOG,*) ' Q2M         : AMOUNT, BIAS, STDEV'
  WRITE(IOUNLOG,*) COUNT(KKQ2M), MEANT(KKQ2M), STDET(KKQ2M)
  WRITE(IOUNLOG,*) 
ENDIF

IF(LL_DRIFTER_SST) THEN
 CDR=0
 MDR=0._R8
 EDR=0._R8
 SDR=0._R8
 DO JO=1,INS%NO
   IF(INS%FLC(JO).EQ.1 .AND. INS%FLG(JO).EQ.1.AND.&
   & INS%DSRC(JO).EQ.'DRF') THEN
      CDR = CDR+1
      MDR = MDR+INS%RES(JO)
      EDR = EDR+INS%ERR(JO)
   ENDIF
 ENDDO
 IF(CDR.GT.0) THEN
   MDR=MDR/CDR
   EDR=EDR/CDR
   DO JO=1,INS%NO
     IF(INS%FLC(JO).EQ.1 .AND. INS%FLG(JO).EQ.1.AND.&
     & INS%DSRC(JO).EQ.'DRF') THEN
       SDR = SDR + &
       & (INS%RES(JO)-MDR)**2
     ENDIF
   ENDDO
   SDR = SQRT( SDR/(CDR-1) )
 ENDIF
 WRITE(IOUNLOG,*) 
 WRITE(IOUNLOG,*) ' ** DRIFTER TYPES:'
 WRITE(IOUNLOG,*) ' SST         : AMOUNT, BIAS, STDEV'
 WRITE(IOUNLOG,*) CDR,MDR,SDR,EDR,&
 & MINVAL(INS%ERR,MASK=(INS%DSRC.EQ.'DRF')),&
 MAXVAL(INS%ERR,MASK=(INS%DSRC.EQ.'DRF'))
 WRITE(IOUNLOG,*) 
! DO JO=1,INS%NO
!   IF(INS%DSRC(JO).EQ.'DRF') WRITE(90+MYPROC,*) &
!   & JO,INS%EVE(JO),INS%DPT(JO),INS%LON(JO),INS%LAT(JO),INS%TIM(JO),INS%VAL(JO)
! ENDDO
ENDIF

COUNT(1) = 0
MEANT(1) = 0._R8
STDET(1) = 0._R8
DO JO=1,SLA%NO
   IF(SLA%FLC(JO).EQ.1 ) THEN
      COUNT(1) = COUNT(1) + 1
      MEANT(1)  = MEANT(1) + SLA%RES(JO)
   ENDIF
ENDDO
IF(COUNT(1).GT.0) MEANT(1) = MEANT(1)/REAL(COUNT(1))
DO JO=1,SLA%NO
   IF(SLA%FLC(JO).EQ.1) THEN
      STDET(1)  = STDET(1) + &
      & (SLA%RES(JO)-MEANT(1))*(SLA%RES(JO)-MEANT(1))
   ENDIF
ENDDO
IF(COUNT(1).GT.1) STDET(1) = SQRT(STDET(1)/REAL(COUNT(1)-1))
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ** SLA OBSERVATIONS:'
WRITE(IOUNLOG,*) ' SLA : AMOUNT, BIAS, STDEV'
WRITE(IOUNLOG,*) COUNT(1), MEANT(1), STDET(1)


COUNT(1) = 0
MEANT(1) = 0._R8
STDET(1) = 0._R8
DO JO=1,SST%NO
   IF(SST%FLC(JO).EQ.1 .AND. SST%FLG(JO).EQ.1) THEN
      COUNT(1) = COUNT(1) + 1
      MEANT(1)  = MEANT(1) + SST%RES(JO)
   ENDIF
ENDDO
IF(COUNT(1).GT.0) MEANT(1) = MEANT(1)/REAL(COUNT(1))
DO JO=1,SST%NO
   IF(SST%FLC(JO).EQ.1 .AND. SST%FLG(JO).EQ.1) THEN
      STDET(1)  = STDET(1) + &
      & (SST%RES(JO)-MEANT(1))*(SST%RES(JO)-MEANT(1))
   ENDIF
ENDDO
IF(COUNT(1).GT.1) STDET(1) = SQRT(STDET(1)/REAL(COUNT(1)-1))
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ** SST OBSERVATIONS:'
WRITE(IOUNLOG,*) ' SST : AMOUNT, BIAS, STDEV'
WRITE(IOUNLOG,*) COUNT(1), MEANT(1), STDET(1)


COUNT(1) = 0
MEANT(1) = 0._R8
STDET(1) = 0._R8
DO JO=1,SSS%NO
   IF(SSS%FLC(JO).EQ.1 .AND. SSS%FLG(JO).EQ.1) THEN
      COUNT(1) = COUNT(1) + 1
      MEANT(1)  = MEANT(1) + SSS%RES(JO)
   ENDIF
ENDDO
IF(COUNT(1).GT.0) MEANT(1) = MEANT(1)/REAL(COUNT(1))
DO JO=1,SSS%NO
   IF(SSS%FLC(JO).EQ.1 .AND. SSS%FLG(JO).EQ.1) THEN
      STDET(1)  = STDET(1) + &
      & (SSS%RES(JO)-MEANT(1))*(SSS%RES(JO)-MEANT(1))
   ENDIF
ENDDO
IF(COUNT(1).GT.1) STDET(1) = SQRT(STDET(1)/REAL(COUNT(1)-1))
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ** SSS OBSERVATIONS:'
WRITE(IOUNLOG,*) ' SSS : AMOUNT, BIAS, STDEV'
WRITE(IOUNLOG,*) COUNT(1), MEANT(1), STDET(1)

END SUBROUTINE OBSSTATS
