SUBROUTINE PREP_C202

USE SET_KND
USE OBS_STR
USE ALLOCOBS
USE RUN

IMPLICIT NONE

INTEGER(I4), PARAMETER :: MD=2000,MO=250000000, NLIB=2
INTEGER(I4) :: IERR, IDATES(MD)
INTEGER(I4) :: NOBS, MM, IFL, JK, NK, ITMP
CHARACTER(LEN=10) :: CAUX
CHARACTER(LEN=12) :: CVARN(0:2)
CHARACTER(LEN=99) :: CAUX2, CDDIR
LOGICAL :: LLEX

INQUIRE(FILE='list_dates', EXIST=LLEX)
IF(LLEX) THEN
  OPEN(16,FILE='list_dates')
  IERR=0
  JK=0
  DO WHILE(IERR.EQ.0)
     READ(16,*,IOSTAT=IERR) ITMP
     IF( IERR.EQ.0) THEN
        JK=JK+1
        IDATES(JK)=ITMP
     ENDIF
  ENDDO
  NK=JK
ELSE
  CALL ABOR1('PREP_MDTOI : NO LIST_DATES FILE')
ENDIF

CALL GETENV('DATA_DIR',CDDIR)
IF( LEN_TRIM(CDDIR) .EQ. 0 ) THEN
  CALL ABOR1('PREP_MDTOI : NO DATA_DIR VARIABLE')
ENDIF

CALL ALLOCSLA(MO,.FALSE.)

NOBS=0
DO JK=1,NK
   WRITE(*,*)
   WRITE(CAUX(1:6),'(I6.6)') INT(IDATES(JK)/10000) ; READ(CAUX(5:6),*) MM
   WRITE(*,*) 'READING DATE',IDATES(JK),' MONTH IS ',MM
   CALL READ_SLAMIS(SLA,IDATES(JK),NSUBDOMAINS,MO,NOBS,NLIB,CDDIR,LL_UNBIAS_SLA)
   WRITE(*,*) 'TOTAL NO OF OBS = ',NOBS
ENDDO

SLA%NO=NOBS
SLA%NC=NOBS
INS%NO=0
INS%NC=0
SST%NO=0
SST%NC=0
SSS%NO=0
SSS%NC=0

END SUBROUTINE PREP_C202
