SUBROUTINE PREPPROF

!.. ANDREA STORTO, *INGV* 2009-03-23

USE SET_KND
USE OBS_STR, ONLY : SST,INS,SLA,OBS,SSS
USE GRD_STR
USE IOUNITS
USE ALLOCOBS
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE RUN, ONLY : ZANJUL1950

IMPLICIT NONE

CHARACTER(LEN=20) :: CFILE
INTEGER(I4), PARAMETER :: NMAX = 1500000,MAXPROFS = 400000
INTEGER(I4) :: NOBS , IFILE, KOSUM
INTEGER(I4) :: STOBS,ENOBS,TOTOBS
INTEGER(I4), DIMENSION(NMAX) :: OTYPE, OPAR, OPROF
REAL   (R8), DIMENSION(NMAX) :: ODEP,  OVAL
REAL   (DP), DIMENSION(NMAX) :: OTIME
REAL   (R8), DIMENSION(NMAX) :: OLON,  OLAT
CHARACTER(LEN=8), DIMENSION(NMAX) :: OPLA
LOGICAL :: LPROCEED, LFLAGS(10), LDUPL, LDUPLA(MAXPROFS)
INTEGER(I4) :: KPRC, KDUPL, JOBS,JPROF,JPROF2, KPIND, KPIND2,UPPROF,K

WRITE(IOUNOUT,*) ' PREPARING PROFILE INDEXES FOR IN-SITU OBSERVATIONS'

IF(INS%NO .GT. 0) THEN

  ALLOCATE(INS%PRIND(MAXPROFS))
  INS%PRIND=-1

  KPRC=1
  INS%PRIND(KPRC) = 1

  DO JOBS=2,INS%NO
     IF(INS%PROF(JOBS) .NE. INS%PROF(JOBS-1) ) THEN

       KPRC=KPRC+1
       IF(KPRC.GT. MAXPROFS ) &
       & CALL ABOR1('READOBS: MAXPROFS MUST BE INCREASED')

       INS%PRIND(KPRC) = JOBS

     ENDIF
  ENDDO

  INS%NPROFS = KPRC

  KDUPL = 0
  OUTER : DO JPROF=1,INS%NPROFS
     KPIND=INS%PRIND(JPROF)
     LDUPL = .FALSE.
     LDUPLA(JPROF) = .FALSE.
     INNER : DO JPROF2=1,INS%NPROFS
        KPIND2=INS%PRIND(JPROF2)
        IF( LDUPL) CYCLE OUTER
        IF (KPIND.EQ.KPIND2) CYCLE INNER
        IF (INS%PLNO(KPIND)(1:8) .EQ. INS%PLNO(KPIND2)(1:8)) THEN
            KDUPL = KDUPL + 1
            LDUPL = .TRUE.
            LDUPLA(JPROF) = .TRUE.
        ENDIF
     ENDDO INNER
  ENDDO OUTER

  DO JPROF=1,INS%NPROFS
     KPIND=INS%PRIND(JPROF)
  ENDDO

  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' /// TOTAL INS OBSERVATIONS READ-IN :',INS%NO
  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' NUMBER OF PROFILES : ',INS%NPROFS
  WRITE(IOUNLOG,*) ' NUMBER OF STATIONS WITH MORE THAN ONE REPORT : ',KDUPL
  WRITE(IOUNLOG,*)

  CALL FLUSH(IOUNLOG)

 ENDIF
END SUBROUTINE PREPPROF
