SUBROUTINE READ_RFC(NX,NY,NZ,SCXT,SCYT,GALXT,GALYT,GBTXT,GBTYT,&
                      & SCXS,SCYS,GALXS,GALYS,GBTXS,GBTYS)

  USE SET_KND
  USE NETCDF
  USE MYFRTPROF
  USE RECFILTER, ONLY : LLRFCBOUNDED, ZRFMAXC

  IMPLICIT NONE

  INTEGER(I4) :: NX, NY, NZ

  INTEGER(I4) :: NCID,VARID(6)

  REAL(R8), DIMENSION(NX,NY,NZ) :: SCXT,SCYT,GALXT,GALYT,GBTXT,GBTYT,&
                             & SCXS,SCYS,GALXS,GALYS,GBTXS,GBTYS
  INTEGER(I4) :: X, Y

  CALL MYFRTPROF_WALL('READ_RFC: READ RF COEFFS',0)

  CALL CHECK( NF90_OPEN('rf_coeffs_TEM.nc', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'scx', VARID(1)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'scy', VARID(2)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'galx', VARID(3)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'galy', VARID(4)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'gbtx', VARID(5)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'gbty', VARID(6)) )

  CALL CHECK( NF90_GET_VAR(NCID, VARID(1),SCXT ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(2),SCYT ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(3),GALXT ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(4),GALYT ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(5),GBTXT ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(6),GBTYT ) )

  CALL CHECK( NF90_CLOSE(NCID) )

  CALL CHECK( NF90_OPEN('rf_coeffs_SAL.nc', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'scx', VARID(1)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'scy', VARID(2)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'galx', VARID(3)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'galy', VARID(4)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'gbtx', VARID(5)) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'gbty', VARID(6)) )

  CALL CHECK( NF90_GET_VAR(NCID, VARID(1),SCXS ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(2),SCYS ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(3),GALXS ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(4),GALYS ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(5),GBTXS ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID(6),GBTYS ) )

  CALL CHECK( NF90_CLOSE(NCID) )

  IF(LLRFCBOUNDED) THEN

     WHERE(GALXT .GT. ZRFMAXC ) GALXT = ZRFMAXC
     WHERE(GALYT .GT. ZRFMAXC ) GALYT = ZRFMAXC
     WHERE(GBTXT .GT. ZRFMAXC ) GBTXT = ZRFMAXC
     WHERE(GBTYT .GT. ZRFMAXC ) GBTYT = ZRFMAXC

     WHERE(GALXS .GT. ZRFMAXC ) GALXS = ZRFMAXC
     WHERE(GALYS .GT. ZRFMAXC ) GALYS = ZRFMAXC
     WHERE(GBTXS .GT. ZRFMAXC ) GBTXS = ZRFMAXC
     WHERE(GBTYS .GT. ZRFMAXC ) GBTYS = ZRFMAXC

  ENDIF

  CALL MYFRTPROF_WALL('READ_RFC: READ RF COEFFS',1)

END SUBROUTINE READ_RFC
