SUBROUTINE READDRIFTERFILE(CFIN,IOUN,NMAX,NOB,KTYP,PAR,DEP,VAL,TIM,LON,LAT,&
& PRF,PLA,INST,BIAS)

! READ OBSERVATION IN REFORMATTED SST/DRIFTER FORMAT
!
! A.S. - 26.11.2013

  USE SET_KND
  USE CALENDAR
  USE OBSDEF
  USE NETCDF
  USE RUN , ONLY : ZJULSTART, ZJULEND

  IMPLICIT NONE

  INTEGER(I4), INTENT(IN) :: IOUN,NMAX
  CHARACTER(LEN=*), INTENT(IN) :: CFIN
  INTEGER(I4), INTENT(OUT) :: NOB
  INTEGER(I4), DIMENSION(NMAX),INTENT(OUT) :: KTYP, PAR, PRF, INST
  REAL   (DP), DIMENSION(NMAX),INTENT(OUT) :: TIM
  REAL   (R8), DIMENSION(NMAX),INTENT(OUT) :: DEP,  VAL, LON, LAT, BIAS
  CHARACTER(LEN=8 ), DIMENSION(NMAX),INTENT(OUT) :: PLA

  INTEGER(I4), PARAMETER :: MAXVARS=14
  INTEGER(I4) :: KOBS, NOTW, NFLR, KKTP, KKOP
  INTEGER(I4) :: NCID, ID, JOBS, NOBS
  REAL(DP)    :: ZTIME, ZJULTMP

  REAL(R8) :: RLON, RLAT, RVAL, RERR, RTIME, RAUX1
  INTEGER(I4) :: IAUX1, IDRIFT, IERR

  WRITE(IOUN,*) ' ^^^ READDRIFTERFILE PROCESSING FILE ',TRIM(CFIN)

  KOBS=0
  KKOP=0
  NOTW=0
  NFLR=0

  OPEN(101,FILE=TRIM(CFIN),STATUS='OLD',IOSTAT=IERR)
  IF(IERR.NE.0) CALL ABOR1('READDRIFTERFILE: PROBLEMS OPENING '//TRIM(CFIN))

  BIAS = 0._R8
  CALL YMDS2JU( 1950, 1, 1, 0._DP, ZJULTMP )

  CYOBS : DO WHILE (IERR.EQ.0) 
    READ(101,*,IOSTAT=IERR) IAUX1,RAUX1,RTIME,IDRIFT,RLON,RLAT,RVAL,RERR
    IF(IERR.NE.0) EXIT CYOBS
    IF( RTIME+ZJULTMP .LT. ZJULSTART .OR. RTIME+ZJULTMP .GT. ZJULEND) THEN
       NOTW = NOTW + 1
       CYCLE CYOBS
    ENDIF
    KOBS=KOBS+1
    IF(KOBS.GT.NMAX) CALL ABOR1('READDRIFTERFILE: NMAX TO INCREASE')
    LON(KOBS) = RLON
    LAT(KOBS) = RLAT
    PAR(KOBS) = KKSST
    INST(KOBS) = IDRIFT
    DEP(KOBS) = MAX(RERR,0.2_R8)
    VAL(KOBS) = RVAL
    KTYP(KOBS) = KKBUOY
    PRF(KOBS) = KOBS
    TIM(KOBS) = RTIME
    WRITE(PLA(KOBS)(1:8),'(I8.8)') IDRIFT
  ENDDO CYOBS

  CLOSE(101)

  NOB = KOBS

  WRITE(IOUN,*)
  WRITE(IOUN,*) ' ^^^ REPORT '
  WRITE(IOUN,*) ' TOTAL NUMBER OF OBS     :', NOBS
  WRITE(IOUN,*) ' NUMBER OF BAD  OBS COO  :', KKOP
  WRITE(IOUN,*) ' NUMBER OF GOOD OBSERV.  :', KOBS
  WRITE(IOUN,*) ' NUMBER OF P OUT OF TIME :', NOTW
  WRITE(IOUN,*) ' NUMBER OF BAD FLAGS OBS :', NFLR
  WRITE(IOUN,*) 

END SUBROUTINE READDRIFTERFILE
