SUBROUTINE READ_RFCEG

  USE SET_KND
  USE NETCDF
  USE MYFRTPROF
  USE RECFILTER

  IMPLICIT NONE

  INTEGER(I4) :: NX, NY, NZ

  INTEGER(I4) :: NCID,VARID

  CALL MYFRTPROF_WALL('READ_RFCEG: READ EXTENDED GRID RF COEFFS',0)

  CALL CHECK( NF90_OPEN('RF_AEX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'rf_aex', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,RF_AEX ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('RF_AEY.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'rf_aey', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,RF_AEY ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('RF_BEX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'rf_bex', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,RF_BEX ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('RF_BEY.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'rf_bey', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,RF_BEY ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('IMX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'imx', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,IMX ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('INX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'inx', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,INX ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('JMX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'jmx', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,JMX ) )
  CALL CHECK( NF90_CLOSE(NCID) )
  CALL CHECK( NF90_OPEN('JNX.NC', NF90_NOWRITE, NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID, 'jnx', VARID ) )
  CALL CHECK( NF90_GET_VAR(NCID, VARID,JNX ) )
  CALL CHECK( NF90_CLOSE(NCID) )

  CALL MYFRTPROF_WALL('READ_RFCEG: READ EXTENDED GRID RF COEFFS',1)

END SUBROUTINE READ_RFCEG
