SUBROUTINE READOBSA

USE SET_KND
USE ALLOCOBS
USE OBS_STR
USE READOBAS

IMPLICIT NONE

INTEGER(I4) :: NOBSBF(NOFAMS)
INTEGER(I4) :: KR(NOFAMS), JO

#include "obs_events.h"

CALL GETOASN(NOBSBF)

INS%NO = NOBSBF(NNINS)
INS%NC = NOBSBF(NNINS)
SLA%NO = NOBSBF(NNSLA)
SLA%NC = NOBSBF(NNSLA)
SST%NO = NOBSBF(NNSST)
SST%NC = NOBSBF(NNSST)
SSS%NO = NOBSBF(NNSLA)
SSS%NC = NOBSBF(NNSLA)

CALL ALLOCINS(INS%NO,.TRUE.)
CALL ALLOCSLA(SLA%NO,.TRUE.)
CALL ALLOCSST(SST%NO,.TRUE.)
CALL ALLOCSSS(SSS%NO,.TRUE.)

CALL GETOASOBS

KR=0

IF ( SST%NO .GT. 0 ) THEN
  DO JO=1,SST%NO
    IF( SST%LON(JO) .LT. MIMA_LL(1) .OR. SST%LON(JO) .GT. MIMA_LL(2) .OR. &
       SST%LAT(JO) .LT. MIMA_LL(3) .OR. SST%LAT(JO) .GT. MIMA_LL(4) ) THEN
        SST%FLC(JO) = 0
        SST%EVE(JO) = KEVE_PDOM
        KR(3)=KR(3)+1
    ENDIF
  ENDDO
ENDIF

IF ( SSS%NO .GT. 0 ) THEN
  DO JO=1,SSS%NO
    IF( SSS%LON(JO) .LT. MIMA_LL(1) .OR. SSS%LON(JO) .GT. MIMA_LL(2) .OR. &
       SSS%LAT(JO) .LT. MIMA_LL(3) .OR. SSS%LAT(JO) .GT. MIMA_LL(4) ) THEN
        SSS%FLC(JO) = 0
        SSS%EVE(JO) = KEVE_PDOM
        KR(4)=KR(4)+1
    ENDIF
  ENDDO
ENDIF

IF ( SLA%NO .GT. 0 ) THEN
  DO JO=1,SLA%NO
    IF( SLA%LON(JO) .LT. MIMA_LL(1) .OR. SLA%LON(JO) .GT. MIMA_LL(2) .OR. &
       SLA%LAT(JO) .LT. MIMA_LL(3) .OR. SLA%LAT(JO) .GT. MIMA_LL(4) ) THEN
        SLA%FLC(JO) = 0
        SLA%EVE(JO) = KEVE_PDOM
        KR(2)=KR(2)+1
    ENDIF
  ENDDO
ENDIF

IF ( INS%NO .GT. 0 ) THEN
  DO JO=1,INS%NO
    IF( INS%LON(JO) .LT. MIMA_LL(1) .OR. INS%LON(JO) .GT. MIMA_LL(2) .OR. &
       INS%LAT(JO) .LT. MIMA_LL(3) .OR. INS%LAT(JO) .GT. MIMA_LL(4) ) THEN
        INS%FLC(JO) = 0
        INS%EVE(JO) = KEVE_PDOM
        KR(1)=KR(1)+1
    ENDIF
  ENDDO
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// OUT OF DOMAIN REJECTION '
WRITE(IOUNLOG,*) ' INS : ', KR(1)
WRITE(IOUNLOG,*) ' SLA : ', KR(2)
WRITE(IOUNLOG,*) ' SST : ', KR(3)
WRITE(IOUNLOG,*) ' SSS : ', KR(4)
WRITE(IOUNLOG,*)


END SUBROUTINE READOBSA
