SUBROUTINE READSST

!! READ SPACE-BORNE MW OR IR SST FROM FILE

USE IOUNITS
USE RUN
USE SET_KND
USE OBS_STR
USE GRD_STR
USE ALLOCOBS
USE CALENDAR, ONLY : JU2YMDS


IMPLICIT NONE

INTEGER(I4) :: NOBS,IERR,JSAT,KFILE,KSAT,ISTART,&
             & K,IJ,JOBS,IDIFFER1,IRET,ISAT,KOS,IFILE
LOGICAL :: LLEXIST,LEX
INTEGER(I4),PARAMETER :: MAX_SSTOBS = 10368000
CHARACTER(LEN=10) :: &
                   & CSSTDATE,CTEMPDATE
CHARACTER(LEN=60) :: CFILEIN, CFILEIN2
REAL(R8),DIMENSION(MAX_SSTOBS) :: ZLON,ZLAT,ZDAT,ZERR
REAL(DP),DIMENSION(MAX_SSTOBS) :: ZTIM
REAL(R8)          :: DTSTART,DTEND
CHARACTER(LEN=10) :: CDTSTART,CDTEND
INTEGER(I4) :: YYYY,MM,DD
REAL(R8) :: SS, RDAY

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) '... ENTERING READSST ...'

DTSTART = ZJULSTART - ZJUL1950
DTEND   = ZJULEND   - ZJUL1950

WRITE(IOUNLOG,*) ' STARTDATE (JULIAN DAYS SINCE 1950) : ', DTSTART
WRITE(IOUNLOG,*) ' END  DATE (JULIAN DAYS SINCE 1950) : ', DTEND
WRITE(IOUNLOG,*)


SST%NO=0

CALL ALLOCSST(MAX_SSTOBS,.TRUE.)

   IF ( SST%LLAMSRE ) THEN

       KOS=0
       ISAT = 1
       CSSTDATE=CDTSTART
       DO WHILE( CSSTDATE .NE. CDTEND )

          WRITE(CFILEIN,'(A,A,A)') 'AMSRE_',CSSTDATE(1:8),'V5'
          INQUIRE(FILE=CFILEIN,EXIST=LEX)

          IF(LEX) THEN

           CALL DIFFTIME('D',CSSTDATE(1:8),'19500101',IDIFFER1,IRET,.FALSE.)

           CALL READ_AMSR_DAY(CFILEIN,IDIFFER1,MAX_SSTOBS,NOBS,ZDAT,&
           & ZTIM,ZLON,ZLAT)

           SST%NO = SST%NO + NOBS
           ISTART = SST%NO-NOBS+1
           KOS = KOS + NOBS

           IF( SST%NO .GT. MAX_SSTOBS ) &
           & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

           SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
           SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
           SST%TIM(ISTART:SST%NO) = ZTIM(1:NOBS)
           SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)

           SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
           SST%KSAT (ISTART:SST%NO) = ISAT

          ENDIF

          CALL ADDTIME('D',CSSTDATE(1:8),CTEMPDATE(1:8),1,IERR,.FALSE.)
          CSSTDATE(1:8)=CTEMPDATE(1:8)

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LLREMSS_SWATH_AMSRE ) THEN

       IF(SST%LLAMSRE ) THEN
         WRITE(IOUNERR,*) 'LLREMSS_SWATH_AMSRE, LLAMSRE :',&
         & SST%LLREMSS_SWATH_AMSRE, SST%LLAMSRE
         CALL ABOR1('READSST: REDUNDANCY IN SST SOURCES')
       ENDIF

       KOS=0
       ISAT = 4
       CSSTDATE=CDTSTART
       DO WHILE( CSSTDATE .NE. CDTEND )

        CALL DIFFTIME('D',CSSTDATE(1:8),'19500101',IDIFFER1,IRET,.FALSE.)

        LLEXIST = .TRUE.
        IFILE = 0
        DO WHILE( LLEXIST )

          IFILE = IFILE + 1
          WRITE(CFILEIN,'(A,A,I2.2)') CSSTDATE(1:8),&
          & '_SWATH_AMSRE.NC',IFILE

          INQUIRE(FILE=CFILEIN,EXIST=LLEXIST)

          IF(LLEXIST) THEN

            CALL READ_REMSS_SWATH_AMSRE_NC(CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
            & ZLON,ZLAT,ZTIM,ZERR,SST%LLSSTDACORR)

            SST%NO = SST%NO + NOBS
            ISTART = SST%NO-NOBS+1
            KOS = KOS + NOBS

            IF( SST%NO .GT. MAX_SSTOBS ) &
            & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

            SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
            SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
            SST%TIM(ISTART:SST%NO) = ZTIM(1:NOBS)
            SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
            SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

            SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
            SST%KSAT (ISTART:SST%NO) = ISAT
          ENDIF
       ENDDO

            CALL ADDTIME('D',CSSTDATE(1:8),CTEMPDATE(1:8),1,IERR,.FALSE.)
            CSSTDATE(1:8)=CTEMPDATE(1:8)

     ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LLREMSS_SWATH_TMI ) THEN

       KOS=0
       ISAT = 5
       CSSTDATE=CDTSTART
       DO WHILE( CSSTDATE .NE. CDTEND )

        CALL DIFFTIME('D',CSSTDATE(1:8),'19500101',IDIFFER1,IRET,.FALSE.)

        LLEXIST = .TRUE.
        IFILE = 0
        DO WHILE( LLEXIST )

          IFILE = IFILE + 1
          WRITE(CFILEIN,'(A,A,I2.2)') CSSTDATE(1:8),&
          & '_SWATH_TMI.NC',IFILE

          INQUIRE(FILE=CFILEIN,EXIST=LLEXIST)

          IF(LLEXIST) THEN

            CALL READ_REMSS_SWATH_AMSRE_NC(CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
            & ZLON,ZLAT,ZTIM,ZERR,SST%LLSSTDACORR)

            SST%NO = SST%NO + NOBS
            ISTART = SST%NO-NOBS+1
            KOS = KOS + NOBS

            IF( SST%NO .GT. MAX_SSTOBS ) &
            & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

            SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
            SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
            SST%TIM(ISTART:SST%NO) = ZTIM(1:NOBS)
            SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
            SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

            SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
            SST%KSAT (ISTART:SST%NO) = ISAT
          ENDIF
       ENDDO

            CALL ADDTIME('D',CSSTDATE(1:8),CTEMPDATE(1:8),1,IERR,.FALSE.)
            CSSTDATE(1:8)=CTEMPDATE(1:8)

     ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LLREMSS_MWOI_NC ) THEN

       IF(SST%LLAMSRE .OR. SST%LLTMI) THEN
         WRITE(IOUNERR,*) 'LLREMSS_MWOI_NC, LLAMSRE, LLTMI :',&
         & SST%LLREMSS_MWOI_NC, SST%LLAMSRE, SST%LLTMI
         CALL ABOR1('READSST: REDUNDANCY IN SST SOURCES')
       ENDIF

       KOS=0
       ISAT = 3
       CSSTDATE=CDTSTART
       DO WHILE( CSSTDATE .NE. CDTEND )

          CALL DIFFTIME('D',CSSTDATE(1:8),'19500101',IDIFFER1,IRET,.FALSE.)

          WRITE(CFILEIN,'(A,A)') CSSTDATE(1:8),&
          & '-REMSS-L4LRFND-GLOB-V01-FV02-TMI_AMSRE_OI.NC'

          CALL READ_REMSS_MWOISST_NC(CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
          & ZLON,ZLAT)

          SST%NO = SST%NO + NOBS
          ISTART = SST%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SST%NO .GT. MAX_SSTOBS ) &
        & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

          SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
          SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
          SST%TIM(ISTART:SST%NO) = REAL(IDIFFER1,KIND=R8)
          SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)

          SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
          SST%KSAT (ISTART:SST%NO) = ISAT

          CALL ADDTIME('D',CSSTDATE(1:8),CTEMPDATE(1:8),1,IERR,.FALSE.)
          CSSTDATE(1:8)=CTEMPDATE(1:8)

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LL_COPERN_L3S ) THEN

       KOS=0
       ISAT = 7
       CSSTDATE=CDTSTART
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0.5_R8

       DO WHILE( CSSTDATE .NE. CDTEND )

          WRITE(CFILEIN,'(A,A)') CSSTDATE(1:8),&
          & '_L3S.NC'

          INQUIRE(FILE=CFILEIN,EXIST=LEX)
          IF(LEX) THEN
            CALL READ_L3S_SST_NC(CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
            & ZLON,ZLAT,ZERR)

            SST%NO = SST%NO + NOBS
            ISTART = SST%NO-NOBS+1
            KOS = KOS + NOBS

            IF( SST%NO .GT. MAX_SSTOBS ) &
            & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

            SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
            SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
            SST%TIM(ISTART:SST%NO) = DTSTART+RDAY
            SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
            SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

            SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
            SST%KSAT (ISTART:SST%NO) = ISAT
          ELSE
            WRITE(IOUNLOG,*) ' WARNING  - FILE ',TRIM(CFILEIN) ,' NOT FOUND'
          ENDIF

          RDAY = RDAY + 1._R8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LL_COPERN_L3 ) THEN

       KOS=0
       ISAT = 8
       CSSTDATE=CDTSTART
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0.5_R8

       DO WHILE( CSSTDATE .NE. CDTEND )

          WRITE(CFILEIN,'(A,A)') CSSTDATE(1:8),&
          & '_L3S.NC'
          WRITE(CFILEIN2,'(A,A)') CSSTDATE(1:8),&
          & '_L3S_ERR.NC'

          INQUIRE(FILE=CFILEIN,EXIST=LEX)
          IF(LEX) THEN
            CALL READ_L3_SST_NC(CFILEIN,CFILEIN2,MAX_SSTOBS,NOBS,ZDAT,&
            & ZLON,ZLAT,ZERR)

            SST%NO = SST%NO + NOBS
            ISTART = SST%NO-NOBS+1
            KOS = KOS + NOBS

            IF( SST%NO .GT. MAX_SSTOBS ) &
            & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

            SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
            SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
            SST%TIM(ISTART:SST%NO) = DTSTART+RDAY
            SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
            SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

            SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
            SST%KSAT (ISTART:SST%NO) = ISAT
          ELSE
            WRITE(IOUNLOG,*) ' WARNING  - FILE ',TRIM(CFILEIN) ,' NOT FOUND'
          ENDIF

          RDAY = RDAY + 1._R8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LL_AMSR2 ) THEN

       KOS=0
       ISAT = 8
       CSSTDATE=CDTSTART
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0._8

       DO WHILE( CSSTDATE .LE. CDTEND )

          WRITE(CFILEIN,'(A,A,A)') 'amsr2_',CSSTDATE(1:8),&
          & '.nc'

          CALL READ_AMSR2_SST_NC(DTSTART,DTEND,CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
          & ZLON,ZLAT,ZTIM,ZERR)

          SST%NO = SST%NO + NOBS
          ISTART = SST%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SST%NO .GT. MAX_SSTOBS ) &
        & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

          SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
          SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
          SST%TIM(ISTART:SST%NO) = ZTIM(1:NOBS)
          SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
          SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

          SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
          SST%KSAT (ISTART:SST%NO) = ISAT

          RDAY = RDAY + 1._8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LL_METOPA_AVHRR ) THEN

       KOS=0
       ISAT = 9
       CSSTDATE=CDTSTART
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0._DP

       DO WHILE( CSSTDATE .LE. CDTEND )

          WRITE(CFILEIN,'(A,A,A)') 'metop-a_avhrr_',CSSTDATE(1:8),&
          & '.nc'

          CALL READ_AVHRR_SST_NC(DTSTART,DTEND,CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
          & ZLON,ZLAT,ZTIM,ZERR)

          SST%NO = SST%NO + NOBS
          ISTART = SST%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SST%NO .GT. MAX_SSTOBS ) &
        & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

          SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
          SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
          SST%TIM(ISTART:SST%NO) = ZTIM(1:NOBS)
          SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
          SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

          SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
          SST%KSAT (ISTART:SST%NO) = ISAT

          RDAY = RDAY + 1._8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

   IF ( SST%LL_NOAA_OI ) THEN

       KOS=0
       ISAT = 6
       CSSTDATE=CDTSTART
       CALL JU2YMDS (ZJULSTART,YYYY,MM,DD,SS)
       WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       CALL JU2YMDS (ZJULEND,YYYY,MM,DD,SS)
       WRITE(CDTEND,'(I4.4,I2.2,I2.2)') YYYY,MM,DD
       RDAY=0.5_DP

       DO WHILE( CSSTDATE .LE. CDTEND )

          WRITE(CFILEIN,'(A,A,A)') 'noaa_oiv2_',CSSTDATE(1:8),&
          & '.nc'

          CALL READ_NOAA_SST_NC(CFILEIN,MAX_SSTOBS,NOBS,ZDAT,&
          & ZLON,ZLAT,ZERR)

          SST%NO = SST%NO + NOBS
          ISTART = SST%NO-NOBS+1
          KOS = KOS + NOBS

          IF( SST%NO .GT. MAX_SSTOBS ) &
        & CALL ABOR1('FATAL IN READSST: MAX_SSTOBS MUST BE INCREASED')

          SST%LON(ISTART:SST%NO) = ZLON(1:NOBS)
          SST%LAT(ISTART:SST%NO) = ZLAT(1:NOBS)
          SST%TIM(ISTART:SST%NO) = DTSTART + RDAY
          SST%VAL(ISTART:SST%NO) = ZDAT(1:NOBS)
          SST%ERR(ISTART:SST%NO) = ZERR(1:NOBS)

          SST%TDIST(ISTART:SST%NO) = SST%TIM(ISTART:SST%NO) - ZANJUL1950
          SST%KSAT (ISTART:SST%NO) = ISAT

          RDAY = RDAY + 1._8
          CALL JU2YMDS (ZJULSTART+RDAY,YYYY,MM,DD,SS)
          WRITE(CSSTDATE,'(I4.4,I2.2,I2.2)') YYYY,MM,DD

       ENDDO

       SST%ISSTOBS(ISAT) = KOS

   ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ========================================'
WRITE(IOUNLOG,*) ' SST REPORT : TOTAL NO OF OBS IS',SST%NO

END SUBROUTINE READSST
