SUBROUTINE READFG4DF(CFILE,CVARNAME,NX,NY,NZ,FS,ISTEPS,MX,MY,F3D,LOP,LCL,NCID)
USE SET_KND
USE NETCDF
USE IOUNITS, ONLY : IOUNOUT ,IOUNERR ,IOUNLOG
USE READFG
USE RUN, ONLY : LL_RESTART_FILE, LLONLYOBSPP, LL_PROJDOWN

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CVARNAME,CFILE
INTEGER(I4)      , INTENT(IN)  :: NX,NY,NZ,ISTEPS,MX,MY,FS
INTEGER(I4)      , INTENT(INOUT)  :: NCID
INTEGER(I4)       :: NCID2
INTEGER(I4)                    :: STAT, IDVAR,K,ITIME,JK
REAL(R8),INTENT(OUT)  ::  F3D(MX,MY,NZ,ISTEPS)
INTEGER(I4) :: X,Y,TIMES,Z
INTEGER(I4) :: JX,JY,JZ,JT
LOGICAL :: LOP,LCL
LOGICAL, PARAMETER :: LCHECK=.FALSE.

WRITE(901,*) CFILE,' ',CVARNAME,NX,NY,NZ,ISTEPS,LOP,LCL,NCID,FS
CALL FLUSH(901)

IF(LOP) THEN
STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID2)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
WRITE(IOUNLOG,*) ' FIRST GUESS FILE ',CFILE,' OPENED'
ENDIF

IF(LCHECK) THEN

STAT = NF90_INQ_DIMID (NCID2, 'x', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = X )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID (NCID2, 'y', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = Y)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

IF ( LL_RESTART_FILE ) THEN
  STAT = NF90_INQ_DIMID (NCID2, 'z', IDVAR)
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
  STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = Z )
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

  STAT = NF90_INQ_DIMID (NCID2, 't', IDVAR)
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
  STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = TIMES)
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
ELSE
  STAT = NF90_INQ_DIMID (NCID2, 'deptht', IDVAR)
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
  STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = Z )
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

  STAT = NF90_INQ_DIMID (NCID2, 'time_counter', IDVAR)
  IF (STAT /= NF90_NOERR) THEN
    IF(LLONLYOBSPP) THEN
      TIMES=1
    ELSE
      CALL HANDLE_ERR(STAT)
    ENDIF
  ELSE
    STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = TIMES)
    IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
  ENDIF

ENDIF

ELSE

STAT = NF90_INQ_DIMID (NCID2, 'x', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = X )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID (NCID2, 'y', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID2, IDVAR, LEN = Y)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

ENDIF

STAT = NF90_INQ_VARID (NCID2, CVARNAME, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
IF ( LL_PROJDOWN ) THEN
  STAT = NF90_GET_VAR(NCID2,IDVAR,F3D,START=(/1,1,1,FS/),COUNT=(/X,Y,1,ISTEPS/))
  DO JK=2,NZ
    F3D(:,:,JK,:) = F3D(:,:,1,:)
  ENDDO
ELSE
  STAT = NF90_GET_VAR(NCID2,IDVAR,F3D,START=(/1,1,1,FS/),COUNT=(/X,Y,NZ,ISTEPS/))
ENDIF
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
WRITE(IOUNLOG,*) ' DONE '//CVARNAME
CALL FLUSH(IOUNLOG)

IF(LCL) STAT = NF90_CLOSE(NCID2)

END SUBROUTINE READFG4DF
