SUBROUTINE READ_AMSR2_SST_NC(DT1,DT2,CFILE,MAXOBS,NTOBS,ZDATA,&
          & ZLLON,ZLLAT,ZZTIM,ZERR)

USE SET_KND
USE RUN
USE NETCDF
USE IOUNITS
USE CALENDAR

IMPLICIT NONE

REAL   (DP), INTENT(IN) :: DT1, DT2
CHARACTER(LEN=*), INTENT(IN) :: CFILE
INTEGER(I4), INTENT(IN) :: MAXOBS
INTEGER(I4), INTENT(OUT) :: NTOBS
REAL   (DP), DIMENSION(MAXOBS), INTENT(OUT) :: ZZTIM
REAL   (R8), DIMENSION(MAXOBS), INTENT(OUT) :: ZDATA,&
          & ZLLON,ZLLAT,ZERR
INTEGER(I4), PARAMETER :: NX=1440, NY=720
REAL(DP) :: ZOTIM(NX,NY,2)
REAL(R4) :: ZOLON(NX),ZOLAT(NY),ZOSST(NX,NY,2),ZOERR(NX,NY,2)
INTEGER(I4) :: STAT,IDVAR,IDF,JX,JY,JT

REAL(R8), ALLOCATABLE, DIMENSION(:,:) :: lonnight,latnight
REAL(R8), ALLOCATABLE, DIMENSION(:,:) :: sst_cumulated,temp_sst
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: sec_ofday
INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: day_ofday
INTEGER(I4) :: ZJULSTART_SINCE1950,DDSINCE1950,ZJULEND_SINCE1950
REAL(R8) :: MISSVAL,MISSVALSST,ZJULYEAR,SEC
INTEGER(I4) :: COUT,TT,II,NN,NCID,varid
INTEGER(I4) :: VD(3), VDIM(3),XD,YD,TD,T_COUNT,nday,YEAR,MONTH,DAY
LOGICAL :: init


WRITE(IOUNOUT,*) ' :: OPENING AMSR2 FILE '//TRIM(CFILE)
WRITE(IOUNLOG,*) ' :: OPENING AMSR2 FILE '//TRIM(CFILE)

STAT=NF90_OPEN(CFILE,NF90_NOWRITE, IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (IDF, 'lon', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOLON)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (IDF, 'lat', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOLAT)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (IDF, 'sst', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOSST)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_ATT(NCID, varid, 'missing_value',MISSVALSST)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (IDF, 'sst_err', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOERR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (IDF, 'days', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (IDF,IDVAR,ZOTIM)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT= NF90_GET_ATT(NCID, varid, 'missing_value',MISSVAL)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT=NF90_CLOSE(IDF)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

IF (LL_NIGHT_ONLY_AMSR2_AVHHR) THEN
        WRITE(IOUNLOG,*) ' REMOVING OBSERVATION DURING DAYLIGHT'
        COUT=0
        DO II=1,2
        DO NN=1,NY
        DO TT=1,NX
                if (ZOSST(TT,NN,II)/=MISSVALSST) COUT=COUT+1
        ENDDO
        ENDDO
        ENDDO
        WRITE(IOUNLOG,*) '..STARTING NUMBER OF DATA',COUT

        ALLOCATE(day_ofday(NX,NY,2),sec_ofday(NX,NY,2),lonnight(NX,NY),latnight(NX,NY),temp_sst(NX,NY),sst_cumulated(NX,NY))
        DO II=1,NX
        latnight(II,:)=ZOLAT(1:NY)
        ENDDO

        DO II=1,NY
        lonnight(:,II)=ZOLON(:)
        ENDDO
        WHERE (lonnight > 180. ) lonnight=lonnight-360

        WHERE(ZOSST==MISSVALSST .OR. ZOTIM==MISSVAL) ZOSST=MISSVALSST
        WHERE(ZOSST==MISSVALSST .OR. ZOTIM==MISSVAL) ZOTIM=MISSVALSST

        sec_ofday=MOD(ZOTIM,1.)*24.
        day_ofday=INT(ZOTIM-sec_ofday/24.)
        WHERE(ZOTIM==MISSVALSST) day_ofday=MISSVALSST
        WHERE(ZOTIM==MISSVALSST) sec_ofday=MISSVALSST

        ZJULSTART_SINCE1950=INT(ZJULSTART)-INT(ZJUL1950)
        ZJULEND_SINCE1950=INT(ZJULEND)-INT(ZJUL1950)
        DO II=1,2
        
        sst_cumulated=MISSVALSST
        DDSINCE1950=ZJULSTART_SINCE1950
                DO WHILE(DDSINCE1950 .GE. ZJULSTART_SINCE1950 .AND. DDSINCE1950 .LE. ZJULEND_SINCE1950)
                DO NN=1,24
                temp_sst=ZOSST(:,:,II)
                WHERE ( (sec_ofday(:,:,II) .LT. REAL(NN-1) ) .OR. &
                 & (sec_ofday(:,:,II) .GT. REAL(NN) ) .OR.   &
                 & (DDSINCE1950 .NE. day_ofday(:,:,II)) ) temp_sst=MISSVALSST
                init=.FALSE.
                IF (NN==1 .AND. II==1 .AND. DDSINCE1950==ZJULSTART_SINCE1950) init=.TRUE.
        !write(*,*) NN
                CALL JU2YMDS (REAL(DDSINCE1950+ZJUL1950,DP),YEAR,MONTH,DAY,SEC)
                CALL YMDS2JU(YEAR,01,01,0._DP,ZJULYEAR)
                nday= DDSINCE1950-(INT(ZJULYEAR)-INT(ZJUL1950))+1
       !WRITE(*,*) DDSINCE1950
                !CALL sbc_dcy(NN*3600,nday,lonnight,latnight,temp_sst,NX,NY,MISSVALSST,init )
                WHERE (temp_sst .NE. MISSVALSST ) sst_cumulated=temp_sst
                ENDDO
                DDSINCE1950=DDSINCE1950+1
                 ENDDO
        ZOSST(:,:,II)=sst_cumulated
        ENDDO

        WRITE(IOUNLOG,*) '..DONE'
         COUT=0
        DO II=1,2
        DO NN=1,NY
        DO TT=1,NX
                if (ZOSST(TT,NN,II)/=MISSVALSST) COUT=COUT+1
        ENDDO
        ENDDO
        ENDDO
        WRITE(IOUNLOG,*) '..NUMBER OF NIGHT TIME DATA',COUT

        IF (PRINT_NIGHT_OBSERVATION_ONLY) THEN
                WRITE(IOUNLOG,*) 'PRINTING OBSERVATION IN NIGHT_ONLY_',TRIM(CFILE)
                CALL CHECK( NF90_CREATE("NIGHT_ONLY_"//TRIM(CFILE), NF90_CLOBBER, NCID) )
                CALL CHECK( NF90_DEF_DIM(NCID, 'lon',NX, XD) )
                CALL CHECK( NF90_DEF_DIM(NCID, 'lat',NY, YD) )
                CALL CHECK( NF90_DEF_DIM(NCID, 't',nf90_unlimited, TD) )
                VDIM = (/XD, YD, TD /)
                CALL CHECK( NF90_DEF_VAR(NCID, 'lon', NF90_REAL, VDIM(1:2), VD(1) ))
                CALL CHECK( NF90_DEF_VAR(NCID, 'lat', NF90_REAL, VDIM(1:2), VD(2) ))
                CALL CHECK( NF90_DEF_VAR(NCID, 'sst', nf90_REAL, VDIM, VD(3) ) )
                CALL CHECK( NF90_PUT_ATT(NCID, VD(1), 'units','degrees_east'))
                CALL CHECK( NF90_PUT_ATT(NCID, VD(2), 'units','degrees_north'))
                CALL CHECK( NF90_PUT_ATT(NCID, VD(3), 'missing_value',MISSVALSST))
                CALL CHECK( NF90_ENDDEF(NCID) )
                CALL CHECK( NF90_PUT_VAR(NCID, VD(1), lonnight) )
                CALL CHECK( NF90_PUT_VAR(NCID, VD(2), latnight) )
        DO T_COUNT=1,2
                CALL CHECK(NF90_PUT_VAR(NCID,VD(3),ZOSST(:,:,T_COUNT),start=(/1,1,T_COUNT/),count=(/NX,NY,1/)))
        ENDDO
        CALL CHECK( NF90_CLOSE(NCID) )
        ENDIF
DEALLOCATE(day_ofday,sec_ofday,lonnight,latnight,temp_sst,sst_cumulated)
ENDIF


NTOBS=0

DO JT=1,2
 DO JY=1,NY
  DO JX=1,NX
        IF(ZOSST(JX,JY,JT).GE.-3._R4 .AND. ZOSST(JX,JY,JT).LT.35._R4 .AND. &
        & ZOERR(JX,JY,JT) .GT. 0._R8 .AND. ZOERR(JX,JY,JT) .LT. 1.5_R8 .AND. &
        & ZOTIM(JX,JY,JT).GE.DT1  .AND. ZOTIM(JX,JY,JT).LE.DT2) THEN
          NTOBS=NTOBS+1
          IF(NTOBS.GT.MAXOBS) &
          & CALL ABOR1('READ_AMSR2_NC   : MAXOBS TO INCREASE')
          ZDATA(NTOBS) = REAL(ZOSST(JX,JY,JT),KIND=R8)
          ZLLON(NTOBS) = REAL(ZOLON(JX),KIND=R8)
          ZLLAT(NTOBS) = REAL(ZOLAT(JY),KIND=R8)
          ZZTIM(NTOBS) = REAL(ZOTIM(JX,JY,JT),KIND=8)
          ZERR(NTOBS)  = REAL(ZOERR(JX,JY,JT),KIND=R8)
        ENDIF
  ENDDO
 ENDDO
ENDDO

WRITE(IOUNLOG,*) ' --> FOUND ',NTOBS,' OBSERVATIONS'
!call sbc_dcy_dealloc()

END SUBROUTINE READ_AMSR2_SST_NC
