SUBROUTINE READOBS103BIN

!.. READ OBS IN BINARY OR NETCDF FORMAT

USE SET_KND
USE RUN , ONLY : NSUBDOMAINS, IO_OBSFORMAT, LL_ONEPROC103, LL_LSBC
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE OBSDEF
USE OBS_STR
USE GRD_STR
USE ALLOCOBS
USE EXTGRID
USE NETCDF
USE STATS
USE MYNETCDF
USE MPIREL, ONLY : MYPROC

IMPLICIT NONE

INTEGER(I4) :: JP, KKCNT(NOFAMS)
INTEGER(I4) :: IAUX,IST,IEN,NMAXOBS,JO,NOINT,KOBS,JSAT,K
INTEGER(I4) :: NCID, DIMID, VARID, JOBS, MAXINS, MAXSLA, D, KK
INTEGER(I4) :: ITMP1, ITMP2
CHARACTER(LEN=30) :: CFILE
REAL(R8) :: ZICO, ZZTMP
LOGICAL, PARAMETER :: LL_PARTIALDOM = .TRUE.
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: TBIAS, SBIAS

#include "obs_events.h"

CALL MYFRTPROF_WALL('READOBS103BIN: READ BINARY OBS FILES',0)

ZICO = 0.2_R8

WRITE(IOUNLOG,*) ' MULTIPLICATIVE COEFFICIENT FOR SAFE EXTENSION'
WRITE(IOUNLOG,*) ' OF OBSERVATIONAL ARRAYS IS ',ZICO

CALL SETFGFILES(NSUBDOMAINS)
CALL SETFGFLAYOUT

!.. GET OBS VECT INDEX

OPEN(913,FILE='OBS_TAB.BIN',STATUS='OLD')
    READ(913,*) KKCNT(NNINS),KKCNT(NNSLA),&
                & KKCNT(NNSST),KKCNT(NNSSS)
CLOSE(913)

INS%NO = KKCNT(NNINS)
IF( OBS%ARG + OBS%XBT + OBS%GLD .EQ. 0 ) THEN
    INS%NO = 0
ENDIF
INS%NC = INS%NO

IF(INS%NO.GT.0) THEN

  CALL ALLOCINS(INS%NO+INT(INS%NO*ZICO),.TRUE.)

  INS%FLC = 0
  INS%FLG = 0

ENDIF

SLA%NO = KKCNT(NNSLA)
IF( OBS%SLA .EQ. 0 ) THEN
    SLA%NO = 0
ENDIF
SLA%NC=SLA%NO

IF(SLA%NO.GT.0) THEN
   
  CALL ALLOCSLA(SLA%NO+INT(SLA%NO*ZICO),.TRUE.)

  SLA%FLC = 0
  SLA%FLG = 0

ENDIF

SST%NO=KKCNT(NNSST)
IF( OBS%SST .EQ. 0 ) THEN
    SST%NO = 0
ENDIF
SST%NC=SST%NO

IF(SST%NO.GT.0) &
CALL ALLOCSST(SST%NO+INT(SST%NO*ZICO),.TRUE.)

SSS%NO=KKCNT(NNSSS)
IF( OBS%SSS .EQ. 0 ) THEN
    SSS%NO = 0
ENDIF
SSS%NC=SSS%NO

IF(SSS%NO.GT.0) &
CALL ALLOCSSS(SSS%NO+INT(SSS%NO*ZICO),.TRUE.)

CALL FLUSH(IOUNLOG)

IF ( INS%NO .GT. 0 ) THEN
  KOBS=INS%NO
  OPEN(31,FILE='INSMIS_ALL.bin',FORM='UNFORMATTED',&
  & ACCESS='SEQUENTIAL',STATUS='OLD')
  READ(31) INS%FLG(1:KOBS)
  READ(31) INS%FLC(1:KOBS)
  READ(31) INS%INO(1:KOBS)
  READ(31) INS%OTYPE(1:KOBS)
  READ(31) INS%PAR(1:KOBS)
  READ(31) INS%PLNO(1:KOBS)
  READ(31) INS%INST(1:KOBS)
  READ(31) INS%EVE(1:KOBS)
  READ(31) INS%KTY(1:KOBS)
  READ(31) INS%PROF(1:KOBS)
  READ(31) INS%TDIST(1:KOBS)
  READ(31) INS%LON(1:KOBS)
  READ(31) INS%LAT(1:KOBS)
  READ(31) INS%DPT(1:KOBS)
  READ(31) INS%TIM(1:KOBS)
  READ(31) INS%VAL(1:KOBS)
  READ(31) INS%BIA(1:KOBS)
  READ(31) INS%IB(1:KOBS,:)
  READ(31) INS%JB(1:KOBS,:)
  READ(31) INS%KB(1:KOBS)
  READ(31) INS%RB(1:KOBS)
  READ(31) INS%PQ(1:KOBS,:)
  READ(31) INS%BAC(1:KOBS)
  READ(31) INS%RES(1:KOBS)
  CLOSE(31)

  IF( ABS(IDOUBLEDOM) .EQ. 1 ) THEN
    INS%IBH(1:KOBS,:)=INS%IB(1:KOBS,:)
    INS%JBH(1:KOBS,:)=INS%JB(1:KOBS,:)
    INS%PQH(1:KOBS,:)=INS%PQ(1:KOBS,:)
    CALL INT_PAR_INS_2
  ENDIF

  WRITE(IOUNLOG,*) ' INS READ'
  CALL FLUSH(IOUNLOG)

  IF( LL_PARTIALDOM ) THEN
    WHERE( INS%IB(1:INS%NO,1).LT.GRD%I0 .OR. &
           INS%IB(1:INS%NO,1).GT.GRD%IM+GRD%I0-1 .OR. &
           INS%JB(1:INS%NO,1).LT.GRD%J0 .OR. &
           INS%JB(1:INS%NO,1).GT.GRD%JM+GRD%J0-1 .OR. &
           INS%IB(1:INS%NO,2).LT.GRD%I0 .OR. &
           INS%IB(1:INS%NO,2).GT.GRD%IM+GRD%I0-1 .OR. &
           INS%JB(1:INS%NO,2).LT.GRD%J0 .OR. &
           INS%JB(1:INS%NO,2).GT.GRD%JM+GRD%J0-1 .OR. &
           INS%IB(1:INS%NO,3).LT.GRD%I0 .OR. &
           INS%IB(1:INS%NO,3).GT.GRD%IM+GRD%I0-1 .OR. &
           INS%JB(1:INS%NO,3).LT.GRD%J0 .OR. &
           INS%JB(1:INS%NO,3).GT.GRD%JM+GRD%J0-1 .OR. &
           INS%IB(1:INS%NO,4).LT.GRD%I0 .OR. &
           INS%IB(1:INS%NO,4).GT.GRD%IM+GRD%I0-1 .OR. &
           INS%JB(1:INS%NO,4).LT.GRD%J0 .OR. &
           INS%JB(1:INS%NO,4).GT.GRD%JM+GRD%J0-1  ) 
                INS%FLG(1:INS%NO) = 0
                INS%FLC(1:INS%NO) = 0
                INS%EVE(1:INS%NO) = KEVE_PDOM
    ENDWHERE
    WRITE(IOUNLOG,*) ' INS OBS OUT OF MPI DOMAIN :',&
    & COUNT(INS%EVE(1:INS%NO) .EQ. KEVE_PDOM)
    INS%IB(1:INS%NO,:) = INS%IB(1:INS%NO,:) - GRD%I0 + 1
    INS%JB(1:INS%NO,:) = INS%JB(1:INS%NO,:) - GRD%J0 + 1
  ENDIF

  ! FIRST STEP WHEN SEPARATE SST ASSIMILATION IS ON
  IF( NN_INS_SST .EQ. 1 ) THEN
          WRITE(IOUNLOG,*) ' SST ASSIMILATION STEP IS 1'
          WRITE(IOUNLOG,*) ' REARRANGING SST OBS - REJECTING OTHERS'

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST )
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST )

          WRITE(IOUNLOG,*) ' *** TOTAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)

          WRITE(IOUNLOG,*) ' *** PARTIAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO

          WHERE( INS%PAR(1:INS%NO) .NE. KKSST ) 
                INS%FLG(1:INS%NO) = 0
                INS%FLC(1:INS%NO) = 0
                INS%EVE(1:INS%NO) = KEVE_NSST
          ENDWHERE
          WHERE( INS%PAR(1:INS%NO) .EQ. KKSST ) 
                INS%PAR(1:INS%NO) = KKTEMP
                INS%ERR(1:INS%NO) = INS%DPT(1:INS%NO)
                INS%DPT(1:INS%NO) = 0._R8
          ENDWHERE
  ENDIF
  ! SECOND STEP WHEN SEPARATE SST ASSIMILATION IS ON
  IF( NN_INS_SST .EQ. 2 .OR. NN_INS_SST .EQ. 3) THEN
          WRITE(IOUNLOG,*) ' SST ASSIMILATION STEP IS 2/3'
          WRITE(IOUNLOG,*) ' REJECTING SST OBS'

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST )
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST )

          WRITE(IOUNLOG,*) ' *** TOTAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)

          WRITE(IOUNLOG,*) ' *** PARTIAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO


          WHERE( INS%PAR(1:INS%NO) .EQ. KKSST )
                INS%FLG(1:INS%NO) = 0
                INS%FLC(1:INS%NO) = 0
                INS%EVE(1:INS%NO) = KEVE_NSST
          ENDWHERE
  ENDIF
  IF( NN_INS_SST .EQ. 0 ) THEN
          WRITE(IOUNLOG,*) ' SST ASSIMILATION STEP IS 0'
          WRITE(IOUNLOG,*) ' REARRANGING SST OBS'

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST )
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST )

          WRITE(IOUNLOG,*) ' *** TOTAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO

          ITMP1 = COUNT( INS%PAR(1:INS%NO) .EQ. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)
          ITMP2 = COUNT( INS%PAR(1:INS%NO) .NE. KKSST .AND. INS%FLC(1:INS%NO) .EQ. 1)

          WRITE(IOUNLOG,*) ' *** PARTIAL REPORT ***'
          WRITE(IOUNLOG,*) ' SST   INSITU OBS = ', ITMP1
          WRITE(IOUNLOG,*) ' OTHER INSITU OBS = ', ITMP2
          WRITE(IOUNLOG,*) ' TOTAL INSITU     = ',INS%NO

          WHERE( INS%PAR(1:INS%NO) .EQ. KKSST )
                INS%ERR(1:INS%NO) = INS%DPT(1:INS%NO)
                INS%DPT(1:INS%NO) = 0._R8
                INS%PAR(1:INS%NO) = KKTEMP
                INS%DSRC(1:INS%NO) = 'ICO'
          ENDWHERE
  ENDIF

  IF( LL_LSBC .OR. NN_INS_SST .EQ. 2 ) THEN

    ALLOCATE( TBIAS(GRD%IM,GRD%JM,GRD%KM) )
    ALLOCATE( SBIAS(GRD%IM,GRD%JM,GRD%KM) )

    IF( LL_LSBC ) THEN
      CALL GETNCVAR('FGUESS_BIAS.NC','INCTEMPER',GRD%IM,GRD%JM,GRD%KM,TBIAS)
      CALL GETNCVAR('FGUESS_BIAS.NC','INCSALINE',GRD%IM,GRD%JM,GRD%KM,SBIAS)
    ELSE
      CALL GETNCVAR('ANINCR_SST.NC','INCTEMPER',GRD%IM,GRD%JM,GRD%KM,TBIAS)
      CALL GETNCVAR('ANINCR_SST.NC','INCSALINE',GRD%IM,GRD%JM,GRD%KM,SBIAS)
    ENDIF

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(SHARED), PRIVATE(KK,D)
!$OMP DO SCHEDULE(STATIC,1)
#endif
    CYOBS : DO KK = 1,INS%NO

     D=INS%KB(KK)

     IF( INS%PAR(KK).EQ.KKTEMP)THEN

       ZZTMP = & 
       & OSUM( INS%PQ(KK,1:NPQ),TBIAS(INS%IB(KK,1:NPQ),INS%JB(KK,1:NPQ),D) )+ &
       & OSUM( INS%PQ(KK,NPQ+1:2*NPQ),TBIAS(INS%IB(KK,1:NPQ),INS%JB(KK,1:NPQ),D+1) )

       INS%BAC(KK) = INS%BAC(KK) + ZZTMP
       INS%BIA(KK) = ZZTMP

     ELSE IF(INS%PAR(KK).EQ.KKSAL )THEN

       ZZTMP = &
       & OSUM( INS%PQ(KK,1:NPQ),SBIAS(INS%IB(KK,1:NPQ),INS%JB(KK,1:NPQ),D) )+ &
       & OSUM( INS%PQ(KK,NPQ+1:2*NPQ),SBIAS(INS%IB(KK,1:NPQ),INS%JB(KK,1:NPQ),D+1) )

       INS%BAC(KK) = INS%BAC(KK) + ZZTMP
       INS%BIA(KK) = ZZTMP

     ENDIF

     INS%RES(KK) = INS%VAL(KK) - INS%BAC(KK)

    ENDDO CYOBS
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

    DEALLOCATE( TBIAS )
    DEALLOCATE( SBIAS )

  ENDIF

  IF( OBS%AIR .NE. 1 ) THEN
    CYOBA : DO KK = 1,INS%NO
      IF(INS%PAR(KK) .EQ. 13 .OR. INS%PAR(KK) .EQ. 14 .OR. &
         INS%KTY(KK) .EQ. 5 ) THEN
            INS%FLG(KK) = 0
            INS%FLC(KK) = 0
            INS%EVE(KK) = KEVE_UNSP
      ENDIF
    ENDDO CYOBA
  ENDIF

ENDIF

IF ( SLA%NO .GT. 0 ) THEN
  KOBS=SLA%NO
  OPEN(32,FILE='SLAMIS_ALL.bin',FORM='UNFORMATTED',&
  & ACCESS='SEQUENTIAL', STATUS='OLD')
  READ(32) SLA%FLC(1:KOBS)
  READ(32) SLA%NIND(1:KOBS)
  READ(32) SLA%INO(1:KOBS)
  READ(32) SLA%TRACK(1:KOBS)
  READ(32) SLA%EVE(1:KOBS)
  READ(32) SLA%KSAT(1:KOBS)
  READ(32) SLA%BOT(1:KOBS)
  READ(32) SLA%TDIST(1:KOBS)
  READ(32) SLA%LON(1:KOBS)
  READ(32) SLA%LAT(1:KOBS)
  READ(32) SLA%TIM(1:KOBS)
  READ(32) SLA%VAL(1:KOBS)
  READ(32) SLA%BIA(1:KOBS)
  READ(32) SLA%IB(1:KOBS,:)
  READ(32) SLA%JB(1:KOBS,:)
  READ(32) SLA%PQ(1:KOBS,:)
  READ(32) SLA%DPT(1:KOBS)
  READ(32) SLA%BAC(1:KOBS)
  READ(32) SLA%TB(1:KOBS,1:GRD%KM)
  READ(32) SLA%SB(1:KOBS,1:GRD%KM)
  READ(32) SLA%BCP(1:KOBS,1:NPRD_SLA)
  READ(32) SLA%RES(1:KOBS)
  CLOSE(32)

  IF( ABS(IDOUBLEDOM) .EQ. 1 ) THEN
    SLA%IBH(1:KOBS,:)=SLA%IB(1:KOBS,:)
    SLA%JBH(1:KOBS,:)=SLA%JB(1:KOBS,:)
    SLA%PQH(1:KOBS,:)=SLA%PQ(1:KOBS,:)
    CALL INT_PAR_SLA_2
  ENDIF

  ! SLA PREPROCESSING
  CALL SLAMDTUNDEF
  CALL UNBIAS_SLA
  IF ( LL_UNBIAS_SLA_LAT ) CALL UNBIAS_SLA_LAT
  IF ( LL_UNBIAS_SLA_AT ) CALL UNBIAS_SLA_AT

  IF( LL_PARTIALDOM ) THEN
    WHERE( SLA%IB(1:SLA%NO,1).LT.GRD%I0 .OR. &
           SLA%IB(1:SLA%NO,1).GT.GRD%IM+GRD%I0-1 .OR. &
           SLA%JB(1:SLA%NO,1).LT.GRD%J0 .OR. &
           SLA%JB(1:SLA%NO,1).GT.GRD%JM+GRD%J0-1 .OR. &
           SLA%IB(1:SLA%NO,2).LT.GRD%I0 .OR. &
           SLA%IB(1:SLA%NO,2).GT.GRD%IM+GRD%I0-1 .OR. &
           SLA%JB(1:SLA%NO,2).LT.GRD%J0 .OR. &
           SLA%JB(1:SLA%NO,2).GT.GRD%JM+GRD%J0-1 .OR. &
           SLA%IB(1:SLA%NO,3).LT.GRD%I0 .OR. &
           SLA%IB(1:SLA%NO,3).GT.GRD%IM+GRD%I0-1 .OR. &
           SLA%JB(1:SLA%NO,3).LT.GRD%J0 .OR. &
           SLA%JB(1:SLA%NO,3).GT.GRD%JM+GRD%J0-1 .OR. &
           SLA%IB(1:SLA%NO,4).LT.GRD%I0 .OR. &
           SLA%IB(1:SLA%NO,4).GT.GRD%IM+GRD%I0-1 .OR. &
           SLA%JB(1:SLA%NO,4).LT.GRD%J0 .OR. &
           SLA%JB(1:SLA%NO,4).GT.GRD%JM+GRD%J0-1 )
                SLA%FLG(1:SLA%NO) = 0
                SLA%FLC(1:SLA%NO) = 0
                SLA%EVE(1:SLA%NO) = KEVE_PDOM
    ENDWHERE
    WRITE(IOUNLOG,*) ' SLA OBS OUT OF MPI DOMAIN :',&
    & COUNT(SLA%EVE(1:SLA%NO) .EQ. KEVE_PDOM)
    SLA%IB(1:SLA%NO,:) = SLA%IB(1:SLA%NO,:) - GRD%I0 + 1
    SLA%JB(1:SLA%NO,:) = SLA%JB(1:SLA%NO,:) - GRD%J0 + 1
  ENDIF

ENDIF

IF ( SST%NO .GT. 0 ) THEN
  KOBS=SST%NO
  OPEN(33,FILE='SSTMIS_ALL.bin',FORM='UNFORMATTED',&
  & ACCESS='SEQUENTIAL',STATUS='OLD')
  READ(33) SST%FLC(1:KOBS)
  READ(33) SST%TRACK(1:KOBS)
  READ(33) SST%EVE(1:KOBS)
  READ(33) SST%KSAT(1:KOBS)
  READ(33) SST%TDIST(1:KOBS)
  READ(33) SST%LON(1:KOBS)
  READ(33) SST%LAT(1:KOBS)
  READ(33) SST%TIM(1:KOBS)
  READ(33) SST%VAL(1:KOBS)
  READ(33) SST%BIA(1:KOBS)
  READ(33) SST%IB(1:KOBS,:)
  READ(33) SST%JB(1:KOBS,:)
  READ(33) SST%PQ(1:KOBS,:)
  READ(33) SST%BAC(1:KOBS)
  READ(33) SST%ERR(1:KOBS)
  READ(33) SST%BCP(1:KOBS,1:NPRD_SLA)
  READ(33) SST%RES(1:KOBS)
  CLOSE(33)

  IF( ABS(IDOUBLEDOM) .EQ. 1 ) THEN
    SST%IBH(1:KOBS,:)=SST%IB(1:KOBS,:)
    SST%JBH(1:KOBS,:)=SST%JB(1:KOBS,:)
    SST%PQH(1:KOBS,:)=SST%PQ(1:KOBS,:)
    CALL INT_PAR_SST_2
  ENDIF

  IF( LL_PARTIALDOM ) THEN
    WHERE( SST%IB(1:SST%NO,1).LT.GRD%I0 .OR. &
           SST%IB(1:SST%NO,1).GT.GRD%IM+GRD%I0-1 .OR. &
           SST%JB(1:SST%NO,1).LT.GRD%J0 .OR. &
           SST%JB(1:SST%NO,1).GT.GRD%JM+GRD%J0-1 .OR. & 
           SST%IB(1:SST%NO,2).LT.GRD%I0 .OR. &
           SST%IB(1:SST%NO,2).GT.GRD%IM+GRD%I0-1 .OR. &
           SST%JB(1:SST%NO,2).LT.GRD%J0 .OR. &
           SST%JB(1:SST%NO,2).GT.GRD%JM+GRD%J0-1 .OR. &
           SST%IB(1:SST%NO,3).LT.GRD%I0 .OR. &
           SST%IB(1:SST%NO,3).GT.GRD%IM+GRD%I0-1 .OR. &
           SST%JB(1:SST%NO,3).LT.GRD%J0 .OR. &
           SST%JB(1:SST%NO,3).GT.GRD%JM+GRD%J0-1 .OR. &
           SST%IB(1:SST%NO,4).LT.GRD%I0 .OR. &
           SST%IB(1:SST%NO,4).GT.GRD%IM+GRD%I0-1 .OR. &
           SST%JB(1:SST%NO,4).LT.GRD%J0 .OR. &
           SST%JB(1:SST%NO,4).GT.GRD%JM+GRD%J0-1  ) 
                SST%FLG(1:SST%NO) = 0
                SST%FLC(1:SST%NO) = 0
                SST%EVE(1:SST%NO) = KEVE_PDOM
    ENDWHERE
    WRITE(IOUNLOG,*) ' SST OBS OUT OF MPI DOMAIN :',&
    & COUNT(SST%EVE(1:SST%NO) .EQ. KEVE_PDOM)
    SST%IB(1:SST%NO,:) = SST%IB(1:SST%NO,:) - GRD%I0 + 1
    SST%JB(1:SST%NO,:) = SST%JB(1:SST%NO,:) - GRD%J0 + 1
  ENDIF

ENDIF

IF ( SSS%NO .GT. 0 ) THEN
  KOBS=SSS%NO
  OPEN(34,FILE='SSSMIS_ALL.bin',FORM='UNFORMATTED',&
  & ACCESS='SEQUENTIAL',STATUS='OLD')
  READ(34) SSS%FLC(1:KOBS)
  READ(34) SSS%TRACK(1:KOBS)
  READ(34) SSS%EVE(1:KOBS)
  READ(34) SSS%KSAT(1:KOBS)
  READ(34) SSS%TDIST(1:KOBS)
  READ(34) SSS%LON(1:KOBS)
  READ(34) SSS%LAT(1:KOBS)
  READ(34) SSS%TIM(1:KOBS)
  READ(34) SSS%VAL(1:KOBS)
  READ(34) SSS%BIA(1:KOBS)
  READ(34) SSS%IB(1:KOBS,:)
  READ(34) SSS%JB(1:KOBS,:)
  READ(34) SSS%PQ(1:KOBS,:)
  READ(34) SSS%BAC(1:KOBS)
  READ(34) SSS%RES(1:KOBS)
  READ(34) SSS%BCP(1:KOBS,:)
  CLOSE(34)

  IF( ABS(IDOUBLEDOM) .EQ. 1 ) THEN
    SSS%IBH(1:KOBS,:)=SSS%IB(1:KOBS,:)
    SSS%JBH(1:KOBS,:)=SSS%JB(1:KOBS,:)
    SSS%PQH(1:KOBS,:)=SSS%PQ(1:KOBS,:)
    CALL INT_PAR_SSS_2
  ENDIF

  IF( LL_PARTIALDOM ) THEN
    WHERE( SSS%IB(1:SSS%NO,1).LT.GRD%I0 .OR. &
           SSS%IB(1:SSS%NO,1).GT.GRD%IM+GRD%I0-1 .OR. &
           SSS%JB(1:SSS%NO,1).LT.GRD%J0 .OR. &
           SSS%JB(1:SSS%NO,1).GT.GRD%JM+GRD%J0-1 .OR. &
           SSS%IB(1:SSS%NO,2).LT.GRD%I0 .OR. &
           SSS%IB(1:SSS%NO,2).GT.GRD%IM+GRD%I0-1 .OR. &
           SSS%JB(1:SSS%NO,2).LT.GRD%J0 .OR. &
           SSS%JB(1:SSS%NO,2).GT.GRD%JM+GRD%J0-1 .OR. &
           SSS%IB(1:SSS%NO,3).LT.GRD%I0 .OR. &
           SSS%IB(1:SSS%NO,3).GT.GRD%IM+GRD%I0-1 .OR. &
           SSS%JB(1:SSS%NO,3).LT.GRD%J0 .OR. &
           SSS%JB(1:SSS%NO,3).GT.GRD%JM+GRD%J0-1 .OR. &
           SSS%IB(1:SSS%NO,4).LT.GRD%I0 .OR. &
           SSS%IB(1:SSS%NO,4).GT.GRD%IM+GRD%I0-1 .OR. &
           SSS%JB(1:SSS%NO,4).LT.GRD%J0 .OR. &
           SSS%JB(1:SSS%NO,4).GT.GRD%JM+GRD%J0-1 )
                SSS%FLG(1:SSS%NO) = 0
                SSS%FLC(1:SSS%NO) = 0
                SSS%EVE(1:SSS%NO) = KEVE_PDOM
    ENDWHERE
    WRITE(IOUNLOG,*) ' SSS OBS OUT OF MPI DOMAIN :',&
    & COUNT(SSS%EVE(1:SSS%NO) .EQ. KEVE_PDOM)
    SSS%IB(1:SSS%NO,:) = SSS%IB(1:SSS%NO,:) - GRD%I0 + 1
    SSS%JB(1:SSS%NO,:) = SSS%JB(1:SSS%NO,:) - GRD%J0 + 1
  ENDIF

ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' COUNTS FOR SLA SATELLITES'
IF( SLA%NO .GT. 0 ) THEN
 DO JSAT=1,NOSLASATS
      SLA%ISLAOBS(JSAT) = COUNT( SLA%KSAT(1:SLA%NO) .EQ. JSAT)
      WRITE(IOUNLOG,*) ' SAT:',JSAT,' ',TRIM(CSLASATID(JSAT)),&
      & '   NO OF OBS:',SLA%ISLAOBS(JSAT)
 ENDDO
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' COUNTS FOR SST SATELLITES'
IF( SST%NO .GT. 0 ) THEN
 DO JSAT=1,NOSSTSATS
      SST%ISSTOBS(JSAT) = COUNT( SST%KSAT(1:SST%NO) .EQ. JSAT)
      WRITE(IOUNLOG,*) ' SAT:',JSAT,' ',TRIM(CSSTSATID(JSAT)),&
      & '   NO OF OBS:',SST%ISSTOBS(JSAT)
 ENDDO
ENDIF

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' COUNTS FOR SSS SATELLITES'
IF( SSS%NO .GT. 0 ) THEN
 DO JSAT=1,NOSSSSATS
      SSS%ISSSOBS(JSAT) = COUNT( SSS%KSAT(1:SSS%NO) .EQ. JSAT)
      WRITE(IOUNLOG,*) ' SAT:',JSAT,' ',TRIM(CSSSSATID(JSAT)),&
      & '   NO OF OBS:',SSS%ISSSOBS(JSAT)
 ENDDO
ENDIF

IF( INS%NO .GT. 0 ) THEN
   WHERE( INS%FLG .NE. 1 ) 
       INS%FLG = 0
       INS%FLC = 0
   END WHERE
   IF( SIZE(INS%FLC) .GT. INS%NO ) &
   INS%FLC( (INS%NO+1):SIZE(INS%FLC) ) = 0
ENDIF

CALL FLUSH(IOUNLOG)
CALL FLUSH(IOUNOUT)

CALL MYFRTPROF_WALL('READOBS103BIN: READ BINARY OBS FILES',1)
END SUBROUTINE READOBS103BIN
