SUBROUTINE READFGETAB(CFILE,CV,NX,NY,FS,ISTEPS,MX,MY,ETAB,LOP,LCL,NCID)

USE SET_KND
USE IOUNITS, ONLY : IOUNERR,IOUNOUT,IOUNLOG
USE NETCDF
USE READFG

IMPLICIT NONE

CHARACTER(LEN=*) , INTENT(IN) :: CFILE, CV
INTEGER(I4),INTENT(IN) :: NX,NY,ISTEPS,MX,MY,FS
REAL(R8),INTENT(OUT)  ::  ETAB(MX,MY,ISTEPS)
INTEGER(I4)            :: STAT, NCID, IDVAR,K,ITIME
INTEGER(I4) :: X,Y,TIMES
LOGICAL :: LOP,LCL

WRITE(901,*) CFILE,' ',CV,NX,NY,1,ISTEPS,LOP,LCL,NCID
CALL FLUSH(901)

IF(LOP) THEN
  STAT = NF90_OPEN(CFILE, NF90_NOWRITE, NCID)
  IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
ENDIF

STAT = NF90_INQ_DIMID (NCID, 'x', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID, IDVAR, LEN = X )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_DIMID (NCID, 'y', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_INQUIRE_DIMENSION (NCID, IDVAR, LEN = Y)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (NCID, CV, IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR(NCID,IDVAR,ETAB,START=(/1,1,FS/),COUNT=(/X,Y,ISTEPS/))
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

IF(LCL) STAT = NF90_CLOSE(NCID)

RETURN
END SUBROUTINE READFGETAB
