SUBROUTINE READ_BGERRS(CFILE,IM,JM,KM,TEMP,SAL,SSH)

!.. READ STATIC BACKGROUND-ERROR VALUES.
!..
!.. ANDREA STORTO *INGV* 2009-06-11

USE GRD_STR
USE NETCDF
USE IOUNITS
USE SET_KND

IMPLICIT NONE

CHARACTER(LEN=*),INTENT(IN) :: CFILE
INTEGER         ,INTENT(IN) :: IM,JM,KM
REAL(R8) , INTENT(OUT) :: TEMP(IM,JM,KM),SAL(IM,JM,KM)
REAL(R8) , INTENT(OUT) :: SSH(IM,JM)
INTEGER(I4) :: STAT,NCID,IDVAR,KW

WRITE(IOUNLOG,*) ' OPENING FILE ',TRIM(CFILE)
CALL FLUSH(IOUNLOG)

STAT=NF90_OPEN(CFILE,NF90_NOWRITE, NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (NCID, 'votemper', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,TEMP,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,GRD%KM/) )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (NCID, 'vosaline', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,SAL,START=(/GRD%I0,GRD%J0,1/),COUNT=(/GRD%IM,GRD%JM,GRD%KM/) )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT = NF90_INQ_VARID (NCID, 'sossheig', IDVAR)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
STAT = NF90_GET_VAR (NCID,IDVAR,SSH,START=(/GRD%I0,GRD%J0/),COUNT=(/GRD%IM,GRD%JM/) )
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)

STAT=NF90_CLOSE(NCID)
IF (STAT /= NF90_NOERR) CALL HANDLE_ERR(STAT)
END SUBROUTINE READ_BGERRS
