SUBROUTINE READAIRFILE(CFIN,IOUN,NMAX,NOB,KTYP,PAR,DEP,VAL,TIM,LON,LAT,&
& PRF,PLA)

! READ OBSERVATION IN REFORMATTED ICOADS FORMAT
!
! A.S. - 26.11.2013

  USE SET_KND
  USE CALENDAR
  USE OBSDEF
  USE RUN , ONLY : ZJULSTART, ZJULEND

  IMPLICIT NONE

  INTEGER(I4), INTENT(IN) :: IOUN,NMAX
  CHARACTER(LEN=*), INTENT(IN) :: CFIN
  INTEGER(I4), INTENT(OUT) :: NOB
  INTEGER(I4), DIMENSION(NMAX),INTENT(OUT) :: KTYP, PAR, PRF
  REAL   (R8), DIMENSION(NMAX),INTENT(OUT) :: DEP,  VAL, LON, LAT
  REAL   (DP), DIMENSION(NMAX),INTENT(OUT) :: TIM
  CHARACTER(LEN=8 ), DIMENSION(NMAX),INTENT(OUT) :: PLA

  INTEGER(I4), PARAMETER :: MAXVARS=14
  INTEGER(I4) :: KOBS, NOTW, NFLR, KKTP, KKOP
  INTEGER(I4) :: IERR,ITTT,ITTS,IYY,IMM,IDD
  REAL(DP)    :: ZTIME, TIME, RHH, ZTIME_REF
  REAL(R8)    :: RLAT, RLON, VALT, T,Q,P,W,D
  LOGICAL     :: LL_INIT, LLTIME, LCOO
  CHARACTER(LEN=9) :: CID, CTMP

  INTEGER(I4) :: PYY,PMM,PDD
  REAL(R8)    :: PHH,PLON,PLAT,PT,PQ

  WRITE(IOUN,*) ' ^^^ READAIRFILE PROCESSING FILE ',TRIM(CFIN)

  KOBS=0
  KKOP=0
  NOTW=0
  NFLR=0

  IERR=0

  CALL YMDS2JU(1950,1,1,0._R8,ZTIME_REF)

  WRITE(IOUN,*) ' REFERENCE TIME IS', ZTIME_REF

800  FORMAT(I2,X,I2,X,I4,X,I2,X,I2,X,3F12.6,5F10.3)

  OPEN(71,FILE=CFIN,STATUS='OLD',IOSTAT=IERR)
  IF( IERR .NE. 0 ) CALL ABOR1('READAIRFILE: OPEN FAILED')
  PROFILES : DO WHILE (IERR .EQ. 0)
     READ(71,800,IOSTAT=IERR) &
     & ITTT,ITTS,IYY,IMM,IDD,RHH,RLON,RLAT,T,Q,P,W,D
     IF( IERR .NE. 0 ) EXIT PROFILES
     LCOO = .TRUE.
     IF(RLON .LT. -180._R8 .OR. RLON .GT. 360._R8 &
     .OR. RLAT .LT. -90._R8 .OR. RLAT .GT. 180.-R8 ) THEN
         KKOP=KKOP+1
         LCOO = .FALSE.
     ENDIF
     TIME = RHH
     CALL YMDS2JU(IYY,IMM,IDD,TIME*3600._R8,ZTIME)
     LLTIME = (ZTIME .GE. ZJULSTART .AND. ZTIME .LE. ZJULEND)
     IF(MOD(NINT(RHH),6).NE.0) LLTIME=.FALSE.
     IF(KOBS.GT.0)THEN
       IF(IYY.EQ.PYY.AND.IMM.EQ.PMM.AND.IDD.EQ.PDD.AND.&
       &  RHH.EQ.PHH.AND.RLON.EQ.PLON.AND.RLAT.EQ.PLAT.AND.&
       &  T.EQ.PT.AND.Q.EQ.PQ) LLTIME=.FALSE.
     ENDIF
     PYY=IYY
     PMM=IMM
     PDD=IDD
     PHH=RHH
     PLON=RLON
     PLAT=RLAT
     PT =T
     PQ =Q
   
     IF(.NOT.LLTIME) NOTW = NOTW + 1
     IF( RLON .GT. 180._R8 ) RLON = RLON -360._R8
     IF(.NOT.LLTIME .OR. .NOT.LCOO) THEN
        CYCLE PROFILES
     ENDIF
     KKTP = -ITTS-ITTT*100

     IF(KOBS.GT.0 .AND. RLON .EQ. LON(KOBS) .AND. &
     & RLAT .EQ. LAT(KOBS) ) CYCLE PROFILES

     ! GET OBS
     IF( T .GT. 220._R8 .AND. T .LT. 330._R8 ) THEN
       KOBS=KOBS+1 
       LON(KOBS) = RLON
       LAT(KOBS) = RLAT
       PAR(KOBS) = KKT2M
       KTYP(KOBS) = KKTP
       DEP(KOBS) = -2._R8
       VAL(KOBS) = T
       TIM(KOBS) = ZTIME-ZTIME_REF
       PRF(KOBS) = KOBS
     ENDIF
     IF( Q .GT. 0._R8 .AND. Q .LT. 999._R8 ) THEN
       KOBS=KOBS+1
       LON(KOBS) = RLON
       LAT(KOBS) = RLAT
       PAR(KOBS) = KKQ2M 
       KTYP(KOBS) = KKTP
       DEP(KOBS) = -2._R8
       VAL(KOBS) = Q/1000._R8
       TIM(KOBS) = ZTIME-ZTIME_REF
       PRF(KOBS) = KOBS
     ENDIF

     PLA(KOBS)(1:3) = 'AIR'
     WRITE(PLA(KOBS)(5:8),'(I4.4)')  KKTP

  ENDDO PROFILES
  CLOSE(71)

  NOB = KOBS

  WRITE(IOUN,*)
  WRITE(IOUN,*) ' ^^^ REPORT '
  WRITE(IOUN,*) ' NUMBER OF BAD  OBS COO  :', KKOP
  WRITE(IOUN,*) ' NUMBER OF GOOD OBSERV.  :', KOBS
  WRITE(IOUN,*) ' NUMBER OF P OUT OF TIME :', NOTW
  WRITE(IOUN,*) ' NUMBER OF BAD FLAGS OBS :', NFLR
  WRITE(IOUN,*) 

END SUBROUTINE READAIRFILE
