#undef SHARED_MEMORY
SUBROUTINE READFGFIELDS_A(T2M,Q2M)

USE SET_KND
USE IOUNITS, ONLY : IOUNERR,IOUNOUT,IOUNLOG
USE GRD_STR, ONLY : GRD
USE READFG
USE RUN, ONLY : NTSTEPS, LL_RESTART_FILE, NSUBDOMAINS
USE MPIREL
USE MYNETCDF

IMPLICIT NONE

REAL(R8),DIMENSION(GRD%IM,GRD%JM,NFGTSTEPS), INTENT(OUT) :: T2M,Q2M
REAL(R8), ALLOCATABLE, DIMENSION(:,:,:)   :: W3D

INTEGER(I4) :: ISTARTX,ISTARTY,IENDX,IENDY
INTEGER(I4) :: ISX,ISY,IEX,IEY
INTEGER(I4) :: JF,MNX,MNY,MNZ,MYT
INTEGER(I4) :: MAXX,MAXY
INTEGER(I4) :: TSFIRST, JT
INTEGER(I4) :: JR,KR

CHARACTER(LEN=8) :: CVARS(7)
CHARACTER(LEN=100) :: CFGFILES_open, CAUX

IF( LL_RESTART_FILE ) THEN
  CVARS(1)(1:2) = 'tn'
  CVARS(2)(1:2) = 'sn'
  CVARS(3)(1:4) = 'sshn'
  CVARS(4)(1:2) = 'un'
  CVARS(5)(1:2) = 'vn'
  CVARS(6)(1:5) = 't_aml'
  CVARS(7)(1:5) = 'q_aml'
ELSE
  CVARS(1)(1:8) = 'votemper'
  CVARS(2)(1:8) = 'vosaline'
  CVARS(3)(1:8) = 'sossheig'
  CVARS(4)(1:8) = 'vozocrtx'
  CVARS(5)(1:8) = 'vomecrty'
  CVARS(6)(1:8) = 'soattaml'
  CVARS(7)(1:8) = 'soatqaml'
ENDIF

#ifdef SHARED_MEMORY
INTEGER(I4) ::  OMP_GET_THREAD_NUM
#endif

!AS  AS VECTOR (DE-)ALLOCATION WITHIN OPENMP PARALLEL REGIONS
!AS  MIGHT FAIL DEPENDING ON THE OPENMP IMPLEMENTATION/VERSION,
!AS  MAXIMUM SIZE OF LOCAL DOMAIN ARE FOUND ON TOP OF THE READING

MAXX=MAXVAL(KDSL(1:NFGFILES,1))
MAXY=MAXVAL(KDSL(1:NFGFILES,2))
MNZ=GRD%KM

WRITE(IOUNLOG,*) '  CHECK --- NFGFILES = ',NFGFILES
WRITE(IOUNLOG,*) '  MAXVALUES FOR LOCAL DOMAIN SIZE =',MAXX,MAXY

ALLOCATE ( W3D(MAXX,MAXY,NFGTSTEPS))

TIMESTEPS : DO JT = 1,NTSTEPS
 IF (LL_FGASSIM(JT) ) THEN
     TSFIRST =  JT
     EXIT TIMESTEPS
 ENDIF
ENDDO TIMESTEPS

IF(LMPION) THEN
  OPEN(901,FILE='FIRSTGUESS_READING.OUT.'//TRIM(CMPIDOM))
ELSE
  OPEN(901,FILE='FIRSTGUESS_READING.OUT')
ENDIF

#ifdef SHARED_MEMORY
!$OMP PARALLEL DEFAULT(PRIVATE),SHARED(Q2M,T2M,ETA,KDNS,KDNE,&
!$OMP & KDLS,KDLE,KDSL,CFGFILES,MAXX,MAXY,NFGTSTEPS,MNZ,NCIDFG)
MYT=OMP_GET_THREAD_NUM() + 1
!$OMP DO SCHEDULE(DYNAMIC,1)
#else
MYT=1
#endif

DO JF=1,NFGFILES

  IF( LMPION .AND. NSUBDOMAINS .EQ. 0) THEN

        IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_t2m.nc'
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(6)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,T2M)
            WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_q2m.nc'
            CALL GETNCVAR(TRIM(CFGFILES_open),TRIM(CVARS(7)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,Q2M)
        ELSE
          IF(LL_READBYREC) THEN
            KR=0
            DO JR=TSFIRST,NFGTSTEPS
              KR=KR+1
              WRITE(CAUX,'(A,I4.4,A)') TRIM(CBGDIR)//'/'//'OPA_FIRSTGUESS_record_',JR,'.nc'
              CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(6)),GRD%IM,GRD%JM,       T2M(:,:,  KR))
              CALL GETNCVAR(TRIM(CAUX),TRIM(CVARS(7)),GRD%IM,GRD%JM,       Q2M(:,:,  KR))
            ENDDO
          ELSE
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(6)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,T2M)
            CALL GETNCVAR(TRIM(CFGFILES(JF)),TRIM(CVARS(7)),GRD%IM,GRD%JM,       TSFIRST,NFGTSTEPS,Q2M)
          ENDIF
        ENDIF

  ELSE

   ISTARTX=KDNS(JF,1)-MP_XST(MYPROC)+1
   ISTARTY=KDNS(JF,2)-MP_YST(MYPROC)+1
   IENDX=KDNE(JF,1)-MP_XST(MYPROC)+1
   IENDY=KDNE(JF,2)-MP_YST(MYPROC)+1
   ISX=KDLS(JF,1)
   ISY=KDLS(JF,2)
   IEX=KDLE(JF,1)
   IEY=KDLE(JF,2)

   MNX=KDSL(JF,1)
   MNY=KDSL(JF,2)

   WRITE(IOUNLOG,*) ' === LOCAL SIZE FOR DOMAIN',JF,' CALLED BY THREAD',MYT,&
   & ':',MNX,MNY,MNZ,NFGTSTEPS
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) '    N      FILE         MNX  MAXX '; CALL FLUSH(IOUNLOG)
   WRITE(IOUNLOG,*) ' ',JF, TRIM(CFGFILES(JF)),MNX,MAXX ; CALL FLUSH(IOUNLOG)


   WRITE(IOUNLOG,*) ' LAYOUT FOR DOMAIN',JF,':',ISTARTX,IENDX,ISTARTY,IENDY
   WRITE(IOUNLOG,*) ' WHICH IS IN FILE:',ISX,IEX,ISY,IEY
   CALL FLUSH(IOUNLOG)

   WRITE(IOUNLOG,*) ' ABOUT TO READ AIR FIELDS'
   CALL FLUSH(IOUNLOG)

   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
     WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_t2m.nc'
   ELSE
     WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF

   CALL READFGETAB(TRIM(CFGFILES_open),TRIM(CVARS(6)),MNX,MNY,TSFIRST,NFGTSTEPS,MAXX,MAXY,&
   & W3D,.TRUE.,.TRUE.,NCIDFG(JF) )
   WRITE(IOUNLOG,*) ' DONE'
   WRITE(IOUNLOG,*) ' T2M  - LOCAL TO GLOBAL COPY'
   CALL FLUSH(IOUNLOG)
   T2M(ISTARTX:IENDX,ISTARTY:IENDY,:) = W3D(ISX:IEX,ISY:IEY,:)
   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

   IF ( INDEX(CFGFILES(JF), ".nc" )==0) THEN
     WRITE(CFGFILES_open,'(A,A)') TRIM(CFGFILES(JF))//'_q2m.nc'
   ELSE
     WRITE(CFGFILES_open,'(A)') TRIM(CFGFILES(JF))
   ENDIF

   CALL READFGETAB(TRIM(CFGFILES_open),TRIM(CVARS(7)),MNX,MNY,TSFIRST,NFGTSTEPS,MAXX,MAXY,&
   & W3D,.TRUE.,.TRUE.,NCIDFG(JF) )
   WRITE(IOUNLOG,*) ' DONE'
   WRITE(IOUNLOG,*) ' Q2M  - LOCAL TO GLOBAL COPY'
   CALL FLUSH(IOUNLOG)
   Q2M(ISTARTX:IENDX,ISTARTY:IENDY,:) = W3D(ISX:IEX,ISY:IEY,:)
   WRITE(IOUNLOG,*) ' DONE'
   CALL FLUSH(IOUNLOG)

  ENDIF

ENDDO
#ifdef SHARED_MEMORY
!$OMP END DO
!$OMP END PARALLEL
#endif

DEALLOCATE( W3D )
CLOSE(901)

END SUBROUTINE READFGFIELDS_A
