SUBROUTINE REG_REJ(NOPT)

USE OBS_STR
USE GRD_STR
USE MYNETCDF
USE IOUNITS
USE OBSHANDLING

IMPLICIT NONE

INTEGER(I4), INTENT(IN) :: NOPT
INTEGER(I4) :: JO
INTEGER(I4) :: NX,NY
REAL(R8), ALLOCATABLE :: TLSM(:,:)
REAL(R8) :: ZLA, ZLS

#include "obs_events.h"

NX=GRD%IM
NY=GRD%JM
ALLOCATE(TLSM(NX,NY))
WRITE(IOUNLOG,*) 

IF(NOPT.EQ.1) THEN
  WRITE(IOUNLOG,*) ' /// REGIONAL REJECTION  --  OPT 1 ' 
  WRITE(IOUNLOG,*) ' /// ATLANTIC NORTH OF 48N '
  CALL GETNCVAR('lsm_atlantic.nc','lsm_atlantic',NX,NY,TLSM)
  ! INSITU
  IF(INS%NO.GT.0) THEN
   DO JO=1,INS%NO
    ZLS=OSUM(INS%PQ(JO,1:NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)) )+ &
    & OSUM(INS%PQ(JO,NPQ+1:2*NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)))
    ZLA=INS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.48._R8 ) THEN
        INS%FLC(JO) = 0
        INS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SLA
  IF(SLA%NO.GT.0) THEN
   DO JO=1,SLA%NO
    ZLS=OSUM(SLA%PQ(JO,1:NPQ),TLSM(SLA%IB(JO,1:NPQ),SLA%JB(JO,1:NPQ)) )
    ZLA=SLA%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.48._R8 ) THEN
        SLA%FLC(JO) = 0
        SLA%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SST
  IF(SST%NO.GT.0) THEN
   DO JO=1,SST%NO
    ZLS=OSUM(SST%PQ(JO,1:NPQ),TLSM(SST%IB(JO,1:NPQ),SST%JB(JO,1:NPQ)) )
    ZLA=SST%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.48._R8 ) THEN
        SST%FLC(JO) = 0
        SST%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SSS
  IF(SSS%NO.GT.0) THEN
   DO JO=1,SSS%NO
    ZLS=OSUM(SSS%PQ(JO,1:NPQ),TLSM(SSS%IB(JO,1:NPQ),SSS%JB(JO,1:NPQ)) )
    ZLA=SSS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.48._R8 ) THEN
        SSS%FLC(JO) = 0
        SSS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
ELSEIF(NOPT.EQ.2) THEN
  WRITE(IOUNLOG,*) ' /// REGIONAL REJECTION  --  OPT 2 ' 
  WRITE(IOUNLOG,*) ' /// ATLANTIC SOUTH OF 48N AND NORTH OF 26N'
  CALL GETNCVAR('lsm_atlantic.nc','lsm_atlantic',NX,NY,TLSM)
  ! INSITU
  IF(INS%NO.GT.0) THEN
   DO JO=1,INS%NO
    ZLS=OSUM(INS%PQ(JO,1:NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)) )+ &
    & OSUM(INS%PQ(JO,NPQ+1:2*NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)))
    ZLA=INS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.26._R8.AND.ZLA.LT.48._R8 ) THEN
        INS%FLC(JO) = 0
        INS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SLA
  IF(SLA%NO.GT.0) THEN
   DO JO=1,SLA%NO
    ZLS=OSUM(SLA%PQ(JO,1:NPQ),TLSM(SLA%IB(JO,1:NPQ),SLA%JB(JO,1:NPQ)) )
    ZLA=SLA%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.26._R8.AND.ZLA.LT.48._R8 ) THEN
        SLA%FLC(JO) = 0
        SLA%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SST
  IF(SST%NO.GT.0) THEN
   DO JO=1,SST%NO
    ZLS=OSUM(SST%PQ(JO,1:NPQ),TLSM(SST%IB(JO,1:NPQ),SST%JB(JO,1:NPQ)) )
    ZLA=SST%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.26._R8.AND.ZLA.LT.48._R8 ) THEN
        SST%FLC(JO) = 0
        SST%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SSS
  IF(SSS%NO.GT.0) THEN
   DO JO=1,SSS%NO
    ZLS=OSUM(SSS%PQ(JO,1:NPQ),TLSM(SSS%IB(JO,1:NPQ),SSS%JB(JO,1:NPQ)) )
    ZLA=SSS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.GE.26._R8.AND.ZLA.LT.48._R8 ) THEN
        SSS%FLC(JO) = 0
        SSS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
ELSEIF(NOPT.EQ.3) THEN
  WRITE(IOUNLOG,*) ' /// REGIONAL REJECTION  --  OPT 3 ' 
  WRITE(IOUNLOG,*) ' /// ATLANTIC SOUTH OF 26N'
  CALL GETNCVAR('lsm_atlantic.nc','lsm_atlantic',NX,NY,TLSM)
  ! INSITU
  IF(INS%NO.GT.0) THEN
   DO JO=1,INS%NO
    ZLS=OSUM(INS%PQ(JO,1:NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)) )+ &
    & OSUM(INS%PQ(JO,NPQ+1:2*NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)))
    ZLA=INS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LT.26._R8 ) THEN
        INS%FLC(JO) = 0
        INS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SLA
  IF(SLA%NO.GT.0) THEN
   DO JO=1,SLA%NO
    ZLS=OSUM(SLA%PQ(JO,1:NPQ),TLSM(SLA%IB(JO,1:NPQ),SLA%JB(JO,1:NPQ)) )
    ZLA=SLA%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LT.26._R8 ) THEN
        SLA%FLC(JO) = 0
        SLA%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SST
  IF(SST%NO.GT.0) THEN
   DO JO=1,SST%NO
    ZLS=OSUM(SST%PQ(JO,1:NPQ),TLSM(SST%IB(JO,1:NPQ),SST%JB(JO,1:NPQ)) )
    ZLA=SST%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LT.26._R8 ) THEN
        SST%FLC(JO) = 0
        SST%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SSS
  IF(SSS%NO.GT.0) THEN
   DO JO=1,SSS%NO
    ZLS=OSUM(SSS%PQ(JO,1:NPQ),TLSM(SSS%IB(JO,1:NPQ),SSS%JB(JO,1:NPQ)) )
    ZLA=SSS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LT.26._R8 ) THEN
        SSS%FLC(JO) = 0
        SSS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
ELSEIF(NOPT.EQ.4) THEN
  WRITE(IOUNLOG,*) ' /// REGIONAL REJECTION  --  OPT 4 ' 
  WRITE(IOUNLOG,*) ' /// ATLANTIC SOUTH OF 30S'
  CALL GETNCVAR('lsm_atlantic.nc','lsm_atlantic',NX,NY,TLSM)
  ! INSITU
  IF(INS%NO.GT.0) THEN
   DO JO=1,INS%NO
    ZLS=OSUM(INS%PQ(JO,1:NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)) )+ &
    & OSUM(INS%PQ(JO,NPQ+1:2*NPQ),TLSM(INS%IB(JO,1:NPQ),INS%JB(JO,1:NPQ)))
    ZLA=INS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LE. -30._R8 ) THEN
        INS%FLC(JO) = 0
        INS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SLA
  IF(SLA%NO.GT.0) THEN
   DO JO=1,SLA%NO
    ZLS=OSUM(SLA%PQ(JO,1:NPQ),TLSM(SLA%IB(JO,1:NPQ),SLA%JB(JO,1:NPQ)) )
    ZLA=SLA%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LE. -30._R8 ) THEN
        SLA%FLC(JO) = 0
        SLA%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SST
  IF(SST%NO.GT.0) THEN
   DO JO=1,SST%NO
    ZLS=OSUM(SST%PQ(JO,1:NPQ),TLSM(SST%IB(JO,1:NPQ),SST%JB(JO,1:NPQ)) )
    ZLA=SST%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LE. -30._R8 ) THEN
        SST%FLC(JO) = 0
        SST%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
  ! SSS
  IF(SSS%NO.GT.0) THEN
   DO JO=1,SSS%NO
    ZLS=OSUM(SSS%PQ(JO,1:NPQ),TLSM(SSS%IB(JO,1:NPQ),SSS%JB(JO,1:NPQ)) )
    ZLA=SSS%LAT(JO)
    IF( ZLS.GT.1.E-3_R8 .AND. ZLA.LE. -30._R8 ) THEN
        SSS%FLC(JO) = 0
        SSS%EVE(JO) = KEVE_REGR
    ENDIF
   ENDDO
  ENDIF
ELSEIF(NOPT.EQ.5) THEN
  CALL REGRNDREJ(NN_OBS_RET)
ELSE
  CALL ABOR1('REG_REJ : UNRECOGNIZED OPTION FOR NOPT')
ENDIF

WRITE(IOUNLOG,*)
DEALLOCATE(TLSM)

END SUBROUTINE REG_REJ
