SUBROUTINE REO4MIN

!*** REO4MIN
!
! PURPOSE: SAFELY REORDER OBS VECTORS IN ORDER
!  TO HAVE ONLY GOOD OBSERVATIONS IN THE NEW
!  OBS ARRAYS. THIS SPEEDS UP MINIMIZATION,
!  ESPECIALLY WITHIN OPENMP PARALLELIZATION.
!
! A.STORTO, 2009

USE GRD_STR
USE SET_KND
USE OBS_STR
USE RUN
USE MYFRTPROF, ONLY : MYFRTPROF_WALL

IMPLICIT NONE

INTEGER(KIND=I4) :: JOBS,K,NGOOD
TYPE(SLA_T) :: NEWSLA
TYPE(INS_T) :: NEWINS
TYPE(SST_T) :: NEWSST
TYPE(SSS_T) :: NEWSSS


CALL MYFRTPROF_WALL('REO4MIN: REORDER OBS VECTOR',0)

!... SLA CASE
IF( SLA%NO .GT. 0 ) THEN

NGOOD=COUNT(SLA%FLC(1:SLA%NO).EQ.1)
NEWSLA%NO=NGOOD
NEWSLA%NC=NGOOD
ALLOCATE(NEWSLA%LON(NEWSLA%NO),&
        &NEWSLA%INO(NEWSLA%NO),&
        &NEWSLA%LAT(NEWSLA%NO),&
        &NEWSLA%VAL(NEWSLA%NO),&
        &NEWSLA%TDIST(NEWSLA%NO),&
        &NEWSLA%FLG(NEWSLA%NO),&
        &NEWSLA%FLC(NEWSLA%NO),&
        &NEWSLA%KSAT(NEWSLA%NO),&
        &NEWSLA%BOT(NEWSLA%NO),&
        &NEWSLA%EVE(NEWSLA%NO),&
        &NEWSLA%INC(NEWSLA%NO),&
        &NEWSLA%BAC(NEWSLA%NO),&
        &NEWSLA%BIA(NEWSLA%NO),&
        &NEWSLA%ERR(NEWSLA%NO),&
        &NEWSLA%BGERR(NEWSLA%NO),&
        &NEWSLA%RES(NEWSLA%NO),&
        &NEWSLA%B_A(NEWSLA%NO),&
        &NEWSLA%IB (NEWSLA%NO,NPQ),&
        &NEWSLA%JB (NEWSLA%NO,NPQ),&
        &NEWSLA%PQ (NEWSLA%NO,NPQ),&
        &NEWSLA%IBH(NEWSLA%NO,NPQ),&
        &NEWSLA%JBH(NEWSLA%NO,NPQ),&
        &NEWSLA%PQH(NEWSLA%NO,NPQ),&
        &NEWSLA%TRACK(NEWSLA%NO),&
        &NEWSLA%DPT(NEWSLA%NO),&
        &NEWSLA%NIND(NEWSLA%NO),&
        &NEWSLA%TIM(NEWSLA%NO))

IF ( NCONF .NE. 202 ) THEN
 ALLOCATE(NEWSLA%TB(NEWSLA%NO,GRD%KM),&
         &NEWSLA%SB(NEWSLA%NO,GRD%KM),&
         &NEWSLA%BCP(NEWSLA%NO,NPRD_SLA))
ENDIF

K=0
SLALOOP : DO JOBS=1,SLA%NO
   IF(SLA%FLC(JOBS) .EQ.1 ) THEN
   K=K+1
        NEWSLA%LON(K)=SLA%LON(JOBS)
        NEWSLA%LAT(K)=SLA%LAT(JOBS)
        NEWSLA%INO(K)=SLA%INO(JOBS)
        NEWSLA%NIND(K)=SLA%NIND(JOBS)
        NEWSLA%VAL(K)=SLA%VAL(JOBS)
        NEWSLA%TDIST(K)=SLA%TDIST(JOBS)
        NEWSLA%FLG(K)=SLA%FLG(JOBS)
        NEWSLA%FLC(K)=SLA%FLC(JOBS)
        NEWSLA%KSAT(K)=SLA%KSAT(JOBS)
        NEWSLA%BOT (K)=SLA%BOT (JOBS)
        NEWSLA%EVE(K)=SLA%EVE(JOBS)
        NEWSLA%INC(K)=SLA%INC(JOBS)
        NEWSLA%BAC(K)=SLA%BAC(JOBS)
        NEWSLA%BIA(K)=SLA%BIA(JOBS)
        NEWSLA%ERR(K)=SLA%ERR(JOBS)
        NEWSLA%BGERR(K)=SLA%BGERR(JOBS)
        NEWSLA%RES(K)=SLA%RES(JOBS)
        NEWSLA%B_A(K)=SLA%B_A(JOBS)
        NEWSLA%IB (K,:)=SLA%IB (JOBS,:)
        NEWSLA%JB (K,:)=SLA%JB (JOBS,:)
        NEWSLA%PQ (K,:)=SLA%PQ(JOBS,:)
        NEWSLA%TRACK(K)=SLA%TRACK(JOBS)
        NEWSLA%DPT(K)=SLA%DPT(JOBS)
        IF( NCONF .NE. 202 ) THEN
          NEWSLA%TB (K,:)=SLA%TB (JOBS,:)
          NEWSLA%SB (K,:)=SLA%SB (JOBS,:)
          NEWSLA%BCP(K,:)=SLA%BCP(JOBS,:)
        ENDIF
        NEWSLA%TIM(K)=SLA%TIM(JOBS)
        NEWSLA%IBH(K,:)=SLA%IBH(JOBS,:)
        NEWSLA%JBH(K,:)=SLA%JBH(JOBS,:)
        NEWSLA%PQH(K,:)=SLA%PQH(JOBS,:)
   ENDIF
ENDDO SLALOOP
NEWSLA%FLC = 1

SLA%NO=NEWSLA%NO
SLA%NC=NEWSLA%NO
SLALOOP2 : DO JOBS=1,SLA%NO
       SLA%LON(JOBS)=NEWSLA%LON(JOBS)
       SLA%LAT(JOBS)=NEWSLA%LAT(JOBS)
       SLA%INO(JOBS)=NEWSLA%INO(JOBS)
       SLA%NIND(JOBS)=NEWSLA%NIND(JOBS)
       SLA%VAL(JOBS)=NEWSLA%VAL(JOBS)
       SLA%TDIST(JOBS)=NEWSLA%TDIST(JOBS)
       SLA%FLG(JOBS)=NEWSLA%FLG(JOBS)
       SLA%FLC(JOBS)=NEWSLA%FLC(JOBS)
       SLA%KSAT(JOBS)=NEWSLA%KSAT(JOBS)
       SLA%BOT (JOBS)=NEWSLA%BOT (JOBS)
       SLA%EVE(JOBS)=NEWSLA%EVE(JOBS)
       SLA%INC(JOBS)=NEWSLA%INC(JOBS)
       SLA%BAC(JOBS)=NEWSLA%BAC(JOBS)
       SLA%BIA(JOBS)=NEWSLA%BIA(JOBS)
       SLA%ERR(JOBS)=NEWSLA%ERR(JOBS)
       SLA%BGERR(JOBS)=NEWSLA%BGERR(JOBS)
       SLA%RES(JOBS)=NEWSLA%RES(JOBS)
       SLA%B_A(JOBS)=NEWSLA%B_A(JOBS)
       SLA%IB (JOBS,:)=NEWSLA%IB (JOBS,:)
       SLA%JB (JOBS,:)=NEWSLA%JB (JOBS,:)
       SLA%PQ (JOBS,:)=NEWSLA%PQ(JOBS,:)
       SLA%TRACK(JOBS)=NEWSLA%TRACK(JOBS)
       SLA%DPT(JOBS)=NEWSLA%DPT(JOBS)
       IF( NCONF .NE. 202 ) THEN
         SLA%TB (JOBS,:)=NEWSLA%TB(JOBS,:)
         SLA%SB (JOBS,:)=NEWSLA%SB(JOBS,:)
         SLA%BCP(JOBS,:)=NEWSLA%BCP(JOBS,:)
       ENDIF
       SLA%TIM(JOBS)=NEWSLA%TIM(JOBS)
       SLA%IBH(JOBS,:)=NEWSLA%IBH(JOBS,:)
       SLA%JBH(JOBS,:)=NEWSLA%JBH(JOBS,:)
       SLA%PQH(JOBS,:)=NEWSLA%PQH(JOBS,:)
ENDDO SLALOOP2

DEALLOCATE(NEWSLA%LON,&
        &NEWSLA%LAT,&
        &NEWSLA%INO,&
        &NEWSLA%VAL,&
        &NEWSLA%TDIST,&
        &NEWSLA%FLG,&
        &NEWSLA%FLC,&
        &NEWSLA%KSAT,&
        &NEWSLA%EVE,&
        &NEWSLA%INC,&
        &NEWSLA%BAC,&
        &NEWSLA%BIA,&
        &NEWSLA%ERR,&
        &NEWSLA%BGERR,&
        &NEWSLA%RES,&
        &NEWSLA%B_A,&
        &NEWSLA%IB ,&
        &NEWSLA%JB ,&
        &NEWSLA%PQ,&
        &NEWSLA%IBH,&
        &NEWSLA%JBH,&
        &NEWSLA%PQH,&
        &NEWSLA%TRACK,&
        &NEWSLA%NIND,&
        &NEWSLA%DPT,&
        &NEWSLA%TIM)

IF( NCONF .NE. 202 ) THEN
DEALLOCATE(NEWSLA%TB,&
        &NEWSLA%SB,&
        &NEWSLA%BCP)
ENDIF

ENDIF

!... INS CASE
IF( INS%NO .GT. 0 ) THEN

NGOOD=COUNT(INS%FLC(1:INS%NO).EQ.1)
NEWINS%NO=NGOOD
NEWINS%NC=NGOOD
NEWINS%DEP=INS%DEP
NEWINS%KDP=INS%KDP

ALLOCATE(NEWINS%INO(NEWINS%NO),NEWINS%FLG(NEWINS%NO),&
& NEWINS%FLC(NEWINS%NO),NEWINS%PAR(NEWINS%NO))
ALLOCATE(NEWINS%LON(NEWINS%NO),NEWINS%LAT(NEWINS%NO),&
& NEWINS%DPT(NEWINS%NO),NEWINS%TIM(NEWINS%NO))
ALLOCATE(NEWINS%VAL(NEWINS%NO),NEWINS%BAC(NEWINS%NO),&
& NEWINS%INC(NEWINS%NO),NEWINS%TDIST(NEWINS%NO))
ALLOCATE(NEWINS%BIA(NEWINS%NO),NEWINS%ERR(NEWINS%NO),&
& NEWINS%EVE(NEWINS%NO),NEWINS%KTY(NEWINS%NO))
ALLOCATE(NEWINS%RES(NEWINS%NO),NEWINS%B_A(NEWINS%NO),&
& NEWINS%OTYPE(NEWINS%NO),NEWINS%PROF(NEWINS%NO))
ALLOCATE(NEWINS%IB(NEWINS%NO,NPQ),NEWINS%JB(NEWINS%NO,NPQ),&
& NEWINS%KB(NEWINS%NO),NEWINS%PLNO(NEWINS%NO))
ALLOCATE(NEWINS%RB(NEWINS%NO))
ALLOCATE(NEWINS%PQ(NEWINS%NO,2*NPQ),NEWINS%INST(NEWINS%NO))
ALLOCATE(NEWINS%IBH(NEWINS%NO,NPQ),NEWINS%JBH(NEWINS%NO,NPQ),NEWINS%PQH(NEWINS%NO,2*NPQ))
ALLOCATE(NEWINS%NIND(NEWINS%NO),NEWINS%BGERR(NEWINS%NO),NEWINS%DSRC(NEWINS%NO))

K=0
INSLOOP : DO JOBS=1,INS%NO
   IF(INS%FLC(JOBS) .EQ. 1) THEN
   K=K+1
   NEWINS%INO(K) = INS%INO(JOBS)
   NEWINS%FLG(K) = INS%FLG(JOBS)
   NEWINS%FLC(K) = INS%FLC(JOBS)
   NEWINS%PAR(K) = INS%PAR(JOBS)
   NEWINS%LON(K) = INS%LON(JOBS)
   NEWINS%LAT(K) = INS%LAT(JOBS)
   NEWINS%DPT(K) = INS%DPT(JOBS)
   NEWINS%TIM(K) = INS%TIM(JOBS)
   NEWINS%VAL(K) = INS%VAL(JOBS)
   NEWINS%BAC(K) = INS%BAC(JOBS)
   NEWINS%INC(K) = INS%INC(JOBS)
   NEWINS%INST(K) = INS%INST(JOBS)
   NEWINS%TDIST(K) = INS%TDIST(JOBS)
   NEWINS%BIA(K) = INS%BIA(JOBS)
   NEWINS%ERR(K) = INS%ERR(JOBS)
   NEWINS%EVE(K) = INS%EVE(JOBS)
   NEWINS%KTY(K) = INS%KTY(JOBS)
   NEWINS%RES(K) = INS%RES(JOBS)
   NEWINS%B_A(K) = INS%B_A(JOBS)
   NEWINS%OTYPE(K) = INS%OTYPE(JOBS)
   NEWINS%PROF(K) = INS%PROF(JOBS)
   NEWINS%IB(K,:) = INS%IB(JOBS,:)
   NEWINS%JB(K,:) = INS%JB(JOBS,:)
   NEWINS%KB(K) = INS%KB(JOBS)
   NEWINS%PLNO(K) =  INS%PLNO(JOBS)
   NEWINS%RB(K) = INS%RB(JOBS)
   NEWINS%PQ(K,:) =  INS%PQ(JOBS,:)
   NEWINS%NIND(K) = INS%NIND(JOBS)
   NEWINS%BGERR(K) = INS%BGERR(JOBS)
   NEWINS%DSRC(K) = INS%DSRC(JOBS)
   NEWINS%IBH(K,:) = INS%IBH(JOBS,:)
   NEWINS%JBH(K,:) = INS%JBH(JOBS,:)
   NEWINS%PQH(K,:) =  INS%PQH(JOBS,:)
   ENDIF
ENDDO INSLOOP
NEWINS%FLC = 1

INS%NO=NEWINS%NO
INS%NC=NEWINS%NO
INSLOOP2 : DO JOBS=1,INS%NO
    INS%INO(JOBS) = NEWINS%INO(JOBS)
    INS%FLG(JOBS) = NEWINS%FLG(JOBS)
    INS%FLC(JOBS) = NEWINS%FLC(JOBS)
    INS%PAR(JOBS) = NEWINS%PAR(JOBS)
    INS%LON(JOBS) = NEWINS%LON(JOBS)
    INS%LAT(JOBS) = NEWINS%LAT(JOBS)
    INS%DPT(JOBS) = NEWINS%DPT(JOBS)
    INS%TIM(JOBS) = NEWINS%TIM(JOBS)
    INS%VAL(JOBS) = NEWINS%VAL(JOBS)
    INS%BAC(JOBS) = NEWINS%BAC(JOBS)
    INS%INC(JOBS) = NEWINS%INC(JOBS)
    INS%INST(JOBS) = NEWINS%INST(JOBS)
    INS%TDIST(JOBS) = NEWINS%TDIST(JOBS)
    INS%BIA(JOBS) = NEWINS%BIA(JOBS)
    INS%ERR(JOBS) = NEWINS%ERR(JOBS)
    INS%EVE(JOBS) = NEWINS%EVE(JOBS)
    INS%KTY(JOBS) = NEWINS%KTY(JOBS)
    INS%RES(JOBS) = NEWINS%RES(JOBS)
    INS%B_A(JOBS) = NEWINS%B_A(JOBS)
    INS%OTYPE(JOBS) = NEWINS%OTYPE(JOBS)
    INS%PROF(JOBS) = NEWINS%PROF(JOBS)
    INS%IB(JOBS,:) = NEWINS%IB(JOBS,:)
    INS%JB(JOBS,:) = NEWINS%JB(JOBS,:)
    INS%KB(JOBS) = NEWINS%KB(JOBS)
    INS%PLNO(JOBS) =  NEWINS%PLNO(JOBS)
    INS%RB(JOBS) = NEWINS%RB(JOBS)
    INS%PQ(JOBS,:) = NEWINS%PQ(JOBS,:)
    INS%NIND(JOBS) = NEWINS%NIND(JOBS)
    INS%BGERR(JOBS)= NEWINS%BGERR(JOBS)
    INS%DSRC(JOBS) = NEWINS%DSRC(JOBS)
    INS%IBH(JOBS,:) = NEWINS%IBH(JOBS,:)
    INS%JBH(JOBS,:) = NEWINS%JBH(JOBS,:)
    INS%PQH(JOBS,:) = NEWINS%PQH(JOBS,:)
ENDDO INSLOOP2

DEALLOCATE(NEWINS%INO,NEWINS%FLG,&
& NEWINS%FLC,NEWINS%PAR)
DEALLOCATE(NEWINS%LON,NEWINS%LAT,&
& NEWINS%DPT,NEWINS%TIM)
DEALLOCATE(NEWINS%VAL,NEWINS%BAC,&
& NEWINS%INC,NEWINS%TDIST)
DEALLOCATE(NEWINS%BIA,NEWINS%ERR,&
& NEWINS%EVE,NEWINS%KTY)
DEALLOCATE(NEWINS%RES,NEWINS%B_A,&
& NEWINS%OTYPE,NEWINS%PROF)
DEALLOCATE(NEWINS%IB,NEWINS%JB,&
& NEWINS%KB,NEWINS%PLNO)
DEALLOCATE(NEWINS%RB)
DEALLOCATE(NEWINS%PQ)
DEALLOCATE(NEWINS%IBH,NEWINS%JBH,NEWINS%PQH)
DEALLOCATE(NEWINS%NIND,NEWINS%BGERR,&
& NEWINS%DSRC)
ENDIF

!... SST CASE
IF( SST%NO .GT. 0 ) THEN

NGOOD=SUM(SST%FLC(1:SST%NO))
NEWSST%NO=NGOOD
NEWSST%NC=NGOOD
ALLOCATE(NEWSST%LON(NEWSST%NO),&
        &NEWSST%LAT(NEWSST%NO),&
        &NEWSST%VAL(NEWSST%NO),&
        &NEWSST%NIND(NEWSST%NO),&
        &NEWSST%TDIST(NEWSST%NO),&
        &NEWSST%FLG(NEWSST%NO),&
        &NEWSST%FLC(NEWSST%NO),&
        &NEWSST%KSAT(NEWSST%NO),&
        &NEWSST%EVE(NEWSST%NO),&
        &NEWSST%INC(NEWSST%NO),&
        &NEWSST%BAC(NEWSST%NO),&
        &NEWSST%BIA(NEWSST%NO),&
        &NEWSST%ERR(NEWSST%NO),&
        &NEWSST%BGERR(NEWSST%NO),&
        &NEWSST%RES(NEWSST%NO),&
        &NEWSST%B_A(NEWSST%NO),&
        &NEWSST%IB (NEWSST%NO,NPQ),&
        &NEWSST%JB (NEWSST%NO,NPQ),&
        &NEWSST%PQ(NEWSST%NO,NPQ),&
        &NEWSST%IBH(NEWSST%NO,NPQ),&
        &NEWSST%JBH(NEWSST%NO,NPQ),&
        &NEWSST%PQH(NEWSST%NO,NPQ),&
        &NEWSST%TRACK(NEWSST%NO),&
        &NEWSST%BCP(NEWSST%NO,NPRD_SST),&
        &NEWSST%TIM(NEWSST%NO))

K=0
SSTLOOP : DO JOBS=1,SST%NO
   IF(SST%FLC(JOBS) .EQ.1 ) THEN
   K=K+1
        NEWSST%LON(K)=SST%LON(JOBS)
        NEWSST%LAT(K)=SST%LAT(JOBS)
        NEWSST%VAL(K)=SST%VAL(JOBS)
        NEWSST%TDIST(K)=SST%TDIST(JOBS)
        NEWSST%FLG(K)=SST%FLG(JOBS)
        NEWSST%FLC(K)=SST%FLC(JOBS)
        NEWSST%KSAT(K)=SST%KSAT(JOBS)
        NEWSST%EVE(K)=SST%EVE(JOBS)
        NEWSST%NIND(K)=SST%NIND(JOBS)
        NEWSST%INC(K)=SST%INC(JOBS)
        NEWSST%BAC(K)=SST%BAC(JOBS)
        NEWSST%BIA(K)=SST%BIA(JOBS)
        NEWSST%ERR(K)=SST%ERR(JOBS)
        NEWSST%BGERR(K)=SST%BGERR(JOBS)
        NEWSST%RES(K)=SST%RES(JOBS)
        NEWSST%B_A(K)=SST%B_A(JOBS)
        NEWSST%IB (K,:)=SST%IB (JOBS,:)
        NEWSST%JB (K,:)=SST%JB (JOBS,:)
        NEWSST%PQ(K,:)=SST%PQ(JOBS,:)
        NEWSST%BCP(K,:)=SST%BCP(JOBS,:)
        NEWSST%TRACK(K)=SST%TRACK(JOBS)
        NEWSST%TIM(K)=SST%TIM(JOBS)
        NEWSST%IBH(K,:)=SST%IBH(JOBS,:)
        NEWSST%JBH(K,:)=SST%JBH(JOBS,:)
        NEWSST%PQH(K,:)=SST%PQH(JOBS,:)
    ENDIF
ENDDO SSTLOOP
NEWSST%FLC = 1

SST%NO=NEWSST%NO
SST%NC=NEWSST%NO
SSTLOOP2 : DO JOBS=1,SST%NO
       SST%LON(JOBS)=NEWSST%LON(JOBS)
       SST%LAT(JOBS)=NEWSST%LAT(JOBS)
       SST%VAL(JOBS)=NEWSST%VAL(JOBS)
       SST%NIND (JOBS)=NEWSST%NIND (JOBS)
       SST%TDIST(JOBS)=NEWSST%TDIST(JOBS)
       SST%FLG(JOBS)=NEWSST%FLG(JOBS)
       SST%FLC(JOBS)=NEWSST%FLC(JOBS)
       SST%KSAT(JOBS)=NEWSST%KSAT(JOBS)
       SST%EVE(JOBS)=NEWSST%EVE(JOBS)
       SST%INC(JOBS)=NEWSST%INC(JOBS)
       SST%BAC(JOBS)=NEWSST%BAC(JOBS)
       SST%BIA(JOBS)=NEWSST%BIA(JOBS)
       SST%ERR(JOBS)=NEWSST%ERR(JOBS)
       SST%BGERR(JOBS)=NEWSST%BGERR(JOBS)
       SST%RES(JOBS)=NEWSST%RES(JOBS)
       SST%B_A(JOBS)=NEWSST%B_A(JOBS)
       SST%IB (JOBS,:)=NEWSST%IB (JOBS,:)
       SST%JB (JOBS,:)=NEWSST%JB (JOBS,:)
       SST%PQ (JOBS,:)=NEWSST%PQ (JOBS,:)
       SST%BCP(JOBS,:)=NEWSST%BCP(JOBS,:)
       SST%TRACK(JOBS)=NEWSST%TRACK(JOBS)
       SST%TIM(JOBS)=NEWSST%TIM(JOBS)
       SST%IBH(JOBS,:)=NEWSST%IBH(JOBS,:)
       SST%JBH(JOBS,:)=NEWSST%JBH(JOBS,:)
       SST%PQH(JOBS,:)=NEWSST%PQH(JOBS,:)
ENDDO SSTLOOP2

DEALLOCATE(NEWSST%LON,&
        &NEWSST%LAT,&
        &NEWSST%VAL,&
        &NEWSST%TDIST,&
        &NEWSST%FLG,&
        &NEWSST%FLC,&
        &NEWSST%KSAT,&
        &NEWSST%EVE,&
        &NEWSST%INC,&
        &NEWSST%BAC,&
        &NEWSST%BIA,&
        &NEWSST%ERR,&
        &NEWSST%BGERR,&
        &NEWSST%RES,&
        &NEWSST%B_A,&
        &NEWSST%NIND,&
        &NEWSST%IB ,&
        &NEWSST%JB ,&
        &NEWSST%PQ,&
        &NEWSST%IBH,&
        &NEWSST%JBH,&
        &NEWSST%PQH,&
        &NEWSST%BCP,&
        &NEWSST%TRACK,&
        &NEWSST%TIM)
ENDIF

!... SSS CASE
IF( SSS%NO .GT. 0 ) THEN

NGOOD=SUM(SSS%FLC(1:SSS%NO))
NEWSSS%NO=NGOOD
NEWSSS%NC=NGOOD
ALLOCATE(NEWSSS%LON(NEWSSS%NO),&
        &NEWSSS%LAT(NEWSSS%NO),&
        &NEWSSS%VAL(NEWSSS%NO),&
        &NEWSSS%NIND(NEWSSS%NO),&
        &NEWSSS%TDIST(NEWSSS%NO),&
        &NEWSSS%FLG(NEWSSS%NO),&
        &NEWSSS%FLC(NEWSSS%NO),&
        &NEWSSS%KSAT(NEWSSS%NO),&
        &NEWSSS%EVE(NEWSSS%NO),&
        &NEWSSS%INC(NEWSSS%NO),&
        &NEWSSS%BAC(NEWSSS%NO),&
        &NEWSSS%BIA(NEWSSS%NO),&
        &NEWSSS%ERR(NEWSSS%NO),&
        &NEWSSS%BGERR(NEWSSS%NO),&
        &NEWSSS%RES(NEWSSS%NO),&
        &NEWSSS%B_A(NEWSSS%NO),&
        &NEWSSS%IB (NEWSSS%NO,NPQ),&
        &NEWSSS%JB (NEWSSS%NO,NPQ),&
        &NEWSSS%PQ(NEWSSS%NO,NPQ),&
        &NEWSSS%IBH(NEWSSS%NO,NPQ),&
        &NEWSSS%JBH(NEWSSS%NO,NPQ),&
        &NEWSSS%PQH(NEWSSS%NO,NPQ),&
        &NEWSSS%TRACK(NEWSSS%NO),&
        &NEWSSS%BCP(NEWSSS%NO,NPRD_SSS),&
        &NEWSSS%TIM(NEWSSS%NO))

K=0
SSSLOOP : DO JOBS=1,SSS%NO
   IF(SSS%FLC(JOBS) .EQ.1 ) THEN
   K=K+1
        NEWSSS%LON(K)=SSS%LON(JOBS)
        NEWSSS%LAT(K)=SSS%LAT(JOBS)
        NEWSSS%VAL(K)=SSS%VAL(JOBS)
        NEWSSS%NIND(K)=SSS%NIND(JOBS)
        NEWSSS%TDIST(K)=SSS%TDIST(JOBS)
        NEWSSS%FLG(K)=SSS%FLG(JOBS)
        NEWSSS%FLC(K)=SSS%FLC(JOBS)
        NEWSSS%KSAT(K)=SSS%KSAT(JOBS)
        NEWSSS%EVE(K)=SSS%EVE(JOBS)
        NEWSSS%INC(K)=SSS%INC(JOBS)
        NEWSSS%BAC(K)=SSS%BAC(JOBS)
        NEWSSS%BIA(K)=SSS%BIA(JOBS)
        NEWSSS%ERR(K)=SSS%ERR(JOBS)
        NEWSSS%BGERR(K)=SSS%BGERR(JOBS)
        NEWSSS%RES(K)=SSS%RES(JOBS)
        NEWSSS%B_A(K)=SSS%B_A(JOBS)
        NEWSSS%IB (K,:)=SSS%IB (JOBS,:)
        NEWSSS%JB (K,:)=SSS%JB (JOBS,:)
        NEWSSS%PQ(K,:)=SSS%PQ(JOBS,:)
        NEWSSS%TRACK(K)=SSS%TRACK(JOBS)
        NEWSSS%TIM(K)=SSS%TIM(JOBS)
        NEWSSS%IBH(K,:)=SSS%IBH(JOBS,:)
        NEWSSS%JBH(K,:)=SSS%JBH(JOBS,:)
        NEWSSS%PQH(K,:)=SSS%PQH(JOBS,:)
        NEWSSS%BCP(K,:)=SSS%BCP(JOBS,:)
   ENDIF
ENDDO SSSLOOP
NEWSSS%FLC = 1

SSS%NO=NEWSSS%NO
SSS%NC=NEWSSS%NO
SSSLOOP2 : DO JOBS=1,SSS%NO
       SSS%LON(JOBS)=NEWSSS%LON(JOBS)
       SSS%LAT(JOBS)=NEWSSS%LAT(JOBS)
       SSS%VAL(JOBS)=NEWSSS%VAL(JOBS)
       SSS%NIND(JOBS)=NEWSSS%NIND(JOBS)
       SSS%TDIST(JOBS)=NEWSSS%TDIST(JOBS)
       SSS%FLG(JOBS)=NEWSSS%FLG(JOBS)
       SSS%FLC(JOBS)=NEWSSS%FLC(JOBS)
       SSS%KSAT(JOBS)=NEWSSS%KSAT(JOBS)
       SSS%EVE(JOBS)=NEWSSS%EVE(JOBS)
       SSS%INC(JOBS)=NEWSSS%INC(JOBS)
       SSS%BAC(JOBS)=NEWSSS%BAC(JOBS)
       SSS%BIA(JOBS)=NEWSSS%BIA(JOBS)
       SSS%ERR(JOBS)=NEWSSS%ERR(JOBS)
       SSS%BGERR(JOBS)=NEWSSS%BGERR(JOBS)
       SSS%RES(JOBS)=NEWSSS%RES(JOBS)
       SSS%B_A(JOBS)=NEWSSS%B_A(JOBS)
       SSS%IB (JOBS,:)=NEWSSS%IB (JOBS,:)
       SSS%JB (JOBS,:)=NEWSSS%JB (JOBS,:)
       SSS%PQ(JOBS,:)=NEWSSS%PQ(JOBS,:)
       SSS%TRACK(JOBS)=NEWSSS%TRACK(JOBS)
       SSS%TIM(JOBS)=NEWSSS%TIM(JOBS)
       SSS%IBH(JOBS,:)=NEWSSS%IBH(JOBS,:)
       SSS%JBH(JOBS,:)=NEWSSS%JBH(JOBS,:)
       SSS%PQH(JOBS,:)=NEWSSS%PQH(JOBS,:)
       SSS%BCP(JOBS,:)=NEWSSS%BCP(JOBS,:)
ENDDO SSSLOOP2

DEALLOCATE(NEWSSS%LON,&
        &NEWSSS%LAT,&
        &NEWSSS%VAL,&
        &NEWSSS%TDIST,&
        &NEWSSS%FLG,&
        &NEWSSS%FLC,&
        &NEWSSS%KSAT,&
        &NEWSSS%EVE,&
        &NEWSSS%INC,&
        &NEWSSS%NIND,&
        &NEWSSS%BAC,&
        &NEWSSS%BIA,&
        &NEWSSS%ERR,&
        &NEWSSS%BGERR,&
        &NEWSSS%RES,&
        &NEWSSS%B_A,&
        &NEWSSS%IB ,&
        &NEWSSS%JB ,&
        &NEWSSS%PQ,&
        &NEWSSS%IBH,&
        &NEWSSS%JBH,&
        &NEWSSS%PQH,&
        &NEWSSS%BCP,&
        &NEWSSS%TRACK,&
        &NEWSSS%TIM)
ENDIF

CALL MYFRTPROF_WALL('REO4MIN: REORDER OBS VECTOR',1)
RETURN
END SUBROUTINE REO4MIN
