SUBROUTINE SETUPRFCR
USE RECFILTER

!-- SETUP CR

USE GRD_STR

IMPLICIT NONE

INTEGER(KIND=I4) :: NX,NY,NZ

NX=GRD%IM
NY=GRD%JM
NZ=GRD%KM

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' /// SETTINGS FOR RECURSIVE FILTER ',&
               & 'CORRELATION LENGTH-SCALES'
WRITE(IOUNLOG,*)

IF(LLVVCR .AND. LLTSAPART) THEN
      WRITE(IOUNLOG,*) &
      & ' --> VERTICALLY-VARYING, (T,S) TREATED INDIPENDENTLY'
      NTOTV=NZ*2
      ALLOCATE(ZGA_CRAD(NTOTV))
      ZGA_CRAD_T=>ZGA_CRAD(1:NZ)
      ZGA_CRAD_S=>ZGA_CRAD(NZ+1:2*NZ)
ELSEIF(LLVVCR .AND. .NOT. LLTSAPART) THEN
      WRITE(IOUNLOG,*) &
      & ' --> VERTICALLY-VARYING, (T,S) INDISTINGUISHED'
      NTOTV=NZ
      ALLOCATE(ZGA_CRAD(NTOTV))
      ZGA_CRAD_T=>ZGA_CRAD(1:NZ)
      ZGA_CRAD_S=>ZGA_CRAD(1:NZ)
ELSEIF(.NOT.LLVVCR .AND. LLTSAPART) THEN
      WRITE(IOUNLOG,*) &
      & ' --> VERTICALLY-CONSTANT, (T,S) TREATED INDIPENDENTLY'
      NTOTV=2*NZ
      ALLOCATE(ZGA_CRAD(NTOTV))
      ZGA_CRAD_T=>ZGA_CRAD(1:NZ)
      ZGA_CRAD_S=>ZGA_CRAD(NZ+1:2*NZ)
ELSEIF(.NOT.LLVVCR .AND. .NOT.LLTSAPART) THEN
      WRITE(IOUNLOG,*) &
      & ' --> VERTICALLY-CONSTANT, (T,S) INDISTINGUISHED'
      NTOTV=NZ
      ALLOCATE(ZGA_CRAD(NTOTV))
      ZGA_CRAD_T=>ZGA_CRAD(1:NZ)
      ZGA_CRAD_S=>ZGA_CRAD(1:NZ)
ENDIF

WRITE(IOUNLOG,*) ' DEGREES OF FREEDOM OF CR ON THE VERTICAL: ',NTOTV
WRITE(IOUNLOG,*)

LLRFINIT=.TRUE.

RETURN
END SUBROUTINE SETUPRFCR
