SUBROUTINE SLAMDTUNDEF

USE SET_KND
USE IOUNITS
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE OBS_STR

IMPLICIT NONE

INTEGER(I4) :: K

#include "obs_events.h"

CALL MYFRTPROF_WALL('SLAMDTUNDEF: CHECK FOR MDT UNDEFINED',0)

IF(SLA%NO.LE.0) THEN
   CALL MYFRTPROF_WALL('SLAMDTUNDEF: CHECK FOR MDT UNDEFINED',1)
   RETURN
ENDIF

WHERE( .NOT. ABS(SLA%BAC(1:SLA%NO)) .LT. 5._R8 ) SLA%BAC(1:SLA%NO) = -999._R8
WHERE( .NOT. ABS(SLA%RES(1:SLA%NO)) .LT. 5._R8 ) SLA%RES(1:SLA%NO) = -999._R8

WHERE( (ABS(SLA%BAC(1:SLA%NO)) .GT. 5._R8 .AND. SLA%FLC(1:SLA%NO) .EQ. 1) .OR. SLA%BAC(1:SLA%NO) .GT. 10._R8 .OR. ABS(SLA%RES(1:SLA%NO)) .GT. 10._R8   )
     SLA%FLC(1:SLA%NO) = 0
     SLA%EVE(1:SLA%NO) = KEVE_MDTU
ENDWHERE


WRITE(IOUNLOG,*) 
WRITE(IOUNLOG,*) ' NUMBER OF SLAs WITH MDT UNDEF = ', &
& COUNT(SLA%EVE(1:SLA%NO) .EQ. KEVE_MDTU)
WRITE(IOUNLOG,*) 

CALL FLUSH(IOUNLOG)

CALL MYFRTPROF_WALL('SLAMDTUNDEF: CHECK FOR MDT UNDEFINED',1)
END SUBROUTINE SLAMDTUNDEF
