SUBROUTINE SURF_LVF

!.. SETUP OF RECURSIVE FILTER ..!
!
!   ALL THE ROUTINES ARE INCLUDED
!   IN THE MODULE RECFILTER

USE SET_KND
USE GRD_STR
USE RECFILTER
USE RUN
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE IOUNITS, ONLY : IOUNOUT,IOUNLOG
USE MYNETCDF

IMPLICIT NONE
INTEGER(KIND=I4) :: NX,NY,NZ
REAL(R8), ALLOCATABLE :: CRB(:,:,:,:)

CALL MYFRTPROF_WALL('SURF_LVF: RECURSIVE FILTER SETUP',0)

  WRITE(IOUNOUT,*) ' ENTERING SURF_LVF'
  WRITE(IOUNLOG,*)
  WRITE(IOUNLOG,*) ' ENTERING SURF_LVF'

  !... SETUP CONFIGURATION

  NX=GRD%IM
  NY=GRD%JM
  NZ=GRD%KM

  LLRFINIT=.TRUE.
  LLTSAPART = .TRUE.

  ALLOCATE( CRB(GRD%IM,GRD%JM,PSV3D*GRD%KM+PSV2D,2) )

  CRB(:,:,:,1) = CRX
  CRB(:,:,:,2) = CRY

  CRX = CRFX
  CRY = CRFY

  !... CALCULATE GEOGRAPHICAL SCALING FACTOR
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: SCALING FACTOR...'
  CALL COMPSC_LV
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  !... CALCULATE ALPHA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: COMPUTE ALPHAS...'
  IF (NCONF .NE. 202) CALL COMPALPHA_LV
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  !... DEFINE EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: EXTENDED GRID...'
  IF (NCONF .NE. 202) CALL DEFEXTGRD_LV
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  !... REARRANGE ALPHAS ACCORDING TO EXTENDED AREA
  WRITE(IOUNOUT,'(2X,A)',ADVANCE='NO') 'SURF: REARRANGE ALPHAS...'
  IF (NCONF .NE. 202) CALL REARRALPHA_LV
  WRITE(IOUNOUT,'(2X,A)') 'DONE'
  CALL FLUSH(IOUNOUT)

  CRX = CRB(:,:,:,1)
  CRY = CRB(:,:,:,2)
  DEALLOCATE( CRB ) 

  NX=GRD%IM
  NY=GRD%JM
  NZ=GRD%KM

  IMAXF=IMAX
  JMAXF=JMAX

  ALLOCATE( RFF_AEX(NY,IMAXF,NTOTV),&
        & RFF_BEX(NY,IMAXF,NTOTV),&
        & RFF_AEY(NX,JMAXF,NTOTV),&
        & RFF_BEY(NX,JMAXF,NTOTV) )
  RFF_AEX = RF_AEX
  RFF_BEX = RF_BEX
  RFF_AEY = RF_AEY
  RFF_BEY = RF_BEY
  DEALLOCATE(RF_AEX,RF_BEX,RF_AEY,RF_BEY)

  IF( RCF_TYPE .EQ. 2 ) THEN
    ALLOCATE( RFF_GEX(NY,IMAXF,NTOTV),&
        & RFF_DEX(NY,IMAXF,NTOTV),&
        & RFF_GEY(NX,JMAXF,NTOTV),&
        & RFF_DEY(NX,JMAXF,NTOTV) )
    RFF_GEX = RF_GEX
    RFF_DEX = RF_DEX
    RFF_GEY = RF_GEY
    RFF_DEY = RF_DEY
    DEALLOCATE(RF_GEX,RF_DEX,RF_GEY,RF_DEY)
  ENDIF

  DEALLOCATE(FCT)

  ALLOCATE(ISTPNSF(NX,NY,NTOTV),JSTPNSF(NX,NY,NTOTV))
  ISTPNSF = ISTPNS
  JSTPNSF = JSTPNS
  DEALLOCATE(ISTPNS,JSTPNS)

  ALLOCATE(IMXF(NTOTV),JMXF(NTOTV))
  IMXF=IMX
  JMXF=JMX
  DEALLOCATE(IMX,JMX)

  ALLOCATE(INXF(NX,NY,NTOTV),JNXF(NX,NY,NTOTV))
  INXF=INX
  JNXF=JNX
  DEALLOCATE(INX,JNX)

  ALLOCATE(SCXNSF(NX,NY,NTOTV), SCYNSF(NX,NY,NTOTV))
  SCXNSF=SCXNS
  SCYNSF=SCYNS
  DEALLOCATE(SCXNS,SCYNS)

  ALLOCATE ( PSVF(GRD%IM,GRD%JM,PSV3D*GRD%KM+PSV2D) )
  ALLOCATE ( PSVF_AD(GRD%IM,GRD%JM,PSV3D*GRD%KM+PSV2D) )
  PSVF = 0._R8
  PSVF_AD = 0._R8

CALL MYFRTPROF_WALL('SURF_LVF: RECURSIVE FILTER SETUP',1)

END SUBROUTINE SURF_LVF
