SUBROUTINE TEST_MACHP

! PRINT OUT MACHINE PRECISION 

USE SET_KND
USE IOUNITS

IMPLICIT NONE

REAL(R4) :: XR4
REAL(R8) :: XR8

 WRITE(IOUNLOG,*) 
 WRITE(IOUNLOG,*) ' BIT_SIZE USED'
 WRITE(IOUNLOG,*) ' BIT_SIZE(I4) ',  BIT_SIZE(I4)
 WRITE(IOUNLOG,*) ' BIT_SIZE(I8) ',  BIT_SIZE(I8)
 WRITE(IOUNLOG,*) ' BIT_SIZE(R4) ',  BIT_SIZE(R4)
 WRITE(IOUNLOG,*) ' BIT_SIZE(R8) ',  BIT_SIZE(R8)
 WRITE(IOUNLOG,*)
 WRITE(IOUNLOG,*) ' FLOATING POINT NUMBERS'
 WRITE(IOUNLOG,*) ' EPSILON (R4) ',  EPSILON (XR4)
 WRITE(IOUNLOG,*) ' EPSILON (R8) ',  EPSILON (XR8)
 WRITE(IOUNLOG,*) ' PRECISION(R4)',  PRECISION(XR4)
 WRITE(IOUNLOG,*) ' PRECISION(R8)',  PRECISION(XR8)
 WRITE(IOUNLOG,*) ' HUGE    (R4) ',  HUGE    (XR4)
 WRITE(IOUNLOG,*) ' HUGE    (R8) ',  HUGE    (XR8)
 WRITE(IOUNLOG,*) ' TINY    (R4) ',  TINY    (XR4)
 WRITE(IOUNLOG,*) ' TINY    (R8) ',  TINY    (XR8)
 WRITE(IOUNLOG,*) ' RANGE   (R4) ',  RANGE   (XR4)
 WRITE(IOUNLOG,*) ' RANGE   (R8) ',  RANGE   (XR8)
 WRITE(IOUNLOG,*)

END SUBROUTINE TEST_MACHP
