SUBROUTINE THINNING

!.. INTERFACE TO GEOGRAPHICAL THINNING OF OBSERVATIONS
!..
!.. ANDREA STORTO *INGV* 2009-04-06

USE SET_KND
USE OBSHANDLING, ONLY : LTHIN_SLA,LTHIN_INS,LTHIN_SST,&
                      & CINSTHINOPT,LDOUBLETHIN,&
                      & RTHIND_SLA_X,RTHIND_SLA_Y,&
                      & RTHIND_SST_X,RTHIND_SST_Y,&
                      & RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z,&
                      & LTHIN_SSS,RTHIND_SSS_X,RTHIND_SSS_Y
USE IOUNITS
USE OBS_STR
USE MYFRTPROF, ONLY : MYFRTPROF_WALL

IMPLICIT NONE

CALL MYFRTPROF_WALL('THINNING: THINNING OF OBSERVATIONS',0)

IF(CINSTHINOPT .NE. 'A' .AND. CINSTHINOPT .NE. 'B') THEN
      WRITE(IOUNERR,*) 'UNKNOWN OPTION ',CINSTHINOPT,' FOR CINSTHINOPT'
      CALL ABOR1('UNKNOWN OPTION FOR CINSTHINOPT')
ENDIF

!... SLA PART

IF( SLA%NO .GT. 0 ) THEN
IF( LTHIN_SLA ) CALL THINOUT_SLA(1,RTHIND_SLA_X,RTHIND_SLA_Y)

IF( LTHIN_SLA .AND.LDOUBLETHIN) CALL THINOUT_SLA(2,RTHIND_SLA_X,RTHIND_SLA_Y)
ENDIF

!... INS PART

IF( INS%NO .GT. 0 ) THEN
IF( LTHIN_INS .AND. CINSTHINOPT .EQ. 'A' ) &
& CALL THINOUT_INS_A(1,RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z)

IF( LTHIN_INS .AND. CINSTHINOPT .EQ. 'A' .AND. LDOUBLETHIN) &
& CALL THINOUT_INS_A(2,RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z)

IF( LTHIN_INS .AND. CINSTHINOPT .EQ. 'B' ) &
& CALL THINOUT_INS_B(1,RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z)

IF( LTHIN_INS .AND. CINSTHINOPT .EQ. 'B' .AND. LDOUBLETHIN) &
& CALL THINOUT_INS_B(2,RTHIND_INS_X,RTHIND_INS_Y,RTHIND_INS_Z)
ENDIF

!... SST PART

IF( SST%NO .GT. 0 ) THEN
IF( LTHIN_SST ) CALL THINOUT_SST(1,RTHIND_SST_X,RTHIND_SST_Y)

IF( LTHIN_SST .AND.LDOUBLETHIN) CALL THINOUT_SST(2,RTHIND_SST_X,RTHIND_SST_Y)
ENDIF

!... SSS PART

IF( SST%NO .GT. 0 ) THEN
IF( LTHIN_SSS ) CALL THINOUT_SSS(1,RTHIND_SSS_X,RTHIND_SSS_Y)

IF( LTHIN_SSS .AND.LDOUBLETHIN) CALL THINOUT_SSS(2,RTHIND_SSS_X,RTHIND_SSS_Y)
ENDIF

CALL MYFRTPROF_WALL('THINNING: THINNING OF OBSERVATIONS',1)
END SUBROUTINE THINNING
