MODULE TLAD_VARS

USE SET_KND
USE GRD_STR

IMPLICIT NONE

      LOGICAL :: LL_4DVAR, LL_TLMODEL, LL_TLDEB=.FALSE., LL_ADMODEL
      LOGICAL :: LL_ADTEST
      INTEGER, PUBLIC, PARAMETER ::   WP = R8
      INTEGER(I4) :: JPI,JPJ,JPK
      INTEGER(I4) :: IDB_COO(3)
      INTEGER(I4) :: JPIM1,JPJM1,JPKM1
      REAL(R8), ALLOCATABLE, DIMENSION(:,:) :: E1T, E2T, E1U, E2U, E1V, E2V
      REAL(R8), ALLOCATABLE, DIMENSION(:  ) :: E3T, E3U, E3V, E3W
      REAL(R8), ALLOCATABLE, DIMENSION(:,:) :: E1UR,E2VR
      REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: UMASK, VMASK, TMASK, AVT
      REAL(R8), ALLOCATABLE, DIMENSION(:,:) :: AHTU, AHTV
      REAL(R8), ALLOCATABLE, DIMENSION(:,:,:,:) :: UB, VB, WB, AVTB
      REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: UBT, VBT, WBT, AVBT, HDIVN
      REAL(R8), ALLOCATABLE, DIMENSION(:,:,:) :: SSTB,SSSB,CEB,CHB,EMPB,WNDB,Q10B
      REAL(R8), ALLOCATABLE, DIMENSION(:) :: RBG1,TLAD_TIMES,RTIMES1950TL
      INTEGER(I4), ALLOCATABLE, DIMENSION(:) :: KBG1,KBG2
      REAL(R8) :: AHT0
      REAL(R8) :: RDT, RDT_TRAJ
      INTEGER(I4)  :: TLAD_TS = 0
      INTEGER(I4)  :: OUT_FREQ, NTS_TRAJ, TS_MOD
      INTEGER(I4)  :: NTS_WRITE, TS_WRITE(99)
      LOGICAL  :: LL_VDIFF
      LOGICAL  :: LL_HDIFF
      LOGICAL  :: LL_HADV
      LOGICAL  :: LL_VADV
      INTEGER(I4)  :: KN_ZDFEXP, NN_VDIFF
      LOGICAL  :: LL_SRFFLX
      LOGICAL  :: LL_VVEL_NEMO
      REAL(R8) :: ZZ_VMIXC = 1._R8

      ! PARAMETERS
      REAL(WP), PARAMETER ::   RHOA =    1.22_WP        ! AIR DENSITY
      REAL(WP), PARAMETER ::   CPA  = 1000.5_WP         ! SPECIFIC HEAT OF AIR
      REAL(WP), PARAMETER ::   LV   =    2.5E6_WP       ! LATENT HEAT OF VAPORIZATION
      REAL(WP), PARAMETER ::   LS   =    2.839E6_WP     ! LATENT HEAT OF SUBLIMATION
      REAL(WP), PARAMETER ::   STEF =    5.67E-8_WP     ! STEFAN BOLTZMANN CONSTANT
      REAL(WP), PARAMETER ::   CICE =    1.63E-3_WP     ! TRANSFER COEFFICIENT OVER ICE
      REAL(WP), PARAMETER ::   ALBO =    0.066_WP       ! OCEAN ALBEDO ASSUMED TO BE CONTANT
      REAL(WP), PARAMETER ::   ZCOEF_QSATW = 0.98_WP * 640380._WP / RHOA
      REAL(WP), PARAMETER ::   RT0      = 273.15_WP
      REAL(WP), PARAMETER ::   RAU0 = 1026._WP
      REAL(WP), PARAMETER ::   RCP  = 4.e+3_WP
      REAL(WP), PARAMETER ::   RO0CPR= 1._wp / (RAU0*RCP)
      REAL(WP), PARAMETER ::   ZSRAU = 1._wp / (RAU0)

END MODULE TLAD_VARS
