SUBROUTINE TOUPPERDT(CDS)
CHARACTER(LEN=*), INTENT(INOUT) :: CDS
INTEGER, PARAMETER :: ICH_A = ICHAR('A')
INTEGER, PARAMETER :: ICHA  = ICHAR('A')
INTEGER, PARAMETER :: ICHZ  = ICHAR('Z')
INTEGER :: I, ICH, NEW_ICH
CHARACTER(LEN=1) CH
DO I=1,LEN(CDS)
  CH = CDS(I:I)
  ICH = ICHAR(CH)
  IF ( ICH >= ICHA .AND. ICH <= ICHZ ) THEN
    NEW_ICH = ICH + (ICH_A - ICHA)
    CH = CHAR(NEW_ICH)
    CDS(I:I) = CH
  ENDIF
ENDDO
END SUBROUTINE TOUPPERDT
