SUBROUTINE USAGEOV

!.. WRITE DOWN HOW SHOULD THE PROGRAM BE CALLED AND ABORT
!..
!.. ANDREA STORTO, 2009-03-20

USE IOUNITS, ONLY : IOUNERR

IMPLICIT NONE

CHARACTER(LEN=300) :: CWHOAMI

CALL GETARG(0,CWHOAMI)

WRITE(IOUNERR,*)
WRITE(IOUNERR,*) ' USAGE: '//TRIM(CWHOAMI),&
               & ' -D ADATE -T ATIME -W ATW -F FGDATE [-C CEN]'
WRITE(IOUNERR,*)
WRITE(IOUNERR,*) '   ADATE : ANALYSIS DATE (YYYYMMDD)'
WRITE(IOUNERR,*) '   ATIME : ANALYSIS TIME (HHMM)'
WRITE(IOUNERR,*) '   ATW   : TIME WINDOW (HOURS CENTERED AT ANALYSIS TIME)'
WRITE(IOUNERR,*) '   FGDATE: FIRST GUESS STARTING DATE (YYYYMMDDHH)'
WRITE(IOUNERR,*) '   CEN   : IF NOT 0, THE TIME WINDOW IS CENTERED AT ANALYSIS'

CALL ABOR1('COMMAND LINE PROBLEMS')

END SUBROUTINE USAGEOV

