INTERFACE
SUBROUTINE WRANINC(IM,JM,KM,LON,LAT,DEP,SAL,TEM,LLS,LL2,LLI,&
& SSH,T2M,Q2M,SIC,SIT,ICU,ICV)
USE SET_KND
USE NETCDF
USE MPIREL
IMPLICIT NONE
INTEGER(I4), INTENT(IN) :: IM, JM, KM
REAL(R8), INTENT(IN) :: LON(IM,JM),LAT(IM,JM),DEP(KM)
REAL(R8), INTENT(IN) :: SAL(IM,JM,KM),TEM(IM,JM,KM)
LOGICAL, INTENT(IN) :: LLS,LL2,LLI
REAL(R8), INTENT(IN), OPTIONAL :: SSH(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: T2M(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: Q2M(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: SIC(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: SIT(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: ICU(IM,JM)
REAL(R8), INTENT(IN), OPTIONAL :: ICV(IM,JM)
END SUBROUTINE WRANINC
END INTERFACE
