SUBROUTINE WRITEOBS102

!.. WRITE OBS IN BINARY OR NETCDF FORMAT

USE SET_KND
USE RUN , ONLY : NSUBDOMAINS, IO_OBSFORMAT, ZJULEND,ZJUL1950
USE OBSDEF
USE OBS_STR
USE GRD_STR
USE READFG, ONLY : KDPF,KDPL,LLMPF
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE MYNETCDF
USE IOUNITS

IMPLICIT NONE

INTEGER(I4) :: NPROCS, JP, NFAULT, I, J, I2, J2, MYPROC, KK, JPNI
INTEGER(I4), ALLOCATABLE :: KCOUNT(:,:)
INTEGER(I4), ALLOCATABLE :: ISNDX(:),PRIND_TEMP(:)
TYPE (INS_T) :: INSC(MAX(1,NSUBDOMAINS))
TYPE (SLA_T) :: SLAC(MAX(1,NSUBDOMAINS))
TYPE (SST_T) :: SSTC(MAX(1,NSUBDOMAINS))
TYPE (SSS_T) :: SSSC(MAX(1,NSUBDOMAINS))
CHARACTER(LEN=30) :: CFILE
INTEGER(I4) :: XIND1, KTOT, MYCT, NFLGOK(NOFAMS), &
& MOTHI(NPQ), MOTHJ(NPQ), SUBDOM1, SUBDOM2, JPQ
LOGICAL :: LMODOT

#include "io_obs.h"

CALL MYFRTPROF_WALL('WRITEOBS102: WRITE BINARY OBS FILES',0)

NPROCS = NSUBDOMAINS

CALL SETFGFILES(NPROCS)
CALL SETFGFLAYOUT
CALL SETMPPNEIGHB

IF(.NOT.LLMPF) THEN
 JPNI=1
 NPROCS=1
 INS%PRIND(:) = 0
ELSE
 DO JP=1,NPROCS
   IF(KDPL(JP,1) .EQ. GRD%IM) THEN
      JPNI=JP
      EXIT
   ENDIF
 ENDDO
ENDIF

WRITE(IOUNLOG,*) ' DOMAIN DECOMPOSITION IS (JPNIxJPNJ): ',JPNI,NPROCS/JPNI

ALLOCATE(KCOUNT(NPROCS,NOFAMS),PRIND_TEMP(INS%NO))

WRITE(IOUNOUT,*) 'NUMBER OF INS, SLA, SST, SSS :',INS%NO, SLA%NO, SST%NO, SSS%NO

DO JP=1,NPROCS
   IF(INS%NO .GT. 0) &
   ALLOCATE(INSC(JP)%FLC(INS%NO),&
            INSC(JP)%NIND(INS%NO),&
            INSC(JP)%INO(INS%NO),&
            INSC(JP)%OTYPE(INS%NO),&
            INSC(JP)%PAR(INS%NO),&
            INSC(JP)%PLNO(INS%NO),&
            INSC(JP)%INST(INS%NO),&
            INSC(JP)%EVE(INS%NO),&
            INSC(JP)%KTY(INS%NO),&
            INSC(JP)%PRIND(INS%NO),&
            INSC(JP)%PROF(INS%NO),&
            INSC(JP)%TDIST(INS%NO),&
            INSC(JP)%LON(INS%NO),&
            INSC(JP)%LAT(INS%NO),&
            INSC(JP)%DPT(INS%NO),&
            INSC(JP)%TIM(INS%NO),&
            INSC(JP)%VAL(INS%NO),&
            INSC(JP)%BIA(INS%NO),&
            INSC(JP)%IB (INS%NO,NPQ),&
            INSC(JP)%JB (INS%NO,NPQ),&
            INSC(JP)%KB (INS%NO),&
            INSC(JP)%RB (INS%NO),&
            INSC(JP)%SD1 (INS%NO),&
            INSC(JP)%SD2 (INS%NO),&
            INSC(JP)%MOI (INS%NO,NPQ),&
            INSC(JP)%MOJ (INS%NO,NPQ),&
            INSC(JP)%PQ(INS%NO,2*NPQ) )

   IF(SLA%NO .GT. 0) THEN
     ALLOCATE(SLAC(JP)%FLC(SLA%NO) )
     ALLOCATE(SLAC(JP)%INO(SLA%NO) )
     ALLOCATE(SLAC(JP)%NIND(SLA%NO) )
     ALLOCATE(SLAC(JP)%TRACK(SLA%NO) )
     ALLOCATE(SLAC(JP)%EVE(SLA%NO) )
     ALLOCATE(SLAC(JP)%KSAT(SLA%NO) )
     ALLOCATE(SLAC(JP)%BOT(SLA%NO) )
     ALLOCATE(SLAC(JP)%TDIST(SLA%NO) )
     ALLOCATE(SLAC(JP)%LON(SLA%NO) )
     ALLOCATE(SLAC(JP)%LAT(SLA%NO) )
     ALLOCATE(SLAC(JP)%TIM(SLA%NO) )
     ALLOCATE(SLAC(JP)%VAL(SLA%NO) )
     ALLOCATE(SLAC(JP)%BIA(SLA%NO) )
     ALLOCATE(SLAC(JP)%IB(SLA%NO,NPQ) )
     ALLOCATE(SLAC(JP)%JB(SLA%NO,NPQ) )
     ALLOCATE(SLAC(JP)%PQ(SLA%NO,NPQ) )
     ALLOCATE(SLAC(JP)%SD1 (SLA%NO) )
     ALLOCATE(SLAC(JP)%SD2 (SLA%NO) )
     ALLOCATE(SLAC(JP)%MOI (SLA%NO,NPQ) )
     ALLOCATE(SLAC(JP)%MOJ (SLA%NO,NPQ) )
     ALLOCATE(SLAC(JP)%DPT(SLA%NO) )
   ENDIF

   IF(SST%NO .GT. 0) &
   ALLOCATE(SSTC(JP)%FLC(SST%NO),&
            SSTC(JP)%TRACK(SST%NO),&
            SSTC(JP)%EVE(SST%NO),&
            SSTC(JP)%NIND(SST%NO),&
            SSTC(JP)%KSAT(SST%NO),&
            SSTC(JP)%TDIST(SST%NO),&
            SSTC(JP)%LON(SST%NO),&
            SSTC(JP)%LAT(SST%NO),&
            SSTC(JP)%TIM(SST%NO),&
            SSTC(JP)%VAL(SST%NO),&
            SSTC(JP)%BIA(SST%NO),&
            SSTC(JP)%IB(SST%NO,NPQ),&
            SSTC(JP)%JB(SST%NO,NPQ),&
            SSTC(JP)%SD1 (SST%NO),&
            SSTC(JP)%SD2 (SST%NO),&
            SSTC(JP)%MOI (SST%NO,NPQ),&
            SSTC(JP)%MOJ (SST%NO,NPQ),&
            SSTC(JP)%PQ(SST%NO,NPQ))

   IF(SSS%NO .GT. 0) &
   ALLOCATE(SSSC(JP)%FLC(SSS%NO),&
            SSSC(JP)%TRACK(SSS%NO),&
            SSSC(JP)%EVE(SSS%NO),&
            SSSC(JP)%NIND(SSS%NO),&
            SSSC(JP)%KSAT(SSS%NO),&
            SSSC(JP)%TDIST(SSS%NO),&
            SSSC(JP)%LON(SSS%NO),&
            SSSC(JP)%LAT(SSS%NO),&
            SSSC(JP)%TIM(SSS%NO),&
            SSSC(JP)%VAL(SSS%NO),&
            SSSC(JP)%BIA(SSS%NO),&
            SSSC(JP)%IB(SSS%NO,NPQ),&
            SSSC(JP)%JB(SSS%NO,NPQ),&
            SSSC(JP)%SD1 (SSS%NO),&
            SSSC(JP)%SD2 (SSS%NO),&
            SSSC(JP)%MOI (SSS%NO,NPQ),&
            SSSC(JP)%MOJ (SSS%NO,NPQ),&
            SSSC(JP)%BCP (SSS%NO,NPRD_SSS),&
            SSSC(JP)%PQ(SSS%NO,NPQ))

ENDDO

KCOUNT=0
NFAULT=0
NFLGOK=0

PRIND_TEMP(1)=1
CYOBS : DO KK = 1,INS%NO

  IF(LLMPF .AND. KK .GT. 1) THEN
  IF(INS%PROF(KK) .NE. INS%PROF(KK-1) ) PRIND_TEMP(KK) = KK
  ENDIF   

  IF(INS%FLC(KK) .NE. 1) CYCLE CYOBS

  IF ( LLMPF ) THEN
      CALL PROCSPLIT(JPNI, INS%IB(KK,:), INS%JB(KK,:), SUBDOM1, SUBDOM2, MOTHI, MOTHJ)
  ELSE 
      SUBDOM1=1
      SUBDOM2=1
      MOTHI=0
      MOTHJ=0
  ENDIF
  IF( SUBDOM1 .EQ. 0 ) THEN
    NFAULT=NFAULT+1
    WRITE(1061,'(8I4)') INS%IB(KK,:), INS%JB(KK,:)
    CYCLE CYOBS
  ENDIF

  NFLGOK(NNINS)=NFLGOK(NNINS)+1

  MYPROC = SUBDOM1

  KCOUNT(MYPROC,NNINS)=KCOUNT(MYPROC,NNINS)+1
  MYCT = KCOUNT(MYPROC,NNINS)
  INSC(MYPROC)%FLC(MYCT) = INS%FLC(KK)
  INSC(MYPROC)%NIND(MYCT) = NFLGOK(NNINS)
  INSC(MYPROC)%INO(MYCT) = INS%INO(KK)
  INSC(MYPROC)%OTYPE(MYCT) = INS%OTYPE(KK)
  INSC(MYPROC)%PAR(MYCT) = INS%PAR(KK)
  INSC(MYPROC)%PLNO(MYCT) = INS%PLNO(KK)
  INSC(MYPROC)%INST(MYCT) = INS%INST(KK)
  INSC(MYPROC)%EVE(MYCT) = INS%EVE(KK)
  INSC(MYPROC)%KTY(MYCT) = INS%KTY(KK)
  IF( LLMPF) INSC(MYPROC)%PRIND(MYCT) = PRIND_TEMP(KK)
  INSC(MYPROC)%PROF(MYCT) = INS%PROF(KK)
  INSC(MYPROC)%TDIST(MYCT) = INS%TDIST(KK)
  INSC(MYPROC)%LON(MYCT) = INS%LON(KK)
  INSC(MYPROC)%LAT(MYCT) = INS%LAT(KK)
  INSC(MYPROC)%DPT(MYCT) = INS%DPT(KK)
  INSC(MYPROC)%TIM(MYCT) = INS%TIM(KK)
  INSC(MYPROC)%VAL(MYCT) = INS%VAL(KK)
  INSC(MYPROC)%BIA(MYCT) = INS%BIA(KK)
  INSC(MYPROC)%IB(MYCT,:) = INS%IB(KK,:)
  INSC(MYPROC)%JB(MYCT,:) = INS%JB(KK,:)
  INSC(MYPROC)%KB(MYCT) = INS%KB(KK)
  INSC(MYPROC)%RB(MYCT) = INS%RB(KK)
  INSC(MYPROC)%PQ(MYCT,:) = INS%PQ(KK,:)
  INSC(MYPROC)%SD1(MYCT) = SUBDOM1
  INSC(MYPROC)%SD2(MYCT) = SUBDOM2
  INSC(MYPROC)%MOI(MYCT,1:NPQ) = MOTHI(1:NPQ)
  INSC(MYPROC)%MOJ(MYCT,1:NPQ) = MOTHJ(1:NPQ)

ENDDO CYOBS

DEALLOCATE(PRIND_TEMP)

WRITE(IOUNLOG,*) 'INS FAULTS ',NFAULT

CYOBS2 : DO KK = 1,SLA%NO

  IF(SLA%FLC(KK) .NE. 1) CYCLE CYOBS2

  IF(LLMPF) THEN
      CALL PROCSPLIT(JPNI, SLA%IB(KK,:), SLA%JB(KK,:), SUBDOM1, SUBDOM2, MOTHI, MOTHJ)
  ELSE 
      SUBDOM1=1
      SUBDOM2=1
      MOTHI=0
      MOTHJ=0
  ENDIF
  IF( SUBDOM1 .EQ. 0 ) CYCLE CYOBS2

  NFLGOK(NNSLA)=NFLGOK(NNSLA)+1

  MYPROC = SUBDOM1

  KCOUNT(MYPROC,NNSLA)=KCOUNT(MYPROC,NNSLA)+1
  MYCT = KCOUNT(MYPROC,NNSLA)
  SLAC(MYPROC)%FLC(MYCT) = SLA%FLC(KK)
  SLAC(MYPROC)%INO(MYCT) = SLA%INO(KK)
  SLAC(MYPROC)%NIND(MYCT) = NFLGOK(NNSLA)
  SLAC(MYPROC)%TRACK(MYCT) = SLA%TRACK(KK)
  SLAC(MYPROC)%EVE(MYCT) = SLA%EVE(KK)
  SLAC(MYPROC)%KSAT(MYCT) = SLA%KSAT(KK)
  SLAC(MYPROC)%BOT(MYCT) = SLA%BOT(KK)
  SLAC(MYPROC)%TDIST(MYCT) = SLA%TDIST(KK)
  SLAC(MYPROC)%LON(MYCT) = SLA%LON(KK)
  SLAC(MYPROC)%LAT(MYCT) = SLA%LAT(KK)
  SLAC(MYPROC)%TIM(MYCT) = SLA%TIM(KK)
  SLAC(MYPROC)%VAL(MYCT) = SLA%VAL(KK)
  SLAC(MYPROC)%BIA(MYCT) = SLA%BIA(KK)
  SLAC(MYPROC)%IB(MYCT,:) = SLA%IB (KK,:)
  SLAC(MYPROC)%JB(MYCT,:) = SLA%JB (KK,:)
  SLAC(MYPROC)%PQ(MYCT,:) = SLA%PQ(KK,:)
  SLAC(MYPROC)%DPT(MYCT) = SLA%DPT(KK)
  SLAC(MYPROC)%SD1(MYCT) = SUBDOM1
  SLAC(MYPROC)%SD2(MYCT) = SUBDOM2
  SLAC(MYPROC)%MOI(MYCT,1:NPQ) = MOTHI(1:NPQ)
  SLAC(MYPROC)%MOJ(MYCT,1:NPQ) = MOTHJ(1:NPQ)

ENDDO CYOBS2

CYOBS3 : DO KK = 1,SST%NO

  IF(SST%FLC(KK) .NE. 1) CYCLE CYOBS3

  IF(LLMPF) THEN
      CALL PROCSPLIT(JPNI, SST%IB(KK,:), SST%JB(KK,:), SUBDOM1, SUBDOM2, MOTHI, MOTHJ)
  ELSE 
      SUBDOM1=1
      SUBDOM2=1
      MOTHI=0
      MOTHJ=0
  ENDIF
  IF( SUBDOM1 .EQ. 0 ) CYCLE CYOBS3

  NFLGOK(NNSST)=NFLGOK(NNSST)+1

  MYPROC = SUBDOM1

  KCOUNT(MYPROC,NNSST)=KCOUNT(MYPROC,NNSST)+1
  MYCT = KCOUNT(MYPROC,NNSST)
  SSTC(MYPROC)%TRACK(MYCT) = SST%TRACK(KK)
  SSTC(MYPROC)%NIND(MYCT) = NFLGOK(NNSST)
  SSTC(MYPROC)%FLC(MYCT) = SST%FLC(KK)
  SSTC(MYPROC)%NIND(MYCT) = NFLGOK(NNSST)
  SSTC(MYPROC)%EVE(MYCT) = SST%EVE(KK)
  SSTC(MYPROC)%KSAT(MYCT) = SST%KSAT(KK)
  SSTC(MYPROC)%TDIST(MYCT) = SST%TDIST(KK)
  SSTC(MYPROC)%LON(MYCT) = SST%LON(KK)
  SSTC(MYPROC)%LAT(MYCT) = SST%LAT(KK)
  SSTC(MYPROC)%TIM(MYCT) = SST%TIM(KK)
  SSTC(MYPROC)%VAL(MYCT) = SST%VAL(KK)
  SSTC(MYPROC)%BIA(MYCT) = SST%BIA(KK)
  SSTC(MYPROC)%IB(MYCT,:) = SST%IB (KK,:)
  SSTC(MYPROC)%JB(MYCT,:) = SST%JB (KK,:)
  SSTC(MYPROC)%PQ(MYCT,:) = SST%PQ(KK,:)
  SSTC(MYPROC)%SD1(MYCT) = SUBDOM1
  SSTC(MYPROC)%SD2(MYCT) = SUBDOM2
  SSTC(MYPROC)%MOI(MYCT,1:NPQ) = MOTHI(1:NPQ)
  SSTC(MYPROC)%MOJ(MYCT,1:NPQ) = MOTHJ(1:NPQ)

ENDDO CYOBS3

CYOBS4 : DO KK = 1,SSS%NO

  IF(SSS%FLC(KK) .NE. 1) CYCLE CYOBS4

  IF(LLMPF) THEN
      CALL PROCSPLIT(JPNI, SSS%IB(KK,:), SSS%JB(KK,:), SUBDOM1, SUBDOM2, MOTHI, MOTHJ)
  ELSE 
      SUBDOM1=1
      SUBDOM2=1
      MOTHI=0
      MOTHJ=0
  ENDIF
  IF( SUBDOM1 .EQ. 0 ) CYCLE CYOBS4

  NFLGOK(NNSSS)=NFLGOK(NNSSS)+1

  MYPROC = SUBDOM1

  KCOUNT(MYPROC,NNSSS)=KCOUNT(MYPROC,NNSSS)+1
  MYCT = KCOUNT(MYPROC,NNSSS)
  SSSC(MYPROC)%TRACK(MYCT) = SSS%TRACK(KK)
  SSSC(MYPROC)%FLC(MYCT) = SSS%FLC(KK)
  SSSC(MYPROC)%NIND(MYCT) = NFLGOK(NNSSS)
  SSSC(MYPROC)%EVE(MYCT) = SSS%EVE(KK)
  SSSC(MYPROC)%KSAT(MYCT) = SSS%KSAT(KK)
  SSSC(MYPROC)%TDIST(MYCT) = SSS%TDIST(KK)
  SSSC(MYPROC)%LON(MYCT) = SSS%LON(KK)
  SSSC(MYPROC)%LAT(MYCT) = SSS%LAT(KK)
  SSSC(MYPROC)%TIM(MYCT) = SSS%TIM(KK)
  SSSC(MYPROC)%VAL(MYCT) = SSS%VAL(KK)
  SSSC(MYPROC)%BIA(MYCT) = SSS%BIA(KK)
  SSSC(MYPROC)%IB(MYCT,:) = SSS%IB (KK,:)
  SSSC(MYPROC)%JB(MYCT,:) = SSS%JB (KK,:)
  SSSC(MYPROC)%PQ(MYCT,:) = SSS%PQ(KK,:)
  SSSC(MYPROC)%BCP(MYCT,:) = SSS%BCP(KK,:)
  SSSC(MYPROC)%SD1(MYCT) = SUBDOM1
  SSSC(MYPROC)%SD2(MYCT) = SUBDOM2
  SSSC(MYPROC)%MOI(MYCT,1:NPQ) = MOTHI(1:NPQ)
  SSSC(MYPROC)%MOJ(MYCT,1:NPQ) = MOTHJ(1:NPQ)

ENDDO CYOBS4

OPEN(913,FILE='OBS_TAB.DAT')

ALLOCATE( ISNDX( MAXVAL((/INS%NO,SLA%NO,SST%NO,SSS%NO/)) ) )

DO JP=1,NPROCS

   IF(KCOUNT(JP,NNINS).GT.0) THEN

     CALL INDEX_SORT(INSC(JP)%TIM(1:KCOUNT(JP,NNINS)),&
     & ISNDX(1:KCOUNT(JP,NNINS)),KCOUNT(JP,NNINS) )

       WRITE(CFILE,'(A,I4.4,A)') 'INSOBS_',JP-1,'.NC'

       CALL IO_OBS(CFILE=CFILE,IOPT=1,NOBS=KCOUNT(JP,NNINS),&
       NLEVS=GRD%KM, NPREDS=0, NPQ=NPQ,NPQ2=2*NPQ ,&
       FLC=INSC(JP)%FLC(ISNDX(1:KCOUNT(JP,NNINS))),&
       NIND=INSC(JP)%NIND(ISNDX(1:KCOUNT(JP,NNINS))),&
       INO=INSC(JP)%INO(ISNDX(1:KCOUNT(JP,NNINS))),&
       OTYPE=INSC(JP)%OTYPE(ISNDX(1:KCOUNT(JP,NNINS))),&
       PAR=INSC(JP)%PAR(ISNDX(1:KCOUNT(JP,NNINS))),&
       PLNO=INSC(JP)%PLNO(ISNDX(1:KCOUNT(JP,NNINS))),&
       INST=INSC(JP)%INST(ISNDX(1:KCOUNT(JP,NNINS))),&
       EVE=INSC(JP)%EVE(ISNDX(1:KCOUNT(JP,NNINS))),&
       KTY=INSC(JP)%KTY(ISNDX(1:KCOUNT(JP,NNINS))),&
       PRIND=INSC(JP)%PRIND(ISNDX(1:KCOUNT(JP,NNINS))),&
       PROF=INSC(JP)%PROF(ISNDX(1:KCOUNT(JP,NNINS))),&
       TDIST=INSC(JP)%TDIST(ISNDX(1:KCOUNT(JP,NNINS))),&
       LON=INSC(JP)%LON(ISNDX(1:KCOUNT(JP,NNINS))),&
       LAT=INSC(JP)%LAT(ISNDX(1:KCOUNT(JP,NNINS))),&
       DPT=INSC(JP)%DPT(ISNDX(1:KCOUNT(JP,NNINS))),&
       TIM=INSC(JP)%TIM(ISNDX(1:KCOUNT(JP,NNINS))),&
       VAL=INSC(JP)%VAL(ISNDX(1:KCOUNT(JP,NNINS))),&
       BIA=INSC(JP)%BIA(ISNDX(1:KCOUNT(JP,NNINS))),&
       IB=INSC(JP)%IB(ISNDX(1:KCOUNT(JP,NNINS)),:),&
       JB=INSC(JP)%JB(ISNDX(1:KCOUNT(JP,NNINS)),:),&
       KB=INSC(JP)%KB(ISNDX(1:KCOUNT(JP,NNINS))),&
       RB=INSC(JP)%RB(ISNDX(1:KCOUNT(JP,NNINS))),&
       PQ=INSC(JP)%PQ(ISNDX(1:KCOUNT(JP,NNINS)),:),&
       SD1=INSC(JP)%SD1(ISNDX(1:KCOUNT(JP,NNINS))),&
       SD2=INSC(JP)%SD2(ISNDX(1:KCOUNT(JP,NNINS))),&
       MOI=INSC(JP)%MOI(ISNDX(1:KCOUNT(JP,NNINS)),:),&
       MOJ=INSC(JP)%MOJ(ISNDX(1:KCOUNT(JP,NNINS)),:) )

   ENDIF

   IF(KCOUNT(JP,NNSLA).GT.0) THEN

     CALL INDEX_SORT(SLAC(JP)%TIM(1:KCOUNT(JP,NNSLA)),&
     & ISNDX(1:KCOUNT(JP,NNSLA)),KCOUNT(JP,NNSLA) )

       WRITE(CFILE,'(A,I4.4,A)') 'SLAOBS_',JP-1,'.NC'

       CALL IO_OBS(CFILE=CFILE,IOPT=1,NOBS=KCOUNT(JP,NNSLA),&
       NLEVS=GRD%KM, NPREDS=0,NPQ=NPQ,NPQ2=NPQ,&
       FLC=SLAC(JP)%FLC(ISNDX(1:KCOUNT(JP,NNSLA))),&
       NIND=SLAC(JP)%NIND(ISNDX(1:KCOUNT(JP,NNSLA))),&
       INO=SLAC(JP)%INO(ISNDX(1:KCOUNT(JP,NNSLA))),&
       TRACK=SLAC(JP)%TRACK(ISNDX(1:KCOUNT(JP,NNSLA))),&
       EVE=SLAC(JP)%EVE(ISNDX(1:KCOUNT(JP,NNSLA))),&
       KSAT=SLAC(JP)%KSAT(ISNDX(1:KCOUNT(JP,NNSLA))),&
       BOT=SLAC(JP)%BOT(ISNDX(1:KCOUNT(JP,NNSLA))),&
       TDIST=SLAC(JP)%TDIST(ISNDX(1:KCOUNT(JP,NNSLA))),&
       LON=SLAC(JP)%LON(ISNDX(1:KCOUNT(JP,NNSLA))),&
       LAT=SLAC(JP)%LAT(ISNDX(1:KCOUNT(JP,NNSLA))),&
       TIM=SLAC(JP)%TIM(ISNDX(1:KCOUNT(JP,NNSLA))),&
       VAL=SLAC(JP)%VAL(ISNDX(1:KCOUNT(JP,NNSLA))),&
       BIA=SLAC(JP)%BIA(ISNDX(1:KCOUNT(JP,NNSLA))),&
       IB=SLAC(JP)%IB(ISNDX(1:KCOUNT(JP,NNSLA)),:),&
       JB=SLAC(JP)%JB(ISNDX(1:KCOUNT(JP,NNSLA)),:),&
       PQ=SLAC(JP)%PQ(ISNDX(1:KCOUNT(JP,NNSLA)),:),&
       DPT=SLAC(JP)%DPT(ISNDX(1:KCOUNT(JP,NNSLA))),&
       SD1=SLAC(JP)%SD1(ISNDX(1:KCOUNT(JP,NNSLA))),&
       SD2=SLAC(JP)%SD2(ISNDX(1:KCOUNT(JP,NNSLA))),&
       MOI=SLAC(JP)%MOI(ISNDX(1:KCOUNT(JP,NNSLA)),:),&
       MOJ=SLAC(JP)%MOJ(ISNDX(1:KCOUNT(JP,NNSLA)),:) )

   ENDIF

   IF(KCOUNT(JP,NNSST).GT.0) THEN

     CALL INDEX_SORT(SSTC(JP)%TIM(1:KCOUNT(JP,NNSST)),&
     & ISNDX(1:KCOUNT(JP,NNSST)),KCOUNT(JP,NNSST) )

       WRITE(CFILE,'(A,I4.4,A)') 'SSTOBS_',JP-1,'.NC'

       CALL IO_OBS(CFILE=CFILE,IOPT=1,NOBS=KCOUNT(JP,NNSST),&
       NLEVS=GRD%KM, NPREDS=0, NPQ=NPQ,NPQ2=NPQ,&
       FLC=SSTC(JP)%FLC(ISNDX(1:KCOUNT(JP,NNSST))),&
       NIND=SSTC(JP)%NIND(ISNDX(1:KCOUNT(JP,NNSST))),&
       TRACK=SSTC(JP)%TRACK(ISNDX(1:KCOUNT(JP,NNSST))),&
       EVE=SSTC(JP)%EVE(ISNDX(1:KCOUNT(JP,NNSST))),&
       KSAT=SSTC(JP)%KSAT(ISNDX(1:KCOUNT(JP,NNSST))),&
       TDIST=SSTC(JP)%TDIST(ISNDX(1:KCOUNT(JP,NNSST))),&
       LON=SSTC(JP)%LON(ISNDX(1:KCOUNT(JP,NNSST))),&
       LAT=SSTC(JP)%LAT(ISNDX(1:KCOUNT(JP,NNSST))),&
       TIM=SSTC(JP)%TIM(ISNDX(1:KCOUNT(JP,NNSST))),&
       VAL=SSTC(JP)%VAL(ISNDX(1:KCOUNT(JP,NNSST))),&
       BIA=SSTC(JP)%BIA(ISNDX(1:KCOUNT(JP,NNSST))),&
       IB=SSTC(JP)%IB(ISNDX(1:KCOUNT(JP,NNSST)),:),&
       JB=SSTC(JP)%JB(ISNDX(1:KCOUNT(JP,NNSST)),:),&
       PQ=SSTC(JP)%PQ(ISNDX(1:KCOUNT(JP,NNSST)),:),&
       SD1=SSTC(JP)%SD1(ISNDX(1:KCOUNT(JP,NNSST))),&
       SD2=SSTC(JP)%SD2(ISNDX(1:KCOUNT(JP,NNSST))),&
       MOI=SSTC(JP)%MOI(ISNDX(1:KCOUNT(JP,NNSST)),:),&
       MOJ=SSTC(JP)%MOJ(ISNDX(1:KCOUNT(JP,NNSST)),:) )

   ENDIF

   IF(KCOUNT(JP,NNSSS).GT.0) THEN

     CALL INDEX_SORT(SSSC(JP)%TIM(1:KCOUNT(JP,NNSSS)),&
     & ISNDX(1:KCOUNT(JP,NNSSS)),KCOUNT(JP,NNSSS) )

       WRITE(CFILE,'(A,I4.4,A)') 'SSSOBS_',JP-1,'.NC'

       CALL IO_OBS(CFILE=CFILE,IOPT=1,NOBS=KCOUNT(JP,NNSSS),&
       NLEVS=GRD%KM, NPREDS=NPRD_SSS, NPQ=NPQ,NPQ2=NPQ,&
       FLC=SSSC(JP)%FLC(ISNDX(1:KCOUNT(JP,NNSSS))),&
       NIND=SSSC(JP)%NIND(ISNDX(1:KCOUNT(JP,NNSSS))),&
       TRACK=SSSC(JP)%TRACK(ISNDX(1:KCOUNT(JP,NNSSS))),&
       EVE=SSSC(JP)%EVE(ISNDX(1:KCOUNT(JP,NNSSS))),&
       KSAT=SSSC(JP)%KSAT(ISNDX(1:KCOUNT(JP,NNSSS))),&
       TDIST=SSSC(JP)%TDIST(ISNDX(1:KCOUNT(JP,NNSSS))),&
       LON=SSSC(JP)%LON(ISNDX(1:KCOUNT(JP,NNSSS))),&
       LAT=SSSC(JP)%LAT(ISNDX(1:KCOUNT(JP,NNSSS))),&
       TIM=SSSC(JP)%TIM(ISNDX(1:KCOUNT(JP,NNSSS))),&
       VAL=SSSC(JP)%VAL(ISNDX(1:KCOUNT(JP,NNSSS))),&
       BIA=SSSC(JP)%BIA(ISNDX(1:KCOUNT(JP,NNSSS))),&
       IB=SSSC(JP)%IB(ISNDX(1:KCOUNT(JP,NNSSS)),:),&
       JB=SSSC(JP)%JB(ISNDX(1:KCOUNT(JP,NNSSS)),:),&
       PQ=SSSC(JP)%PQ(ISNDX(1:KCOUNT(JP,NNSSS)),:),&
       BCP=SSSC(JP)%BCP(ISNDX(1:KCOUNT(JP,NNSSS)),:),&
       SD1=SSSC(JP)%SD1(ISNDX(1:KCOUNT(JP,NNSSS))),&
       SD2=SSSC(JP)%SD2(ISNDX(1:KCOUNT(JP,NNSSS))),&
       MOI=SSSC(JP)%MOI(ISNDX(1:KCOUNT(JP,NNSSS)),:),&
       MOJ=SSSC(JP)%MOJ(ISNDX(1:KCOUNT(JP,NNSSS)),:) )

   ENDIF

   WRITE(913,*) JP,KCOUNT(JP,NNINS),KCOUNT(JP,NNSLA),KCOUNT(JP,NNSST),KCOUNT(JP,NNSSS)
   CALL FLUSH(913)

ENDDO

DEALLOCATE(ISNDX)
CLOSE(913)

CALL MYFRTPROF_WALL('WRITEOBS102: WRITE BINARY OBS FILES',1)
END SUBROUTINE WRITEOBS102
