INTEGER(KIND=I4) FUNCTION XIND1(I)
USE GRD_STR
USE IOUNITS
IMPLICIT NONE
INTEGER, INTENT(IN) :: I
IF(GRD%IM.LT.1 .OR. GRD%IM .GT. 10000 ) THEN
 WRITE(IOUNERR,*) ' GRD%IM = ',GRD%IM
 WRITE(IOUNERR,*) ' WHICH PROBABLY MEANS RDGRDS HAS NOT YET BEEN CALLED'
 CALL ABOR1('FUNCTION XIND1 CANNOT PROCEED')
ENDIF
IF(I.EQ.GRD%IM) THEN
   XIND1=3
ELSEIF(I.GE.1 .AND. I.LT.GRD%IM) THEN
   XIND1=I+1
ELSE
   WRITE(IOUNERR,*) 'ERROR: I = ',I, ' AND GRD%IM =',GRD%IM
   CALL ABOR1('FUNCTION XIND1 CANNOT PROCEED')
ENDIF
RETURN
END FUNCTION XIND1
